### ISSUE TITLE
Showing incorrect pickup date when service is delayed due to holiday

### ISSUE THREAD

**Issue by mattclair** [mampfes/hacs_waste_collection_schedule#1005]
Using Republic Services in the US as a source, the addon reports that my trash pickup is scheduled for Thursday June 1st 2023. This is my normal trash pickup day.

Logging into the Republic Services website and checking the schedule for my address, it shows that pickup is delayed one day and will be collected Friday June 2nd, 2023, due to the Memorial Day holiday.

**Comment by dt215git** [comment]
Using one of the  test cases, the script seems to reporting the date returned by the API the website is using. The website appears to be shifting the date to account for the public holiday, but it's not obvious how that correction is being made.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/b1f9d0db-95bc-43a7-aeb0-2a748a20b6e9)

**Comment by 5ila5** [comment]
looks like there is an extra request for holidays to https://www.republicservices.com/api/v3/holidaySchedules/schedules?latitude=38.210095&longitude=-84.559353
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38183212/6b34c1d1-98ff-4447-bd9c-a412937f60e4)

**Comment by dt215git** [comment]
This url seems to give the adjusted collection date: https://www.republicservices.com/api/v1/locations/content?countryCode=US&latitude=41.9132&longitude=-85.0096&postalCode=49036

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/9644161b-8446-4eea-bb28-e590648f44a0)

I'll try and incorporate that  - finding a collection due on the 4th July might be the best test case in the near future.

**Comment by 5ila5** [comment]
#1056 fixed this issue.

This patch will be part of the 1.41.0 release. Or is available now as the master (git) version
