### ISSUE TITLE
The Hills (Sydney) suburb not found

### ISSUE THREAD

**Issue by thekayman** [mampfes/hacs_waste_collection_schedule#1009]
Hi There,
Just trying to use this integration and it seems to be having an issue grabbing the bin data for The Hills

Using the form https://www.thehills.nsw.gov.au/Services/For-Residents/Waste-Recycling/Check-which-bin-to-put-out##276069 I can find my suburb and house but the integration is coming up with an issue as below, i have xx'd out my suburb.

Any chance you can try help?

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 4:39:48 PM (3 occurrences)
Last logged: 5:34:13 PM

fetch failed for source The Hills Shire Council, Sydney: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/thehills_nsw_gov_au.py", line 40, in fetch raise Exception(f"suburb not found: {self._suburb}") Exception: suburb not found: xxxxxxxxx

**Comment by dt215git** [comment]
The script is pulling a suburb list from the website and then looking to see if the one you supplied is contained within it. It it doesn't find a match, it returns that error message.

When you set up the config, wast the suburb all uppercase and spelt exactly as shown on the website?

**Comment by thekayman** [comment]
really appreciate the quick reply, you were spot on... website was all caps and I followed that in the config and after rebooting it had the calendar entries. Thanks so much!

**Comment by thekayman** [comment]
Sorry one more item, seems like the sensor.garbage_days is unkown, I used the code from your FAQ for the garbage collection card but doesnt seem to be populating with anything

**Comment by dt215git** [comment]
If you go to `Developer Tools | States` and search for your waste sensor, what do you see?

It may be that in trying to get it working, HA has created multiple sensors and you're referencing an earlier one that doesn't contain any data, or the `daysTo` attribute is missing because you've not included the `add_days_to: true` arg?

Looks like @Sila5 has already made the change that should prevent the upper/lower/mixed-case being an issue for future users.

**Comment by 5ila5** [comment]
@thekayman can you post your sensor configuration? Did you change the `types` from Garbage to the types returned by the integration? (Recycling and Rubbish)

**Comment by thekayman** [comment]
Thanks for the replies, I had missed the need to add the types in the sensor. I have just added them in and can see it's populated the sensor.garbage_days
my code is below
`  # Sensor for Waste Collection Schedule
  - platform: waste_collection_schedule
    name: garbage_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Garden Organics
      - Recycling

  - platform: template
    sensors:
      garbage:
        value_template: >
          {% if states('sensor.garbage_days')|int > 2 %}
            2
          {% else %}
            {{ states('sensor.garbage_days')|int }}
          {% endif %}
        attribute_templates:
          next_date: "{{ state_attr('sensor.garbage_days', 'Garbage') }}"
          days: "{{ states('sensor.garbage_days')|int }}"
`

With the garbage-collection-card not sure what to put for the entity, here is the existing code when I was using the garbage collection integration, I wanted to be shown details for the Garden Organics (Green) and Recycling (Yellow) bins

`entity: sensor.green_bin
hide_date: true
icon_color: green
icon_size: 35px
type: custom:garbage-collection-card
due_txt: Today
due_color: red
hide_on_click: false
`

and finally, a screenshot of the state of the sensors are reporting
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/68209649/780b0dce-8627-4d02-b1f4-dbbd7265af9c)

let me know if you need any more info and appreciate the help.

**Comment by thekayman** [comment]
I managed to solve the issue, just in case anyone comes along searching here is what I ended up doing.

in configuration.yaml
'''
waste_collection_schedule:
  sources:
    - name: thehills_nsw_gov_au
      args:
        suburb: BEAUMONT HILLS
        street: The Parkway
        houseNo: 7
'''
and for the two different bin types created the sensors
'''
  - platform: waste_collection_schedule
    name: next_collection_green
    types:
      - Garden Organics
    details_format: "generic"
    value_template: "{{ value.daysTo }}"
    leadtime: 10
    
  - platform: waste_collection_schedule
    name: next_collection_yellow
    types:
      - Recycling
    details_format: "generic"
    value_template: "{{ value.daysTo }}"
    leadtime: 10
'''

and for the Garbage-Collection-Card in lovelace as below
'''
type: custom:garbage-collection-card
source: hacs_waste_collection_schedule
entity: sensor.next_collection_green
icon_color: green
icon_size: 40px
hide_before: -7
'''
'''
type: custom:garbage-collection-card
source: hacs_waste_collection_schedule
entity: sensor.next_collection_yellow
icon_color: yellow
icon_size: 40px
hide_before: -7
'''
