### ISSUE TITLE
Source Request. East Riding Waste UK

### ISSUE THREAD

**Issue by psidirect** [mampfes/hacs_waste_collection_schedule#1014]
Hi,

Would it be possible to support East Riding?

https://www.eastriding.gov.uk/environment/bins-rubbish-recycling/bins-and-collections/bin-collection-dates/

Thanks

**Comment by dt215git** [comment]
That looks relatively simple, will try and do it shortly.

**Comment by psidirect** [comment]
> That looks relatively simple, will try and do it shortly.

Awesome, thanks!

**Comment by 5ila5** [comment]
implemented by #1016
