### ISSUE TITLE
Request for Barnsley Council, UK

### ISSUE THREAD

**Issue by cocopops105** [mampfes/hacs_waste_collection_schedule#1027]
Hi,

Wondering if there anyway to add Barnsley council to the list? 

Would be hugely appreciated.

Thanks!

**Comment by dt215git** [comment]
It looks like you need to make an initial request to the website and extract a token from the response. That token needs to be  submitted in subsequent requests. That's simple enough to do.

The requests that pull back the collection schedule looks like it operates two ways. If the house name/number and postcode are unique then it displays the schedule. If there are multiple matches, then is makes a subsequent query using the uprn and full address depending on the selection you make.

A script could potentially mimic both of those approaches, however, after a handful of tests, this is the response I'm getting back :
```bash
This website is secured against online attacks. Your request was blocked due to suspicious behavior
```
Not sure if others see the same thing, or there's something else the back-end is expecting.

**Comment by 5ila5** [comment]
Added by #1735

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
