### ISSUE TITLE
Update readme of WIFFI repo

### ISSUE THREAD

**Issue by caco3** [mampfes/hacs_waste_collection_schedule#1030]
Hi @mampfes 

https://github.com/mampfes/hacs_wiffi is closed and i can not create an issue for it, so I do it this way.
If I understand it right, you closed above reop and the work is ongoing directly in https://github.com/home-assistant/core/tree/dev/homeassistant/components/wiffi

Could you please update https://github.com/mampfes/hacs_wiffi/blob/master/README.md and link to the new place of work? This will help users to find the latest version.

**Comment by mampfes** [comment]
Hi, I can't change any file on an archived repo. Therefore I deleted this repo.

And yes, you are right. The code is now part of the official Home Assistant core repository. Please raises issues their and mention me.

**Comment by caco3** [comment]
Thanks for your response.

You could have briefly unarchive it, see https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#unarchiving-a-repository

**Comment by mampfes** [comment]
Yes. I know. I didn't do it that way because this would reset the timestamp of the last activity - which I wanted to avoid.
