### ISSUE TITLE
Request to add Karlsruhe Stadt Waste management

### ISSUE THREAD

**Issue by Onecton** [mampfes/hacs_waste_collection_schedule#1034]
I was wondering if it would be possible to add Karlsruhe Stadt Waste schedules also. Karlsruhe BW, Germany. There is a scraper around https://github.com/lrswss/akal2ical (all credits to the owner) but i never came around to mess with it, also i was wondering if it would be possible to kind of integrate this into the waste collection schedule? My expertise is limited here sadly.

**Comment by 5ila5** [comment]
Your linked scraper is written in perl so it would not be very easy to implement. Writing a own one is not that difficult.

Implemented in #1037 

Will be available in release 1.41.0 or now with the master (git) version
