### ISSUE TITLE
Cubefour Integration

### ISSUE THREAD

**Issue by maxtheobald** [mampfes/hacs_waste_collection_schedule#104]
Is it possible to integrate the Cubefour Wastesystem to waste collection schedule? 
You can find their system here: https://awido.cubefour.de/Customer/eww-suew/mobile/

**Comment by mampfes** [comment]
There is already an integration for AWIDO/Cubefour:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md

Did you already check this?

**Comment by mampfes** [comment]
I will close this issue because I didn't get a response. If you still need support, feel free to open this issue again.
