### ISSUE TITLE
Adding new source: parsing ical with non-ASCII UID fails due to upstream. Possible workaround?

### ISSUE THREAD

**Issue by pomeloy** [mampfes/hacs_waste_collection_schedule#1042]
I am trying to add a new source via the generic ICS source instructions. 

The service provider url is shipped with non-ASCII UIDs.
This produces an exception with the icalevents parser, see [https://github.com/jazzband/icalevents/issues/128](https://github.com/jazzband/icalevents/issues/128).
`*** failed: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)`

 Is there any workaround for this upstream bug?

**Comment by mampfes** [comment]
You could try to add the option `version : 1` to select `recurring_ical_events` instead of `icalevents`.

**Comment by pomeloy** [comment]
Thanks, works like a charm!

**Comment by DerDreschner** [comment]
`version: 1` was removed with the latest release. I fixed the bug upstream and created a new release there. The upcoming release of wcs will include it.

**Comment by pomeloy** [comment]
Awesome!
