### ISSUE TITLE
Request for South Holland District Council, UK

### ISSUE THREAD

**Issue by pcaouolte** [mampfes/hacs_waste_collection_schedule#1065]
Hi,

Would it be possible to add support for South Holland District Council in the UK please?

This is the search site: https://www.sholland.gov.uk/article/7156/Check-your-collection-days

Note that some households subscribe to a garden waste scheme and others do not. The search results are similar to the following:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/105014804/77b8c5ba-6922-461c-8a8a-cab917c2be8c)
or
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/105014804/e3179296-2094-451c-ae3c-ee0be4fba4e8)
The "Last Garden Collection" date is the date that the subscription expires.

**Comment by 5ila5** [comment]
added by #1069 

[documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/sholland_gov_uk.md) 

will be part of the 1.41.0 Release or is available now as master/git version

**Comment by pcaouolte** [comment]
Thank you
