### ISSUE TITLE
Inquiry for Calden municipality pickup area Calden

### ISSUE THREAD

**Issue by Lice2** [mampfes/hacs_waste_collection_schedule#1066]
Hi , would it be possible from the website
https://webapp.waste-kreis-kassel.de/waste-calendar
To involve the community of Calden and the Calden pickup area?

**Comment by 5ila5** [comment]
https://webapp.waste-kreis-kassel.de/waste-calendar support a ICS import so its supported by the ICS source I added official documentation for Kreis Kassel [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfall_kreis_kassel_de.md).

**Comment by Lice2** [comment]
Thank You !
