### ISSUE TITLE
Request for Dunedin, Otago, New Zealand

### ISSUE THREAD

**Issue by ddebono1984** [mampfes/hacs_waste_collection_schedule#1074]
Hi there

Keem for the Dunedin city council source to be added by someone who has the skills to do so. The Dunedin City Council provide their collections days at:

https://www.dunedin.govt.nz/do-it-online/search/collection-days

Cheers

Dan

**Comment by ddebono1984** [comment]
Thx - it would appear they are the only responses available. An iphone & google android app was also recently released by DCC for waste collection info so not sure if there is a way to located data source used for that.

**Comment by dt215git** [comment]
For the _All Week_  collections, do you know if that means collections happen Monday-Friday, Monday-Saturday, or something else?

And some forewarning - any Dunedin script will probably need refactoring next year. They seem to be changing/increasing the range of wastes collected.
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/70ba7377-4cdb-472b-940a-c86705699379)

**Comment by ddebono1984** [comment]
Thx. There are no collections over the weekend so Monday - Friday

**Comment by 5ila5** [comment]
added by #1087 

Will be part of release 1.42.0 or is available now as master/git version (clone of this reposetory)
