### ISSUE TITLE
Melton City Council  - Sensor goes "unknown"

### ISSUE THREAD

**Issue by UncleSam002** [mampfes/hacs_waste_collection_schedule#1075]
Hi mate,

The sensor goes "unknown" at 10am on the day of collection until next day. The calendar entity shows the right dates though.
<img width="360" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/96687873/e614bf44-4174-427e-91fc-a286f3068ae2">

Thanks

**Comment by 5ila5** [comment]
Manually fetching collection events seems to work. 

Did you change `fetch_time` or `day_switch_time` ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sources))?

Does this happen at 10:00 AM (default for `day_switch_time` ) or before?

**Comment by UncleSam002** [comment]
> Manually fetching collection events seems to work.
> 
> Did you change `fetch_time` or `day_switch_time` ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sources))?
> 
> Does this happen at 10:00 AM (default for `day_switch_time` ) or before?

Manual fetching using the service doesn't seem to fix the issue on the bin day for me.

Thanks for pointing out the configs. I didn't set either of those configs. Default `fetch_time` works for me and I didn't really understand the purpose of `day_switch_time` so I never set those up. But it sounds like that could be the issue. Although I don't understand why it is an issue only on the bin day, my council always provides just 1 value every week. So if HA is dismissing that value at 10:00 everyday, shouldn't it always show `Unknown` between 10:00 and next day 01:00?

I've changed `day_switch_time` to 23:59 now to see if it makes a difference next week, unless you can think of a solution?

Thanks again

**Comment by 5ila5** [comment]
`day_switch_time` prevents the sensor from displaying 0 days the entire collection day. So on the collection day it switches from 0 days to e.g. 14 days (on a 14 day cycle) at day_switch_time (10 AM). 

If you have multiple different collection on consecutive days you probably want to display Tomorrow instead of today after a given time (if the bin is already put outside or even emptied).

**Comment by UncleSam002** [comment]
Okay, that makes sense. I will report back with results next Monday. Thanks

**Comment by UncleSam002** [comment]
I can confirm that changing `day_switch_time` to 23:59 has worked. It now no longer shows "unknown" state throughout the collection day. Thanks for your help! @5ila5
