### ISSUE TITLE
Cherwell Gov UK site is broken

### ISSUE THREAD

**Issue by pbulteel** [mampfes/hacs_waste_collection_schedule#1079]
I was "fighting" with the integration until I started troubleshooting. I thought my config was wrong. I _may_ have something wrong in my config BUT the issue is with the website.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5732473/6e452bbd-efb4-4b52-b405-c37ea782039e)

This is the output from the site. (https://www.cherwell.gov.uk/homepage/129/?uprn=10011931496)

I tried one of the test cases in the module and I get 

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5732473/2045fe23-9bfa-4178-b5a3-70e3a7f05804)

I've opened a case with Cherwell council to see if they can fix it. 

As far as I can tell, nothing is needed from the devs, but this issue should be tracked, so others can avoid reporting it. 

I'll close when Cherwell fixes the site. (If you want to "assign" it to me.)

--
Patrick

**Comment by dt215git** [comment]
Certainly looks to be something to do with the specific address - some of the addressesneighbouring that uprn return the same _collection day_ message, others return _collection dates,_ and some return a _no info_ message.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/a3feb077-54a8-48f4-b043-c18cfdc3f9cc)

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/19b93b9d-78ef-4bd9-a00c-c8ea096d674d)

UPRN  from new(ish) developments have sometimes failed to return collection dates from  other UK-based sources.

**Comment by pbulteel** [comment]
My development is newish - moved in Oct 2020. But the other UPRN I used to test (from a newer house in our development) shows two bins. Our collection is on Tuesdays and alternates between the colours of the bins (like your example screenshot.) I got an email from Cherwell support, but they just sent the PDF without really understanding the issue. I've clarified the problem with example screenshots. Let's see what comes out of it.

**Comment by pbulteel** [comment]
Just as an update: Cherwell contacted me after I explained everything and sent screenshots and they've said it's been forwarded to someone at their depot and are investigating this. The email was on the 13th of July, 2023. Nothing new since.

**Comment by pbulteel** [comment]
Without notice, my address is now showing the bins with dates... but our bins are ONLY collected on Tuesdays and it's showing our next blue bin collection date to be on a Sunday.

![cherwell-bin-collection-wrong-date-2023-07-21_12-23](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5732473/5e1bddb5-cb91-43d4-a154-5a15153d22b4)

I've emailed them back to ask them to verify and correct.

-P

**Comment by pbulteel** [comment]
Looks like the data is now fixed at the source site. I have an error now though. I'm going to open a new ticket for this though.
