### ISSUE TITLE
Error during setup. source not found

### ISSUE THREAD

**Issue by Schmandre** [mampfes/hacs_waste_collection_schedule#1084]
Hello, 

I tried to add the mags from Mönchengladbach in Germany used this [snipped.](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/mags_de.md)

This unfourtinatly returns this error message.

`homeassistant  | 2023-07-13 21:46:00.338 ERROR (MainThread) [waste_collection_schedule.source_shell] source not found: mags_de
`

Any Ideas how I can troubleshoot?

**Comment by 5ila5** [comment]
Source `mags_de` was added after the release of 1.40.0.
I just released 1.41.0 containing `mags_de` just update to this version.


The general approach for sources not yet part of the current release would be to install the master (git) version (up to date clone of this repository)
