### ISSUE TITLE
Request for Borough Council of Kings Lynn and West Norfolk support

### ISSUE THREAD

**Issue by adamndev** [mampfes/hacs_waste_collection_schedule#1088]
[Source](https://www.west-norfolk.gov.uk/info/20174/bins_and_recycling_collection_dates)

It asks for a postcode and to select an address, then sets some cookies and loads with the next few upcoming dates, or a calendar view which is a table.

Is this similar to others or a little more tricky? Thanks.

**Comment by dt215git** [comment]
Looks like selecting an address sets one of the cookies to the URPN of the property.
It may be possible to mimic just the request(s) using that cookie, rather than replicating the whole postcode/address selection process.

**Comment by 5ila5** [comment]
Added by #1090
will be part of release 1.42.0 or is available now as master (git) version (up to date clone of this reposetory)
