### ISSUE TITLE
Borough of Windsor & Maidenhead (UK)

### ISSUE THREAD

**Issue by smcnab1** [mampfes/hacs_waste_collection_schedule#1091]
Was looking to see viability of adding the [Royal Borough of Windsor and Maidenhead ](https://my.rbwm.gov.uk/special/find-your-collection-dates?nid=)to the integration? Site linked is main search site. Search by Postcode but seems like updates URL

**Comment by 5ila5** [comment]
added by #1093 ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/rbwm_gov_uk.md)).

Will be part of release 1.42.0 or is available now as master / git version (up to date clone of this repository)
