### ISSUE TITLE
Request for Burnley, UK

### ISSUE THREAD

**Issue by ThatDeltaGuy** [mampfes/hacs_waste_collection_schedule#1096]
Would it be possible to add Burnley Council as a source?

https://burnley.gov.uk/waste-recycling/binday/

I've had a look and it doesnt seem possible, but someone smarter than me might be able to get it working.

**Comment by dt215git** [comment]
The backend looks similar to the bexley source, I'll see if that can be reworked.

How does the garden waste side of things work?
Picking random addresses has yet to result in a page that displays collection dates, it just seems to say you've requested a calendar. Is there a way to see those dates if you've subscribed to that service, or is garden waste always collected the same time as an existing recycling or refuse collection?

**Comment by ThatDeltaGuy** [comment]
Garden waste is an optional chargable service.

looking at the garden waste calendar, it seems to be on the same week as recycling, but on a different day.

for some addresses it seems to be missing a link, but if you get a good one, you get a link to a pdf for the dates

**Comment by dt215git** [comment]
For previous councils, parsing PDF to extract collection dates has been decided against. So it might just be easier for anyone who's paid for garden waste collection to use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) to generate that schedule. It looks to be a fortnightly collection for most of the year, so wouldn't be too difficult to set up.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/ec5387bc-9047-4b93-80ee-7db6bdb59bda)

**Comment by 5ila5** [comment]
added by #1102

Will be part of release 1.42.0 or is available now as master/git version (up to date clone of this repository)
