### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by rjenx** [mampfes/hacs_waste_collection_schedule#11]
Hi I have configured this to process an ics file I download from our local council, I don't have direct access to the file as its created based on address input to a java form. 

When I download the file I placed it in the /www/ folder and get error message the file cannot be found. Where is the program expecting to find the ics file? 

My config and error message 

`waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "bins.ics"`

fetch failed for source <custom_components.waste_collection_schedule.package.source.ics.Source object at 0x7f5749d84390>: [Errno 2] No such file or directory: 'bins.ics'
Home Assistant has started!

I have tried multiple locations, root of home assistance config, /www/ a subfolder of /wwww/  with the appropriate path and in each case I get the same error. 

Edited to include details of system: 

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.4.59+
python_version | 3.7.7
timezone | Europe/London
version | 0.111.2
virtualenv | false

Thanks

**Comment by mampfes** [comment]
The tool uses the default path defined by HA. According to [https://community.home-assistant.io/t/waste-collection-schedule-framework/186492/12]() it should be `www/bins.ics`. If this doesn't work you can also use an absolute path `/home/...`.

**Comment by rjenx** [comment]
thanks
