### ISSUE TITLE
Integration Erlensee Abfallkalender

### ISSUE THREAD

**Issue by gomble** [mampfes/hacs_waste_collection_schedule#110]
Hey it is possible that you can integrate the trash calendar from erlensee?
https://sperrmuell.erlensee.de/?type=reminder

**Comment by mampfes** [comment]
You can use the ICS source for that. I added an [example](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#erlensee) to the ICS docu.
