### ISSUE TITLE
Request for South Somerset Council UK

### ISSUE THREAD

**Issue by ky3mr2** [mampfes/hacs_waste_collection_schedule#1106]
Hi,

Would anyone be able to look at the South Somerset Council collection:

https://www.somerset.gov.uk/bins-recycling-and-waste/refuse-collections/

https://iweb.itouchvision.com/portal/f?p=customer:BIN_DAYS:::NO:RP:UID:625C791B4D9301137723E9095361401AE8C03934

Looks like it is using Oracle Apex, not something I am familiar with and very much outside my capabilities!

Thanks

**Comment by 5ila5** [comment]
started with this https://github.com/5ila5/hacs_waste_collection_schedule/tree/itouchvision_com and got stuck with a 
`Page protection violation` response not quite sure why.
I will not be on my PC the upcoming week. 
I thought I will just let this here, maybe someone wants to tinker a bit with this.

**Comment by 5ila5** [comment]
added by #1111 
will be part of release 1.42.0 or is available now as master/git version
