### ISSUE TITLE
Add Landkreis Emsland, Germany source

### ISSUE THREAD

**Issue by gebongt** [mampfes/hacs_waste_collection_schedule#1112]
Hello,

is it possible to add Landkreis Emsland (Germany) to sources?

They have data on website and also via app download:

Website:
https://www.awb-emsland.de/service/abfuhrkalender/

APP:
https://www.awb-emsland.de/service/awb-emsland-app/

Thansk a lot

**Comment by 5ila5** [comment]
Added by #1129

[Documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awb_emsland_de.md)

Will be part of release 1.42.0 or is available now as master/git version (up to date clone of this repository)
