### ISSUE TITLE
“TBA” Basingstoke and Deane waste collection

### ISSUE THREAD

**Issue by clipzwb** [mampfes/hacs_waste_collection_schedule#1125]
Keep getting “TBA” on collection icons (waste, recycle and garden) and not the date anymore. Will randomly work again but then goes back to TBA and can stay like this for days/weeks on end. Any ideas?

**Comment by 5ila5** [comment]
looks like a SSL Error they seem to not provide the full certificate chain (Browsers can work around this, the python requests library using openssl cannot) I disable SSL all together for now (#1127).

Changes will be part of release 1.42.0 or are available now as git/master version
