### ISSUE TITLE
Details_format: None, feature request

### ISSUE THREAD

**Issue by ThomDietrich** [mampfes/hacs_waste_collection_schedule#113]
Hey,
simple request. With multiple sensors defined it does not make sense to add the same attributes to all of them. No harm but still, a None option would be nice.

https://github.com/mampfes/hacs_waste_collection_schedule/blob/a961a3099454e2919b62524f38f537c39236cb87/custom_components/waste_collection_schedule/sensor.py#L27-L32

**Comment by ThomDietrich** [comment]
Any opinion on this? Happy to contribute PR

**Comment by mampfes** [comment]
Hi, feel free to submit a PR. But I'm not sure which problem you want to solve? Do you want to save resources? From a user perspective it is pleasant if the data is available on every sensor. Or do I miss something?

**Comment by ThomDietrich** [comment]
I generally agree with you! I made heavy use of the `value_template` to generate many entities and ended up with this:

![image](https://user-images.githubusercontent.com/2870104/144759673-30d81ad8-385d-495b-ae1e-8b2320f9b646.png)

Absolutely agree that the additional data doesn't hurt, nor is there a performance argument. I would simply feel better if they were gone, for ease of mind I guess :)
No harm in offering the option. Maybe I am not the only one using them :)

**Comment by ThomDietrich** [comment]
Ignore what I said.
While looking at my own screenshot I had to agree that the addition information is useful, but too much. This can be solved by the option `count`.

```
```

From my point of view, this is settled. Thanks for your great work with this integration
