### ISSUE TITLE
Integration with Somset Council

### ISSUE THREAD

**Issue by jameswilso** [mampfes/hacs_waste_collection_schedule#1135]
I'm trying to configure for Somerset Council with configuration.yaml of:
waste_collection_schedule:
  sources:
    - name: iweb_itouchvision_com
      args:
        postcode: "BS25 XXX"
        uprn: "1000XXXXXXXX"
        council: "SOMERSET"
      customize:
        - type: Refuse
          show: True

Sensor.yaml of:
- platform: waste_collection_schedule
  source_index: 0
  name: somerset
  details_format: "upcoming"
  types:
    - Refuse

Log file is generating several errors as below. Any advice as to what I'm doing wrong.
Error adding entities for domain sensor with platform waste_collection_schedule
21:57:07 – (ERROR) Sensor (custom integration) - message first occurred at 21:57:07 and shows up 2 times
Error while setting up waste_collection_schedule platform for calendar
21:57:07 – (ERROR) Calendar (custom integration)
Error doing job: Future exception was never retrieved
21:57:07 – (ERROR) waste_collection_schedule (custom integration)
source not found: iweb_itouchvision_com
21:57:07 – (ERROR) waste_collection_schedule (custom integration)

**Comment by dt215git** [comment]
Are you sure your local HA instance has the relevant source file?
This GitHub repo runs ahead of the version installed using HACS. If the file is missing you can manually copy it from here to you local system, or wait for the next release to be pushed out.

**Comment by jameswilso** [comment]
I've reinstalled through HACS and showing it is at 1.41.0.

**Comment by dt215git** [comment]
This source was added after the 1.41.0 release was pushed out, hence the `source not found: iweb_itouchvision_com` error message. If you want to get it working ahead of the next release, you'll need to copy the [iweb_itouchvision_com.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/iweb_itouchvision_com.py) file to your local HA instance, restart it, and then it should find it.

**Comment by jameswilso** [comment]
perfect works now thank you
