### ISSUE TITLE
Request Aylesbury Vale Council (Buckinghamshire, UK)

### ISSUE THREAD

**Issue by MrSeanRoss** [mampfes/hacs_waste_collection_schedule#1139]
Name of Council
Aylesbury Vale 

Example Postcode
LU7 9EQ

Additional Information
https://www.buckinghamshire.gov.uk/waste-and-recycling/find-out-when-its-your-bin-collection/

https://account.aylesburyvaledc.gov.uk/resident2/s/guest-flow-form?service_ref=DSHLC_AVDC_Find_Bin_Days

This council site is a child of the Buckinghamshire Council site and seems to work the same as the Chilterns site https://github.com/robbrad/UKBinCollectionData/issues/154#issue-1523059303

**Comment by 5ila5** [comment]
added by #1153

will be part of release 1.42.0 or is available now as master/git version (up to date clone of this repository)
