### ISSUE TITLE
FR: Add Belgian "Recycle!" service provider

### ISSUE THREAD

**Issue by kbrigitta** [mampfes/hacs_waste_collection_schedule#114]
Not sure if this is the correct location to post requests, but I was wondering if the Belgian service provider "Recycle!" could be added to the supported service providers?

Website: https://recycleapp.be/

**Comment by mvereecken** [comment]
I was looking for the same!

**Comment by mampfes** [comment]
Could you share some test addresses to examine the service?

**Comment by mvereecken** [comment]
Hi, it uses data from recycleapp.be. I can find more info in another custom component that uses it: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/master/custom_components/afvalbeheer/sensor.py (search voor recycleapp in the file). Maybe this is useful?

**Comment by mampfes** [comment]
See release 1.13.0. Please let me know if it is working for you.
