### ISSUE TITLE
Add support for ESN Neustadt an der Weinstraße

### ISSUE THREAD

**Issue by dev-inside** [mampfes/hacs_waste_collection_schedule#1142]
Hey guys,
it would be great, if you could implement the support for my local service. They seem to use a customized version of the MyMüll.de service. They provide us with a search under https://esn.jumomind.com/webmodul/neustadt/ for ICS-Downloads or schedule printing.

I'd looked into the Chrome Dev-Tools and it returns with my credentials the following JSON-File: https://esn.jumomind.com/webservice.php?idx=termins&city_id=1&area_id=427&ws=3

Thank you in advance.

**Comment by 5ila5** [comment]
jumomind is allready supported by [the jumomind_de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/jumomind_de.md) I added documentation for ESN in #1160
