### ISSUE TITLE
Problem with 'North Adelaide Waste Management Authority" info

### ISSUE THREAD

**Issue by haps-basset** [mampfes/hacs_waste_collection_schedule#1144]

**Comment by haps-basset** [comment]
Could you help me to troubleshoot the following problem?  After updating the integration to the latest version, I lost the capability to get info about the waste collection.  
The config contains 
waste_collection_schedule:
  sources:
    - name: nawma_sa_gov_au
      args:   
        suburb:   XXXXX
        street_name: YYYYY 
where YYYYY and XXXX are recognized by https://www.nawma.sa.gov.au/

The log and history show that the service is off and No logbook events found.
 Any advice on this matter is highly appreciated.

**Comment by 5ila5** [comment]
We did not change this source in the last 15 months and our test cases work just fine:

```python
TEST_CASES = {
    "128 Bridge Road": {
        "street_number": "128",
        "street_name": "Bridge Road",
        "suburb": "Pooraka",
    },  # Monday
    "226 Bridge Road": {
        "street_number": "226",
        "street_name": "Bridge Road",
        "suburb": "Pooraka",
    },  # Monday reverse
    "Whites Road": {"street_name": "Whites Road", "suburb": "Paralowie"},  # Tuesday
    "Hazel Avenue": {
        "street_name": "Hazel Avenue",
        "suburb": "Angle Vale",
    },  # Wednesday
    "155 Murray St": {
        "street_name": "Murray Street (sec between Ayers and the railway line",
        "suburb": "Gawler",
    },  # Thursday
    "Edward Crescent": {
        "street_name": "Edward Crescent",
        "suburb": "Evanston Park",
    },  # Friday
}
```


you could try to open your developer tools on the calendar page https://www.nawma.sa.gov.au/kerbside-collections/bin-collection-days/ open the network section and search for your address. You should see a request to .../admin-ajax.php in the payload section you can see the parameters needed for the correct response.

area = suburb 
+ is normal space

Example: 
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38183212/c39b9364-a25e-4564-a025-b56d294d587e)

Make sure the page actually returns data and your parameters match the ones of the request. pid defaults to 2444 (worked for all our cases)

**Comment by haps-basset** [comment]
Many thanks for your support,  I have followed your instruction and I found the culprit.  I did something foolish and somehow I installed two instances of the integration entity, but what I did, no idea.
Now both calendars work fine although the entity shows a message off. I am confused, can you explain why I am getting this message?
Once again, sorry for my ignorance but HA development is new for me
Once again many thanks
![Screenshot 2023-08-18 145302](https://github.com/mampfes/hacs_waste_collection_schedule/assets/20885804/cc4f5a8d-b2ba-4c37-813a-b53c0c10ea77)

**Comment by 5ila5** [comment]
This is expected behaviour.
The state of an calendar entity signals weather an event of this calendar is currently "running" (the state would be set to true on any collection date of this calendar entity).
