### ISSUE TITLE
Regioentsorgung_de: sensors go to unkown state after reaching 0 days

### ISSUE THREAD

**Issue by pinsdorf** [mampfes/hacs_waste_collection_schedule#1159]
I've been using this integration successfully for months now. Currently, I'm observing that all my sensors go to 'Unknown' state one after another. More precisely, each sensor changes to ..., 3, 2, 1, 0 days as expected and then turns to 'unkown' for the next date scheduled, instead of starting again at 14 days (or whatever the value is). The unknown state stays, i.e. it is *not* just on collection day.

I use source regioentsorgung_de. The url in the source file seems ok. Calling the service `waste_collection_schedule.fetch_data` manually does not help.

The version of my integration is 1.41.0 (latest). Updated to this version a few days ago (from 1.39.0 ?). HA, HACS, and HA OS are on latest versions as well. In the HA logs I could not find any error related to this. Data on the source's website is available. I could not find any extra log file of this integration in the file system.

Thanks for your help.

**Comment by 5ila5** [comment]
are there any future events in the calendar when your sensor gets unknown. Does this happen because "not enough" events are fetched? could you provide your sensor configuration?

**Comment by pinsdorf** [comment]
Thanks, @5ila5. I took a deep look in my configuration and the data received from `regioentsorgung_de`. In fact, the source has modified its data fields! Three out of six waste collection names have changed. 

* `Restabfall 2-Rad-Behaelter 02-woechentl.` became `Restabfall S035 02-woechentl.`
* `Papierabfuhr 2-Rad-Behaelter 04-woechentl.`became `Papierabfuhr 0360 04-woechentl.` 
* `Bioabfall 2-Rad-Behaelter 02-woechentl.` became `Bioabfall 0240 02-woechentl.`
* `Gelbe Saecke` did not change
* `Gruenschnitt-Strassensammlung` did not change
* `Weihnachtsbaum-Sammlung` did not change

So, this was not issue with the plugin as such, but was rooted in the data provider. If you run into a similar issue then download the ICS file from https://regioentsorgung.de/service/abfallkalender/, open it in a text editor / VS Code  and doublecheck the names of the calendar entries.  Adapt your configuration in HA accordingly.

Thank you!

**Comment by pinsdorf** [comment]
Supplemental: data provider [Regioentsorgung](https://regioentsorgung.de) (`regioentsorgung_de`) did it again. They made major changes to the labels in their ICS file. Well, the naming is more conistent now, but you have to touch your Home Assistant configuration again to fix it. Afterwards restart Home Assistant.

Here are the new correct names:
* `Restabfall 2-Rad Behaelter 02-woechentl.`
* `Papierabfuhr 2-Rad Behaelter 04-woechentl.`
* `Bioabfall 2-Rad Behaelter 02-woechentl.`
* `Gelbe Saecke`
* `Gruenschnitt-Strassensammlung`
* `Weihnachtsbaum-Sammlung`
        
Hope this helps!
