### ISSUE TITLE
Crawley

### ISSUE THREAD

**Issue by marc115uk** [mampfes/hacs_waste_collection_schedule#1166]
Hi would it be possible to add Crawley West Sussex? https://my.crawley.gov.uk/en/service/check_my_bin_collection
Many thanks

**Comment by 5ila5** [comment]
added by #1177 
[Documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/crawley_gov_uk.md) 

Will be part of release 1.42.0 or is available now as master/git version
