### ISSUE TITLE
How to add new sources for AWG

### ISSUE THREAD

**Issue by SkylightXD** [mampfes/hacs_waste_collection_schedule#117]
I like to add the calender from the AWG
https://awg-wuppertal.de/privatkunden/abfallkalender.html
by the abc_com.py script or any other way ;)
or this [https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/example.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/example.py)
At the moment I do not understand how it works ...
Could somebody help me?

I downloaded the file and at it locally to my HA, that works :) The next step is to automate the next years :)

**Comment by mampfes** [comment]
Hi, I already try to integrate AWG Wuppertal with the generic ICS source. Unfortunately, the service uses dynamic IDs and therefore requires a dedicated source.

I failed to figure out how the cHash parameter in the URLs is generated. If you want to contribute, I would look at this issue first.

You can also have a look at all the other source. Maybe this helps to understand who it works.

**Comment by SkylightXD** [comment]
The generation of the cHash was my first issue... I have no idea to fix it...

The next step for me is
- insert the street
- download the file for the current year

I have no idea for both :( but I try to understand the other scripts to solve this :)

Thanks for your answer :)

**Comment by mampfes** [comment]
cHash is a caching mechanism of Typo3. But I didn't yet found out how to either calculate the value for the given arguments or how to fetch the cHash value from webpage.

**Comment by SkylightXD** [comment]
I send them an email. If I got any information I will share them with you :)

**Comment by SkylightXD** [comment]
In the near future they will change the file name to a readable version, so I think we can wait for this? 
This is the answer by the AWG :)

Wir haben unserer IT-Abteilung informiert und haben folgende Antwort erhalten:

Im Moment wird dieser Hash aber automatisch berechnet – aus den Parametern wie Format, Straße, Hausnummer und Jahr.

In naher Zukunft könnten wir das für alle Exporte in eine lesbare Form umsetzen, wie z.B. „awg-abfallkalender-2022-Korzert-15.ics“. Im Moment ist das aber noch nicht möglich und der Hash lässt sich auch nicht leicht aus den Komponenten nachbauen.

Wir werden dies also auf unserer To do-Liste setzen.

**Comment by mampfes** [comment]
Yes, then I would wait.

**Comment by ThomDietrich** [comment]
> Im Moment ist das aber noch nicht möglich 

Sounds like "we will put this in the todo list, due date whenever". My guess is you need to ask for an update every two weeks to move anything there... Good luck!!

**Comment by mampfes** [comment]
Closed for the moment. Feel free to open this issue again if you have updates.

**Comment by KarlKaracho** [comment]
I have successfully installed the AWG Wuppertal calendar on my device.
The only thing I had to adjust was 

args:
  split_at: "/"

Because the summary writes several types of garbage in one line.

Here you can get the ics file for your adress.
https://awg-wuppertal.de/privatkunden/abfallkalender.html

**Comment by mampfes** [comment]
Great, thank!
