### ISSUE TITLE
Request for Rhondda Cynon Taf source

### ISSUE THREAD

**Issue by undulattice** [mampfes/hacs_waste_collection_schedule#1170]
Sample address here:
https://www.rctcbc.gov.uk/EN/Resident/RecyclingandWaste/RecyclingandWasteCollectionDays.aspx?uprn=200003766267

Collects

Recycling
Garden Waste
Food Waste
Black Bags

Thanks. :-)

**Comment by dt215git** [comment]
Looks like it's possible to extract a few month's worth of collections by iterating through from the calendar it displays, will see what I can come up with.

**Comment by undulattice** [comment]
> Looks like it's possible to extract a few month's worth of collections by iterating through from the calendar it displays, will see what I can come up with.

Nice once. Appreciate it. :-)

**Comment by 5ila5** [comment]
Added by #1181 

Will be part of release 1.42.0 or is available now as master/git version
