### ISSUE TITLE
South Holland, UK issue returning events

### ISSUE THREAD

**Issue by tapnet88** [mampfes/hacs_waste_collection_schedule#1172]
Hello I have setup the following in my config yaml

```
waste_collection_schedule:
  sources:
    - name: sholland_gov_uk
      args:
        postcode: "PE12 9**"
        uprn: "100943535**"
```

I can see a separate calendar created, however when the events are being returned i'm getting this error

``
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 11:41:24 (1 occurrences)
Last logged: 11:41:24

fetch failed for source South Holland District Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/sholland_gov_uk.py", line 92, in fetch date = datetime.datetime.strptime(re.sub(r'(\d)(st|nd|rd|th)', r'\1', date_str), "%A %d %B %Y").date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '' does not match format '%A %d %B %Y'
``

So in my mind this is something where its expecting a different time format? Is this a misconfig in my HA setup?

**Comment by tapnet88** [comment]
```

Refuse : Friday
Next Refuse Collection: (present by 6am)
Recycling : Wednesday
Next Recycling Collection: (present by 6am)
Garden

You are not currently subscribed to our Garden Waste Collection Service.
```

Ah I think I see the problem..

I just tried a house number next door and got this:

```
Refuse : Friday
Next Refuse Collection: Friday 25th August 2023 (present by 6am)
Recycling : Wednesday
Next Recycling Collection: Thursday 31st August 2023 (present by 6am)
Garden

You are not currently subscribed to our Garden Waste Collection Service.
```

I will just use their uprn then

**Comment by 5ila5** [comment]
Looks like an error on their side

**Comment by Marvman100** [comment]
Hi
I know this is an old post but I'm having the same issue.
Same source - "sholland_gov_uk"

```
`waste_collection_schedule:
  sources:
    - name: sholland_gov_uk
      args:
        uprn: "100943573xx"
        postcode: PE12 6xx`
```

getting this in my log
```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 5:16:50 PM (1 occurrences)
Last logged: 5:16:50 PM

fetch failed for source South Holland District Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/sholland_gov_uk.py", line 92, in fetch date = datetime.datetime.strptime(re.sub(r'(\d)(st|nd|rd|th)', r'\1', date_str), "%A %d %B %Y").date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '' does not match format '%A %d %B %Y'
```

It creates the local colander "South Holland District Council" but empty 
 
Guessing this is an issue with the source/format received as I tested with another users/source found on Reddit and this works

```
 waste_collection_schedule:
    sources:
    - name: maldon_gov_uk
      args:
        uprn: "100091257514"
```

Any help appreciated

**Comment by 5ila5** [comment]
@Marvman100 when checking your address on the website are there valid dates for the next [...] collection attributes?

 (https://github.com/mampfes/hacs_waste_collection_schedule/issues/1172#issuecomment-1690113763)
  if so could you please post your next collection strings.

If there is no valid date listed (like for https://github.com/mampfes/hacs_waste_collection_schedule/issues/1172#issuecomment-1690271190), you need to check weather the address for you neighbours (with the same schedule) return valid addresses and use their uprn. In this case there is not really something we can do about it.

**Comment by Marvman100** [comment]
@5ila5 
Thanks for your reply and sorry I should have given that information in my post 

Yes when I go to https://www.sholland.gov.uk/mycollections I do get next pick info (see screenshot)

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/98971642/fc187fb1-431d-445b-8aa1-5c6c5595a6af)

I have tested using a neighbours uprn or even another street but same issue

Thanks

**Comment by 5ila5** [comment]
your address has the same problem to not list any date but just the weekday. You can either find a address wit the same schedule, that lists specific dates. or use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) to display refuse on Tuesdays and Recycling on Wednesdays you can add exceptions (for holidays)
