### ISSUE TITLE
Waste Collection today only on for 1 hour.

### ISSUE THREAD

**Issue by jasonwfrancis1** [mampfes/hacs_waste_collection_schedule#1173]
When waste is due to be collected on the day, the sensor only shows that status for 1 hour. It changes at midnight, and then changes to the next collection status at 1am. I'm assuming this is when the polling happens to update data?

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/6323379/d47f6831-d0c9-4648-8b67-bb339b724f6d)

I have this value in my yaml set to 1700 which is when i would expect the status to change?
day_switch_time: "17:00"

**Comment by 5ila5** [comment]
What source are you using. We might be able to change this behaviour to prevent this for the default configuration.

**Comment by jasonwfrancis1** [comment]
UK - bristol city council

Sent from my iPhone

On 23 Aug 2023, at 3:58 pm, 5ila5 ***@***.***> wrote:

﻿

What source are you using. We might be able to change this behaviour to prevent this for the default configuration.

**Comment by 5ila5** [comment]
Made this minor improvement in #1176, which will be part of release 1.42.0 or now as master/git branch

**Comment by jasonwfrancis1** [comment]
Thanks!
