### ISSUE TITLE
recollect.md links point to missing files in forks

### ISSUE THREAD

**Issue by dt215git** [mampfes/hacs_waste_collection_schedule#1178]
**@5ila5:** This might be related to the recent changes you made as part of #1154.

The links are currently pointing to a non-existent files in your fork. If I run update_docu_links.py, the links then point to a non-existent files in my repo. It seems to have affected info.md, README.md and ics.md

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/cd9156b8-e599-48db-b96b-d66a9dd22f24)

**Comment by 5ila5** [comment]
Thanks for pointing this out.

fixed by #1180
