### ISSUE TITLE
Request for Jülich (ZEW)

### ISSUE THREAD

**Issue by enwi** [mampfes/hacs_waste_collection_schedule#1182]
Can you add Jülich or all ZEW cities?

Website:
[https://zew-entsorgung.de/](https://zew-entsorgung.de/)

API:
[https://zew2-abfallapp.regioit.de/abfall-app-zew2/rest/hausnummern/11608250/termine?fraktion=0&fraktion=5&fraktion=6&fraktion=7&fraktion=8&fraktion=9&fraktion=10](https://zew2-abfallapp.regioit.de/abfall-app-zew2/rest/hausnummern/11608250/termine?fraktion=0&fraktion=5&fraktion=6&fraktion=7&fraktion=8&fraktion=9&fraktion=10)

[https://zew2-abfallapp.regioit.de/abfall-app-zew2/rest/hausnummern/11608250/fraktionen](https://zew2-abfallapp.regioit.de/abfall-app-zew2/rest/hausnummern/11608250/fraktionen)

**Comment by 5ila5** [comment]
ZEW is already supported by the [abfallnavi_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md) source. under the name `AWA Entsorgungs GmbH`

I added  to `ZEW Zweckverband Entsorgungsregion West` to the readme in #1183

**Comment by enwi** [comment]
@5ila5 Ahh very nice, I must have missed that :)
