### ISSUE TITLE
Request: Sandnes, Norway

### ISSUE THREAD

**Issue by sjabby** [mampfes/hacs_waste_collection_schedule#1190]
Would it be possible to add support for the Collection Schedule for Sandnes, Norway?
Cant find any ical, rss, or data source. Maybe scraping?
Search for address: https://www.hentavfall.no/rogaland/sandnes/tommekalender/
Valid address: https://www.hentavfall.no/rogaland/sandnes/tommekalender/show?id=181e5aac-3c88-4b0b-ad46-3bd246c2be2c&municipality=Sandnes%20kommune%202020&gnumber=62&bnumber=281&snumber=0

I believe its using the same backend as #662

**Comment by 5ila5** [comment]
We could try to use the MinRenovasjon app (https://play.google.com/store/apps/details?id=no.norkart.komtek.renovasjon.client&hl=no) this would add support for a lot more Norwegian municipals

**Comment by sjabby** [comment]
@5ila5 MinRenovasjon does not support Sandnes Kommune.
