### ISSUE TITLE
Request: Dudley Council, UK

### ISSUE THREAD

**Issue by danbayliss** [mampfes/hacs_waste_collection_schedule#1193]
Would it be possible to add Dudley Council to this integration? You can view the specific schedule by going to http://maps.dudley.gov.uk/mycouncil.aspx and entering a postcode (Use DY8 5PE if you need a postcode) then select the address. You then get the following details in one of the panes

![O0LUsTT](https://github.com/mampfes/hacs_waste_collection_schedule/assets/54558493/ad36f931-0726-48ce-bd2b-903ba8fd6e00)

**Comment by dt215git** [comment]
Looks like you can get results pages with a single query using the uprn.
Might need to guess at whether they stick with the DD MMM date format towards the year end, or switch to DD MMM YYYY when there are dates from two calendar years involved.

The response also seems to contain this info, but it's not displayed on the website.
<table class='ResultsTable'>
<tr><th align="left">Collections due...</th><th>...will be collected on</th></tr>
<tr><td>Monday 21 Dec</td><td>Saturday 19 Dec</td></tr>
<tr><td>Tuesday 22 Dec</td><td>Monday 21 Dec</td></tr>
<tr><td>Wednesday 23 Dec</td><td>Tuesday 22 Dec</td></tr>
<tr><td>Thursday 24 Dec</td><td>Wednesday 23 Dec</td></tr>
<tr><td>Friday 25 Dec</td><td>Thursday 24 Dec</td></tr>
<tr><td>Friday 1 Jan</td><td>Saturday 2 Jan</td></tr>
</table>

Do you know if they account for this in what they display, or whether we'd have to also factor this into a script?

**Comment by dt215git** [comment]
Great, I'll tidy up what I've got and submit a PR, we can always revisit it in Dec/Jan if things go wonky.

**Comment by 5ila5** [comment]
Added by #1192 
Will be part of release 1.42.0 or is available now as master/git version
