### ISSUE TITLE
Request: Gwynedd Council, UK

### ISSUE THREAD

**Issue by TheMadAxeMan** [mampfes/hacs_waste_collection_schedule#1194]
Would it be possible to add Gwynedd Council to the integration?  

https://diogel.gwynedd.llyw.cymru/Daearyddol/en/LleDwinByw/Index/200003177805

The lookup URL is via the UPRN like the example above which produces the output as shown below

<img width="283" alt="Screenshot 2023-08-29 at 10 51 23" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/74316854/65aee713-aa6b-4568-9906-f3fd02f5ce4d">

Many thanks for your efforts

**Comment by 5ila5** [comment]
Added by #1196

Will be part of release 1.42.0 or is available now as master/git version
