### ISSUE TITLE
Request: Durham County Council

### ISSUE THREAD

**Issue by andyblac** [mampfes/hacs_waste_collection_schedule#1200]
could you add support for Durham County Council

https://www.durham.gov.uk/bincollections

test post code: DL16 7AB

Thanks

**Comment by 5ila5** [comment]
Added by #1201

Will be part of release 1.42.0 or is available now as master/git version

**Comment by andyblac** [comment]
Wow!!, thanks a lot it works great.
<img width="311" alt="Screenshot 2023-08-30 at 21 58 28" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/77936/4620a54a-c5e6-47f5-8a2c-16c2f068e4b8">
