### ISSUE TITLE
Possible to add new source / Landkreis Cham

### ISSUE THREAD

**Issue by Zuendapp** [mampfes/hacs_waste_collection_schedule#1208]
Hi :),

is it possible to add a new source for the landkreis Cham in Germany (https://pwa.entsorgung-cham.de/).

Thank you very much for your plugin!!!

BR

**Comment by 5ila5** [comment]
Landkreis Cham provides a static ICS file download so it's supported by the ics source
added [documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/entsorgung_cham_de.md) for Cham in #1210
