### ISSUE TITLE
Add a relaxed retry period to fetching errors

### ISSUE THREAD

**Issue by ThomDietrich** [mampfes/hacs_waste_collection_schedule#121]
Relates to:

https://github.com/mampfes/hacs_waste_collection_schedule/blob/9ce0fd55010bbab3948f1ee0aa5edb4b65b7d866/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py#L130

It is to be expected that services are not always reachable at every given time. Would you consider to accept a certain amount of unsuccessful attempts before an error is written to log (on the ERROR level)!? The HA log should be kept clean as much as possible and a single fetch error in the waste_collection_schedule shouldn't be worth spooking the user :)

**Comment by mampfes** [comment]
I agree that the home assistant log should not be flodded with error messages. From my experience, the services are available almost 100% (to be honest, I have never experienced an outage). Therefore a missing fetch is a noticeable failure which I have no doubt to write to the log (once per day). Do you have other experiences?

**Comment by ThomDietrich** [comment]
Seems like it. In fact two of my Home Assistant instances that query the AWM München web service have the issue in their log. Can't currently say when or how often this happens.

![image](https://user-images.githubusercontent.com/2870104/144759990-54126906-8ce6-43c2-8826-696f3b7d3f39.png)

Happy to keep an eye out for it.

> Therefore a missing fetch is a noticeable failure

While at it, maybe you could improve the error a little. The typical end user will only be distracted by the object address

**Comment by ThomDietrich** [comment]
Traced the error and had to find out that @jberrenberg already commited a fix. Thanks! https://github.com/mampfes/hacs_waste_collection_schedule/commit/47f8250bdd40eb9a4b4f842498b3cd4af5968062

Food for thought: This would have been a lot easier without the cascade of super generic `try ... except Exception` blocks in the code. Python offers a lot more than that. Example: After removing them it took me seconds to identify the error and a solution. 

Feel free to close the issue

**Comment by mampfes** [comment]
Agree. The error message and the try .. except cascade is bad. Feel free to submit a PR :-)

**Comment by ThomDietrich** [comment]
I would be happy to but I feel this is a job better suited for someone who has a deeper understanding of the project, to make the right structural decisions. 

Let's discuss. I would probably approach this by putting a `try...except` block around `entries = self._source.fetch()` alone. This method is just too explosive looking at all the different sources already implemented. Next I would break out different Exception classes to narrow down the error. Alternatively or additionally use the traceback library to recover the trace for logging. In case of doubt I would always want more logging details.

**Comment by mampfes** [comment]
fixed in release 1.16.0
