### ISSUE TITLE
Request for North Yorkshire Council [UK] (Hambleton)

### ISSUE THREAD

**Issue by antonyslater** [mampfes/hacs_waste_collection_schedule#1211]
Hi,
Would it be possible to add North Yorkshire Council (Hambleton)?

https://hambletondc-self.achieveservice.com/service/Bin_collection_finder

Thank you

**Comment by 5ila5** [comment]
I nearly finished the source.

But the website shows different collection dates in different sections. Do you know which of them are the real ones?
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38183212/cc73e8fd-c312-4d4f-a0cf-0e5225ed2a7f)

**Comment by antonyslater** [comment]
> I nearly finished the source.
> 
> But the website shows different collection dates in different sections. Do you know which of them are the real ones @antonyslater? ![grafik](https://user-images.githubusercontent.com/38183212/264733061-cc73e8fd-c312-4d4f-a0cf-0e5225ed2a7f.png)

For the recycling and garden it will be Mon 4th, for the refuse it will be Mon 11th. Or should be based on my address.

**Comment by dt215git** [comment]
The lower  table has `week beginning` dates, so collections in that row of the table take place the week beginning on that date (assumes the date is for a Monday).

The bin image indicates the collection is on the Tuesday - that's 1 day after the Monday `week beginning` date, so the collection date is incremented by 1 day giving the dates in the upper table.

If you wanted to use the  extended collection schedule, you'd need to pull out the day from the _img alt_ tag and  increment the `week beginning` date by the appropriate amount.

**Comment by 5ila5** [comment]
Added by #1212 

Will be part of release 1.43.0 or is available now as master/git version.

Using the extended calendar is more complex and unfavourable to minor changes (delay text etc.) so I used the table above. Hope the dates are correct on holidays. Unfortunately this only returns one collection date in the future per type.

**Comment by antonyslater** [comment]
Thank you for sorting this so quickly!! :-) 
I will await the next release, just out of curiosity do you have any idea when that might be?

**Comment by 5ila5** [comment]
@antonyslater 1.41.0 was just released 2 days ago. We typically release a new version every 1-2 Month.
If you want to use this now and you use HACS you can change the version to `master` (3 dot menu -> redownload)
(HACS will report now Version every time we change something in this repository which is very often so you might want to switch back once 1.42.0 releases)
