### ISSUE TITLE
Error when trying to add recycleapp api

### ISSUE THREAD

**Issue by mvereecken** [mampfes/hacs_waste_collection_schedule#122]
Hi, I tried to add the new collector; I got this error:

Exception in _update_sensor when dispatching 'wcs_update_sensors_signal': () Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/sensor.py", line 188, in _update_sensor upcoming1 = self._scraper.get_upcoming_group_by_day( File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 161, in get_upcoming_group_by_day self._filter( File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 191, in _filter entries = list(filter(lambda e: e.date > now, entries)) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 191, in <lambda> entries = list(filter(lambda e: e.date > now, entries)) TypeError: can't compare datetime.datetime to datetime.date

**Comment by mampfes** [comment]
Oh, sorry. Please try release 1.13.1

**Comment by mvereecken** [comment]
No problem, it works now! Thanks a lot!!
