### ISSUE TITLE
Add Braunschweig (Germany)

### ISSUE THREAD

**Issue by BiasF** [mampfes/hacs_waste_collection_schedule#1221]
Hey,

I am trying to Add ALBA Braunschweig to WCS. ALBA Uses AbfallPlus / Abfall IO, but the Website seems to be different 

The Website does not allow me to get the needed Values for the configuration as described in the doku.

Website: https://alba-bs.de/service/abfuhrtermine.html
Used Documentation: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md

Any Ideas?

Bias

**Comment by 5ila5** [comment]
They don't seem to use the "normal" abfallIO API for the web.
But you can get an ICS link. Do you now if this link (example https://alba-bs.de/service/abfuhrtermine/ajax-kalender.html?tx_mfabfallkalender_mfabfallkalender[action]=makeical&tx_mfabfallkalender_mfabfallkalender[controller]=Abfallkalender&tx_mfabfallkalender_mfabfallkalender[mf-trash-hausnr]=1&tx_mfabfallkalender_mfabfallkalender[mf-trash-hausnrzusatz]=&tx_mfabfallkalender_mfabfallkalender[mf-trash-month]=6&tx_mfabfallkalender_mfabfallkalender[mf-trash-strasse]=Hauptstraße&tx_mfabfallkalender_mfabfallkalender[mf-trash-thisyear]=2023&cHash=19f8231f1157557005a576f5dfc91646) is working indefinitely? Then you could just use the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) and I would just add documentation for alba-bs.de

The cHash parameter can be removed an the link still works.

**Comment by 5ila5** [comment]
alba-bs.de is supported by the ics source added documentation in #1223.

[Documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/alba_bs_de.md)
