### ISSUE TITLE
Add Enzkreis Mönsheim (germany)

### ISSUE THREAD

**Issue by satho2210** [mampfes/hacs_waste_collection_schedule#1230]
Hi, 

please add Mönsheim in Enzkreis
Details https://www.entsorgung-regional.de/entsorgung/leerungstermine/terminservice-ics-datei.html?icsgemeinde=M%C3%B6nsheim&icsortsteil=M%C3%B6nsheim&icsabfallart%5B%5D=Glas&icsabfallart%5B%5D=LVP&icsabfallart%5B%5D=Papier&icsabfallart%5B%5D=Restm%C3%BCll

or can you explain , how to add the information ?

**Comment by 5ila5** [comment]
entsorgung-regional.de is supported by the [ics/ical source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added specific documentation for for [entsorgung-regional.de / Enzkreis](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/entsorgung_regional_de.md). in #1235 
It might break if they change the ICS_DOWNLOAD key. If so we would need to write a dedicated source. Please raise a Issue (reopen this one)  if this ever happens
