### ISSUE TITLE
Request for Tameside Council (UK)

### ISSUE THREAD

**Issue by leopold005** [mampfes/hacs_waste_collection_schedule#1239]
I've had a good scour through the requests and I've not seen one for the borough I live in, which seems odd because there seems to be a heck of a lot of people who live here.  Maybe they're all tech luddites and I'm the only enlightened one??

Anyway, the URL for the link to the bin collections is: [https://public.tameside.gov.uk/forms/bin-dates.asp](https://public.tameside.gov.uk/forms/bin-dates.asp)

It goes off and asks for a postcode and/or address, then assembles what looks like a PDF, but appears to assemble dynamically.

Pretty much any postcode in OL5, OL6, SK14, SK15, SK16 or M34 should work.

**Comment by dt215git** [comment]
Looks like  the postcode and uprn can be used to pull back the schedule.
There are no DD/MM/YYY dates in the response, but it should be possible to reconstruct those using the `year`, `month`, and `day` text it displays. Will have a play.

**Comment by 5ila5** [comment]
Source will be part of release 1.43.0 or is available now as master (git) version

**Comment by leopold005** [comment]
I've just given this a whirl and so far it looks great!  I'll have to do a little tweaking to it and then figure out how I'm going to convert the information into something useful as a reminder, but the base is there and I'm well happy with it.

Thanks so much for the very rapid response and release for this, I appreciate all your efforts
