### ISSUE TITLE
Stadrreinigung Hamburg changed their endpoint

### ISSUE THREAD

**Issue by jurijzahn8019** [mampfes/hacs_waste_collection_schedule#124]
Hi there! 

as stated the guys changed the endpoint of the `ics`

the new one is: 

<https://backend.stadtreinigung.hamburg/kalender/abholtermine.ics?hnIds=HNID>

Can i just make a PR?

**Comment by mampfes** [comment]
fixed in 8fb27ccb860aee7a8751eb2fd920dde67ed42663

**Comment by jurijzahn8019** [comment]
When can we expect this to be released? :smile:

**Comment by JonasDoebertin** [comment]
@mampfes Can we support you in publishing this fix in a release in any way?

**Comment by mampfes** [comment]
@JonasDoebertin Please see release 1.14.0
