### ISSUE TITLE
Request for district Stadt Erlangen, Germany

### ISSUE THREAD

**Issue by mileskroell** [mampfes/hacs_waste_collection_schedule#1242]
Hi, would be great if you could support Stadt Erlangen, Germany
https://erlangen.mein-abfallkalender.de

**Comment by 5ila5** [comment]
Erlangen is already supported  (mein-abfallkalender listed in README.md) by the ICS source. Documentation for the ICS source with mein-abfallkalender can be found [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/mein_abfallkalender_de.md)
