### ISSUE TITLE
WAS Wolfsburg missing entries

### ISSUE THREAD

**Issue by boehser-enkel** [mampfes/hacs_waste_collection_schedule#125]
Hey there,

the WAS Wolfsburg integration is missing some dates:

Examples:
15.12.: Altpapier, Restabfall
22.12.: Bioabfall

Is there a bug?

Config:

`waste_collection_schedule:
  sources:
    - name: was_wolfsburg_de
      args:
        city: Vorsfelde-Nord
        street: "Zum Alten Teich"
      calendar_title: Müll          
  day_switch_time: " 12:00"  
  
sensor:
  - platform: waste_collection_schedule
    name: Abfall
    details_format: upcoming
    count: 4
    leadtime: 4
    value_template: '{{value.types|join(", ")}}'
    add_days_to: true
#    types:
#      - altpapier

  - platform: waste_collection_schedule  
    name: Abfalltage
    details_format: upcoming
    value_template: '{{ value.daysTo }}'
    count: 4
    leadtime: 4`

![grafik](https://user-images.githubusercontent.com/59539881/146133234-49b0d238-a5c9-4a97-a979-308d2ef26459.png)

greetz

**Comment by mampfes** [comment]
This source uses the ICS file provided by WAS Wolfsburg. But this file only includes schedules for 2022. Obviously they simply replaced the ICS file for 2021 :-( 
Sorry, but this issue is mainly caused by your service provider.

**Comment by boehser-enkel** [comment]
That's it. Thanks for the info
