### ISSUE TITLE
Add AHE (Ennepe-Ruhr-Kreis, Germany)

### ISSUE THREAD

**Issue by iSnackyCracky** [mampfes/hacs_waste_collection_schedule#1255]
I'd be great if [AHE GmbH](https://www.ahe.de/abfuhrtermine/) for Ennepe-Ruhr-Kreis (Germany) could be added.
They provide a proprietary mobile app and also a website from where one can download the specific schedule as either CSV or ICS file:
https://ahe.atino.net/pickup-dates

I've already looked into the requests made by that page.
First you need to get specific postal-code, city and street IDs from the `/search/` endpoint. With these you can issue a POST request to the `/pickup-dates` endpoint, however this seems to need a cookie containing a `PHPSESSID` and a `_token` value in the POST body (I think these make it impossible to use the generic ICS source), which you can both get from an initial request to the same endpoint.

I'd be happy to provide a pull-request but I don't have any python experience..
I've got a working PowerShell example however, maybe this can help somehow:

```
# base URI
$apiBase = "https://ahe.atino.net"

# address Values
$postalCode = "58300"
$street = "Nielandstr"
$houseNumber = "36"

# output format (0 = csv, 1 = ics)
$format = 1

# create new PHP session
$initialRequest = Invoke-WebRequest "$apiBase/pickup-dates"

# get API-Token from request
$token = ($initialRequest.InputFields | Where-Object id -eq pickup_date__token).value

# get address Info from /search/ API endpoint
$postalCodeId = Invoke-RestMethod "$apiBase/search/postalcode?q=$postalCode"
$cityId = Invoke-RestMethod "$apiBase/search/city?postalCode=$postalCode"
$streetId = Invoke-RestMethod "$apiBase/search/street?q=$street&cityId=$($cityId.id)"

# extract PHP session ID from request...
[string]$initialRequest.Headers."Set-Cookie" -match "PHPSESSID=(.*?);"
$PhpSessionId = $Matches[1]

# ... and create a cookie with it
$Cookie = New-Object System.Net.Cookie
$Cookie.Name = "PHPSESSID"
$Cookie.Value = $phpSessionId
$Cookie.Domain = ([System.Uri]$apiBase).DnsSafeHost

# create session to use the cookie in final request
$WebSession = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$WebSession.Cookies.Add($Cookie)

# create POST data with values from above
$params = @{
    "pickup_date[postalCode]" = $postalCodeId.id;
    "pickup_date[street]" = $streetId.id;
    "pickup_date[houseNumber]" = $houseNumber;
    "pickup_date[format]" = $format;
    "pickup_date[submit]" = "";
    "pickup_date[_token]" = $token
}

# finally send the POST request to /pickup-dates API endpoint
Invoke-RestMethod "$apiBase/pickup-dates" -Method Post -Body $Params -WebSession $WebSession
```

The result seems to include the schedule for the next  4.75 Months (19 weeks) at least from today. Could also be always for the current year or so though.

I'm happy to try and provide further explanation or details if needed.

**Comment by 5ila5** [comment]
source will be part of release 1.43.0 or is available now as master (git) version
