### ISSUE TITLE
Request to add County/District/ Stendal (Germany)

### ISSUE THREAD

**Issue by EmilSepa** [mampfes/hacs_waste_collection_schedule#1276]
Hey, 
first of all for your great work. 
Is it possible to add the collection schedule for the district Stendal (Germany). 
You can find all the information here: 
https://als-stendal.de/entsorgungstermine/

Thanks in advance. :)

**Comment by 5ila5** [comment]
als-stendal.de uses abfall-app.net it's supported by the ics source I added [documentation for this](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfall_app_net.md) in #1279
