### ISSUE TITLE
Source awigo_de not working

### ISSUE THREAD

**Issue by nosp00n84** [mampfes/hacs_waste_collection_schedule#1277]
Hi,

awigo_de is not working. No Calendar entries.
Tried the example and other adressess. Even with postcode (as required on the website).

Another source was working without problems.

**Comment by kevinholtkamp** [comment]
See #1268

**Comment by nosp00n84** [comment]
Ah, didn't notice that one. Sorry!
Changed to master. Everything working fine now.
Thank you!
