### ISSUE TITLE
Inner West garbage rule is wrong

### ISSUE THREAD

**Issue by alexohoh** [mampfes/hacs_waste_collection_schedule#1282]
Hi, the inner_west_gov_au source forces waste collection on the same day as any other bin type - this is incorrect (at least in SD12). Waste collection is separate to other types (though, the day coincides with recycling each fortnight)

**Comment by 5ila5** [comment]
fixed by #1284 
Will be part of release 1.43.0 or is available now as master (git) version

Looks like they changed the frontent too it does not do the same requests as our script we might need change this if they stop providing the data this way

**Comment by aaronpowell** [comment]
Just a note on what changed - the council has altered what bins are picked up when (we've moved to an organics collection weekly and then alternate recycling and rubbish across fortnights).

Thanks for the catch @alexohoh, I've just got back home and noticed the entities were wrong so went to fix it but I see @5ila5 beat me to it
