### ISSUE TITLE
Landkreis Roth Germany

### ISSUE THREAD

**Issue by tomg1970** [mampfes/hacs_waste_collection_schedule#1290]
Please integrate Landkreis Roth / Greding / Germany

https://www.landratsamt-roth.de/themen/bauen-wohnen/abfall/individueller-abfuhrplan

Many thanks

**Comment by 5ila5** [comment]
Landkreis Roth is supported by the awido_de source. I added Landkreis Roth to the documentation in #1292.

[Documentation for awido_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md)
