### ISSUE TITLE
Request to add Edlitz (AUT)

### ISSUE THREAD

**Issue by DaHofa02** [mampfes/hacs_waste_collection_schedule#1300]
would it be possible to add Edlitz Loweraustria to this schedule?

https://www.edlitz.at/Buergerservice/Muellabfuhrtermine

**Comment by dt215git** [comment]
It looks like  the whole town collected on the same day, so that correct?

**Comment by DaHofa02** [comment]
Yeah 

maybe this links help

Grüne Tonne
https://www.edlitz.at/app/kalender/225592185/895/1

Biomüllabfuhr
https://www.edlitz.at/app/kalender/225592094/895/1

**Comment by 5ila5** [comment]
added in above pull request.

will be part of release 1.44.0 or now as master version (HACS: 3 dot menu -> redownload -> change version to master)
