### ISSUE TITLE
Request: Please Add Braunschweig

### ISSUE THREAD

**Issue by Patrick38110** [mampfes/hacs_waste_collection_schedule#1301]
Please add Braunschweig :)

[https://alba-bs.de/service/abfuhrtermine.html](url)

**Comment by 5ila5** [comment]
alba-bs.de is supported by the ics source added documentation in #1223.

[Documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/alba_bs_de.md)
