### ISSUE TITLE
South Glos UK doesn't return all Recycling / Food Bin dates

### ISSUE THREAD

**Issue by AlexCPU** [mampfes/hacs_waste_collection_schedule#1305]
The South Gloucester UK source is only returning the Food Bin and Recycling bins every other week, when they should be every week.

Calendar in HA shows like this for me:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/4178651/ac283ac4-584a-429d-a20b-3f0dcf3a28c6)

The South Glos webpage shows:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/4178651/9ec0502d-0fc9-48a5-a16b-a44d69409f5f)

And the service endpoint that you are querying replies with:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/4178651/5f7dc0ec-762f-40a1-93a7-8824ac8c91e9)

I could put a PR in to treat the Rx dates as Recycling and Food as well?

**Comment by 5ila5** [comment]
Is this a problem with all addresses or just yours (your neighbourhood)? 
If it's a problem for all addresses feel free to make a PR

**Comment by 5ila5** [comment]
Thanks for your contribution
Fixed by #1311 will be part of release 1.43.0 or is available now as master (git) version
