### ISSUE TITLE
Set weekday language

### ISSUE THREAD

**Issue by SkylightXD** [mampfes/hacs_waste_collection_schedule#131]
How to change the weekday language from english to german?

This does not work:

value_template: >
      {% set days = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"] %}
      {% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} am {{value.date.strftime("%A")}}

Thanks and Regards

**Comment by SkylightXD** [comment]
obviously it is not possible to change the location in home assistant, so that the language of strftime is allways english ...
 
I try some more:
I create an array with the german weekdays an try to get them by value.date and some test values

    value_template: >-
      {% set wochentag = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"] %}
      {% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} am {{ wochentag[value.date.strftime("%w")] }} {{value.date.strftime("%w")}} {{ wochentag[1] }}

the result is 
in 14 Tagen am 5 Dienstag

That means 
{{value.date.strftime("%w")}}  is working, because the result is 5
{{ wochentag[1] }} is working, because the result is Dienstag
but the combination {{ wochentag[value.date.strftime("%w")] }} do not give any result ... it is just empty, but why? :D

**Comment by mampfes** [comment]
Maybe you have to convert it to an int first: `| int`

**Comment by SkylightXD** [comment]
yes! thats ist :)

`
value_template: '{% set wochentag = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}{% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} am {{ wochentag[ int(value.date.strftime("%w")) ] }}'
`

Now it works! Thanks a lot :)
