### ISSUE TITLE
Location request: Falkirk UK

### ISSUE THREAD

**Issue by Suldrun1** [mampfes/hacs_waste_collection_schedule#1319]
Please could you add Falkirk, UK?

https://www.falkirk.gov.uk/services/bins-rubbish-recycling

Thanks!

**Comment by 5ila5** [comment]
is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added [documentation for falkirk](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/falkirk_gov_uk.md)
