### ISSUE TITLE
Source add request Gotha (GER)

### ISSUE THREAD

**Issue by electrigga** [mampfes/hacs_waste_collection_schedule#1327]
https://www.landkreis-gotha.de/service/abfallservice/entsorgungsplaene/

**Comment by 5ila5** [comment]
allready supported by https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md 

You can even find it on the main README as [Landkreis Gotha](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) / landkreis-gotha.de
