### ISSUE TITLE
Source : sysav_se not working anymore?

### ISSUE THREAD

**Issue by maglerod** [mampfes/hacs_waste_collection_schedule#1337]
**Url are no longer valid?**
https://www.sysav.se/api/my-pages/PickupSchedule/ScheduleForAddress
https://www.sysav.se/api/my-pages/PickupSchedule/findAddress

HA Error:

fetch failed for source Sysav Sophämntning: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/sysav_se.py", line 47, in fetch waste_type = item["WasteType"] ~~~~^^^^^^^^^^^^^ TypeError: string indices must be integers, not 'str'

**Comment by maglerod** [comment]
> I don't think the urls are invalid. Only one of our 3 test cases has the same issue. the others return valid responses. The not working address also does not work on their side and returns 500 error on the website (https://www.sysav.se/Privat/min-sophamtning/) I do not think this is an issue on our side but on theirs
> 
> working:
> 
> * Sommargatan 1, Svedala
> * Stationsplan 1, Svedala
> 
> not working:
> 
> * Ekhagsvägen 204, Svedala
> 
> you may want to inform them about this error for some addresses

Thankyou, i will let them know!

**Comment by Zorkny** [comment]
This is the new URL and format - https://ca-weu-sysav-edp-api-prod.icypond-fdc05156.westeurope.azurecontainerapps.io/api/PickupSchedules/foraddress/Erlandsdalsgatan%201,%20Svedala

**Comment by 5ila5** [comment]
I'm closing this as this is fixed by the same fix as for #1536

**Comment by Zorkny** [comment]
Thanks for really great stuff and support, works for me too with master.

**Comment by 5ila5** [comment]
> Thanks for really great stuff and support, works for me too with master.

you should be able to use the newly released 1.45.0 as well
