### ISSUE TITLE
Add new source from Hungary/Erd

### ISSUE THREAD

**Issue by 5ila5** [mampfes/hacs_waste_collection_schedule#1341]
### Discussed in https://github.com/mampfes/hacs_waste_collection_schedule/discussions/1339

<div type='discussions-op-text'>

<sup>Originally posted by **sthevenp** October 19, 2023</sup>
Dear All,

Is there any chance to add this waste collection schedule service:

https://www.eth-erd.hu/hulladeknaptar

This page looks similar to this one: 
FKF Budapest, HU (tahnks @TMShader)

Thanks in advance.</div>

**Comment by TMShader** [comment]
Added it with PR #1344 :)

**Comment by 5ila5** [comment]
Source will be part of release 1.44.0 or is available now as master (git) version

**Comment by judgetom** [comment]
Hi, I tried to use this provider, but unfortunately it doesn't work. I also tried to change the API_URL in eth_erd_hu.py from "https://www.eth-erd.hu/trashcalendarget" to ""https://www.eth-erd.hu/hulladeknaptar", but it still does not work. Can you please check it? Thanks in advance.

**Comment by judgetom** [comment]
Hi,

unfortunately I don't see anything in the logs, the status of the entity is
"unknown". I tried it with the first and the second test case, nothing is
returned. If I try the other one for Hungary (fkf_bp_hu) it works properly.
What else should I check?
(The site https://eth-erd.hu/trashcalendergetstreets is currently under
construction, but I'm also not sure if it is the correct URL - can you
please check and give me some more information?

Thank you!

**Comment by 5ila5** [comment]
Which entity is unknown, the calendar or the sensors you created? "unknown" sensors mostly indicate an incorrect configured sensor. Is your calendar entity unknown? Are there entries in the calendar tab of HA? If so, make sure your `type` attribute (if used) of your sensor configuration actually matches the name of the returned entries in your calendar tab.

```yaml
waste_collection_schedule:
  sources:
    - name: eth_erd_hu
      args:
        city: Diósd
        street: Diófasor
        house_number: 10
```

If you still encounter any problems, please post your configuration (feel free to use example configuration instead of real address)

**Comment by judgetom** [comment]
Hi,

I get the attached error message when trying to configure it via integration.

![Image](https://github.com/user-attachments/assets/5a7d97b5-5f90-4c9e-b2d5-e5f1d79cb22f)
### 
Can you please check this issue?

Thanks!

**Comment by 5ila5** [comment]
looks like they changed their page (see #4227)

**Comment by galrenato** [comment]
Is there any chance to update Érd? It does not work.
Thanks in advance!
