### ISSUE TITLE
Source Request: For PTBO, Ont

### ISSUE THREAD

**Issue by Scraggarax** [mampfes/hacs_waste_collection_schedule#1346]
Hi there!

Would someone be able to add this source? 
[https://www.peterborough.ca/en/city-services/collection-schedule-and-events.aspx](url)

I'm not too versed with this, and having trouble figuring it out on my own...

Thanks!

**Comment by dt215git** [comment]
They appear to be using recollect.net, you should be able to use the [recollect.net](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md) source to pull back your calendar.

If it works, we can add Peterborough to to examples listed.
