### ISSUE TITLE
North Lincolnshire Collection fails to bring back collection information, issue and a possible fix

### ISSUE THREAD

**Issue by liamatkinsstorm** [mampfes/hacs_waste_collection_schedule#1354]
North Lincolnshire have added a (*) by the collection data:

"CollectionDate" : "2024-01-02 (*)"

Causing the waste collection schedule to fail with the error: pytho json ValueError: unconverted data remains: (*)

I have amended the source file northlincs_gov_uk.py by performing some try and except error correction to resolve this issue.  Below is the code I used which replaces from line 38 onwards:

        for collection in r_json:
            try:
                date = datetime.strptime(collection["CollectionDate"], "%Y-%m-%d").date()
                waste_type = collection["BinCodeDescription"]
                entries.append(
                    Collection(
                        date=date,
                        t=waste_type,
                        icon=ICON_MAP.get(waste_type),
                    )
                )
            except ValueError:
                collectiondate = collection["CollectionDate"]
                collectiondate = collectiondate.split(' ')
                date = datetime.strptime(collectiondate[0], "%Y-%m-%d").date()
                waste_type = collection["BinCodeDescription"]
                entries.append(
                    Collection(
                        date=date,
                        t=waste_type,
                        icon=ICON_MAP.get(waste_type),
                    )
                )
        return entries

Please can we get the source file updated with this?

Thanks

**Comment by 5ila5** [comment]
fix will be part of release 1.44.0 or is available now as master (git) version
