### ISSUE TITLE
Source Issue - Newcastle Under-Lyme

### ISSUE THREAD

**Issue by Malawigold** [mampfes/hacs_waste_collection_schedule#1358]
Hi all, I wonder if someone can help me fix this issue, I'm not getting any updates and the log files show:

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 15:32:44 (2 occurrences)
Last logged: 15:33:06
fetch failed for source Newcastle Under Lyme Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/newcastle_staffs_gov_uk.py", line 52, in fetch dt = datetime.strptime(cell.text, "%A %d %B %Y").date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '\n\r\n\r\n\r\n\r\n<configuration>\r\n <system.web>\r\n <customErrors mode="RemoteOnly" defaultRedirect="mycustompage.htm"/>\r\n </system.web>\r\n</configuration>\n' does not match format '%A %d %B %Y'

**Comment by dt215git** [comment]
It looks like they've changed the website url and page format that displays the schedule, the script will need updating.

**Comment by Doghousestaffs** [comment]
Strangely getting exact same error for stoke gov uk as well! Hello neighbour 🤣

**Comment by RyanTunstall** [comment]
Hi Neighbour. I’m also in Newcastle-under-Lyme and am having the same issue.

**Comment by 5ila5** [comment]
fixed by above PR.
Fix will be part of release 1.44.0 or is available now as master version (HACS: 3-dot menu -> redownload -> change version to master)

**Comment by RyanTunstall** [comment]
Many thanks. Sent from my iPhoneOn 4 Nov 2023, at 13:52, 5ila5 ***@***.***> wrote:﻿
fixed by above PR.
Fix will be part of release 1.44.0 or is available now as master version (HACS: 3-dot menu -> redownload -> change version to master)
