### ISSUE TITLE
Request: New source 

### ISSUE THREAD

**Issue by sam43434** [mampfes/hacs_waste_collection_schedule#137]
Hi, unsure if its possible but my local council uses the app https://apps.apple.com/au/app/my-local-services/id814144172   any possible way to add this as a source,  Have tried to find any api or source but seems to be out of my tech expertise

**Comment by mampfes** [comment]
Hi, does your local council offer a web based access?
Apps can't be used to create a source, because the typically use encryted traffic which cannot be easily examined.

**Comment by sam43434** [comment]
> Hi, does your local council offer a web based access? Apps can't be used to create a source, because the typically use encryted traffic which cannot be easily examined.

sadly not, and their calendar they offer is PDF based.   its okay figured it wasn't possible but thought id ask as if you don't ask you don't know lol
