### ISSUE TITLE
[source request]: Landkreis Anhalt-Bitterfeld

### ISSUE THREAD

**Issue by tonizabel** [mampfes/hacs_waste_collection_schedule#1385]
### Municipality / Region

Landkreis Anhalt-Bitterfeld, Germany

### Collection Calendar Webpage

https://www.abikw.de/kundenportal/abfalltourenplan/

### Example Address

Weißandt-Gölzau

### Collection Data Format

As ICS/ICAL file, Dedicated IOS/Android APP, As PDF Download

**Comment by 5ila5** [comment]
Landkreis Anhalt-Bitterfeld is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md)
[Documentation for Landkreis Anhalt-Bitterfeld](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abikw_de.md) added in above PR
