### ISSUE TITLE
[Source Request]: Anglesey, UK

### ISSUE THREAD

**Issue by paulcdb-backup** [mampfes/hacs_waste_collection_schedule#1388]
### Municipality / Region

Anglesey, UK

### Collection Calendar Webpage

https://myaccount.anglesey.gov.wales/en/AchieveForms/?form_uri=sandbox-publish://AF-Process-89048f70-485c-478f-a54b-7a8efa220be4/AF-Stage-fb0d5987-1701-43b3-ae64-7d53f15b0ad4/definition.json

### Example Address

LL65 1LF

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Anglesey is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) 
[Documentation for Anglesey](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/anglesey_gov_wales.md) added in above PR

The ICS file returned contains values which break the old implementation of ICS file parsing.
The fix/workaround for this will be part of release 1.44.0 or is available now as master (git) version (HACS: 3 dot menu -> re download -> change version)
