### ISSUE TITLE
[Source Request]: Moreton Bay, Australia

### ISSUE THREAD

**Issue by Slippery-Silvia** [mampfes/hacs_waste_collection_schedule#1391]
### Municipality / Region

Moreton Bay, Australia

### Collection Calendar Webpage

https://www.moretonbay.qld.gov.au/Services/Waste-Recycling/Collections/Bin-Days

### Example Address

4 Caspian Parade, Warner QLD 4500

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Moreton Bay is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md)
[Documentation for Moreton Bay](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/moretonbay_qld_gov_au.md) added in above PR
