### ISSUE TITLE
[Bug]: whittlesea_vic_gov_au source documentation incorrect

### ISSUE THREAD

**Issue by XeKToReX** [mampfes/hacs_waste_collection_schedule#1402]
### I Have A Problem With:

The integration in general

### What's Your Problem

In the file doc/source/whittlesea_vic_gov_au.md the first configuration listed is incorrect as it lists suburb for both suburb and postcode.

waste_collection_schedule:
  sources:
    - name: whittlesea_vic_gov_au
      args:
        street_number: STREET_NUMBER
        suburb: SUBURB
        street_name: STREET_NAME
        **suburb: POSTCODE**

### Source (if relevant)

whittlesea_vic_gov_au

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed 

Thanks for the notice
