### ISSUE TITLE
[Bug]: number should be a string for kwu_de

### ISSUE THREAD

**Issue by paulstegmann** [mampfes/hacs_waste_collection_schedule#1416]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Hi,

@mampfes thank you very much for your work!
A small detail: The number must be specified as a string ("") for the KWU to work.
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/kwu_de.md

waste_collection_schedule:
  sources:
    - name: kwu_de
      args:
        city: Bad Saarow
        street: Ahornallee
        number: "1"

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed by #1417 

Fix will be part of release 1.44.0 or is available now as master (git) version (HACS: 3-dot menu -> re-download -> change version -> master)
