### ISSUE TITLE
[Source Request]: London Borough of Redbridge

### ISSUE THREAD

**Issue by ncodee** [mampfes/hacs_waste_collection_schedule#1434]
### Municipality / Region

London, Redbridge, UK

### Collection Calendar Webpage

https://my.redbridge.gov.uk/RecycleRefuse

### Example Address

Postcode range: IG1 - IG11 (ex: 254 Eastern Avenue, Ilford, IG1 5AA)

### Collection Data Format

Something different (add to additional information)

### Additional Information

Address locator using some sort of Geolocation API.

**Comment by 5ila5** [comment]
Allready supported.
README.md:
[Redbridge Council](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/redbridge_gov_uk.md) / redbridge.gov.uk

**Comment by ncodee** [comment]
> Redbridge Council

Ah apologies thanks, I didn't seem it listed in the readme for some reason.
