### ISSUE TITLE
[Source Request]: Hobsons Bay Council, Melbourne, Vic, Austraila

### ISSUE THREAD

**Issue by tinstep** [mampfes/hacs_waste_collection_schedule#1449]
### Municipality / Region

Hobsons Bay Council, Melbourne, Vic, Austraila

### Collection Calendar Webpage

https://hbcc.maps.arcgis.com/apps/webappviewer/index.html?id=4db29582f74b4ba2ab2152fedeefe7b1

### Example Address

11 Tubruk Crescent 
Williamstown, Melbourne
Victoria, 3016, AUS

### Collection Data Format

As html on a webpage, Dedicated IOS/Android APP, As PDF Download

### Additional Information

HTML: https://hbcc.maps.arcgis.com/apps/webappviewer/index.html?id=4db29582f74b4ba2ab2152fedeefe7b1
Android App: https://play.google.com/store/apps/details?id=au.gov.vic.hobsonsbay
PDF website to download 4 pdfs:  https://www.hobsonsbay.vic.gov.au/Services/Waste-Recycling/When-will-my-bins-be-collected

**Comment by 5ila5** [comment]
add in #1616 

This will be part of release 1.45.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
