### ISSUE TITLE
How to use ics from local waste company?

### ISSUE THREAD

**Issue by d3claes** [mampfes/hacs_waste_collection_schedule#147]
Hello,

I am trying to use your integration for my local waste processor: [Limburg.net](https://www.limburg.net/) (Belgium).
[This is the location](https://www.limburg.net/afvalkalender) of their calendar, where you can download an ics file (see attachment)
_(as example you can take this data: municipality = Peer, street = Zuidervest, number = 1)._

This is the URL for the ics file:
https://limburg.net/api-proxy/public/kalender-download/ical/72030?straatNummer=66536&huisNummer=1&toevoeging=&includeAllEventTypes=1&eventTypes[]=14&eventTypes[]=22&eventTypes[]=23&eventTypes[]=26&eventTypes[]=27&eventTypes[]=29

72030 is the [NIS number](https://en.wikipedia.org/wiki/NIS_code) of our municipality.
66536 is the number of the street.
Both numbers are automatically looked up by the website and placed in the URL, after you have entered your address details or geolocation.

Since I already have the ics file, I wanted to start with the following configuration:

configuration.yaml:
```
waste_collection_schedule:
  source:
    - name: afvalkalender_ics
      args:
        file: "www/afvalkalender.ics"
```

sensors.yaml:
```
- platform: waste_collection_schedule
  name: limburg_net
```

This is the result in development tools:
![image](https://user-images.githubusercontent.com/2638856/149768861-968fea46-78bf-49ae-b42e-82016706c761.png)

There are no items in the HA calendar.

The ics file does not appear to be being processed.
Thank you very much for more information

[afvalkalender.ics.txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/7881770/afvalkalender.ics.txt)
.

**Comment by Haitec** [comment]
Try `ics` instead of `afvalkalender_ics`.

**Comment by d3claes** [comment]
Thank you! That solved the issue. I must have used a wrong example to start.
I'll also try the integration with the url as source, so our waste company can be added to the list of service providers.

**Comment by d3claes** [comment]
Pull request added for documentation on service provider Limburg.net in Belgium. Issue closed
