### ISSUE TITLE
[Source Request]: Denbighshire County Council

### ISSUE THREAD

**Issue by slip83** [mampfes/hacs_waste_collection_schedule#1471]
### Municipality / Region

Denbighshire, UK

### Collection Calendar Webpage

https://www.denbighshire.gov.uk/en/bins-and-recycling/bin-collections.aspx

### Example Address

LL19 7JB

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
Note to myself: GET https://www.denbighshire.gov.uk/api/Custom/RefuseApi/GetCollectionDates?uprn=200004305884

**Comment by slip83** [comment]
I think after the questionable upgrade to the bin collection service Denbighshire also updated their calendar as it no longer works correctly... It's saying household collection today which is not and not mentioned recycling, which is now every week...

**Comment by 5ila5** [comment]
Moved the source to the new API/Web request.

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
