### ISSUE TITLE
[Source Request]: City of Stirling (Western Australia)

### ISSUE THREAD

**Issue by rainbowsnail99** [mampfes/hacs_waste_collection_schedule#1474]
### Municipality / Region

Stirling, Western Australia

### Collection Calendar Webpage

https://www.stirling.wa.gov.au/waste-and-environment/waste-and-recycling/residential-bin-collections

### Example Address

12 Morgans Street, Tuart Hill WA, Australia

### Collection Data Format

As html on a webpage

### Additional Information

Hello! I live in the City of Stirling (quite a large city council area here in Western Australia) and was hoping you could add them to the West Collection Schedule. I've tried to get this add-on working in my home assistant instance using the calendar method to no avail and could benefit from having our council integrated. I would try and do it myself and open a PR if it was PHP rather than Python as PHP is where my skills are at!

I'm hoping this example of retrieving the data from one of their API endpoints helps;
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/57337675/ee1f10c5-62a2-49b8-960e-915745d15987)

**Comment by Pete331** [comment]
Keen for this one also. Thanks for your work

**Comment by 5ila5** [comment]
Added in #2378 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
