### ISSUE TITLE
[Bug]: fetch failed for source Basingstoke and Deane Borough Council

### ISSUE THREAD

**Issue by AndreaCCIE** [mampfes/hacs_waste_collection_schedule#1475]
### I Have A Problem With:

A specific source

### What's Your Problem

I can't retrieve the data from my council.

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 12:18:56 (1 occurrences)
Last logged: 12:18:56

fetch failed for source Basingstoke and Deane Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/basingstoke_gov_uk.py", line 65, in fetch date=datetime.strptime(schedule.text, "%A, %d %B %Y").date(), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 352, in _strptime raise ValueError("unconverted data remains: %s" % ValueError: unconverted data remains: (Christmas and New Year rescheduling)
```

### Relevant Configuration

```YAML
I'm running version 1.44. I never tested it before, so I can't say if this is a server-side change or if the script got broken somewhere.
Thanks!
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Thy made some changes and added ` (Christmas and New Year rescheduling)` after certain dates.
fixed by #1447

Fix will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> re-download -> change version to master (Will increase update cycles by a lot))
