### ISSUE TITLE
Vancouver, B.C. Canada Request

### ISSUE THREAD

**Issue by 88fingerslukee** [mampfes/hacs_waste_collection_schedule#1484]
### Municipality / Region

Vancouver, Canada

### Collection Calendar Webpage

https://vancouver.ca/home-property-development/garbage-and-recycling-collection-schedules.aspx

### Example Address

166 W 47th Ave, Vancouver

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP, As PDF Download

**Comment by panteLx** [comment]
created PR with your request

**Comment by 88fingerslukee** [comment]
thanks!

**Comment by 5ila5** [comment]
Vancouver is using recollect and therefore supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) recollect documentation can be found [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md) . Vancouver was added to the supported list in #1490
