### ISSUE TITLE
[Bug?]: garbage type string contains " : "

### ISSUE THREAD

**Issue by eggmich** [mampfes/hacs_waste_collection_schedule#1487]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

my garbage type from ics-file contains two : 

therefore customazition in yaml fails. also "..." is ignored like
      customize:
        - type: "Abholung: Biosack - Abholbezirk: 4"
          show: false

what can i do?

cheers
 Michael

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
You can use the regex parameter (in ICS source configuration not sensor) like:
`regex: "Abholung: (.*) - Abholbezirk: 4"`
Will just return `Biosack` you can use [0-9] instead of 4 to Match all numbers. There is probably a way to escape the : if not we should probably provide some way to do this, I will habe a detailed look later.

**Comment by 5ila5** [comment]
I cannot reproduce your Issue I have the following configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: test.ics
      customize:
        - type: "Abholung: Biosack - Abholbezirk: 4"
          show: false
```

My ICS contains an entry with the title "Abholung: Biosack - Abholbezirk: 4" and the event is listed as this in the calendar without the customize options but not with the option.
Did you spell the `type` exactly like it is returned?

**Comment by eggmich** [comment]
I deleted my entries and re-importet th ics-file without the ":"

and now the costomazation as above works for me.

thanks a lot.
