### ISSUE TITLE
After upgrade to latest version, Integration does not load anymore

### ISSUE THREAD

**Issue by nohn** [mampfes/hacs_waste_collection_schedule#150]
Waste collection schedule 1.15.0
Home Assistant core-2021.12.10

```
2022-01-18 18:33:52 ERROR (MainThread) [homeassistant.config] Platform error: sensor - Integration 'waste_collection_schedule' not found.
2022-01-18 18:33:52 ERROR (MainThread) [homeassistant.config] Platform error: sensor - Integration 'waste_collection_schedule' not found.
2022-01-18 18:33:52 ERROR (MainThread) [homeassistant.config] Platform error: sensor - Integration 'waste_collection_schedule' not found.
2022-01-18 18:34:10 ERROR (MainThread) [homeassistant.setup] Setup failed for waste_collection_schedule: Integration not found.

```

**Comment by mampfes** [comment]
Check if the [source configuration ](https://github.com/mampfes/hacs_waste_collection_schedule#1-configure-the-sources )is still part of your configuration.

Could it be that you have removed it meanwhile and not the upgrade was the first reboot since then?

**Comment by nohn** [comment]
Yes it is:

```
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Rsa
        mm_frm_ort_sel: xxx
        mm_frm_str_sel: xxx
        # mm_frm_hnr_sel: HNR_SEL
      customize:
        - type: RSAG Biotonne Regelabfuhr
          show: false
```

**Comment by wojciea** [comment]
Had the same.
comment the `waste_collection_schedule` block, along with all sensors you have
restart HASS
uncomment it back
restart HASS 

worked for me. Couldn't be bothered to investigate anymore...

**Comment by mampfes** [comment]
Strange. I can't reproduce this on my machines. Therefore I need some help:
- Does a simple HA restart fix the issue?
- Does a downgrade fix the issue?
- Does another upgrade again lead to the same issue?

**Comment by nohn** [comment]
> Had the same. comment the `waste_collection_schedule` block, along with all sensors you have restart HASS uncomment it back restart HASS
> 
> worked for me. Couldn't be bothered to investigate anymore...

For me, this unfortunately didn't work.

**Comment by nohn** [comment]
> Strange. I can't reproduce this on my machines. Therefore I need some help:
> 
> * Does a simple HA restart fix the issue?

No.

> * Does a downgrade fix the issue?
> * Does another upgrade again lead to the same issue?

How to perform the downgrade?

**Comment by mampfes** [comment]
Ok, good for you. But I don't have an idea whats going on here...

As this is fixed for you - can we close the issue?

**Comment by nohn** [comment]
Sure.
