### ISSUE TITLE
[Bug]: Doppelte Einträge im Kalender SBAZV_DE seit dem Update der Einträge für 2024

### ISSUE THREAD

**Issue by TK-HomeAssistant** [mampfes/hacs_waste_collection_schedule#1500]
### I Have A Problem With:

The integration in general

### What's Your Problem

Am 01.12.23 gab es ein Update, hier würden die Quellen für 2024 geladen. Seit dem Update sind alle Einträge meiner Sensoren doppelt!

Sensor_Restmülltonne ist jetzt Sensor_Restmülltonne, Restmülltonne
Im Kalender von HA sind alle Einträge doppelt aufgelistet.
Es betrifft alle Sensorarten!

Als Beispiel ein Auszug der Restmülltonne:
023-12-13: Restmülltonnen, Restmülltonnen
2023-12-28: Restmülltonnen, Restmülltonnen
2024-01-10: Restmülltonnen, Restmülltonnen
2024-01-24: Restmülltonnen, Restmülltonnen
2024-02-07: Restmülltonnen, Restmülltonnen
2024-02-21: Restmülltonnen, Restmülltonnen
2024-03-06: Restmülltonnen, Restmülltonnen
2024-03-20: Restmülltonnen, Restmülltonnen
2024-04-04: Restmülltonnen, Restmülltonnen
2024-04-17: Restmülltonnen, Restmülltonnen
2024-05-02: Restmülltonnen, Restmülltonnen
...

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Der Fehler wurde eigentlich in #1469 behoben und sollte mit der aktuellen Version 1.44.0 verteilt worden sein.
Hast du die Integration upgedatet?

**Comment by TK-HomeAssistant** [comment]
![Bild 09 12 23 um 11 59](https://github.com/mampfes/hacs_waste_collection_schedule/assets/148004910/efff97ad-ec21-4072-9fe7-b327c96d313c)
![Bild 09 12 23 um 12 00](https://github.com/mampfes/hacs_waste_collection_schedule/assets/148004910/02ff1d39-1265-4a8d-994c-ad27767b660f)
Habe die neuste Version, auch bereits erneut geladen.
Anbei die Übersicht und file editor Ausschnitt, sollen hier zwei ICS hinterlegt sein?

**Comment by 5ila5** [comment]
Ja da sollen 2 ICS Services sein, Beim verwenden der ICS source kann man auswählen welche benutzt wird.

Ich hatte das übersehen: der Fix (#1469) wurde kurz nach dem Release 1.44.0 gemerged. Er wird also erst mit 1.45.0 veröffentlicht oder ist jetzt erhältlich mit der master (git) version (HACS: 3-Punkt-Menu -> Redownload -> Version auf master setzten -> HA Neustarten)

Dieses Issue is Duplikat von #1467

**Comment by TK-HomeAssistant** [comment]
Vielen Dank für den Hinweis mit "Master" 
Habe ich ausgewählt und das Problem konnte so beseitigt werden.

**Comment by eddso** [comment]
Habe die Version 1.46.0 und auch alle Einträge im Kalender doppelt, Konfig:
```
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: sbm
        city: Minden
        street: xxx
        house_number: xxx
```

**Comment by 5ila5** [comment]
@eddso Ich kann das leider nicht reproduzieren.

Ich bekomme mit der Konfiguration 

```
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: sbm
        city: Minden
        street: Alte Sandtrift
        house_number: 24
```

Jeden Eintrag nur einmal.

Wenn du es mit HACS installiert hast, probier mal die Integration zu deinstallieren und neu zu installieren, manchmal geht da beim Update Prozess was schief. (kompletter HA Neustart nicht vergessen)

Oder es ist direkt deine Adresse? Kannst du mal den Test Case von oben ausprobieren?

**Comment by eddso** [comment]
@5ila5 danke für schnelle Antwort
- `waste_collection_schedule` block aus kommentieren zeigt kein Kalender.
- `street: Alte Sandtrift`, `house_number: 24`, zeigt tatsächlich 1 Eintrag so wie sein soll.
- `street: Meissener Str.` , `house_number: 6a`, zeigt 3 Einträgel.
- Probiert auch `MEISSENER STR.`, `6`, `10`, `0006A` (so zeigt es die App an) keine Verbesserung. Schaltet man um auf deine Adresse gehts, schaltet wieder auf meine = 3 Einträge.

**Comment by 5ila5** [comment]
Mir ist nicht ganz klar, was das Problem war, aber von der API kamen die Einträge doppelt. Die App scheint (mittlerweile???) einen anderen Endpunkt anzusprechen, um die Daten (jetzt die gleiche wie für Adressen) zu bekommen, damit habe ich das Problem nicht mehr. Der fix #1946 behebt also das Problem.

This will be part of release 1.47.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by eddso** [comment]
Version 1.47.0 getestet. Funktioniert wie es soll. Danke, super arbeit.
