### ISSUE TITLE
[Source Request]: Coventry City Council, UK

### ISSUE THREAD

**Issue by nexusmaniac** [mampfes/hacs_waste_collection_schedule#1512]
### Municipality / Region

Coventry, West Midlands, UK

### Collection Calendar Webpage

https://www.coventry.gov.uk/bin-collection-calendar

### Example Address

The site takes road names in, so-called, 'kebab-case`.

E.g. Lutterworth Road becomes: `https://www.coventry.gov.uk/directory-record/54834/lutterworth-road-`

The URLs are unique and require `12345/road-name-`. Without either of these elements, no dates are rendered.

Collections are then spit into `a` & `b`:
- https://www.coventry.gov.uk/binsfridaya
- https://www.coventry.gov.uk/binsfridayb

### Collection Data Format

As html on a webpage

### Additional Information

An email address can also be provided for push-notifications from the council.

**Comment by 5ila5** [comment]
Added in #3332

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
