### ISSUE TITLE
[Source Request]: Shropshire Council, UK

### ISSUE THREAD

**Issue by pshankland** [mampfes/hacs_waste_collection_schedule#1513]
### Municipality / Region

Shropshire, UK

### Collection Calendar Webpage

https://bins.shropshire.gov.uk/

### Example Address

SY2 6PH

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Something different (add to additional information)

### Additional Information

The URL seems to comprise of the UPRN, eg: https://bins.shropshire.gov.uk/property/100070034745

Also, when you go to the services page (eg: https://bins.shropshire.gov.uk/property/100070034745#services) there is also an ical download next to the next collection date.

**Comment by 5ila5** [comment]
Added by #1736

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
