### ISSUE TITLE
[Bug]: Dudley Council, UK - Xmas Collections

### ISSUE THREAD

**Issue by danbayliss** [mampfes/hacs_waste_collection_schedule#1526]
### I Have A Problem With:

A specific source

### What's Your Problem

Is it possible to update the Dudley source to reflect the change in collection dates as listed in the table below? If a refuse or recycling collection falls on the date then both will be changed to the new date. Appreciate this is just one or two collections so if its too much effort that's fine too

![6uu1eIa](https://github.com/mampfes/hacs_waste_collection_schedule/assets/54558493/caaa3919-aaa4-4cd5-886f-76de9b8bd59e)

### Source (if relevant)

dudley_gov_uk

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
"fix" will be part of relase 1.45.0 or is available now as master/git version (HACS: 3-dot menu -> redownload -> change version to master)

**Comment by danbayliss** [comment]
Confirmed all working as expected. Thank you!
