### ISSUE TITLE
[Feature]: please support "Austria/Traiskirchen"

### ISSUE THREAD

**Issue by cleversmart** [mampfes/hacs_waste_collection_schedule#1529]
### I propose a feature for:

The integration in general

### Describe your wanted feature

Please add support of "Austria/Traiskirchen"  find on https://www.traiskirchen.gv.at/abfall-entsorgung/online-abfuhrplan/

**Comment by 5ila5** [comment]
Traiskirchen is supported by the ICS source I added specific documentation in #1533 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/traiskirchen_gv_at.md).
