### ISSUE TITLE
[Source Request]: Landkreis Peine https://www.ab-peine.de/Abfuhrtermine/

### ISSUE THREAD

**Issue by Danny-DFx** [mampfes/hacs_waste_collection_schedule#1540]
### Municipality / Region

Landkreis Peine

### Collection Calendar Webpage

https://www.ab-peine.de/Abfuhrtermine/

### Example Address

For the whole destrict "Landkreis Peine"

### Collection Data Format

As ICS/ICAL file, As PDF Download

**Comment by 5ila5** [comment]
ab-peine.de is supported by the ICS source 
I added Peine specific documentation for this in #1541 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/ab_peine_de.md)

**Comment by Danny-DFx** [comment]
Thanks a lot!!!! :-)
