### ISSUE TITLE
[Source Request]: Heidelberg

### ISSUE THREAD

**Issue by tkaefer** [mampfes/hacs_waste_collection_schedule#1545]
### Municipality / Region

Heidelberg, Germany

### Collection Calendar Webpage

https://www.gipsprojekt.de/featureGips/Gips?Anwendung=Abfuhrkalender&Mandant=Heidelberg&Abfuhrkalender=Heidelberg

### Example Address

Achim-von-Armin-Straße (Rohrbach)

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Heidelberg is supported by the ICS source I added specific documentation in #1551 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/gipsprojekt_de.md)

**Comment by DerDreschner** [comment]
Heidelberg stopped using gipsprojekt this week. Instead, they have a new web app under [abfallkalender.heidelberg.de](abfallkalender.heidelberg.de). The app generates an ICS file by itself. The data comes from these two web services:

https://garbage.datenplattform.heidelberg.de/streetnames
https://garbage.datenplattform.heidelberg.de/collections?street={streetname}

**Comment by DerDreschner** [comment]
I opened a new source request to track the new implantation (#3248).
