### ISSUE TITLE
[Source Request]: Friedrichsdorf (Taunus)

### ISSUE THREAD

**Issue by Flow269** [mampfes/hacs_waste_collection_schedule#1546]
### Municipality / Region

Friedrichsdorf, Hochtaunuskreis, Germany

### Collection Calendar Webpage

https://friedrichsdorf.mein-abfallkalender.de/app/webcal.html

### Example Address

Am Eisspeicher

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP

**Comment by 5ila5** [comment]
already supported: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/mein_abfallkalender_de.md
