### ISSUE TITLE
[Source Request]: Add  Hounslow Council  UK

### ISSUE THREAD

**Issue by kiranbhakre** [mampfes/hacs_waste_collection_schedule#1548]
### Municipality / Region

United Kingdom

### Collection Calendar Webpage

https://www.hounslow.gov.uk/homepage/86/recycling_and_waste_collection_day_finder

### Example Address

17 A Lapton road, TW3 4HS

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Implementation approach:

```python
r = requests.post("https://www.hounslow.gov.uk/homepage/86/recycling_and_waste_collection_day_finder", data={"UPRN": uprn})
soup = BeautifulSoup(r.text, features="html.parser")
... HTML Parsing ...
```

**Comment by kiranbhakre** [comment]
I am trying to build it but getting some error in config.  Can you please build it.?
   #   
       soup = BeautifulSoup(r.text, features="html.parser")
        # Find all div elements with class 'bincal_heading_wrapper'
        bin_cal_divs = soup.find_all('div', class_='bin_day_main_wrapper')

        print (bin_cal_divs)

        for bin_cal_div in bin_cal_divs:
            # Extract the address information
            address_h2 = bin_cal_div.find('h2')
            if address_h2:
                address = address_h2.text.strip()
                print(f"Address: {address}")
            collection_info = bin_cal_div.find_all('h4')
            for info in collection_info:
                date = info.text.strip()
                bins = [li.text.strip() for li in info.find_next('ul', class_='list-group').find_all('li')]
                print(f"Collection Date: {date}")
                print("Bins:")
                for bin in bins:
                    print(f"  - {bin}")
                    entries.append(
                        Collection(
                            date=date,
                            t=bin,
                            icon=ICON_MAP.get(bin),
                        )
                    )

            print("\n")
        return entries

**Comment by 5ila5** [comment]
Sorry for the delay. You need to provide a Date object as date.
I added hounslow_gov_uk in #1730 

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by ronschaeffer** [comment]
Working perfectly. Thanks so much.
