### ISSUE TITLE
Add Garden waste type to Cornwall, UK source

### ISSUE THREAD

**Issue by js3678** [mampfes/hacs_waste_collection_schedule#1556]
### I propose a feature for:

Sources

### Describe your wanted feature

Can you please add Garden to the cornwall_gov_uk.py source?

Change - COLLECTIONS = {"Rubbish", "Recycling"}
to COLLECTIONS = {"Rubbish", "Recycling", "Garden"}

For my house I'm getting the following html snip so I think it should work. 

<div id="my-waste-collection">
        <h3 class="font-weight-bolder">Current collections</h3>
        <div class="row text-center">
                <div class="col-12 col-md-4">
                    <div id="recycling" class="collection text-center service">
                            <span>Recycling</span>
                            <span>SAT</span>
                            <span>30 Dec</span>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div id="rubbish" class="collection text-center service">
                            <span>Rubbish</span>
                            <span>TUE</span>
                            <span>2 Jan</span>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div id="gardenhassubscription" class="collection text-cente              r service">
                            <span>Garden</span>
                            <span>FRI</span>
                            <span>22 Dec</span>
                    </div>
                </div>
        </div>

**Comment by 5ila5** [comment]
added by #1558 
Will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master)
