### ISSUE TITLE
[Feature]: Add Braig-Ehingen

### ISSUE THREAD

**Issue by Chris909090** [mampfes/hacs_waste_collection_schedule#1561]
### I propose a feature for:

Sources

### Describe your wanted feature

Paper waste from Braig-Ehingen still missing
Can this possibly be added?
[Braig-Ehingen](https://www.braig-ehingen.de/dienstleistungen/blaue-tonne/abfuhrtermine)

Thank you very much!

**Comment by 5ila5** [comment]
As far as I can tell they are only offerering pdf files on this site (which we will not parse) but:

The city of Ulm is supported by the [Jumomind.de / MyMuell.de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/jumomind_de.md) or the [ics source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/ebu_ulm_de.md): documentation added in #1562

Landkreis Günzburg is supported by [AWIDO source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md)

 Alb-Donau-Kreis is supported by the [buergerportal_de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/buergerportal_de.md)

or did I miss something here?

**Comment by Chris909090** [comment]
Thanks for your answer!

Yes, you're right and I've already added Alb-Donaus-Kreis. However, they are only responsible for residual waste, organic waste, yellow bag and hazardous waste collection.

The paper waste is collected by another company.

Unfortunately...

If .pdf does not work, is there a way to manually specify garbage dates?

**Comment by 5ila5** [comment]
Yes you can use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) for that

**Comment by Chris909090** [comment]
Perfekt thanks! :)
