### ISSUE TITLE
Add GWA Kreis Unna (Abfallnavi)

### ISSUE THREAD

**Issue by theoldphilip** [mampfes/hacs_waste_collection_schedule#1563]
### I propose a feature for:

Sources

### Describe your wanted feature

For the Unna district, the collection dates are now also available via the “Abfallnavi”.

Can you also integrate this (e.g. into the Wizzad)

https://abfallnavi.de/unna/

**Comment by maxirnilian** [comment]
Push request is already available ;)  #1565

**Comment by 5ila5** [comment]
done by @maxirnilian in #1565
