### ISSUE TITLE
[Bug]: abfall_lippe_de source stopped working (for ICS files for 2024)

### ISSUE THREAD

**Issue by alexanderbeermann** [mampfes/hacs_waste_collection_schedule#1568]
### I Have A Problem With:

A specific source

### What's Your Problem

Hey guys,

The source abfall_lippe_de stopped working. For 2023 it was working fine - for 2024 it stopped working.
So, right now all my sensors display "unknown" since there is no data.

I just visited the site, they changed the way to download the ICS, i guess that's why the integration isn't able to fetch any data.

Unfortunately I do not see any hints within the logs: 

I already figured out, that they changed the URL structure for the ics files: - they switched the position of "year" and "bezirk"
> 2023: https://abfall-lippe.de/wp-content/uploads/2022/12/Bad_Salzuflen_AA_2023.ics
> 2024: https://abfall-lippe.de/wp-content/uploads/2023/12/Bad-Salzuflen-2024_AA.ics

### Logs

```Shell
no log entry - I assume WCS is still finding the ics files for 2023 and thus no exception is raised.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: abfall_lippe_de
      args:
        gemeinde: Bad Salzuflen
        bezirk: AA
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
It's not really a big bug. The current source tries to fetch the current year first. if this does fail it tries to fetch different years. This source will return valid 2024 entries beginning from the 1st January 2024.
It does not fetch the ICS file URL directly but gets the ics urls from the overview html.

But I made some changes in #1570 which will be part of the 1.45.0 release which will try to fetch the next year in December as well.

Fix will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master)
