### ISSUE TITLE
Home assistant calendar as source

### ISSUE THREAD

**Issue by grimmaldus** [mampfes/hacs_waste_collection_schedule#157]
Can you use as a source individual calendar created via Home Assistant Calendar integrations ?

**Comment by mampfes** [comment]
Do you mean: Another HA integration adds data to a HA calendar. And the waste_collection_schedule shall use this data as input?

This is currently not supported, but sounds like an interesting idea. Could you give an example?

**Comment by grimmaldus** [comment]
Yea exactly I don't know even if it is possible to read HA calendar events. Since it only creates sensors I don't know how to get to calendar data store in HA in first place. But if it would be possible it could be more convenient. 

My use-case:

- I have all calendars(including garbage calendar) stored in my Google Calendar service
- These calendars are integrated into my HA instance via Google Calendar Integration
- I want to use your Integration and set HA garbage calendar (integrated in previous) as a source

However I even cannot if there is away how to obtain these events from HA Calendars nor on dev documentation (maybe I'm just blind)

**Comment by Hoellenwesen** [comment]
Hi,
is there any update for this feature request? It would be very nice to use already imported calenders in the waste collection integration.

**Comment by mampfes** [comment]
No, not yet.

**Comment by diwiesign** [comment]
Hello, that would be really great, because I already use the HA calendar for the trash appointments. 

BTW, is there any chance of removing old entries from the HA calendar that were created during various config attempts?

<img width="600" alt="Kalender – Home Assistant 2022-10-30 20-09-08" src="https://user-images.githubusercontent.com/61392630/198897026-f4e619dc-50a6-4631-af60-10a7c2a60b4a.png">

**Comment by Senbei123** [comment]
In the documentation it states, that it will work with the local calender - but I didn't find a documentation how to do it?! Any hint?

**Comment by mampfes** [comment]
How did you get the data in the local calendar? *Waste Collection Schedule* itself published a calendar and can therefore not use another calendar as source.

**Comment by Senbei123** [comment]
Hi Steffen, sry I misunderstood your documentation. I used the new integration from 2022.12 "local calendar" to create manually the appointments. 

I'm currently in the state, that I don't need your "source" component but would be nice to use it with local calendar source for your very nice sensors!

**Comment by mampfes** [comment]
not to be fixed. You can use the `static` source instead of `local calendar`.
