### ISSUE TITLE
[Bug]: awb_mainz_bingen_de source stopped working

### ISSUE THREAD

**Issue by marwoo33** [mampfes/hacs_waste_collection_schedule#1578]
### I Have A Problem With:

A specific source

### What's Your Problem

Hey guys,

The source awb_mainz_bingen_de stopped working.

So, right now all my sensors display "unknown" since there is no data.

It would be great if you may fix it in time, got used to the integration :).

Thanks a lot and merry x-mas!

### Source (if relevant)

awb_mainz_bingen_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
It's not really a big bug. The current implementation only gets the first ical file which is still the one from 2023 so there aren't a lot of events shown so this bug should be resolve itself when they remove the 2023 file from the page (probably 1. st January, 2024. 

I made some changes to get all ical links in #1587 to show all available events. This fix will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master)
