### ISSUE TITLE
Error parsing ics data

### ISSUE THREAD

**Issue by moi6767** [mampfes/hacs_waste_collection_schedule#158]
I have a problem with this ics :
https://agglo-haguenau.fr/calendrierom/DAUENDORF-NEUBOURG/calendrierom.ics

The error message was Parsing ics data failed:'datetime.date' object has no attribute 'tzinfo'

When I use this ics with my iPhone I have no error.

**Comment by mampfes** [comment]
The ics data is ill-formed. The mandatory time zone info is missing. Please contact your service provider so that they provide a valid ics file.

**Comment by mampfes** [comment]
Or raise an issue in the ICS parsing library which is used by waste_collection_schedule: https://github.com/collective/icalendar/issues
