### ISSUE TITLE
[Bug]: was_wolfsburg_de stopped fetching data

### ISSUE THREAD

**Issue by NeoNamek** [mampfes/hacs_waste_collection_schedule#1593]
### I Have A Problem With:

A specific source

### What's Your Problem

The Source was_wolfsburg_de stopped fetching data for 2024. I suspect because the request link is no longer accurate.
I have experimented a bit, and with the following address I receive current data: 

https://was-wolfsburg.de/subabfuhrtermine/php/abfuhrtermine.php

It only concerns "Restmüll, Bioabfall und Papierabfall". "Gelber Sack" is still functioning.

### Source (if relevant)

was_wolfsburg_de

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The source used the html list for Gelber Sack collections but for the other collections it tries to get an ICS file. But I could not find it on theire website and it may not be updated anymore. So i did some changes in #1599 to fetch the other collection types like the Gelber Sack ones.
Fix will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master)
