### ISSUE TITLE
[Bug]: abfallwirtschaft_pforzheim_de has change the URL.

### ISSUE THREAD

**Issue by hrvat94** [mampfes/hacs_waste_collection_schedule#1595]
### I Have A Problem With:

A specific source

### What's Your Problem

The URL changes from "https://www.abfallwirtschaft-pforzheim.de/kundenportal/abfallkalender" to "https://www.abfallwirtschaft-pforzheim.de/abfallkalender". On the new Site you need to select a checkbox for the year. I think this option would disappear on the beginning of the next year. But the addon doesnt show me the calendar for 2023 anymore. Its complete empty.

### Source (if relevant)

abfallwirtschaft_pforzheim_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
abfallwirtschaft_pforzheim_de
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The url of the web requests acutally did no change. But it requires the Zeitraum argument to collect data for the next year but the problem might solve itself in 2024.

I added this argument in # and changed the URL in the md file

This fix will be part of 1.45.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
