### ISSUE TITLE
Cant download or run script

### ISSUE THREAD

**Issue by crohot** [mampfes/hacs_waste_collection_schedule#16]
Hi, i try to run the script "How to get the source arguments" but its not working. Isn´t it for Windows?

And even without correct parameters, should there be no entities visible already after installing through hacs?

Thank you and kind regards,
Crohot

**Comment by mampfes** [comment]
Hi, unfortunately the script is not running on Windows. See also: https://community.home-assistant.io/t/waste-collection-schedule-framework/186492/11. If you don't own a Linux machine you can send me a private message and I can extract the values for you.

Without a configuration (see examples) to don't see any entities.

Best regards

Steffen

**Comment by crohot** [comment]
Hi Steffen,
nein, ich habe keine Linux-Maschine... 
Ich schicke Dir meine Daten direkt.
Danke!

**Comment by crohot** [comment]
Hmpf, hier gibt es offensichtlich keine DM-Funktion...

**Comment by mampfes** [comment]
Du kannst mir via Home Assistent Forum eine PN schicken:
https://community.home-assistant.io/t/waste-collection-schedule-framework/186492

**Comment by mampfes** [comment]
Closed because user is not responding.
