### ISSUE TITLE
[Source Request]: Please add source "West Suffolk Council" schedule (UK)

### ISSUE THREAD

**Issue by L81ker** [mampfes/hacs_waste_collection_schedule#1605]
### Municipality / Region

West Suffolk, UK

### Collection Calendar Webpage

https://www.westsuffolk.gov.uk/bins/when-are-my-bins-emptied.cfm

### Example Address

Flat, The Flying Shuttle, Three Counties Way, Withersfield, CB9 7FB

### Collection Data Format

As html on a webpage

### Additional Information

**Website has a separate link to a place where postcode must be entered (https://maps.westsuffolk.gov.uk/MyWestSuffolk.aspx).**

The link is in the text "When are my bins emptied?
Your bins are emptied on alternate weeks. When there is a public holiday, the collection days will be revised. To see when your bins are emptied, use our [Find my nearest](https://maps.westsuffolk.gov.uk/MyWestSuffolk.aspx) service and enter your postcode into the Search for a location box and select your address. Your bin collection information will be displayed."

**The bin schedule for the next few days is shown in a panel, with a title, and further links. note that garden refuse (brown bin) may not be shown if the resident has not paid for the service, as in this example:**
---------------------------------------------------------------------------------------
_copy-paste of the web text_

[Waste and recycling](https://maps.westsuffolk.gov.uk/MyWestSuffolk.aspx#Waste_and_recycling)
Bin collection days
Please leave your bin out for collection by 6:15am.

Your [collection day](http://www.westsuffolk.gov.uk/bins/my-bin-hasnt-been-emptied.cfm) will change on weeks with bank holidays.

Your next bin collection days are:

Black bin: Saturday 6th January
Blue bin: Saturday 30th December
Your [garden waste collection](https://www.westsuffolk.gov.uk/gardenwaste) is an optional subscription service.

[Report a missed bin](http://www.westsuffolk.gov.uk/bins/my-bin-hasnt-been-emptied.cfm)

---------------------------------------------------------------------------------------------------
**Example including the brown bin:**
_copy-paste of the text_

Bin collection days
Please leave your bin out for collection by 6:15am.

Your [collection day](http://www.westsuffolk.gov.uk/bins/my-bin-hasnt-been-emptied.cfm) will change on weeks with bank holidays.

Your next bin collection days are:

Black bin: Saturday 6th January
Blue bin: Saturday 30th December
Brown bin: Thursday 11th January
Your [garden waste collection](https://www.westsuffolk.gov.uk/gardenwaste) is an optional subscription service.

[Report a missed bin](http://www.westsuffolk.gov.uk/bins/my-bin-hasnt-been-emptied.cfm)

-------------------------------------------------------------------------------------------------------
**Screenshot:**

![waste collection dates](https://github.com/mampfes/hacs_waste_collection_schedule/assets/105645866/ebaa0d6d-74a7-4e9f-8017-fd4eec1ec528)

**Comment by 5ila5** [comment]
added in #1606 

This will be part of 1.45.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
