### ISSUE TITLE
[Source Request]: Chelmsford Council, Essex, UK

### ISSUE THREAD

**Issue by Johnyb62** [mampfes/hacs_waste_collection_schedule#1633]
### Municipality / Region

Chelmsford Council, Essex, UK

### Collection Calendar Webpage

https://www.chelmsford.gov.uk/myhome/

### Example Address

2 Drywoods (CM3 5ZG) 

### Collection Data Format

As html on a webpage

### Additional Information

Visiting https://www.chelmsford.gov.uk/myhome/ to enter a postcode or street name, & click Search
This provides the results within that postcode / street, clicking on the house number shows a summary of services, at the bottom beneath 'Waste' a link "[view or download the collection calendar](https://www.chelmsford.gov.uk/bins-and-recycling/check-your-collection-day/tuesday-b-collection-calendar/)" which takes you to page which allows you to download the PDF but also lists the next collections

Unfortunately you cannot bookmark the final 'myhome' URL, its dynamically generated?

**Comment by 5ila5** [comment]
added in #2767

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by 5ila5** [comment]
I don't understand what you mean. This is the only Chelmsofrd source I could find, and I do not see any other issues from you ([issue Search](https://github.com/mampfes/hacs_waste_collection_schedule/issues?q=is%3Aissue+author%3AJohnyb62))

**Comment by Johnyb62** [comment]
I'm sorry please completely ignore me.  I got this confused with a different project doing a very similar thing.

**Comment by Johnyb62** [comment]
Ok so tried testing this, think there is a minor issue.
Looks like the generate link has an unnecessary '-' in the URL  (see below).

<img width="422" alt="image" src="https://github.com/user-attachments/assets/16caf9b1-2563-4db1-b749-114cc177e353">

URL shown in error: - https://www.chelmsford.gov.uk/bins-and-recycling/check-your-collection-day/tuesday-b--collection-calendar/
What I believe is the correct one: https://www.chelmsford.gov.uk/bins-and-recycling/check-your-collection-day/tuesday-b-collection-calendar/

Hope this helps.
