### ISSUE TITLE
Braintree error when selecting address

### ISSUE THREAD

**Issue by amildenhall** [mampfes/hacs_waste_collection_schedule#1649]
I have had the follow error for the past couple of months:

> fetch failed for source Braintree District Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py", line 45, in fetch id = next( ^^^^^ StopIteration

I am seeing address["value"] on line 43 having a length of 11.
Removing this line cures the problem for me, and I am not sure what this line is achieving?

https://github.com/mampfes/hacs_waste_collection_schedule/blob/73baeef472c5db4c85db3a7b725df68f3a15a101/custom_components/waste_collection_schedule/waste_collection_schedule/source/braintree_gov_uk.py#L43

**Comment by 5ila5** [comment]
I think this line should filter out the first element of the select button where the ID is 0 and not a valid ID. But There are IDS with length 11 and 12 (as far as I can tell with our test cases)

it was originally written by @cpressland and added in #484

I changed this line to filter out id's shorter that 5 digits as this should probably not cause any problems
