### ISSUE TITLE
Notification Blueprint

### ISSUE THREAD

**Issue by gomble** [mampfes/hacs_waste_collection_schedule#166]
Hello,

do you maybe have a Notification Blueprint ?
To notify one day before via alexa or ios app ?

**Comment by pschneider87** [comment]
maybe this one will help: https://community.home-assistant.io/t/garbage-reminder/284213
I guess you need to set up a sensor for the date beforehand, see https://community.home-assistant.io/t/garbage-reminder/284213

**Comment by idominiki** [comment]
I just forked a Blueprint from @Hooverjc to make this Automation work with Waste Collection Schedule:
(https://gist.github.com/idominiki/76d57efc075042c22b02a553fc3d78ab)

**Comment by gomble** [comment]
> I just forked a Blueprint from @Hooverjc to make this Automation work with Waste Collection Schedule:
> 
> https://gist.github.com/idominiki/76d57efc075042c22b02a553fc3d78ab

Does not work. Cant select the Sensor:
![image](https://user-images.githubusercontent.com/6769445/181913903-122d5b03-9762-48a5-8153-e7d3a80650a4.png)

**Comment by idominiki** [comment]
> > I just forked a Blueprint from @Hooverjc to make this Automation work with Waste Collection Schedule:
> 
> > 
> 
> > https://gist.github.com/idominiki/76d57efc075042c22b02a553fc3d78ab
> 
> 
> 
> Does not work. Cant select the Sensor:
> 
> ![image](https://user-images.githubusercontent.com/6769445/181913903-122d5b03-9762-48a5-8153-e7d3a80650a4.png)
> 
> 

Yes sure. Sensors are automatically selected through the script.

**Comment by gomble** [comment]
Can i test this automatisation ?
I i click run automatisation, i get an empty result.

**Comment by idominiki** [comment]
> Can i test this automatisation ?
> I i click run automatisation, i get an empty result.

Try this automation: 
- alias: Garbage Reminder
  description: ''
  use_blueprint:
    path: idominiki/GarbageCollection.yaml
    input:
      reminder_time: '20:00:00'
      day_offset: '1'

Then you can test it by settings the day_offset to the actual value of daysTo.

**Comment by thewillwilson** [comment]
Does this still work in 2023? A test notification just sends me "The following rubbish will be picked up tomorrow :"

Thanks

**Comment by Hooverjc** [comment]
I just use the built in calendar now as it has the same features for the most part.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
