### ISSUE TITLE
[Source Request]: Herford, Deutschland

### ISSUE THREAD

**Issue by akata6868** [mampfes/hacs_waste_collection_schedule#1661]
### Municipality / Region

Herford, Deutschland

### Collection Calendar Webpage

https://swk.herford.de/Entsorgung/Abfallkalender-/

### Example Address

https://swk.herford.de/Entsorgung/Abfallkalender-/
Kann mann auch Herford mit einfügen

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Herford is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1663 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/swk_herford_de.md)
