### ISSUE TITLE
Parsing ics data failed:Content line could not be parsed into parts: 'REFRESH - INTERVAL; VALUE = DURATION:PT48H': REFRESH - INTERVAL

### ISSUE THREAD

**Issue by MaxRei-dev** [mampfes/hacs_waste_collection_schedule#167]
I got this error from this Source: https://data.umweltprofis.at/OpenData/AppointmentService/AppointmentService.asmx/GetIcalWastePickupCalendar?key=UixrcO9GyWsrzB1TEMsJdiNt5TybWZRxJymo7F1gg1zkrJwWqAV-YeCv4wIEBb144fBdsvki_q5Pa8JE7SXO8w2

**Comment by mampfes** [comment]
I'm sorry: This is an incompatibility between the data provided by your service provider and the ICS parsing library which is used by waste_collection_schedule. Please contact either your service provider or raise an issue here: https://github.com/collective/icalendar/issues

**Comment by MaxRei-dev** [comment]
Thank you.

**Comment by andyboeh** [comment]
@mampfes I just ran into the same issue (same data provider), it seems like `REFRESH - INTERVAL` is spelled incorrectly (the whitespaces shouldn't be there - I didn't test whether it works without the whitespaces though). 

Is fixing up the ICS before parsing it an option, since the ICS looks broken? 
Or should we add a new service that fixes up the ICS and calls the parser?

**Comment by mampfes** [comment]
If it is a typo, I would add a new source that fixes the ICS upfront and then calls the ICS parser.

I don't want to have service provider specific fixes in the generic ICS source - because this adds unnecessary complexity to the code and especially the configuration.

Can you provide a PR?

**Comment by andyboeh** [comment]
Perfect, I'll try to come up with something when I have the time to!

**Comment by andyboeh** [comment]
@MaxRei-dev I just noticed that there is an XML API as well that would allow the specification of city name etc. In the last step, a key is needed - do you happen to know how to get the key? Do you know for how long the ICS link is valid?

Coming up with a data source that just fixes the ICS file was very easy and I can create a PR tonight.

**Comment by mampfes** [comment]
The link from the original post is now 27 days old and still valid. Therefore it seems to be a persistent key.

**Comment by MaxRei-dev** [comment]
> @MaxRei-dev I just noticed that there is an XML API as well that would allow the specification of city name etc. In the last step, a key is needed - do you happen to know how to get the key? Do you know for how long the ICS link is valid?
> 
> Coming up with a data source that just fixes the ICS file was very easy and I can create a PR tonight.

Hi, sorry i have no idea how long the link is working.
I've been using it almost one year now with node red.
So i think the would "almost never" expire...
I just see your PR an it would be nice to include it. 
For the moment i get the ics via node red, replace the string like you an save it for home assistant.

**Comment by andyboeh** [comment]
Perfect, maybe they expire links without access for some time. I tried to contact them a week ago, but didn't receive a response.

Let's see for how long it's valid - PR #178 has just been merged :)
