### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by CyberGecko** [mampfes/hacs_waste_collection_schedule#1674]
### Municipality / Region

Bedburg

### Collection Calendar Webpage

https://buerger-portal-bedburg.azurewebsites.net/calendar/

### Example Address

Am Schirkerhof 2, Bedburg, Broich

### Collection Data Format

Something different (add to additional information)

### Additional Information

The city of Bedburg change its Waste Collection Provider. Thus the old Abfall+ Source doesn't work anymore. The new provider is Drekopf. Unfortunately they do not use the existing Drekopf API. The Webpage provided by Drekopf has multiple outputs. You can download the calendar via PDF, XLS, CSV and ICS, but i can't find the url. The underlying API seems to be C-Trace, but when calling this API, credentials are requested. Maybe i am missing something...

**Comment by 5ila5** [comment]
added by #1676 will be part of the buergerportal_de source:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/buergerportal_de.md

is part of new release 1.45.0
