### ISSUE TITLE
[MANNHEIM not available via Abfall+ anymore]: 

### ISSUE THREAD

**Issue by RobertoCravallo** [mampfes/hacs_waste_collection_schedule#1682]
### I Have A Problem With:

The integration in general

### What's Your Problem

Data for MANNHEIM is not available via Abfall+ anymore! They have their own APP now. 

Please remove Mannheim form the list. 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Mannheim is now using the same approach like "Offenbach am Main" (source: offenbach_de). Url for Mannheim:  https://www.insert-it.de/BmsAbfallkalenderMannheim

**Comment by BlaM** [comment]
Has this been solved? The ticket is still open, but there is an updated example config in the documentation. When I try to use the example code from the documentation I run into `source not found: insert_it_de` errors in my logs, though.

**Comment by weaseel** [comment]
Any news when the next release is going to happen. Almost missed putting out the bins because the new Mannheim app is garbage (pun intended)

**Comment by derDeno** [comment]
Actually you can use it for now with a workaround until the next release releases. 

For that go to HACS and inside the waste collection integration there are three dots on the top right. There you can select to redownload the repo and select which version to download. Just select master instead of a specific version. This will download the latest state.

Sometimes you need to delete the current integration and redownload it to work.

**Comment by weaseel** [comment]
Ah thanks. I checked „beta versions“ and was looking for „master“. But I never realized master is on the bottom of the list
