### ISSUE TITLE
[Bug]: Awigo / The dates for organic waste are not being read.

### ISSUE THREAD

**Issue by Phase174** [mampfes/hacs_waste_collection_schedule#1684]
### I Have A Problem With:

A specific source

### What's Your Problem

The dates for organic waste are not being read. All other dates are read correctly. The "class" seems to match with the source code of the address "https://www.awigo.de/index.php."

### Source (if relevant)

awigo_de.py

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Can you share the city name? I checked the webportal and for some cities "organic waste" dates are not available. The source works for "Ankum" for example.

**Comment by Phase174** [comment]
The name of the City is „Bohmte“

**Comment by ReneNulschDE** [comment]
I checked with the setting 
```
    - name: awigo_de
      args:
        ort: "Bohmte"
        strasse: "Am Hügel"
        hnr: "6"
```
and dates for "Bio-Tonne" are collected and visible in HA.

Did you checked the online portal if the entries are visible for your location? You can share the street and number if you like.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/33263735/fd9fb094-fdc3-4ada-9eda-b2a10b980b80)

**Comment by Phase174** [comment]
After some trial and error, I figured out the mistake. It was my error. I forgot to include the "a" in our house number. As a result, the system retrieved appointments for our neighbor. The neighbor doesn't even have organic waste. Didn't think our provider's website was that clever.

Thank you, for your help.

Problem solved.
