### ISSUE TITLE
[Bug]: 1.45.0 - fetch failed for source Bürgerportal / Bedburg

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_waste_collection_schedule#1685]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi,

I have installed the resource for the Bedburg citizen portal (Bürgerportal) that was newly added in 1.45.0, but I don't get any data... but there are errors :-)

TIA

Gerd

### Source (if relevant)

buergerportal_de

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 22:50:09 (1 occurrences)
Last logged: 22:50:09

fetch failed for source Bürgerportal: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode obj, end = self.raw_decode(s) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode return self.scan_once(s, idx=_w(s, idx).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/buergerportal_de.py", line 136, in fetch district_id = self.fetch_district_id(session) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/buergerportal_de.py", line 196, in fetch_district_id payload: DistrictsRes = res.json() ^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: buergerportal_de
      args:
        operator: bedburg
        district: "Bedburg"
        subdistrict: "Königshoven"
        street: "Pannengasse"
        number: "24"
        show_volume: true
      calendar_title: Drekopf via Bürgerportal
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by CyberGecko** [comment]
I noticed this too. The API url is missing the '/api' part. It will be fixed in one of the next releases:
https://github.com/mampfes/hacs_waste_collection_schedule/pull/1680
alternatively you can change the file where the url is defined yourself (see file in PR)
