### ISSUE TITLE
[Source Request]: Nanaimo BC, Canada

### ISSUE THREAD

**Issue by Deep-Six** [mampfes/hacs_waste_collection_schedule#1697]
### Municipality / Region

Nanaimo, BC, Canada

### Collection Calendar Webpage

https://www.nanaimo.ca/city-services/garbage-recycling/collectionschedule

### Example Address

161 Black Powder Trail, Nanaimo, BC V9S 3G4

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Nanaimo is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1707 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md)
