### ISSUE TITLE
Verify for new supported generic ICS file

### ISSUE THREAD

**Issue by LNS-MrGoodkat** [mampfes/hacs_waste_collection_schedule#17]
Hey, 

I can verify that the generic ICS file works with the generated URLs from [here](https://abfall.landkreis-stade.de/abfuhrkalender/).
So you can add it to the supported services [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md).

Thanks for the Plugin!

**Comment by mampfes** [comment]
Thanks for sharing! I updated the documentation accordingly.
