### ISSUE TITLE
ical download failure

### ISSUE THREAD

**Issue by kauthmbt** [mampfes/hacs_waste_collection_schedule#170]
After the latest update to HA 2022.3.1 it seems like the ical download is broken on my system.
Not quite sure if the add-on needs adjustment due to a HA breaking change...

Logger: waste_collection_schedule.service.ICS
Source: custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py:24
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 09:28:27 (1 occurrences)
Last logged: 09:28:27

Parsing ics data failed:Content line could not be parsed into parts: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">`

**Comment by kauthmbt** [comment]
just to provide you with a feedback:
I recently recognized that you did a pre-release which seems to fix the problem for me.
Thanks for the quick support!

**Comment by mampfes** [comment]
Fixed in release 1.16.0
