### ISSUE TITLE
[Bug]: Setup failed for custom integration 'waste_collection_schedule': Requirements for waste_collection_schedule not found: ['shapely'].

### ISSUE THREAD

**Issue by Ruko2010** [mampfes/hacs_waste_collection_schedule#1709]
### I Have A Problem With:

The integration in general

### What's Your Problem

After Update to 1.45.0 I get this error in the logs and waste collection is not working any more. Even if I remove the configuration from my configuration.yaml I get this errors.

### Source (if relevant)

ics File

### Relevant Configuration

```YAML
I use Home Assistant in an Docker enviroment.
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by CedricBojoly** [comment]
same issue here https://github.com/mampfes/hacs_waste_collection_schedule/issues/1705

**Comment by Ruko2010** [comment]
ok, so I'm watching the other issue an closing this one.
