### ISSUE TITLE
[Bug]: WasteNet Southland url has changed

### ISSUE THREAD

**Issue by etamtlosz** [mampfes/hacs_waste_collection_schedule#1718]
### I Have A Problem With:

A specific source

### What's Your Problem

The url for wastenet southland has changed. It looks like they published a new website.
The search form has moved here -> https://www.wastenet.org.nz/bin-day/
The results look like this -> https://www.wastenet.org.nz/bin-day/?entry_id=3554

The search form is sometimes a PITA, spitting out multiple addresses after pressing search, but if one knows his ID, like 3554, then the search result spits out the right result. 

### Source (if relevant)

wastenet_org_nz

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Do you see any way to get some real dates?

For something like `Collection Day: Friday; Frequency: Weekly` we can generate the dates, but do you see a way to get the actual weeks for something like `Collection Day: Friday Frequency: Fortnightly`?

**Comment by etamtlosz** [comment]
I've been in contact with wastenet and they are still working on the database. It feels like they have pushed an alpha version to public.

The PDF below the search box shows the weeks in yellow for the "recycling".
One issue could arise due to public holidays, when the collection day is delayed by one day.  For example if we had a public holiday on Tuesday, then every pickup day during that week (after Tuesday) gets shifted to the next day. I my example Friday becomes Saturday.

**Comment by etamtlosz** [comment]
Looks like I managed to convince them how important the date and the day of the week + the presence of the text TOMORROW/TODAY is.
I think the script needs just a slight code adjustment.

**Comment by 5ila5** [comment]
Fixed the source in #1798

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
