### ISSUE TITLE
[Source Request]: Stadt und Landkreis Bamberg

### ISSUE THREAD

**Issue by LightBringer81** [mampfes/hacs_waste_collection_schedule#1731]
### Municipality / Region

Stadt und Landkreis Bamberg

### Collection Calendar Webpage

https://www.abfalltermine-bamberg.de/

### Example Address

Example URL for Hallstadt, in Landkreis Bamberg: https://www.abfalltermine-bamberg.de/Bamberg/Landkreis/Hallstadt for Hallstadt

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP, As PDF Download

**Comment by 5ila5** [comment]
Bamberg is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1733 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfalltermine_bamberg_de.md)
