### ISSUE TITLE
[Source Request]: Wollondilly Shire Council (NSW, Australia)

### ISSUE THREAD

**Issue by PULterHO** [mampfes/hacs_waste_collection_schedule#1744]
### Municipality / Region

Wollondilly Shire Council

### Collection Calendar Webpage

https://www.wollondilly.nsw.gov.au/waste-services/lookup-your-clean-up-details

### Example Address

87 Remembrance Driveway TAHMOOR NSW

### Collection Data Format

As html on a webpage, As documented API, Something different (add to additional information)

### Additional Information

Hi,
Thanks for taking the time to investigate this request.

WSC for this would be great.
The Shire has two means of getting the data, the first being through the web, and the second being through the Shire's publicly published dataset & documented API

Firstly, it would seem that when entering an address on WSC's collection calendar page (as above) calls are made to:
> https://yokqi4ofx1.execute-api.ap-southeast-2.amazonaws.com/Live/wcc_details_lookup

From there, 
> ?fields=xxxxxxx

is appended to the end of the URL when a valid address hit is found. "Fields" appears to relate to the Parcel number - I can't find anything on a rates notice that relates or links to a parcel number, and a quick look on SIXMaps doesn't point out anything obvious to me either.

For example, the address "87 Remembrance Driveway Tahmoor NSW" reaches out to:
> https://yokqi4ofx1.execute-api.ap-southeast-2.amazonaws.com/Live/wcc_details_lookup?fields=10029

When put into Postman, the Pretty view is as follows:

```json
[
    [
        {
            "name": "parcel_no",
            "caption": "parcel no",
            "value": "10029"
        },
        {
            "name": "Waste Service",
            "caption": "Waste Service",
            "value": "Commercial"
        },
        {
            "name": "Waste Pickup",
            "caption": "Waste Pickup",
            "value": "Thursday"
        },
        {
            "name": "WasteNextPickupType1",
            "caption": "WasteNextPickupType1",
            "value": "Thursday, 08 February 2024, Garbage and Recycling"
        },
        {
            "name": "WasteNextPickupType2",
            "caption": "WasteNextPickupType2",
            "value": "Thursday, 01 February 2024, Garbage and Garden Organics"
        },
        {
            "name": "Waste Run",
            "caption": "Waste Run",
            "value": "Run 2"
        },
        {
            "name": "Clean Up Zone",
            "caption": "Clean Up Zone",
            "value": "Commercial - no service entitlement"
        },
        {
            "name": "Last clean up date",
            "caption": "Last clean up date",
            "value": "Commercial - no service entitlement"
        },
        {
            "name": "Next clean up date",
            "caption": "Next clean up date",
            "value": "Commercial - no service entitlement"
        },
        {
            "name": "Future clean up date",
            "caption": "Future clean up date",
            "value": "Commercial - no service entitlement"
        }
    ]
]
```

The second is through a published dataset with a documented API, available here:
https://data.wollondilly.nsw.gov.au/explore/dataset/wasteweeklypickup/information/

I'm not much of a data person, however, if it helps, WSC (currently) have two waste collection cycles - one for Rubbish & Recycling, the other for Rubbish and Compost. These alternate weekly - so one week is R&R, the other is R&C, and then R&R again.

**Comment by 5ila5** [comment]
Added in #1750 I used the web "API" as the official API requires calculating the dates yourself and matching geolocation.
This one is pretty straight forward 

request https://yokqi4ofx1.execute-api.ap-southeast-2.amazonaws.com/Live/wcc_address_lookup?fields={ADDRESS}

get first response and its value

request https://yokqi4ofx1.execute-api.ap-southeast-2.amazonaws.com/Live/wcc_details_lookup?fields={VALUE}

extract dates

Just need to hope the aws domain does not change in the future.

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
