### ISSUE TITLE
[Source Request]: Tunbridge Wells

### ISSUE THREAD

**Issue by romkromk** [mampfes/hacs_waste_collection_schedule#1751]
### Municipality / Region

Tunbridge Wells, UK

### Collection Calendar Webpage

https://tunbridgewells.gov.uk/bins-and-recycling/check-your-bin-collection-day

### Example Address

14 Holly Tree Close, Tunbridge Wells, TN4 9XZ

### Collection Data Format

As html on a webpage

**Comment by billinternet** [comment]
I'd also be keen for this source to be added!

**Comment by 5ila5** [comment]
added by #1758 
This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
