### ISSUE TITLE
[Source Request]: Request for Selby

### ISSUE THREAD

**Issue by Markbez** [mampfes/hacs_waste_collection_schedule#1755]
### Municipality / Region

Selby, North Yorks

### Collection Calendar Webpage

https://www.northyorks.gov.uk/bin-calendar/Selby/results/100052176620

### Example Address

UPRN: 10013454353

https://www.northyorks.gov.uk/bin-calendar/Selby/results/10013454353

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in #1756

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by Markbez** [comment]
Hi! Thanks for adding this! I had to redownload this but it appears to have disappeared from Master

**Comment by 5ila5** [comment]
It has not disappeard from the master. It's still [there](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/northyorks_selby_gov_uk.py) and has not chaged. There sometimes seems to be a problem with HACS not downloading all or the correct files (not sure why and not a problem with this integration). If the file is missing, you can download the [file](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/northyorks_selby_gov_uk.py) and add it manually to custom_components/waste_collection_schedule/waste_collection_schedule/source/northyorks_selby_gov_uk.py ([raw file](https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/northyorks_selby_gov_uk.py))
