### ISSUE TITLE
[Bug]: recycleapp_be.py access token no longer valid

### ISSUE THREAD

**Issue by braham2019** [mampfes/hacs_waste_collection_schedule#1763]
### I Have A Problem With:

A specific source

### What's Your Problem

Since a few weeks, the integration with the Recycle! app in Belgium is no longer working.  HA log indicates unauthorized client. Seems like the access token is no longer valid.

### Source (if relevant)

recycleapp_be

### Logs

```Shell
fetch failed for source Recycle!: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", line 54, in fetch r.raise_for_status() File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.fostplus.be/recycle-public/app/v1/access-token
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
I just checked this with the test addresses and I do not get an error. Does the error occur on startup? 
```
  found 0 entries for 1140 Evere, Bazellaan 1
  found 20 entries for 3001, Waversebaan 276 with events
  found 13 entries for 3001, Waversebaan 276 without events
  found 20 entries for 1400, Rue de namur 1 with events
```

**Comment by braham2019** [comment]
Yes, it does. Can't tell when exactly this started.

**Comment by kristofpoppe** [comment]
Same here, no more data from Recycle app

**Comment by macraspberrypi** [comment]
Hi I confirm I have the same error with recycleapp.
The error appeared when updating to 1.45

**Comment by motsu7** [comment]
I only installed the plugin today but can confirm the same issue on an almost clean HA Core installation with HACS and v1.45 of this plugin.

**Comment by maximede** [comment]
It seems like 1.45.1 is still using the old x-secret ( starting with `8eT` ) instead of the one starting with `eyJhb` used in master (https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py )  
Updating the new key in `custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py` solved my issue until we wait for the next release

**Comment by braham2019** [comment]
That did the trick, thanks !

**Comment by Vlackho** [comment]
I can confirm I had the same issue for a couple of weeks; and changing the old x-secret (with the new one, found in the python script) solved it.

Thanks!
