### ISSUE TITLE
[Bug]: ximmio - bar not returning any data

### ISSUE THREAD

**Issue by jjvandenberg** [mampfes/hacs_waste_collection_schedule#1781]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi, i've installed and tested the intergration. I live in the Netherlands and need to use the Ximmio.nl - "bar" source for my garbage schedule. That does not return any data. I tested with another Ximmio source, like the example     
- name: ximmio_nl
      args:
        company: acv
        post_code: 6721MH
        house_number: 1

that runs just fine. but when used with "bar" data:

waste_collection_schedule:
  sources:
    - name: ximmio_nl
      args:
        company: bar
        post_code: 2991AB
        house_number: 1

No data are returned. Just one value:  
    attribution: "Last update: 02/11/24 11:45:14"

How can I troubleshoot this. It is a known fact dat Barendrecht (the b in "bar") has made a mess of the garbage collection organisation, but i suppose since the (android) app is working more or less ok, an API should be working, somewhere ;-)
Any help is higly appreciated !

### Source (if relevant)

ximmio_nl

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I'm not quite sure if Bar is still supported by this source. It looks like their website uses some other backend now. Needs some further investigation.

**Comment by 5ila5** [comment]
Your config seems to work again, will close this now
