### ISSUE TITLE
[Source Request]: Stadt Emden, Germany

### ISSUE THREAD

**Issue by ciddi89** [mampfes/hacs_waste_collection_schedule#1794]
### Municipality / Region

Stadt Emden, Germany

### Collection Calendar Webpage

https://www.bee-emden.de/abfall/entsorgungssystem/abfuhrkalender/

### Collection Data Format

As ICS/ICAL file

### Additional Information

There is a seperate calendar for each disctrict. It would be great if you can add these. Thank you

**Comment by 5ila5** [comment]
Stadt Emden is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1797 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/bee_emden_de.md)

**Comment by ciddi89** [comment]
Thank you 🙏🏻
