### ISSUE TITLE
RFC: Normalize project

### ISSUE THREAD

**Issue by boesing** [mampfes/hacs_waste_collection_schedule#18]
Hey there,

I am using this component for some time now. I really appreciate it as I've created several automations around it.
But while doing this, I had to create several "helper" template entities.

```yaml
---
platform: template
sensors:
  next_waste_collection_date:
    friendly_name: "Nächste Abholung"
    value_template: >-
      {% set waste_namespace = namespace(next_waste_collection_date="Unbekannt") %}
      {% for attribute in states.sensor.muell.attributes %}
          {% if waste_namespace.next_waste_collection_date == "Unbekannt" and
            (as_timestamp(attribute)|int) > (as_timestamp(states('sensor.date')) | int) %}
            {% set waste_namespace.next_waste_collection_date =
                as_timestamp(attribute) | timestamp_custom("%d.%m.%Y", True) %}
          {%- endif %}
      {%- endfor %}
      {{ waste_namespace.next_waste_collection_date }}
    icon_template: mdi:calendar-clock

  next_waste_collection_type:
    friendly_name: "Nächste Tonne(n)"
    value_template: >-
      {% set waste_namespace = namespace(next_waste_collection_types="Keine") %}
      {% for attribute in states.sensor.muell.attributes %}
          {% if waste_namespace.next_waste_collection_types == "Keine" and
            (as_timestamp(attribute)|int) > (as_timestamp(states('sensor.date')) | int) %}
            {% set waste_namespace.next_waste_collection_types = state_attr("sensor.muell", attribute) %}
          {%- endif %}
      {%- endfor %}
      {% set translation = {
        "grey": "Restmüll",
        "brown": 'Bio',
        "blue": "Papier",
        "wertstoff": "Wertstoff",
      } %}
      {% for barrel in waste_namespace.next_waste_collection_types.split(',') -%}
      {{ translation[barrel]|default(barrel) }}{% if not loop.last %},{% endif %}
      {%- endfor %}
    icon_template: mdi:delete
```

As you can see, I had to parse those barrel types `grey`, `brown`, e.g. to a useful output. This could be avoided if we normalize all kinds of "barrels" so we can map different "types" to a well-known "barrel" in this component.

I've created an example enum for my cases:

```python
from enum import Enum, unique
@unique
class Barrel(Enum):
    PAPER = 'paper'
    RESIDUAL = 'residual'
    BIO = 'bio'
    RECYCLABLE = 'recyclable'
```

I am pretty sure, there are several of other barrels around the globe. I've seen some kind of "Christmas Trees" or "Medical Waste" aswell. So there are dozens of different Barrels but all of them could be mapped to a single value within that Enum, no matter if one API calls it `paper`, the other calling it `blue` and another one calls it `Papier`.

So, if we end up using such enums, it would be quite easy to create translation files for any language aswell as having interoperability as you could move to another city without having to re-write all automations as the enum for your barrels wont change.

```json
{
    "barrels": {
        "paper": "Papier",
        "residual": "Restmüll",
        "bio": "Bio",
        "recyclable": "Wertstoff"
    }
}
```

What do you think about it? I've already played around a bit but as I ain't a python native developer and not that familiar with HA and how it provides translation support, I didn't come that far.

**Comment by mampfes** [comment]
Hi, thanks for sharing your helper entities. I would like to add them to the documentation (if this is ok for you), but for this some little pieces are missing: Could you please also share your initial waste_collection_schedule sensor configuration and some example png's?

Regarding normalization: I think there are a lot of different waste types out there in the world.. And I also think that there are always people who want to have their own naming for their local waste types. Normalization wouldn't help them and you still need a way to customize your appointment types. On the other side I see your problem, but I would solve it in a different way: You can already set an alias for every appointment type (see https://github.com/mampfes/hacs_waste_collection_schedule, section "Customize Source"). If you use this feature you don't have to translate it within your helper entities anymore and they become generic therefore.

Maybe the documentation is not obvious enough and I should add another example. What do you think? Would this fix your problem?

**Comment by boesing** [comment]
> I would like to add them to the documentation (if this is ok for you)

Feel free.

## Sensor config
```yaml
waste_collection_schedule:
  sources:
    - name: awbkoeln_de
      args:
        street_code: <code>
        building_number: <building>
  day_switch_time: "23:59"
```

## Screenshots
![image](https://user-images.githubusercontent.com/2189546/101552555-54d35f80-39b3-11eb-8f67-7b10c595d2e5.png)


> And I also think that there are always people who want to have their own naming for their local waste types

Overwriting enum translations from within the YAML configuration would be quite easy. 
As you already mentioned in your comment, there is already a way to use an alias tho.
However, I am not sure if that would work when there are two appointment types on the same date as these are `comma` separated and thus there might be multiple values like `blau, grau` or `grau, blau` and so on. The more waste is scheduled, the merrier combinations would be available. One could solve that with using a list of enums for a specific date instead of having just a string value.

> Normalization wouldn't help them and you still need a way to customize your appointment types

Well, I think it would as you dont have to override `blue` or `papier` or `paper` or whatever color that is in another country as you have a dedicated enum value for `paper` waste.

--- 

However, I see that this normalization wont suit your needs and thus there is no need to put that much work in that kind of refactoring.

Anyways, thanks for your time. 👍
