### ISSUE TITLE
[Bug]: Ashfield District Council is broken

### ISSUE THREAD

**Issue by jerbzz** [mampfes/hacs_waste_collection_schedule#1811]
### I Have A Problem With:

A specific source

### What's Your Problem

When attempting to retrieve data for Ashfield District Council, a `400 Bad Request` error is generated.

I have verified that the UPRN is correct.

Ashfield's online calendar was recently offline for a period of time but has now been fixed, and I suspect a breaking change on its return.

I confirm that I have tried the example parameters, verified that the website is working, and tested with `master`.

### Source (if relevant)

ashfield_gov_uk

### Logs

```Shell
-02-20 14:48:23.163 ERROR (SyncWorker_23) [waste_collection_schedule.source_shell] fetch failed for source Ashfield District Council:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ashfield_gov_uk.py", line 74, in fetch
    r.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.ashfield.gov.uk/api/powersuite/GetCollectionByUprnAndDate/[REDACTED]
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: ashfield_gov_uk
      args:
        uprn: [REDACTED]

sensor:
  - platform: waste_collection_schedule
    source_index: 0
    name: "Bin Collection"
    count: 2
    #value_template: VALUE_TEMPLATE
    #date_template: DATE_TEMPLATE
    add_days_to: True
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jerbzz** [comment]
@ConfusedTA I believe you originally added this integration.

I've had a look at what the site is currently doing but this is outside my area of expertise!

**Comment by ConfusedTA** [comment]
I was hoping no one else would notice, and I wouldn't have to look at it! 🤣 

But yeah, it's substantially changed, I _think_ it's similar to Croydon/Bracknell now, but I haven't had the time to look much closer at it, other priorities I'm afraid 😢 

Maybe one of the developers who looked at those could help, as they've already figured out some of the difficulties...

Can't guarantee when I'll have time again to look, I'm afraid. It didn't take me very long to add it in the first place, as it was relatively simple - now, not so much 😞

**Comment by 5ila5** [comment]
They completely changed the requests made by the website. So we need a complete rewrite (they made it a lot harder to parse)

**Comment by jerbzz** [comment]
Yep agreed - though I doubt it's a totally unknown system they are using. I'll keep it on my list of stuff to dig into...

**Comment by qusaizakir** [comment]
Any updates on this? I've tried my (amateur) hand at getting something working but didn't get very far!

**Comment by 5ila5** [comment]
The website is a pretty big pain to reverse engineer, I avoided it for a while and spend some hours today. I'm pretty far, but the last request still returns 403 Forbidden

my testing: https://gist.github.com/5ila5/4e3a42b62675a08f1ced0a55e7da941f

**Comment by jerbzz** [comment]
Amazing work! I will test later. Looks like it was not a good one for my first try at such reverse engineering 😂

**Comment by qusaizakir** [comment]
Thank you very much!!
