### ISSUE TITLE
[Bug]: RenoSyd seems to have changed its website

### ISSUE THREAD

**Issue by rbgaard** [mampfes/hacs_waste_collection_schedule#1814]
### I Have A Problem With:

A specific source

### What's Your Problem

Information is no longer updated using the site used in [custom_components/waste_collection_schedule/waste_collection_schedule/source/renosyd_dk.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/renosyd_dk.py)

### Source (if relevant)

renosyd_dk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
Seems the information is now available on this url: https://skoda-selvbetjeningsapi.renosyd.dk/api/v1/toemmekalender?nummer=012879 
where nummer is a unique number for the address. Can easily be found using developer mode in the browser.
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed by #1817
