### ISSUE TITLE
[Bug]: Renoweb doesn't work for Jammerbugt Kommune

### ISSUE THREAD

**Issue by Bluhme1** [mampfes/hacs_waste_collection_schedule#1816]
### I Have A Problem With:

A specific source

### What's Your Problem

@r-poulsen 
Trying to use Renoweb to collect data from my summer cabin in Jammerbugt Kommune.
I am also using the integration https://github.com/briis/renoweb and everything works fine here
I am using the correct address and have also found the address-Id

### Source (if relevant)

renoweb.dk

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 10.56.06 (1 occurrences)
Last logged: 10.56.06

fetch failed for source RenoWeb: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/renoweb_dk.py", line 107, in fetch json={"adrid": self._address_id, "common": False}, ^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/renoweb_dk.py", line 95, in _address_id self._get_address_id() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/renoweb_dk.py", line 78, in _get_address_id json={"searchterm": f"{self._address},", "addresswithmateriel": 3}, ^^^^^^^^^^^^^ AttributeError: 'Source' object has no attribute '_address'. Did you mean: '_address_id'?
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
   - name: renoweb_dk
      args:
         municipality: jammerbugt
         address: Skorr-Karensvej 7
         address_id: 5300
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Bluhme1** [comment]
Sorry. Used a wrong address_id. Closing
Thanks for the great work

**Comment by r-poulsen** [comment]
Ah, I think I see what happened; It's only necessary to use either address or address_id, but address_id will take precedence. If the address_id isn't one that actually exists, then it will fail.

I'll see if I can improve the error handling.
