### ISSUE TITLE
Telford and Wrekin Calendar stopped working

### ISSUE THREAD

**Issue by kakarotto185** [mampfes/hacs_waste_collection_schedule#1819]
### I Have A Problem With:

A specific source

### What's Your Problem

Telford and wrekin calendar not showing any dates. looking at the log it looks like that the date format could be wrong.

### Source (if relevant)

telford_gov_uk

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 17:47:44 (2 occurrences)
Last logged: 17:49:26

fetch failed for source Telford and Wrekin Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/telford_gov_uk.py", line 93, in fetch date = datetime.datetime.strptime(datestring, "%A %d %B").date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/_strptime.py", line 566, in _strptime_datetime return cls(*args) ^^^^^^^^^^ ValueError: day is out of range for month
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
This issue because we try to parse a date without an year and add the current correct year later. The datetime library then defaults to 1900 which isn't a leap year and therefore the parsing fails for 29 February.

Fixed in #1826

This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

but it will resolve itself after the 29 Februray
