### ISSUE TITLE
[Source Request]: Can 

### ISSUE THREAD

**Issue by preis98** [mampfes/hacs_waste_collection_schedule#1821]
### Municipality / Region

Wohlbach, gemeinde Mühlental

### Collection Calendar Webpage

https://www.vogtlandkreis.de/B%C3%BCrgerservice-und-Verwaltung/Infos-und-Services/Abfallentsorgung/Abfuhrtermine

### Example Address

Obere Dorfstraße 33a, 08626 Mühlental

### Collection Data Format

As ICS/ICAL file, Something different (add to additional information)

### Additional Information

https://awi.vogtlandkreis.de/WasteManagementVogtland/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=1031600001&AboID=217949&Fra=R2;P;P1;B;G;R1

**Comment by 5ila5** [comment]
Landkreis Vogtland is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1825 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/vogtlandkreis_de.md)
