### ISSUE TITLE
[Bug]: ART Trier Germany collecting no more Data

### ISSUE THREAD

**Issue by Primax02** [mampfes/hacs_waste_collection_schedule#1835]
### I Have A Problem With:

A specific source

### What's Your Problem

ART Trier Germany collecting no more Data. It worked till yesterday. I think they have a new homepage.
The Calender is now empty, only one Entry on February 26th: A.R.T. Wichtiger Hinweis!
The link (https://www.art-trier.de/cms/abfuhrtermine-1002.html) in the Description for ART Trier doesn't work anymore. Get a 404 Error Page.

Ver. 1.45.1

### Source (if relevant)

art_trier_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
- name: art_trier_de
      args:
        district: "Fellerich"
        zip_code: "54456"
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Primax02** [comment]
New Source URL for art_trier_de.py

def fetch(self):
        url = f"{API_URL}/{self._zip_code}:{self._district}::@{REMINDER_DAY}-{REMINDER_TIME}.ics"

**Comment by 5ila5** [comment]
The url does work for some regions but not all as some remove chars like `(` and others don't. As this source just uses the ICS backend anyway, it is much easier to maintain if users just use the [already documented ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/art_trier_de.md). I made the change that fixes the url for some regions, but added a deprecated warning advising to move to the ICS source in #1837.

**Comment by 5ila5** [comment]
That's a leap year bug, it's fixed in #1855 but should work now without the fix as it's not the 29th, February anymore

**Comment by clemone210** [comment]
I have the isse with 54344 Kenn.
The working URL is https://www.art-trier.de/abfuhrtermin/2024/

**Comment by 5ila5** [comment]
@clemone210 This works with the new implementation added in #1837.
This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

But I suggest switching to the ICS version, documentation for art-trier.de can be found [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/art_trier_de.md)

**Comment by clemone210** [comment]
> @clemone210 This works with the new implementation added in #1837. This will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
> 
> But I suggest switching to the ICS version, documentation for art-trier.de can be found [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/art_trier_de.md)

any idea why it jumps back to 1.45.1 after selecting master?
