### ISSUE TITLE
[Bug]: Hacs wants update to 1.45.1 but it is actually older than "master"

### ISSUE THREAD

**Issue by Bluhme1** [mampfes/hacs_waste_collection_schedule#1842]
### I Have A Problem With:

The integration in general

### What's Your Problem

When I "upgrade" to 1.45.1 it is actually a downgrade as "master" is newer 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I changed the version number in the manifest.json to the next release number. Does this stop the behavior? I'm not sure if there is anything else I can do.
