### ISSUE TITLE
[Bug]: "Ortsteil" missing for AbfallPlus in Weißenburg/Gunzenhausen

### ISSUE THREAD

**Issue by SvenJ76** [mampfes/hacs_waste_collection_schedule#1845]
### I Have A Problem With:

A specific source

### What's Your Problem

For my part of the village (aka "Ortsteil") it is not choosable. 
You can check it here: https://www.landkreis-wug.de/abfall/abfuhrkalender/ , I have to select
Stadt/Gemeinde:Haundorf
Straße/Ortsteil: Obererlbach
Straße: Alle Straßen

I tried the app_abfallplus_de.py script, but I can't select my "Ortsteil", just the Maincommunity/-city "Haundorf".
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallappwug
        city: Haundorf
        strasse: alle Straßen

### Source (if relevant)

app_abfallplus_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
try:

```yaml
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallappwug
        city: Haundorf
        bezirk: Obererlbach
```

The wizard should now correctly ask for the `bezirk` argument (fixed in #1857)
