### ISSUE TITLE
[Bug]: Icons for crawley

### ISSUE THREAD

**Issue by marc115uk** [mampfes/hacs_waste_collection_schedule#1853]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

please change crawley_gov_uk.py file, ICON_MAP. change "bio": "mdi:leaf", to "GREENbin Garden Waste Collection": "mdi:leaf", as this is how it it provided from the api.

Many thanks 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by marc115uk** [comment]
May have done it as a pull request, new to editing filles sorry

**Comment by 5ila5** [comment]
Updated in #1845. 
Just so you know, you can provide custom icons using the [customize argument](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#attributes-for-customize) in your source configuration
