### ISSUE TITLE
[Source Request]: Gelbersack for Stuttgart

### ISSUE THREAD

**Issue by sthubig** [mampfes/hacs_waste_collection_schedule#1860]
### Municipality / Region

Germany, Stuttgart, Gelber Sack

### Collection Calendar Webpage

https://www.gelbersack-stuttgart.de/

### Example Address

Stadtteile

Retrieved Stadtteile from sourcecode of the side:
Altenburg;Am Bismarckturm;Am Pragfriedhof;Am Rosensteinpark;An der Burg;Asemwald;Auf der Prag;Bahnhof Feuerbach;Benzviertel;Berg;Bergheim;Birkach-Nord;Birkach-Süd;Birkenäcker;Bopser;Botnang-Nord;Botnang-Ost;Botnang-Süd;Botnang-West;Bruckwiesen;Burgholzhof;Büsnau;Cannstatt-Mitte;Chausseefeld;Dachswald;;Degerloch;Diemershalde;Dobel;Dürrlewang;Espan;Europaviertel;Fasanenhof;Fasanenhof-Ost;Feuerbach-Mitte;Feuerbach-Ost;Feuerbacher Tal;Feuersee;Flohberg;Frauenkopf;Freiberg;Gablenberg;Gaisburg;Gänsheide;Gehrenwald;Giebel;Hafen;Haigst;Hallschlag;Hasenberg;Hauptbahnhof;Hausen;Hedelfingen;Heerstraße;Heilbronner Straße;Heslach;Heumaden;Heusteigviertel;Hofen;Hoffeld;Hohe Warte;Hohenheim;Höhenrand;Hölderlinplatz;Im Geiger;Kaltental;Karlshöhe;Kernerviertel;Killesberg;Kräherwald;Kurpark;Lauchäcker;Lederberg;Lehen;Lemberg/Föhrich;Lenzhalde;Lindenschulviertel;Luginsland;Möhringen-Mitte;Möhringen-Nord;Möhringen-Ost;Möhringen-Süd;Mönchfeld;Mönchhalde;Muckensturm;Mühlhausen;Münster;Neckarvorstadt;Neue Vorstadt;Neugereut;Neuwirtshaus;Nordbahnhof;Oberer Schlossgarten;Obertürkheim;Österfeld;Ostheim;Pfaffenwald;Plieningen;Pragstraße;Rathaus;Relenberg;Riedenberg;Rohr;Rohracker;Rosenberg;Rosental;Rot;Rotebühl;Rotenberg;Schmidener Vorstadt;Schönberg;Seelberg;Siegelberg;Sillenbuch;Solitude;Sommerrain;Sonnenberg;Stammheim-Mitte;Stammheim-Süd;Steckfeld;Steinhaldenfeld;Sternhäule;Stöckach;Südheim;Tränke;Uhlandshöhe;Uhlbach;Universität;Untertürkheim;Vaihingen-Mitte;Veielbrunnen;Vogelsang;Waldau;Wallgraben-Ost;Wallgraben-West;Wangen;Wasen;Weilimdorf;Weilimdorf-Nord;Weinsteige;Weißenhof;Wildpark;Winterhalde;Wolfbusch;Zazenhausen;Zuffenhausen-Am Stadtpark;Zuffenhausen-Elbelen;Zuffenhausen-Frauensteg;Zuffenhausen-Hohenstein;Zuffenhausen-Im Raiser;Zuffenhausen-Mitte;Zuffenhausen-Mönchsberg;Zuffenhausen-Schützenbühl;

### Collection Data Format

As html on a webpage

### Additional Information

I Dont really know what the data format is, u need

**Comment by 5ila5** [comment]
gelbersack-stuttgart.de is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1861 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/gelbersack_stuttgart_de.md)

**Comment by sthubig** [comment]
Great, thank you very much for your quick implementation!
