### ISSUE TITLE
[Bug]: Barnsley MBC. Fails when running with collection date as today

### ISSUE THREAD

**Issue by LZStealth** [mampfes/hacs_waste_collection_schedule#1880]
### I Have A Problem With:

A specific source

### What's Your Problem

Barnsley Council source does not work when the bin collection date is 'today'
This attempted to parse the date and then fails.

It looks like something with a check if the date is 'today' could resolve this.
```
if heading[0].text == "Today": 
    bin_date = datetime.today().date()
else:
    bin_date = datetime.strptime(heading[0].text, "%A, %B %d, %Y").date()
```

### Source (if relevant)

barnsley_gov_uk 

### Logs

```Shell
fetch failed for source Barnsley Metropolitan Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/barnsley_gov_uk.py", line 83, in fetch bin_date = datetime.strptime(heading[0].text, "%A, %B %d, %Y").date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data 'Today' does not match format '%A, %B %d, %Y'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: barnsley_gov_uk
      args:
        postcode: S70 3QU
        uprn: '100050607581'
      calendar_title: Waste Collection
  day_switch_time: '12:00'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed in #1884


This will be part of release 1.47.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
