### ISSUE TITLE
[Feature]: add ALP-LUP, City: Gammelin Germany 

### ISSUE THREAD

**Issue by Marco99887766** [mampfes/hacs_waste_collection_schedule#1882]
### I propose a feature for:

The integration in general

### Describe your wanted feature

Hi,
Can you add the town of Gammelin to the waste calendar.  
The service runs at www.alp-lup.de - 
https://alp-lup.de/Service-Center/Abfuhrtermine/Abfallkalender/.  
The link for the app is https://play.google.com/store/apps/Details? id=com.gemosgmbh.lwlwasteapp.

Thank you

**Comment by 5ila5** [comment]
is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1883 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/alp_lup_de.md)
