### ISSUE TITLE
[Bug]: New Addresses use 9 digits at ID "Abfuhrkalender Stadt Fürth", but only 8 digits work

### ISSUE THREAD

**Issue by Marcoblue** [mampfes/hacs_waste_collection_schedule#1891]
### I Have A Problem With:

A specific source

### What's Your Problem

If I use an ID with 8 digits, everything works fine. Buit my Address has 9 digits.

For [example](https://abfallwirtschaft.fuerth.eu/?location=105070001)

Also [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallwirtschaft_fuerth_eu.md) it can be changed, when working.

In the meantime, I use an ID from the neighboring street.

### Source (if relevant)

https://abfallwirtschaft.fuerth.eu/?location=105070001

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I cannot reproduce this issue, id 105070001 works just fine on my side. Could you please take a look at your logs and post them here to see what exactly went wrong.

**Comment by Marcoblue** [comment]
Thanks for trying. I changed it back to 9 digits today and restarted it. But it works. No more error messages. In the meantime I only had an update to core_2024.3.0, I don't know if it has anything to do with that.
I close with this.
