### ISSUE TITLE
[Bug]: Faulty source for Kreis Pinneberg?

### ISSUE THREAD

**Issue by olli186** [mampfes/hacs_waste_collection_schedule#1892]
### I Have A Problem With:

A specific source

### What's Your Problem

Kreis Pinneberg is not using abfallnavi_de. Kreis Pinneberg uses https://abfall.kreis-pinneberg.de/.
Please add the correct source.

### Source (if relevant)

abfallnavi_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
https://abfall.kreis-pinneberg.de/ is using **abfall**navi and is sending it requests to the abfallnavi/regioIT site (https://pi-abfallapp.regioit.de/abfall-app-pi). There also is a big **abfall**navi logo as  you can use the abfallnavi_de source with the `service: pi` parameter. Like this:

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: pi
        ort: Groß Nordende
        strasse: Förn Sandweg
```
