### ISSUE TITLE
[Bug]: all_day = true but event end_time overlaps into next day

### ISSUE THREAD

**Issue by richardmx5guys** [mampfes/hacs_waste_collection_schedule#1893]
### I Have A Problem With:

The integration in general

### What's Your Problem

This is what we have ... but this means that events on two consecutive days will have an overlapping ent_time and start_time
```
all_day: true
start_time: "2024-03-14 00:00:00"
end_time: "2024-03-15 00:00:00"
```

should be as below, as the above makes the event longer than one day
```
all_day: true
start_time: "2024-03-14 00:00:00"
end_time: "2024-03-14 23:59:59"
```

Detecting an event 6 hours before start makes it non functional

Thank you 😊 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
> Detecting an event 6 hours before start makes it non functional

I honestly do not understand what you mean with that, could you please be more precice what you mean with that.
I'm not sure if it works like you described. Adding an all day event to HA's local calendar adds an event like this:
```yaml
all_day: true
start_time: 2024-03-16 00:00:00
end_time: 2024-03-17 00:00:00
```
The calendar displays it as one day as well.

**Comment by richardmx5guys** [comment]
My apologies 🙏
Sorry to have wasted your time.
No issue really, it appears it all depends on the perception.
I was using a calendar as a data point disregarding the developed functionality of the integration.
All good.
Thank you for the integration that works very well and is very useful.
