### ISSUE TITLE
[Source Request]: Change sourceintegration landkreis bamberg

### ISSUE THREAD

**Issue by Daniel199614** [mampfes/hacs_waste_collection_schedule#1896]
### Municipality / Region

Bamberg, Deutschland

### Collection Calendar Webpage

https://www.abfalltermine-bamberg.de/Bamberg/Landkreis/Frensdorf

### Example Address

Am Anger 5, 96158 Frensdorf, Deutschland

### Collection Data Format

As ICS/ICAL file

### Additional Information

Landkreis bamberg has the same integration for wast collection on the website as forchheim (https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfalltermine_forchheim_de.md?plain=1).
Can the source for landkreis bamberg change to the same integration as for forchheim.

**Comment by 5ila5** [comment]
Bamberg is already supported and listed in the README. You can find the documentation [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfalltermine_bamberg_de.md).
