### ISSUE TITLE
[Bug]: Cornwall UK - Multiple Rubbish days only detects latest

### ISSUE THREAD

**Issue by wardy277** [mampfes/hacs_waste_collection_schedule#1904]
### I Have A Problem With:

A specific source

### What's Your Problem

Over the next few months cornwall are switching up their schedule caused by adding food waste. I am next in the batch, east cornwall

Now, the addon picks these up well. the issue is that the scrape url shows both existing and new dates, but as they are under the same name, the later is overriding the current.

For example, Rubbish collections will be on a thursday for the next 3 weeks, then after that it will be on a monday. The duplicates we have are:
Rubbish THU 28 Mar
Rubbish MON 15 Apr

The sensor is now picking the value of "MON 15 Apr" so my next collection incorrectly reporting as being in 24 days

I understand that this is a short term, and only affects me for 3 weeks. But wondered if other parts of cornwall will also get this issue later on in the year

### Source (if relevant)

cornwall_gov_uk

### Logs

```Shell
Current collections
Recycling THU 4 Apr
Rubbish THU 28 Mar
Garden MON 1 Apr
Your new collections dates
Your waste collections are changing from the week beginning 8 April.

Below are the dates for your first food waste, recycling and rubbish collections using the new services. Please note: if you subscribe to a garden waste collection this will continue as normal.

Food MON 8 Apr
Recycling MON 8 Apr
Rubbish MON 15 Apr
Garden MON 1 Apr
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I honestly do not understand your issue. Using configuration postcode: "PL17 8PL" housenumberorname: "3" I get all collections like expected:
```
    2024-03-28 : Recycling [mdi:recycle]
    2024-03-28 : Rubbish [mdi:delete]
    2024-04-04 : Garden [mdi:flower]
    2024-04-11 : Food [None]
    2024-04-11 : Recycling [mdi:recycle]
    2024-04-18 : Rubbish [mdi:delete]
    2024-04-04 : Garden [mdi:flower]
```
The sensor should show the dates to the next collection of the specified types (or all if no types specified).
Please provide your sensor configuration if your sensor does not behave like this for some reason.

**Comment by wardy277** [comment]
Interesting, last night the sensor for rubbish changed from 23 days and now shows 5 days

My end point is https://www.cornwall.gov.uk/umbraco/surface/waste/MyCollectionDays?uprn=100040018773&url=https%3A%2F%2Fwww.cornwall.gov.uk%2Fmy-area%2F%3FPostcode%3DPL12%206EH%26Uprn%3D100040018773&subscribe=False&_=1711203718775

With the config:
```
waste_collection_schedule:
  sources:
  - name: cornwall_gov_uk
    args:
      postcode: PL126EH
      uprn: 100040018773

```

```
platform: waste_collection_schedule
name: waste_collection_rubish
value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
types:
  - Rubbish
```

**Comment by 5ila5** [comment]
Not sure what went wrong here. I don't know how to debug this. If it does happen again, let me know. Maybe some weird date stuff.
