### ISSUE TITLE
[Bug]: sensors shown unknow

### ISSUE THREAD

**Issue by Lucascoco** [mampfes/hacs_waste_collection_schedule#1912]
### I Have A Problem With:

A specific source

### What's Your Problem

the sensors stand on unknow

### Source (if relevant)

Zweckverband Abfallwirtschaft Region Hannover

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 12:28:15 (1 Vorkommnisse)
Zuletzt protokolliert: 12:28:15

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 117, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 286, in parse_events raise ValueError("Content is invalid!") ValueError: Content is invalid!
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
One of our test case has the same issue. One of the ICAL files you can Download is completely empty and the parsing fails. The "fix" in #1913 will skip this iCal file and therefore this waste type. The integration then should work again but will not display any events for the skipped waste type. ( `Bioabfall 14- täglich`. Only displays the  `Bioabfall 1x wöchentlich` events)

This behavior might be intended by the developers as `Bioabfall 14- täglich` starts in August.

Our affected test case is:
```json
        {"gemeinde": "Isernhagen",  "Am Lohner Hof / Isernhagen Fb", "10"}
```


This will be part of release 1.47.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
