### ISSUE TITLE
[Feature]: Waste type like wildcast

### ISSUE THREAD

**Issue by Diddlik** [mampfes/hacs_waste_collection_schedule#1915]
### I propose a feature for:

Sensors

### Describe your wanted feature

"In my waste collection calendar, there are various types of collections listed, such as:

    2024-05-10: ASH Restmüll
    2024-06-06:  ASH Umweltmobil auf Tour, ASH Restmüll

I've set up a function to filter and display specific types of collections, like the 'ASH Restmüll'. However, it seems that this function only displays events that exactly match the defined type. This results in mixed events like on 2024-06-06, where both 'ASH Umweltmobil auf Tour' and 'ASH Restmüll' are listed, not being shown when I filter for 'ASH Restmüll'.

Is it possible to adjust the type check to see if the event name contains the specified type, rather than matching it exactly?"

**Comment by 5ila5** [comment]
Thats currently not possible but would probably be not that hard to implement.

The best you can do at the moment is to use the `customize: type: alias:` options (source configuration, not senosr) to alias alll your Restmüll collections to `Restmüll` then you can just use the `Restmüll` type in your sensor, but you still need to list all possible event names.

**Comment by Diddlik** [comment]
Ok, good point, that I can map different event to the same alias. Thank you!
