### ISSUE TITLE
[Request] AWB Esslingen

### ISSUE THREAD

**Issue by psistorm** [mampfes/hacs_waste_collection_schedule#193]
Hi there,

I tried to integrate AWB Esslingen into the Waste Collection Schedule locally which seems to use abfall.io, but I couldn't extract the information needed.

https://www.awb-es.de/abfuhr/abfuhrtermine/__Abfuhrtermine-suchen.html

Are you able to extract the needed information? I couldn't find the id's and so on. Seems like they hid the requests somehow server-side to me. Or am I missing something?

I could just get to the point where they show the ics file like [here](https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=09bfb229c9154cd3f75316e2813a9075)

Thanks in advance,

psi

**Comment by psistorm** [comment]
Awesome! Thank you a lot! So as I understand there was no way to retrieve the ids and you're basically scraping the information with this plugin?

**Comment by mampfes** [comment]
Yes, AWB Esslingen uses a different API than the other abfall.io sources. Therefore I had to create a new source. Maybe this is the first example of a new API generation. Then I have to generalize the source. Let's see...
