### ISSUE TITLE
Cannot run inquirer wizard

### ISSUE THREAD

**Issue by Hohenloherin** [mampfes/hacs_waste_collection_schedule#194]
I installed the inquirer module via terminal:
![image](https://user-images.githubusercontent.com/85617168/160880189-5974ecda-ddc4-4587-87af-b995c9e55664.png)
If I run the wizard I get the following error:
![image](https://user-images.githubusercontent.com/85617168/160880638-5ac375f4-c4c4-43c6-b626-5efdfb3fa624.png)

What am I doing wrong? I cannot find the arguments for my waste collection service like this.

**Comment by mampfes** [comment]
Python doesn't find the inquirer module. Maybe it is installed in a different venv.

Do you have access to a native Linux box? (Where you don't need this magic command line)?

You can also send me your location and will run the wizard for you.

**Comment by Hohenloherin** [comment]
Thanks for your reply. I had the idea too to try the inquirer on my Linux pc, but I didn't find the time yet. I will give this a try today.

**Comment by Hohenloherin** [comment]
What I did: 
1. Installed python 
2. copied the file abfallnavi_de.py from the directory /config/custom_components/waste_collection_schedule/waste_collection_schedule/wizard to my local directory
3. executed abfallnavi_de.py from the command line 
 
It gives me back an error instead of the service details:

`h@h:~$ python3 abfallnavi_de.py
Traceback (most recent call last):
  File "abfallnavi_de.py", line 11, in <module>
    from waste_collection_schedule.service.AbfallnaviDe import SERVICE_DOMAINS, AbfallnaviDe  # type: ignore # isort:skip # noqa: E402
ModuleNotFoundError: No module named 'waste_collection_schedule'
`
4. copied the file abfallnavi_de.py from /config/custom_components/waste_collection_schedule/waste_collection_schedule/source  to my local directory and got this error back:

`h@h:~$ python3 abfallnavi_de.py
Traceback (most recent call last):
  File "abfallnavi_de.py", line 1, in <module>
    from waste_collection_schedule import Collection  # type: ignore[attr-defined]
ModuleNotFoundError: No module named 'waste_collection_schedule'
`
What can I do to make it run or which mistake I make? Thank your for your help in advance.

**Comment by mampfes** [comment]
I would clone the whole repository:

```
git clone git@github.com:mampfes/hacs_waste_collection_schedule.git
cd hacs_waste_collection_schedule/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/
./abfallnavi_de.py
```

**Comment by Hohenloherin** [comment]
So einfach scheint das nicht zu gehen:

`:~$ git clone git@github.com:mampfes/hacs_waste_collection_schedule.git
Klone nach 'hacs_waste_collection_schedule' …
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
`
Jetzt habe ich nur yes angegeben  anstelle des Fingerprints. Jetzt müsste ich die Berechtigung erst wieder löschen. Wie lautet der Befehl dazu?

**Comment by mampfes** [comment]
Ah, ok - you don't have a valid ssh setup. Then use HTTPS instead:

`git clone https://github.com/mampfes/hacs_waste_collection_schedule.git`

**Comment by Hohenloherin** [comment]
Thank you very much. 
This time it worked and I got the service parameters. Now I will continue to set it up.

**Comment by mampfes** [comment]
Any progress?

**Comment by Hohenloherin** [comment]
Thanks for asking. It works perfectly now and I have setup an automation on it.
Great work 👏 👍

**Comment by Hohenloherin** [comment]
I still struggle to make the difference in the definition of the sensor between “Papiertonne” and “Papiertonne 1100”.
This is from here: [https://community.home-assistant.io/t/waste-collection-schedule-framework/186492/174]
