### ISSUE TITLE
DELETE [Bug]: Error during setup of component waste_collection_schedule

### ISSUE THREAD

**Issue by JayZiii** [mampfes/hacs_waste_collection_schedule#1942]
fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 140, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 765, in generate_calendar self.select_street() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 599, in select_street raise Exception(f"Street {self._strasse_search} not found.") Exception: Street xxxrstr. not found.

**Comment by 5ila5** [comment]
I will close this based on your renaming
