### ISSUE TITLE
[Source Request]: For Landkreis Schwandorf , Germany

### ISSUE THREAD

**Issue by faltinho** [mampfes/hacs_waste_collection_schedule#1954]
### Municipality / Region

Landkreis Schwandorf

### Collection Calendar Webpage

https://entsorgung-sad.de/

### Example Address

Hauptstraße 4, 93133 Burglengenfeld

### Collection Data Format

As ICS/ICAL file

### Additional Information

Is it possible to add the calendar for region Schwandorf?

**Comment by 5ila5** [comment]
Landkreis Schwandorf is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1959 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/entsorgung_sad_de.md)
