### ISSUE TITLE
[Source Request]: Flintshire, United Kingdom

### ISSUE THREAD

**Issue by HidYn** [mampfes/hacs_waste_collection_schedule#1955]
### Municipality / Region

Flintshire, United Kingdom

### Collection Calendar Webpage

https://digital.flintshire.gov.uk/FCC_BinDay

### Example Address

7 Drury Lane, BUCKLEY, CH7 3JD 

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
added by #1972

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
