### ISSUE TITLE
[Bug]: ecoharmonogram shows invalid schedule

### ISSUE THREAD

**Issue by travnick** [mampfes/hacs_waste_collection_schedule#1963]
### I Have A Problem With:

A specific source

### What's Your Problem

I see a schedule for a different location. Currently it's for `Kiełkowice (gmina Zawiercie) ul. Łąki` instead of `Zawiercie ul. Równa`. See the reference https://www.czystagmina.zawiercie.eu/kategorie/harmonogram

I'm not very sure if this is the exact place of the issue, but checking if "Zawiercie" is in `name` is not always valid solution: [source code](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/service/EcoHarmonogramPL.py#L65)

There are multiple towns that contain "Zawiercie" in its name. See https://ecoharmonogram.pl/api/api.php?action=getTowns:
```
{"id":"3360","communityId":"157","name":"Kie\u0142kowice (gmina Zawiercie)","district":"Zawiercie","province":"\u015al\u0105skie","icon":"https:\/\/ecoharmonogram.pl\/ecopagenew\/logo\/zawiercie.png","isStrNmrReq":"1","schedulePeriodId":2}

{"id":"3335","communityId":"157","name":"Zawiercie","district":"Zawiercie","province":"\u015al\u0105skie","icon":"https:\/\/ecoharmonogram.pl\/ecopagenew\/logo\/zawiercie.png","isStrNmrReq":"1","schedulePeriodId":2}
```

### Source (if relevant)

ecoharmonogram_pl

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
   sources:
     - name: "ecoharmonogram_pl"
       args:
         town: Zawiercie
         street: Równa
         district: Zawiercie
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed in #1973

If multiple districts match (using `search in response`) it now tries to find a perfect match and if there are multiple matches but no perfect match it will raise an error you can find in your logs.

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by travnick** [comment]
thank you!
I've tried to redownload, or even remove and install `waste_collection_schedule` again from `master`, but it looks like stuck on `1.47.0` version (there are no changes in the code).
Is `waste_collection_schedule` somehow related to this, or it's only HACS/HA issue?

**Comment by 5ila5** [comment]
I'm honestly not sure, but I do not know what should be the problem on our side (but there are multiple reports, that updating does not work correctly) you can modify the file (custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py) manually: https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py

**Comment by travnick** [comment]
I reviewed the situation and:
* it looks like the bug is not gone yet :( - didn't have enough time to debug
* it looks like downloading new wersion is working - I see the changes in `custom_components/waste_collection_schedule/waste_collection_schedule/source/ecoharmonogram_pl.py`. Previously was looking at [print_possible_sides](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/service/EcoHarmonogramPL.py) that is not fixed, so I thought I have the old version.
