### ISSUE TITLE
[Source Request]: Abfallwirtschaft Heidekreis

### ISSUE THREAD

**Issue by ppabst** [mampfes/hacs_waste_collection_schedule#1965]
### Municipality / Region

Heidekreis, Germany

### Collection Calendar Webpage

https://www.ahk-heidekreis.de/fuer-privatkunden/abfuhrzeiten.html

### Example Address

Up de Linnen 101, 29614 Soltau, Germany

### Collection Data Format

As ICS/ICAL file

**Comment by ReneNulschDE** [comment]
Analysis:
1. Final Step to get ICAL
POST : `https://ahkwebapi.heidekreis.de/api/object/40592/QDisposalScheduler/asIcal`
Request BODY 
```
{"von":"2024-04-19T22:00:00.000Z","bis":"2025-04-19T00:00:00.000Z","benachrichtigungVorJederAbholung":false,"abholbenachrichtigungTageVorher":1,"abholbenachrichtigungUhrzeit":{"ticks":28800000,"sekunden":28800,"minuten":480,"stunden":8},"benachrichtigungNächsterKalender":false,"kalenderBenachrichtigungTageVorEnde":3,"kalenderbenachrichtigungUhrzeit":{"ticks":28800000,"sekunden":28800,"minuten":480,"stunden":8}}
```

To get the object id:

First API Request:
`https://ahkwebapi.heidekreis.de/api/QMasterData/QStreetByPartialName?PartialName=a` (No special headers)

Returns a JSON array:
```
[
    {
        "id": 126739,
        "name": "Am Ahlersteich",
        "place": "Walsrode",
        "plz": "29664",
        "zip": {
            "id": 5596,
            "zip": "29664",
            "place": "Walsrode",
            "district": ""
        }
    },
    {
        "id": 159954,
        "name": "Am Allermoor",
        "place": "Bispingen",
        "plz": "29646",
        "zip": {
            "id": 682,
            "zip": "29646",
            "place": "Bispingen",
            "district": ""
        }
    },
]
```

Next:
House Numbers
`https://ahkwebapi.heidekreis.de/api/QMasterData/QHouseNr?StreetID=159954`
Retruns:
```
[
    {
        "houseNr": 2,
        "houseNrAdd": "",
        "idObject": 40592
    },
    {
        "houseNr": 4,
        "houseNrAdd": "",
        "idObject": 40593
    }
]
```

**Comment by 5ila5** [comment]
Added in #2296
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
