### ISSUE TITLE
[Source Request]: City of Mainhausen (Hesse)

### ISSUE THREAD

**Issue by bloodscript** [mampfes/hacs_waste_collection_schedule#1966]
### Municipality / Region

Mainhausen / Hesse

### Collection Calendar Webpage

https://www.mainhausen.de/download-muellkalender

### Example Address

The streets each have their own id as in this link (https://www.mainhausen.de/municipal/downloads/trash/15) the id 15 for Breslauer Straße. So for each of the 144 streets and the one "collection" of addresses not associated with a street the ids would have to be know. In the link above (collection calender webpage) you could select your streetname and receive the correct link.

### Collection Data Format

As ICS/ICAL file

### Additional Information

The files look quite similar to already supported ones from other cities and the mymuell app, but a few attributes differ which may be the reason why it doesnt work for me out of the box. The ICAL file also contains a field "CLASS: CONFIDENTIAL" for every single entry which I find suspicous because other ICAL files dont have this field at all or it has the value "PUBLIC"

**Comment by 5ila5** [comment]
ICS documentation added in #1967
