### ISSUE TITLE
[Source Request]: Kreisabfallwirtschaftsbetrieb Heidenheim

### ISSUE THREAD

**Issue by Schebberle** [mampfes/hacs_waste_collection_schedule#1974]
### Municipality / Region

Kreisabfallwirtschaftsbetrieb Heidenheim

### Collection Calendar Webpage

https://www.abfall-hdh.de/internet/inhalt/inhalt.php?seite=98

### Example Address

Heidenheim, Felsenstraße 36

### Collection Data Format

As ICS/ICAL file, As html on a webpage, As PDF Download

### Additional Information

after you selected the city, and strett adress, you see in the dates on the webpage as HTML. also there is an option to download an .ics file for which you can select what types of waste you want to see. an pdf calendar download is also available

**Comment by 5ila5** [comment]
Kreisabfallwirtschaftsbetrieb Heidenheim is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #1976
Open  you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfall_hdh_de.md)
