### ISSUE TITLE
[Source Request]: Glenelg, South Australia (PDF only)

### ISSUE THREAD

**Issue by flipvkg** [mampfes/hacs_waste_collection_schedule#1975]
### Municipality / Region

Glenelg, South Australia

### Collection Calendar Webpage

https://www.holdfast.sa.gov.au/assets/general-downloads/Services/GIS5614May23HoldfastKerbsideCalendar_WEB.pdf

### Example Address

10 Byron st Glenelg, SA 5045

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
They only provide a PDF we do not parse PDFs. Unless you find a way to get the dates in a parsable format you need to use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

**Comment by flipvkg** [comment]
No worries will give the static a whirl, failing that I will try and use another nearby council, that is supported & uses the same collection schedule
