### ISSUE TITLE
[Bug]: Zollernalbkreis is not working anymore - the url is no more existing

### ISSUE THREAD

**Issue by marcsauter75** [mampfes/hacs_waste_collection_schedule#1980]
### I Have A Problem With:

The integration in general

### What's Your Problem

The page in the documentation is not more existing so zollernalbkreis for Germany is not working anymore

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_zollernalbkreis_de.md

Please can you check this and give me a short update how to proceed - is this working with ics now or connect to their new app ? 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I removed Zollernalbkreis as dedicated source as it seems like they removed the old service completely.

They moved to the new apfall_io API it is supported by the ICS source Documentation for abfall_io_ics can be found here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfall_io_ics.md

The app is already supported: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md

**Comment by marcsauter75** [comment]
Yes I solved it over ICS , that is working very well !
Thanks ...
