### ISSUE TITLE
Stevenage UK has changed service

### ISSUE THREAD

**Issue by jamesmyatt** [mampfes/hacs_waste_collection_schedule#1997]
### I Have A Problem With:

A specific source

### What's Your Problem

API for Stevenage UK has moved to a different service: https://myaccount.stevenage.gov.uk/en/service/my_bin_collection_schedule

This is issue is more of a notification. If I have time, I'll see if I can fix it.

### Source (if relevant)

stevenage_gov_uk

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by jamesmyatt** [comment]
@mehstg , @simonk1969: You might also be interested.

This is issue is more of a notification. If I have time, I'll see if I can fix it.

**Comment by mehstg** [comment]
I've had a cursory look at this and it looks to be totally different to the previous API. Looks like an XML blob inside a JSON wrapper, eugh.

Will try and get something together when I get a chance. The service doesn't seem particularly reliable, or it has a pretty aggressive rate limit as it's stopped working for me for the moment.

**Comment by chinswain** [comment]
I'm a fellow Stevenage user, let me know if you need anything tested.

**Comment by jamesmyatt** [comment]
Specifically, the new service uses Granicus (https://granicus.com/). I wonder if there are any other schedules using this.

**Comment by jamesmyatt** [comment]
Granicus is also mentioned here: https://github.com/mampfes/hacs_waste_collection_schedule/pull/504#issuecomment-1364994675

**Comment by simonk1969** [comment]
Another Stevenage user, let me know if you need anything testing :-)
