### ISSUE TITLE
Setup Stadtreinigung Hamburg with running the py script

### ISSUE THREAD

**Issue by Liese2007** [mampfes/hacs_waste_collection_schedule#2]
Hi,
how do I run the py script?

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/package/wizard/stadtreinigung_hamburg.py

On the HA terminal I cannot run the script.
Then I installed python on my windows pc and started the command line.
I copied the script code to notepad++ and saved it on my windows pc.
I called the py script, but the modules are missing....

Can you please provide a short hint on how to start this?

Regards from Hamburg
Joerg

**Comment by mampfes** [comment]
The wizards requires that the `inquirer` package is installed:

`pip3 install inquirer`

Unfortunately, `inquirer` is not available on Windows!

**Comment by Liese2007** [comment]
OK, I received some help via Discord.
I have done that, but it returns:

> C:\Users\xxx>python stadtreinigung.py
> An error was found, but returning just with the version: No module named '_curses'
> Traceback (most recent call last):
>   File "stadtreinigung.py", line 112, in <module>
>     main()
>   File "stadtreinigung.py", line 59, in main
>     inquirer.Text("strasse", message="Enter search string for street"),
> AttributeError: module 'inquirer' has no attribute 'Text'

I just copied the python code to notepad++ and saved as stadtreinigung.py .
Are there other files to be copied in the same folder?

Greetz

**Comment by Liese2007** [comment]
May I ask why you closed this issue?
Can I raise a question somewhere else, in case this subject does not qualify for an issue topic?

Regards
Jörg

**Comment by mampfes** [comment]
Hi, as I already said: `inquirer` is not supported on Windows, therefore you can't use the wizard on a Windows box. That's not an issue of the waste_collection_schedule, therefore I closed it. 

The good news for you is that the inquirer package is only required for the wizard. This means that once you have the arguments for the Home Assistant integration (= Waste Collection Schedule) it should also work on Windows.

If you want to, you can sent me your address (or an address next to you) and I will send you the arguments back. Please use a private message for this, e.g. in the Home Assistant community (as I know github doesn't support private messages).

Feel free to ask any question, either here on github or in the HA community.

Regards
Steffen
