### ISSUE TITLE
A.R.T. Trier is Abfall.io but python script doesn't work to find

### ISSUE THREAD

**Issue by meistermolli** [mampfes/hacs_waste_collection_schedule#200]
Hi,

searching for Kalender of Basberg but python script run error line 27.
And doesn't find it in Browser Options.

Art Trier uses Abfall.io / Abfall Plus

waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: KEY
        f_id_kommune: KOMMUNE
        f_id_bezirk: BEZIRK
        f_id_strasse: strasse
        f_id_strasse_hnr: HNR
        f_abfallarten:
          - 1
          - 2
          - 3

https://www.art-trier.de/eo/cms?_sprache=de&_bereich=artikel&_aktion=detail&idartikel=413307

Key:? for Basberg
f_id_kommune: ? for Basberg
f_id_strasse: ? all streets or Basberg
f_abfallarten: Restmüll / Altpapier / Gelber Sack

is someone able to get the things for me?

Thanks a lot 

this is the generated ics calendar:
https://www.art-trier.de/ics-feed/54578_basberg_1-1800.ics

**Comment by mampfes** [comment]
From the ART homepage, I do not see an indication that they use abfall.io. Why do you think they use abfall.io?

You could try the [ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source with the provided link. Looks like a static link, so should work.

**Comment by meistermolli** [comment]
Hi, @mampfes  its listet at the Abfall.io site and there is also listet the app ART.

Bundesland: Rheinland Pfalz
Landkreis: Vulkaneifel


![Bildschirmfoto 2022-04-05 um 08 37 19](https://user-images.githubusercontent.com/55836556/161693755-5364066d-ec0f-4cf0-a6ae-330c27ffe348.png)

**Comment by mampfes** [comment]
Ah, ok. The problem is that the required arguments for the source configuration can be only extracted from a website - and not from a smart phone app.

So if the service provider is using the abfall.io app, but uses a different API for the website, we don't have access to the required information. Maybe someone with more app experience could help here.

**Comment by mampfes** [comment]
Did you try the ICS workaround?

**Comment by meistermolli** [comment]
Hi, yes the workaround does its job.
Hope that it work the next years. :-D

**Comment by meistermolli** [comment]
i will update https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md
the next days with my configuration.
