### ISSUE TITLE
[Bug]: Manchester UK changed their setup? No longer working

### ISSUE THREAD

**Issue by majoracehole** [mampfes/hacs_waste_collection_schedule#2003]
### I Have A Problem With:

A specific source

### What's Your Problem

Its looks like since this week Manchester is no longer working - I think they have changed their system. I first assumed it was my system but now not so sure. Trying to start from scratch I do think their webpage looks a little different from what I recall and unless I am being daft I cannot find my UPRN code anymore. Unfortunately to dig any deeper is beyond me!

### Source (if relevant)

manchester_uk

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Analysis of the web flow:

Required attribute: uprn (sample: 77003491)
All requests after 1. need the Authorization-token. A new token is in the response headers and required for for follow-up calls.

1. HTTP-Get to get an auth-token - Request: `https://manchester.form.uk.empro.verintcloudservices.com/api/citizen?archived=Y&preview=false&locale=en`

2. Read Response-Header: `Authorization`

3. Post-Request: `https://manchester.form.uk.empro.verintcloudservices.com/api/custom?action=bin_checker-get_bin_col_info&actionedby=_KDF_custom&loadform=true&access=citizen&locale=en`
    Request-Header: 
   ```
      Accept: application/json, text/javascript, */*; q=0.01
      Content-type: application/json
      Referer: https://manchester.portal.uk.empro.verintcloudservices.com/
      Authorization: "Token from step 2"
   ```
    Request-Body:
   ```
   {"name":"sr_bin_coll_day_checker","data":{"uprn":"77003491","nextCollectionFromDate":"2024-04-21","nextCollectionToDate":"2025-04-20"},"email":"","caseid":"","xref":"","xref1":"","xref2":""}
   ```

4. Result: JSON
```
{
    "data": {
        "uprn": "77003491",
        "nextCollectionFromDate": "2024-04-21",
        "nextCollectionToDate": "2025-04-20",
        "ahtm_dates_black_bin": "24/04/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t08/05/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t",
        "ahtm_dates_brown_commingled_bin": "01/05/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t15/05/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t",
        "ahtm_dates_blue_pulpable_bin": "24/04/2024 00:00:00\n    \t\t\t\t\t;\n    \t\t\t\t08/05/2024 00:00:00\n    \t\t\t\t\t;\n    \t\t\t\t",
        "ahtm_dates_green_organic_bin": "24/04/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t24/04/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t08/05/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t08/05/2024 00:00:00\n\t\t\t\t\t\t;\n\t\t\t\t\t",
        "txt_domestic_col_schedule_code": "WedFort2",
        "txt_number_col_services": "4",
        "txt_col_service_type": "individual",
        "txt_col_service_calendar_url": "/site/custom_scripts/bin_dates_gazops/calendars_2017/WedFort2_MCC_bin_dates_calendar_6.pdf"
    },
    "action": "bin_checker-get_bin_col_info",
    "actionedby": "_KDF_custom",
    "loadform": true,
    "links": [
        {
            "rel": "self",
            "href": "https://manchester.form.uk.empro.verintcloudservices.com/api/custom?access=citizen&action=bin_checker-get_bin_col_info&actionedby=_KDF_custom&loadform=true&locale=en"
        }
    ]
}
```

**Comment by 5ila5** [comment]
fixed in #2295

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by majoracehole** [comment]
Just given it a test and it looks great - amazing! Thank you so much

The only thing I would add - I used my old UPRN and it was fine. If I were starting from scratch I would have no idea how to obtain it, the old instructions don't seem apply to the new site setup and the explanation above is beyond me, so I assume might be to other users as well 😀

**Comment by 5ila5** [comment]
udpated the UPRN section in #2305
