### ISSUE TITLE
[Source Request]: Scarbrough/Whitby Collection

### ISSUE THREAD

**Issue by stevemcan** [mampfes/hacs_waste_collection_schedule#2007]
### Municipality / Region

Scarborough, United Kingdom

### Collection Calendar Webpage

https://www.northyorks.gov.uk/bin-calendar/Scarborough/results/100050497178

### Example Address

Coach Road
Sleights
YO22 5AA
UK

### Collection Data Format

As html on a webpage

**Comment by ReneNulschDE** [comment]
PR created...

**Comment by 5ila5** [comment]
Added in #2009 (thanks @ReneNulschDE)

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
