### ISSUE TITLE
[Source Request]: UK - Eastleigh

### ISSUE THREAD

**Issue by cherrybomb37** [mampfes/hacs_waste_collection_schedule#2010]
### Municipality / Region

Eastleigh, England, UK

### Collection Calendar Webpage

https://www.eastleigh.gov.uk/waste-bins-and-recycling/collection-dates

### Example Address

https://www.eastleigh.gov.uk/waste-bins-and-recycling/collection-dates/your-waste-bin-and-recycling-collections?uprn=100060319000

### Collection Data Format

As html on a webpage, As PDF Download

### Additional Information

There are 5 different dates available for differing collections:
Household Waste Bin
Recycling Bin
Food Waste Bin
Glass Box and Batteries
Garden Waste Bin

**Comment by 5ila5** [comment]
Added by #2012

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
