### ISSUE TITLE
[Bug]: source awlneuss_de does not work anymore

### ISSUE THREAD

**Issue by Spacerat76** [mampfes/hacs_waste_collection_schedule#2014]
### I Have A Problem With:

A specific source

### What's Your Problem

I configured the source awlneuss_de and it worked. But since several days it stopped working.
The calendar for AWL Neuss is empty.

I am using version 1.47.0

### Source (if relevant)

awlneuss_de

### Logs

```Shell
The only entry for waste_collection_schedule i found in homeassistant.log was:
2024-04-24 07:16:04.332 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration waste_collection_schedule which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

### Relevant Configuration

```YAML
> waste_collection_schedule:
>   sources:
>     - name: awlneuss_de
>       args:
>         street_code: "5200"
>         building_number: 1
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Thanks for reporting. This looks like a bug as only the first 3 months of a year are loaded. I'll prepare a fix.

**Comment by coarsy** [comment]
I've the same problem from today with this configuration:

waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.zakb
        city: Heppenheim
        strasse: Schubertweg
        hnr: 2

**Comment by ReneNulschDE** [comment]
@coarsy : your problem is a different one and not related to awlneuss. Please take a look here: #1989 . Scroll to the end, the thread has a lot of messages...

**Comment by coarsy** [comment]
Thank you very much for the fix, it works again!
