### ISSUE TITLE
[Feature]: Config Flow (UI) setup

### ISSUE THREAD

**Issue by dan-r** [mampfes/hacs_waste_collection_schedule#2016]
### I propose a feature for:

The integration in general

### Describe your wanted feature

The preferred method of setting up integrations seems to now be using the config flow (add integration... menu) rather than yaml. As far as I know this can exist alongside yaml setup, and would allow either setup route.

If there is interest in this, I'm happy to work on it.
Perhaps a basic configuration through config flow and then for more advanced setup, keep it to yaml?

**Comment by 5ila5** [comment]
There was some discussion here: #565 

@mampfes worked on a basic setup in the [config_flow branch ](https://github.com/mampfes/hacs_waste_collection_schedule/tree/config_flow) but there wasn't any movement lately (did not look into how far this is yet)



also see: #828

**Comment by mampfes** [comment]
Hi, I started to work on this, but I don't have enough time to continue.

Current state is here: https://github.com/mampfes/hacs_waste_collection_schedule/tree/config_flow

**Comment by dan-r** [comment]
Thank you both for the links. I've been working on this in [my fork](https://github.com/dan-r/hacs_waste_collection_schedule), based on mampfes's branch. Currently I've got a basic config flow, ability to change options (but no customise stuff), and am working on ICS/generic sources now.

I hope to have it done in the next week or two, and will open a PR when I've had a chance to finish it all :)

**Comment by oerix** [comment]
> Thank you both for the links. I've been working on this in [my fork](https://github.com/dan-r/hacs_waste_collection_schedule), based on mampfes's branch. Currently I've got a basic config flow, ability to change options (but no customise stuff), and am working on ICS/generic sources now.
> 
> I hope to have it done in the next week or two, and will open a PR when I've had a chance to finish it all (especially testing and linting) :)

Thank you for your contribution, hopefully it will be merged soon once completed.
