### ISSUE TITLE
[Bug]: Bad sepan_remondis_pl API link

### ISSUE THREAD

**Issue by ShizeRPLx** [mampfes/hacs_waste_collection_schedule#2022]
### I Have A Problem With:

A specific source

### What's Your Problem

After 2023, sepan_remondis_pl changed the website address by adding 2024
2023: https://sepan.remondis.pl/harmonogram
2024: https://sepan.remondis.pl/harmonogram2024
integration doesn't get the correct terms

just update api url from  API_URL = "https://sepan.remondis.pl/harmonogram" to API_URL = "https://sepan.remondis.pl/harmonogram2024"

### Source (if relevant)

sepan_remondis_pl

### Relevant Configuration

```YAML
API_URL = "https://sepan.remondis.pl/harmonogram2024"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed by #2030

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
