### ISSUE TITLE
[Bug]: Integration uses deprecated functions since 2024.5 + Detected blocking call to import_module inside the event loop

### ISSUE THREAD

**Issue by TheZoker** [mampfes/hacs_waste_collection_schedule#2023]
### I Have A Problem With:

The integration in general

### What's Your Problem

Since version 2024.5, HA deprecated some functions. I listed the relevant log errors below

### Logs

```Shell
Detected that custom integration 'waste_collection_schedule' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/waste_collection_schedule/__init__.py, line 120: await hass.helpers.discovery.async_load_platform(, please report it to the author of the 'waste_collection_schedule' custom integration


Detected blocking call to import_module inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module( (offender: /config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module(), please report it to the author of the 'waste_collection_schedule' custom integration
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
The second one is not that easy. The workday and smartthings integration have the same problem and it was solved there. I tried to adopt that to this component but without success so far. Still working on it but with limited time - traveling through Europe for the next 5 weeks.

**Comment by larena1** [comment]
> The second one is not that easy. The workday and smartthings integration have the same problem and it was solved there. I tried to adopt that to this component but without success so far. Still working on it but with limited time - traveling through Europe for the next 5 weeks.

No idea what you're trying but fixing that only takes a few seconds as in https://github.com/mampfes/hacs_waste_collection_schedule/pull/2041

**Comment by ArMaTeC** [comment]
I have the same issue 
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 15:59:19 (1 occurrences)
Last logged: 15:59:19

Detected blocking call to import_module inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module( (offender: /config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module(), please report it to the author of the 'waste_collection_schedule' custom integration

**Comment by Morpheus2018** [comment]
Same here!
Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

**Comment by bcutter** [comment]
Is this an issue for older HA (Core) versions? Or are the implemented changes to remove the deprecation method warnings "just" a future investment without downsides to HA versions prior to 2024.5?

**Comment by 5ila5** [comment]
@bcutter I don't know exactly when these two methods were introduced, but there are pretty old references to them, so if you do not run a multiple year-old version you should be fine.
