### ISSUE TITLE
[Source Request]: Vale Of Glamorgan Council, Wales, UK 

### ISSUE THREAD

**Issue by thomasmoreton** [mampfes/hacs_waste_collection_schedule#2025]
### Municipality / Region

Vale of Glamorgan, Wales, United Kingdom

### Collection Calendar Webpage

https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/Recycling-and-Waste.aspx

### Example Address

Use example postcode - CF62 7JP. 
Select any address from the drop down after entering the postcode.

### Collection Data Format

As html on a webpage, Something different (add to additional information)

### Additional Information

Shows dates on web page.
Not sure about Garden Waste collection.

Can sign up for email reminders. Not sure if this helps.

**Comment by thomasmoreton** [comment]
Garden Waste is on a different URL - 
https://www.valeofglamorgan.gov.uk/en/living/Recycling-and-Waste/Garden-Waste.aspx

**Comment by 5ila5** [comment]
I only get response `AddressInfoCallback({"Results":{"waste":{"Info":"<p>No results found nearby</p>"}}});` need to check again later. So I currently cannot check how easy it is to integrate

**Comment by 5ila5** [comment]
Added in #2203

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by thomasmoreton** [comment]
I will attempt to test and let you know if there's any issues! Thanks for adding this!

**Comment by thomasmoreton** [comment]
Confirmed all working. 
Thanks again for making this happen!
