### ISSUE TITLE
[Source Request]: Sutton Council, London

### ISSUE THREAD

**Issue by 73ttv627re77** [mampfes/hacs_waste_collection_schedule#2026]
### Municipality / Region

Sutton, London

### Collection Calendar Webpage

https://waste-services.sutton.gov.uk/waste

### Example Address

8 thread street, sm67fb

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
added by #2031

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
