### ISSUE TITLE
[Source Request]: West Northants

### ISSUE THREAD

**Issue by thecork3004** [mampfes/hacs_waste_collection_schedule#2036]
### Municipality / Region

West Nothants, UK

### Collection Calendar Webpage

https://www.westnorthants.gov.uk/bin-collection-services/bin-collection-day

### Example Address

NN7 4PZ, any address will provide data

### Collection Data Format

As html on a webpage

### Additional Information

Site is identical to the recently added north northants source

**Comment by 5ila5** [comment]
Added in #2037

This will be part of release 1.48.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
