### ISSUE TITLE
[Bug]: wyreforestdc_gov_uk stopped working

### ISSUE THREAD

**Issue by johntheth1rd** [mampfes/hacs_waste_collection_schedule#2047]
### I Have A Problem With:

A specific source

### What's Your Problem

wyreforestdc_gov_uk always returns unknown.
Calendar is showing as off, and Next Collection showing as Unknown.

Had a look through the integration source, and it appears that the API urls are returning 500 error
   "address_search": "https://forms.wyreforestdc.gov.uk/bindays/",
    "collection": "https://forms.wyreforestdc.gov.uk/bindays/Home/Details",
it looks like the address search page might now be 
https://www.wyreforest.gov.uk/wfdcbins.asp
and the request url is 
https://www.wyreforest.gov.uk/querybin.asp?txtStreetName=street+name

### Source (if relevant)

wyreforestdc_gov_uk

### Relevant Configuration

```YAML
1.47.0
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I rewrote the source to use parse the HTML of these pages:

- Garden: https://forms.wyreforestdc.gov.uk/gardenwastechecker
- general Waste: https://forms.wyreforestdc.gov.uk/querybin.asp

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
