### ISSUE TITLE
[Bug]: Ku-ring-gai Council stopped working

### ISSUE THREAD

**Issue by AnthonyBe** [mampfes/hacs_waste_collection_schedule#2050]
### I Have A Problem With:

A specific source

### What's Your Problem

Ku-ring-gai Council has stopped working (sorry, not sure exactly when it stopped, but likely in the last week).
https://www.krg.nsw.gov.au/Community/Waste-and-recycling/Bins-and-collection-days

### Source (if relevant)

Ku-ring-gai Council (NSW, Australia)

### Logs

```Shell
2024-05-04 20:33:02.213 ERROR (SyncWorker_4) [waste_collection_schedule.source_shell] fetch failed for source Ku-ring-gai Council:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/kuringgai_nsw_gov_au.py", line 112, in fetch
    waste_type = item.find('h3').text
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed by #2193 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by AnthonyBe** [comment]
Thanks @5ila5 !
Thanks @werdnum !

**Comment by jonwaland** [comment]
Can I ask when next release is scheduled? 
(sorry for resurrecting this)

**Comment by AnthonyBe** [comment]
I had been wondering the same :)
Was working on the rough assumption of release every ~4 weeks based on past release schedule so hoping this is due soon!

**Comment by 5ila5** [comment]
Probably after #2197 gets fixed, as there seem to be a lot of people relying on this

**Comment by AnthonyBe** [comment]
I saw v2.0.0 was just released but this issue wasn't listed as being fixed? 
I updated and tested anyway and am now getting a slightly different error. 

```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
integration: Waste Collection Schedule (documentation)
First occurred: 00:42:47 (1 occurrences)
Last logged: 00:42:47

fetch failed for source Ku-ring-gai Council: 
Traceback (most recent call last): 
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch 
    entries = self._source.fetch()
                     ^^^^^^^^^^^^^^^^^^^^ 
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/kuringgai_nsw_gov_au.py", line 101, in fetch 
    re.escape(self.post_code), 
    ^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/usr/local/lib/python3.12/re/__init__.py", line 262, in escape 
    pattern = str(pattern, 'latin1') 
    ^^^^^^^^^^^^^^^^^^^^^^ 
TypeError: decoding to str: need a bytes-like object, int found
```

**Comment by 5ila5** [comment]
You need to

**Comment by AnthonyBe** [comment]
Ah! Copy that. Working perfectly now having made above changes!
