### ISSUE TITLE
[Bug]: Highland Council source broken

### ISSUE THREAD

**Issue by Supermillhouse** [mampfes/hacs_waste_collection_schedule#2053]
### I Have A Problem With:

A specific source

### What's Your Problem

The government website has been updated for the collection dates and this integration no longer works for my service.
I think there were issues before where the record id would change after a few weeks for a particular house address, I'm finally getting around to reporting this now new problem as it has completely changed its design.

was previously
https://www.highland.gov.uk/bindays
this now redirects to
https://highland-self.achieveservice.com/en/service/Check_your_household_bin_collection_days

Looks like the below URL returns the info you will need, not too sure how it is structured, I don't know if the id changes week to week when the calendar changes, I can test again in a few weeks to see if my address id changes.

https://highland-self.achieveservice.com/apibroker/runLookup?id=

### Source (if relevant)

https://highland-self.achieveservice.com/en/service/Check_your_household_bin_collection_days

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Johnellegon** [comment]
I'm having the same issue following the new bins that have been issued in my area, URL for area has changed

**Comment by Supermillhouse** [comment]
Been a bit more than a few weeks but i can confirm the id has stayed the same for my location, hopefully you can identify the other magic that needs to happen in the form POST.

**Comment by 5ila5** [comment]
I fixed the Highland Council source in #2179

But you need to change your configuration as you now need your UPRN instead of the record ID

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
