### ISSUE TITLE
Buckinghamshire Waste Not working

### ISSUE THREAD

**Issue by abbottcam** [mampfes/hacs_waste_collection_schedule#2060]
### I Have A Problem With:

The integration in general

### What's Your Problem

Hello, the Buckinghamshire waste sensors don't seem to be working anymore...

### Source (if relevant)

chiltern_gov_uk

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
integration: waste_collection_schedule (documentation)
First occurred: 6 May 2024 at 22:30:49 (2 occurrences)
Last logged: 01:23:10

fetch failed for source Buckinghamshire Waste Collection - Former Chiltern, South Bucks or Wycombe areas: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/chiltern_gov_uk.py", line 44, in fetch form_url = form["action"] ~~~~^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 3dogzzz** [comment]
I have this same error too with the same source provider.

**Comment by 3dogzzz** [comment]
Seems to be working again without any update of the integration

**Comment by 5ila5** [comment]
My test cases work. Maybe some temporary outage. I will close this for now
