### ISSUE TITLE
[Bug]: Lewisham Source Not Working

### ISSUE THREAD

**Issue by Blucose** [mampfes/hacs_waste_collection_schedule#2077]
### I Have A Problem With:

A specific source

### What's Your Problem

I'm not sure how to troubleshoot this any better (limited technical knowledge), but within lewisham_gov_uk.py the websites referenced appear to not be working.
```
API_URLS = {
    "address_search": "https://lewisham.gov.uk/api/AddressFinder",
    "collection": "https://lewisham.gov.uk/api/roundsinformation",
```
are both no longer functioning, and lead to a 404.

### Source (if relevant)

lewisham_gov_uk

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
integration: waste_collection_schedule (documentation)
First occurred: 8 May 2024 at 23:41:35 (6 occurrences)
Last logged: 01:07:29

fetch failed for source London Borough of Lewisham: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/lewisham_gov_uk.py", line 84, in fetch r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://lewisham.gov.uk/api/roundsinformation?item=%7B79b58e9a-0997-4f18-bb97-637fac570dd1%7D&uprn=REDACTED
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed in #2171 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
