### ISSUE TITLE
[Bug]: Gateshead Council not working even after update

### ISSUE THREAD

**Issue by michaelthompson1991** [mampfes/hacs_waste_collection_schedule#2080]
### I Have A Problem With:

The integration in general

### What's Your Problem

Hi, apologies I didn’t report this sooner, I’ve been on holiday. Im using the Gateshead Council in the UK https://github.com/mampfes/hacs_waste_collection_schedule/blob/1.48.0/doc/source/gateshead_gov_uk.md And it didn’t start working again after the recent update, so I removed it from HACS and deleted my yaml and started again. It still wont work, it appears Gateshead Council in my local calendar but it has no entries. Ive set the yaml up exactly how it says in the link I provided and I had it working previous to the problems. Not sure what I can do now?

Thanks!

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
uprns `100000077407`, `100000058404` and `100000033887` do return entries in my tests. Maybe try one of them to know if your UPRN or something else is the problem. If you still get no entries, take a look in your logs (settings -> system -> logs) and post them here if there are any for this integration.

**Comment by michaelthompson1991** [comment]
Well all 3 of those worked, so I tried mine again and it worked 🤷‍♂️ thank you for all your help and keep up the great work!
