### ISSUE TITLE
[Feature]: All widths of the cards are the same width as the max card width

### ISSUE THREAD

**Issue by philippk80** [mampfes/hacs_waste_collection_schedule#2092]
### I propose a feature for:

The integration in general

### Describe your wanted feature

Hello,
thanks for the great effort on this card so far. 
Would it be possible to implement this as option for the card mode?
Now its like that:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/6973619/4414529a-7b8e-4bf7-aa35-ec8efdc0ebe0)

I would love to have following:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/6973619/13b309a2-b97a-4fbb-97e2-bcf8c8d0fb06)

...or am I missing a way to do that? I couldn't make that work with card-mod.

Thanks. :)

**Comment by 5ila5** [comment]
I'm not quite sure what you mean exactly. This source does not provide any card, but just the sensor you configured. You then can add this sensor to some card that support sensors. What card/configuration are you using?

**Comment by philippk80** [comment]
I'm so sorry. You are right. I'm using your work as source for the card. 
For everyone interested:
You can use the great work of this guys here with these card:
https://github.com/idaho/hassio-trash-card
