### ISSUE TITLE
[Bug]: Maidstone stopped working

### ISSUE THREAD

**Issue by FarleighRed** [mampfes/hacs_waste_collection_schedule#2106]
### I Have A Problem With:

A specific source

### What's Your Problem

Stopped working around 24th May

### Source (if relevant)

Maidstone_gov_uk

### Logs

```Shell
Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 27 May 2024 at 19:15:37 (1 occurrences)
Last logged: 27 May 2024 at 19:15:37

Detected blocking call to import_module inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module( (offender: /config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module(), please report it to the author of the 'waste_collection_schedule' custom integration
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Snux** [comment]
Just to confirm I have the same issue when trying to pull the data for Maidstone collections.

**Comment by 5ila5** [comment]
They changed their API. I fixed this issue in #2119 you log is not the reason this failed.

You may need to adjust your sensor config as the names of the collection events changed.

This will be part of release 1.49.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by FarleighRed** [comment]
This seems to have stopped working again after todays update

**Comment by 5ila5** [comment]
What do you mean with "todays update"? Our test cases still work fine
