### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute '_entries'

### ISSUE THREAD

**Issue by kalhimeo** [mampfes/hacs_waste_collection_schedule#2107]
### I Have A Problem With:

The integration in general

### What's Your Problem

Since a recent HA update my waste sensor does not work anymore. HA shows the error "AttributeError: 'NoneType' object has no attribute '_entries'" in logs and the waste sensor has the "unavailable" state. Before that I was using this integration for months without problem and I did not change anything to my waste schedule configuration.

Note that I also see this warning, already reported by others, in my logs. I don't know if it's linked to my other error : 

`Detected blocking call to import_module inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module( (offender: /config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py, line 188: source_module = importlib.import_module(), please report it to the author of the 'waste_collection_schedule' custom integration`

### Source (if relevant)

static

### Logs

```Shell
Error adding entity sensor.poubelles for domain sensor with platform waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1358, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 147, in async_added_to_hass
    self._update_sensor()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 206, in _update_sensor
    upcoming1 = self._aggregator.get_upcoming_group_by_day(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 68, in get_upcoming_group_by_day
    self._entries,
    ^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 17, in _entries
    return [e for s in self._shells for e in s._entries]
                                             ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_entries'


AND


Exception in _update_sensor when dispatching 'wcs_update_sensors_signal': () Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/sensor.py", line 206, in _update_sensor upcoming1 = self._aggregator.get_upcoming_group_by_day( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 68, in get_upcoming_group_by_day self._entries, ^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 17, in _entries return [e for s in self._shells for e in s._entries] ^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute '_entries'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  day_switch_time: '12:00'
  sources:
    - name: static
      args:
        type: "Normale et Bleue"
        frequency: WEEKLY
        interval: 2
        start: '2024-01-08'
        until: '2099-12-31'
        weekdays: WE
        dates:
          - '2024-05-04'
          - '2024-12-28'
        excludes:
          - '2024-05-01'
          - '2024-12-25'
    - name: static
      args:
        type: "Carton"
        frequency: WEEKLY
        interval: 4
        start: '2024-01-15'
        until: '2099-12-31'
        weekdays: WE
    - name: static
      args:
        type: "Sapin"
        frequency: MONTHLY
        interval: 12
        start: '2024-01-01'
        until: '2099-12-31'
        weekdays: { MO: 3 }

Note: I tried also with only one basic source (the second one in this list called "Carton") and had the same errors.
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by kalhimeo** [comment]
Thanks for your reply. I just tried to uninstall the integration from HACS, then restart, then re-install it, restart, but same error in logs. I also tried to delete the sensor created by the integration and restart HA, but still the same error in logs :/

**Comment by 5ila5** [comment]
Could you please post your sensor configuration as I cannot reproduce your issue

**Comment by kalhimeo** [comment]
Sure, here it is :

```
- platform: waste_collection_schedule
  source_index:
    - 0
    - 1
    - 2
    - 3
  name: Poubelles
  details_format: appointment_types
  count: 4
  leadtime: 28
  value_template: '{{ value.types | join }} - {% if value.daysTo == 0 or ( value.daysTo == 1 and now().hour > 20 ) %}maintenant{% elif value.daysTo == 1 %}ce soir{% elif value.daysTo == 2 %}demain soir{% else %}dans {{value.daysTo}} jours{% endif %}'
  date_template: '{% if value.daysTo == 0  or ( value.daysTo == 1 and now().hour > 20 ) %}Maintenant{% elif value.daysTo == 1 %}Ce soir{% elif value.daysTo == 2 %}Demain soir{% else %}dans {{value.daysTo}} jours{% endif %}'
  add_days_to: true
```

**Comment by kalhimeo** [comment]
ok I am stupid, sorry for wasting your time... I deleted one of my sources recently and forgot about the sensor confiuration, the fact that I had one too many index caused the error. Thanks a lot for pointing me to the right direction with your question and again excuse me for the disturbances.
