### ISSUE TITLE
[Bug]: Australia > Hume City Council / hume.vic.gov.au > Food and garden (Green Waste)

### ISSUE THREAD

**Issue by weppa** [mampfes/hacs_waste_collection_schedule#2108]
### I Have A Problem With:

A specific source

### What's Your Problem

Green Waste attribute does not match Service Provider; however, Recycling and Rubbish attributes do match.

**[sensor.waste_collection]**
![sensor waste_collection](https://github.com/mampfes/hacs_waste_collection_schedule/assets/58678210/0f14e0bb-45ef-403f-81f1-0df66626c001)

**Hume City Council / hume.vic.gov.au**
![Hume City Council](https://github.com/mampfes/hacs_waste_collection_schedule/assets/58678210/9b83f9ff-5a38-4d0f-9222-c0842bef643c)

### Source (if relevant)

hume_vic_gov_au

### Logs

```Shell
no relevant logs
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The source uses the [maps service](https://maps.hume.vic.gov.au/IntraMaps98/ApplicationEngine/frontend/mapbuilder/default.htm?configId=00000000-0000-0000-0000-000000000000&liteConfigId=a0ca08ad-7531-4cf3-b653-5d2533d007f0&title=SHVtZSBDaXR5IENvdW5jaWwgTmVhck1l), is your green waste reported correctly on there?

**Comment by weppa** [comment]
@5ila5, thank you for bringing this to my attention. I checked the maps service as you suggested, and it appears that the green waste reported there is incorrect. I will reach out to them to address this discrepancy as soon as possible.
