### ISSUE TITLE
Create separate entity for days_to?

### ISSUE THREAD

**Issue by dergreg** [mampfes/hacs_waste_collection_schedule#2127]
### I propose a feature for:

Sensors

### Describe your wanted feature

Is it possible to create a separate numeric entity for the days_to attribute?

Working with attributes is less comfortable than directly using a separate entity, and attributes cannot be simply used in condition cards without creating additional template sensors.

Use case: I would like to show the bins in my frontend only when days_to < 2 using a condition card.

**Comment by 5ila5** [comment]
https://github.com/mampfes/hacs_waste_collection_schedule/issues/2114#issuecomment-2139505362

**Comment by dergreg** [comment]
Thanks, that's what I need.
