### ISSUE TITLE
[Source Request]: Dithmarschen, Germany

### ISSUE THREAD

**Issue by TheRealPrimetime** [mampfes/hacs_waste_collection_schedule#2144]
### Municipality / Region

Dithmarschen, Germany

### Collection Calendar Webpage

https://www.awd-online.de/

### Example Address

Hauptstraße 24A, 25785 Nordhastedt

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
awd-online.de is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2147 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/awd_online_de.md
)
