### ISSUE TITLE
[Source Request]: Hull City Council

### ISSUE THREAD

**Issue by toxicneo** [mampfes/hacs_waste_collection_schedule#2152]
### Municipality / Region

UK

### Collection Calendar Webpage

https://www.hull.gov.uk/household-collections

### Example Address

1 Tickton Grove, Hull, HU6 8NL

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
added in #2161

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
