### ISSUE TITLE
[Source Request]: Stroud District Council, UK

### ISSUE THREAD

**Issue by alxchong** [mampfes/hacs_waste_collection_schedule#2153]
### Municipality / Region

Stroud, UK

### Collection Calendar Webpage

https://www.stroud.gov.uk/my-house/

### Example Address

Market Square, Minchinhampton, Stroud GL6 9BW

### Collection Data Format

Something different (add to additional information)

### Additional Information

On webpage and also via pdf download

**Comment by 5ila5** [comment]
Do you see any waste collection dates? I only see this when selecting an address
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38183212/b6af68da-4eff-4c6a-907b-f01aa1170618)

**Comment by alxchong** [comment]
This is back up and working now @5ila5 thank you
