### ISSUE TITLE
[Source Request]: Add Wychavon Council

### ISSUE THREAD

**Issue by akrasia** [mampfes/hacs_waste_collection_schedule#2162]
### Municipality / Region

Wychavon, United Kingdom

### Collection Calendar Webpage

https://selfservice.wychavon.gov.uk/wdcroundlookup/wdc_search.jsp

### Example Address

1 Amphlett Way, Wychbold, Droitwich Spa, WR9 7PJ

### Collection Data Format

As html on a webpage

### Additional Information

Postcode is required first (eg. WR9 7PJ) as a free-text entry, followed by a drop-down selector when your select your house number. Thank you!

**Comment by 5ila5** [comment]
Added in #2165 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by akrasia** [comment]
Brilliant, thank you!
