### ISSUE TITLE
[Bug]: SSL Error port_enf_sa_gov_au.py

### ISSUE THREAD

**Issue by illuzn** [mampfes/hacs_waste_collection_schedule#2163]
### I Have A Problem With:

A specific source

### What's Your Problem

I receive the following error when using the `port_enf_sa_gov_au.py` source:
```
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
```

Seems similar to #1329 and #1125 where the full certificate chain is not being provided.

### Source (if relevant)

port_enf_sa_gov_au

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Disabled ssl Verification for the POST requests, it was already disabled for the GET requests (pretty much the same as #2146)

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
