### ISSUE TITLE
[Source Request]: Ards and North Down Borough Council

### ISSUE THREAD

**Issue by hiimjames** [mampfes/hacs_waste_collection_schedule#2164]
### Municipality / Region

Ards and North Down Borough Council, NI/UK

### Collection Calendar Webpage

https://collections-ardsandnorthdown.azurewebsites.net/calendar.html

### Example Address

BT20 4BT
BANGOR CASTLE 2B, CASTLE PARK AVENUE, CORPORATION BANGOR, BT20 4BT

### Collection Data Format

As html on a webpage, Something different (add to additional information)

### Additional Information

It appears to be powered by a SOAP service: 

https://collections-ardsandnorthdown.azurewebsites.net/WSCollExternal.asmx?WSDL

where the calendar can be obtained using _getRoundCalendarForUPRN_

An example UPRN, which may not be recognised as a UPRN in other systems, is 185833845. The XML response contains the schedule in HTML.

**Comment by 5ila5** [comment]
Added in #2166

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

Getting the data was not the problem (other than with a lot of other UK sources) but decoding this table was a bit harder. (The other functions shown on the API Documentation site seem to need a password)

**Comment by hiimjames** [comment]
Awesome, thank you
