### ISSUE TITLE
[Feature]: Adding Already supported Sources for Austria, Vorarlberg to the Documentation

### ISSUE THREAD

**Issue by benniStelzer** [mampfes/hacs_waste_collection_schedule#2168]
### I propose a feature for:

Sources

### Describe your wanted feature

Hi,

i have been trying to add my home city, but at first i couldn' find my city in the documentation. After fiddling around a little by myself i found out the whole province of Vorarlberg, Austria is already supported by your integration.

To add it to my homeassistant i just used the same procedure as for the "muellapp.com"-sources but with another link -> <https://abfallv.zerowaste.io/web-reminder?channel=calendar>

![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/97283718/4c37dea5-783a-4aa6-9857-c5b121fc239c)

In total it is about 87 additional cities in austria that is already covered by this integration. Would be glad if you can add this entries to your documentation so others can use it too.

Thanks for your work, i love it.

**Comment by 5ila5** [comment]
Do you think #2169 is sufficient?
