### ISSUE TITLE
[Source Request]: Kreis Steinburg, Germany

### ISSUE THREAD

**Issue by chlctt** [mampfes/hacs_waste_collection_schedule#2175]
### Municipality / Region

Kreis Steinburg, Germany

### Collection Calendar Webpage

https://www.steinburg.de/kreisverwaltung/informationen-der-fachaemter/amt-fuer-umweltschutz/abfallwirtschaft/abfuhrtermine/muellabfuhr.html

### Example Address

Große Tonkuhle 2, 25524 Itzehoe

### Collection Data Format

As ICS/ICAL file

### Additional Information

Type of waste are configurable and are part of the URL: "R02-B02-P04-D02-R04-R11-W0" is everything including Christmas Tree Pickup.

To get the correct Town and Street, Users need to fill out the form and get the values after "ort", "strasse" and "hausnummern" to configure the correct pickup place.

https://abfall.steinburg.de/api_v2/collection_dates/1/ort/46/strasse/1180/hausnummern/2/abfallarten/R02-B02-P04-D02-R04-R11-W0/kalender.ics

**Comment by 5ila5** [comment]
Kreis Steinburg is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2177 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/steinburg_de.md)
