### ISSUE TITLE
[Source Request]: Solihull Council, UK

### ISSUE THREAD

**Issue by jackm96** [mampfes/hacs_waste_collection_schedule#2186]
### Municipality / Region

Solihull, United Kingdom

### Collection Calendar Webpage

https://digital.solihull.gov.uk/BinCollectionCalendar/

### Example Address

Postcode: B92 8JX, any address on the list. 

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
Added in #2187 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
