### ISSUE TITLE
[Source Request]: Darlington Borough Council

### ISSUE THREAD

**Issue by jaysuk** [mampfes/hacs_waste_collection_schedule#2189]
### Municipality / Region

Darlington, UK

### Collection Calendar Webpage

https://www.darlington.gov.uk/bins-waste-and-recycling/weekly-refuse-and-recycling-collection-lookup/

### Example Address

Woodlands Road, DL3 9AB

### Collection Data Format

As html on a webpage

### Additional Information

There are 3 additional calendar webpages that are provided where XXXX is the uprn
https://www.darlington.gov.uk/bins-waste-and-recycling/calendar/?uprn=XXXX&collectiontype=Garden
https://www.darlington.gov.uk/bins-waste-and-recycling/calendar/?uprn=XXXX&collectiontype=Refuse
https://www.darlington.gov.uk/bins-waste-and-recycling/calendar/?uprn=XXXX&collectiontype=Recycling

**Comment by 5ila5** [comment]
The implementation (#2190) shows other dates than the website from January - March and November, December.

I think the website shows the wrong dates as they change the collection date (probably some weird time zone thing, I'm one hour ahead of the UK) Do you see this behavior as well? Do you know if these dates are correct?


![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38183212/8fc681f7-3294-45a2-bb70-8787f50dbef6)
*Source returns 10th of January while the website shows 11th of January*

screenshot taken from:

https://www.darlington.gov.uk/bins-waste-and-recycling/calendar/?uprn=010013315817&collectiontype=Recycle

**Comment by 5ila5** [comment]
added in #2190

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
