### ISSUE TITLE
Abfallkalender Bremen

### ISSUE THREAD

**Issue by boklubre** [mampfes/hacs_waste_collection_schedule#219]
Hello,

unfortunately for my Home Town it dosn´t work. It seens Bremen has a own format:

https://web.c-trace.de/bremenabfallkalender/(S(dytpzs5sl1ivu44sptolg2t4))/abfallkalender/cal?Gemeinde=Bremen&Strasse=Oslebshauser%20Heerstra%C3%9Fe&Hausnr=44

https://www.die-bremer-stadtreinigung.de/abfallwirtschaft/entsorgung/bremer-abfallkalender-23080

It´s possible to fix it?
Cheers

Boris

**Comment by mampfes** [comment]
Bremen uses c-trace.de as service provider. I added a new source for them.
