### ISSUE TITLE
[Source Request]: Steinburg, Germany

### ISSUE THREAD

**Issue by stefankoehne** [mampfes/hacs_waste_collection_schedule#2192]
### Municipality / Region

Steinburg, Germany

### Collection Calendar Webpage

https://abfall.steinburg.de/

### Example Address

25348 Glückstadt, Am Fleth 44

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP, As PDF Download

### Additional Information

For the example address given above, the following URL results for the ical file:
https://abfall.steinburg.de/api_v2/collection_dates/1/ort/29/strasse/70/hausnummern/44/abfallarten/R02-B02-P04-D02/kalender.ics

and for the HTML and PDF format:
https://abfall.steinburg.de/api_v2/collection_dates/1/ort/29/strasse/70/hausnummern/44/abfallarten/R02-B02-P04-D02/kalender/2024.html

Default settings for most users are:
_Restabfall (14-täglich), Bioabfall (14-täglich), Papiertonne (monatlich), Gelber Sack (14-täglich)_. For API it is the "R02-B02-P04-D02" part. The other two options are for business and special customers of the garbage collection provider.

**Comment by 5ila5** [comment]
Steinburg is already supported by the ICS source, Documentation for Steinberg is linked in the README.md like this:
[Kreis Steinburg](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/steinburg_de.md) / steinburg.de
