### ISSUE TITLE
[Source Request]: City of Darebin, Victoria, Australia

### ISSUE THREAD

**Issue by joshuapmorgan** [mampfes/hacs_waste_collection_schedule#2198]
### Municipality / Region

City of Darebin, Victoria, Australia

### Collection Calendar Webpage

https://darebin.maps.arcgis.com/apps/instant/basic/index.html?appid=51d4de7339f84dd5a6d2790cb2081be2

### Example Address

274 Gower Street, Preston, VIC 3072

### Collection Data Format

Something different (add to additional information)

### Additional Information

Undocumented ArcGIS API

**Comment by 5ila5** [comment]
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
