### ISSUE TITLE
New waste collection- Ku-ring-gai Council, NSW, Australia 

### ISSUE THREAD

**Issue by AnthonyBe** [mampfes/hacs_waste_collection_schedule#221]
Could you please add? 

https://www.krg.nsw.gov.au/Community/Waste-and-recycling/Bins-and-collection-days

**Comment by dt215git** [comment]
It might be possible to rework the [Campbelltown NSW script](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/campbelltown_nsw_gov_au.py), their website look to use the same approach for searching/displaying collection schedules.

It'd be useful to have a few different test address formats to play around with - some local knowledge on how house or appartment addresses are structured would be helpful. Any chance you could suggest a few?

**Comment by mampfes** [comment]
fixed with #241 by @dt215git
