### ISSUE TITLE
[Bug]: Bedford Borough Council fetch fails

### ISSUE THREAD

**Issue by 3shirts** [mampfes/hacs_waste_collection_schedule#2219]
### I Have A Problem With:

A specific source

### What's Your Problem

Data cannot be fetched. I have restarted HA just in case but the issue persists.

### Source (if relevant)

bedford_gov_uk

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
integration: waste_collection_schedule (documentation)
First occurred: 11:52:04 (1 occurrences)
Last logged: 11:52:04

fetch failed for source Bedford Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/bedford_gov_uk.py", line 34, in fetch json_data = json.loads(r.text)["BinCollections"] ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^ KeyError: 'BinCollections'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Unfortunately, I cannot reproduce this issue with our test cases (UPRNS: `100080009302` `100081207036` `100080018481` `100080023672`) Could you please try one of them to test if it's a problem with your installation or your UPRN.

The source gets the data from: https://bbaz-as-prod-bartecapi.azurewebsites.net/api/bincollections/residential/getbyuprn/100081207036/35 (you could check what's returned when replacing the UPRN with your UPRN)

**Comment by 3shirts** [comment]
Hi. My UPRN is 100080043813 and that does seem to return data that looks ok to my eye. Not sure why the integration isn't working then

**Comment by 3shirts** [comment]
UPDATE: I completely removed the integration and config then restarted. Then reinstalled and redid the config and restarted again. Seems to be working again now! I had tried reinstalling but not a complete wipe, restart, install, restart cycle.

Apologies for wasting your time then. Not really sure what happened as I literally restored the same config yaml after the reinstall so nothing, in theory, has changed.

**Comment by 3shirts** [comment]
UPDATE: I completely removed the integration and config then restarted. Then reinstalled and redid the config and restarted again. Seems to be working again now! I had tried reinstalling but not a complete wipe, restart, install, restart cycle.

Apologies for wasting your time then. Not really sure what happened as I literally restored the same config yaml after the reinstall so nothing, in theory, has changed.
