### ISSUE TITLE
[Bug]: Solihull Council is incorrectly named as Denbighshire County Council 

### ISSUE THREAD

**Issue by jackm96** [mampfes/hacs_waste_collection_schedule#2224]
### I Have A Problem With:

The integration in general

### What's Your Problem

As per the title, Solihull Council is displayed as Denbighshire County Council on the GitHub docs and in the integration. Im guessing just a renaming exercise as the integration correctly pulls solihull council data, but I guess when the code was copied to add Solihull, the name wasn't changed. 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed in #2226
Thanks for pointing this out, must have missed it somehow when copying code
