### ISSUE TITLE
Landkreis Amberg-Sulzbach

### ISSUE THREAD

**Issue by Andi1969** [mampfes/hacs_waste_collection_schedule#2239]
### Municipality / Region

Poppenricht

### Collection Calendar Webpage

https://www.landkreis-as.de/abfallwirtschaft/abfuhrtermine.php

### Example Address

92284 Poppenricht, Waldstraße 20

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Landkreis Amberg-Sulzbach is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2242 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/landkreis_as_de.md)
