### ISSUE TITLE
No Import BMV

### ISSUE THREAD

**Issue by Terra2000** [mampfes/hacs_waste_collection_schedule#224]
Hi !
Thanks for the plugin, but unfortunately I can't get any data in. I checked, it may be that the street and the street are different. Thank you

**Comment by mampfes** [comment]
Please provide more info. Which source are you using? Which information is missing or errorneous?

**Comment by Terra2000** [comment]
waste_collection_schedule :   sources :    - name : bmv_at      args :        ort : RATTERSDORF        strasse : SIEBENBRÜNDLGASSE        hausnummer : 30
this is my configuration.yaml 
    Am Sonntag, 1. Mai 2022, 10:17:50 MESZ hat Steffen Zimmermann ***@***.***> Folgendes geschrieben:  
 
 


Please provide more info. Which source are you using? Which information is missing or errorneous?
