### ISSUE TITLE
[Bug]: New config_flow - data is requested twice on config_entry setup

### ISSUE THREAD

**Issue by ReneNulschDE** [mampfes/hacs_waste_collection_schedule#2243]
### I Have A Problem With:

The integration in general

### What's Your Problem

When I setup the integration with the new config_flow setup, the data gets requested twice. Sensors and calendars are created only once.

Example: Add the app_abfallplus_de with the new config_flow:

config_entry:
```
        "data": {
          "name": "app_abfallplus_de",
          "args": {
            "app_id": "de.k4systems.abfallappzak",
            "city": "Fischen",
            "bezirk": "Ortsteile"
          }
```

Proxy-Log
![image](https://github.com/user-attachments/assets/c19bbc41-03d0-41d9-a66b-1a37e3ab03d8)

Example: Create Stadtreinigung_Leipzig_de with the new config flow:

config_entry:
```
        "data": {
          "name": "stadtreinigung_leipzig_de",
          "args": {
            "street": "Eisenacher Straße",
            "house_number": "34"
          }
        },
```

Proxy-log
![image](https://github.com/user-attachments/assets/9405d3e6-4fd2-47ad-bd1c-a67ac1ef1bbf)

### Logs

```Shell
No specific logs.
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
The data gets loaded twice ([here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/7fe7ae547edd38e0dbb8a7abf3899e203ffa7dd6/custom_components/waste_collection_schedule/init_ui.py#L64) and [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/7fe7ae547edd38e0dbb8a7abf3899e203ffa7dd6/custom_components/waste_collection_schedule/init_ui.py#L86)). But I do not know why

**Comment by 5ila5** [comment]
I think the first fetch (l 64) is for checking if the fetch fails and report a ConfigEntryNotReady to HA 

> Raise the ConfigEntryNotReady exception from async_setup_entry in the integration's __init__.py, and Home Assistant will automatically take care of retrying set up later. To avoid doubt, raising ConfigEntryNotReady in a platform's async_setup_entry is ineffective because it is too late to be caught by the config entry setup 
(https://developers.home-assistant.io/docs/integration_setup_failures/)

The second one is to populate/update the calendar for the first time.

The first check is differently not necessary, as the second one (async_config_entry_first_refresh) already does the same:
>Refresh data for the first time when a config entry is setup.
Will automatically raise ConfigEntryNotReady if the refresh fails. Additionally logging is handled by config entry setup to ensure that multiple retries do not cause log spam.
