### ISSUE TITLE
[Source Request]: East Lothian Council, UK

### ISSUE THREAD

**Issue by dochtie** [mampfes/hacs_waste_collection_schedule#2251]
### Municipality / Region

Lothian, Scotland

### Collection Calendar Webpage

http://collectiondates.eastlothian.gov.uk/your-calendar

### Example Address

EH21 8GU

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
Source added in #2253 they only show the next collection in an easy parsable format (not PDF) and seem to not show garden waste. This source only gets these events.

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by dochtie** [comment]
I downloaded the latest release - thank you again.

i may be doing something wrong but I can’t get recycling or food waste to show up. Can you check it is working for you?

**Comment by 5ila5** [comment]
It works for me.
Does it show up in the calendar tab? If yes, where do you want it to show up? You can define a lot of different sensors with different behavior
