### ISSUE TITLE
[Bug]: Kreis Plön

### ISSUE THREAD

**Issue by DocF00** [mampfes/hacs_waste_collection_schedule#2252]
### I Have A Problem With:

A specific source

### What's Your Problem

Hey, I just updated to v2.0, sadly I cant find 'Kreis Plön' or 'Abfallwirtschaft Kreis Plön' at the list of sources from the GUI configuration. Under v1.x I had no issues. 
My sensor from configuration.yaml is not working anymore either. Before no issues.
Thanks in advance!

### Source (if relevant)

https://www.kreis-ploen.de/output/abfall_export.php

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Kreis Plön is not a source, but just documentation on how to use the ics source for it. You can find the ICS source in country: Generic -> source: ics

I cannot reproduce your issue with sensors, Could you please share your sensor configuration and take a look if there are any logs (English: settings -> system -> logs) (German: einstellungen -> system -> Protokolle)

**Comment by DocF00** [comment]
The url which was working till yesterday now delivers via Generic → ics the error 'pop from empty list'.
The Integration and the sensor from v1.x looks like this:
##
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.kreis-ploen.de/output/abfall_export.php?csv_export=1&mode=vcal&ort=2156.41&strasse=2156.373.1&abfart%5B0%5D=1.1&abfart%5B1%5D=1.3&abfart%5B2%5D=1.4&abfart%5B3%5D=1.5&vtyp=4&vMo=1&vJ={%Y}&bMo=12
        
sensor:
  - platform: waste_collection_schedule
    name: Abfallplan
    details_format: 'upcoming'
    count: 2
    leadtime: 1
    date_template: '{{value.date.strftime("%d.%m.%Y")}}'
    value_template: '{{value.types|join(", ")|replace(": Laboe", "")|replace(" 14-täglich", "")|replace(" 4-wöchentlich", "")|replace(" 2-wöchentlich", "")}}'
    add_days_to: 1
##

The configuation above now delivers this error via the protocol readout (which reads to me as if the problem is pop from empty list aswell): 
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 13. Juli 2024 um 20:41:33 (2 Vorkommnisse)
Zuletzt protokolliert: 01:28:52

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 164, in fetch entries = self.fetch_url(url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 205, in fetch_url return self._convert(r.text) ^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 216, in _convert dates = self._ics.convert(data) ^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalendar/cal.py", line 360, in from_ical component = stack.pop() ^^^^^^^^^^^ IndexError: pop from empty list

**Comment by 5ila5** [comment]
```bash
curl "https://www.kreis-ploen.de/output/abfall_export.php?csv_export=1&mode=vcal&ort=2156.41&strasse=2156.373.1&abfart%5B0%5D=1.1&abfart%5B1%5D=1.3&abfart%5B2%5D=1.4&abfart%5B3%5D=1.5&vtyp=4&vMo=1&vJ=2024&bMo=12"
```
results in:
```
BEGIN:VCALENDAR
METHOD:PUBLISH
X-WR-TIMEZONE:Europe/Berlin
PRODID:http://www.kreis-ploen.de
CALSCALE:GREGORIAN
VERSION:2.0

END:VEVENT
END:VCALENDAR
```

It looks like your ICL URL got invalid somehow. Did you try to get a new one? Does it match the old one?
