### ISSUE TITLE
[Bug]: Golemio.cz LAT/LON GUI configuration only integer

### ISSUE THREAD

**Issue by fumantsu** [mampfes/hacs_waste_collection_schedule#2255]
### I Have A Problem With:

A specific source

### What's Your Problem

In GUI configuration page for Golemio.cz the Lat/Lon fields doesn't support proper values rather than only integer.

### Source (if relevant)

golemio.cz

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Fixed in #2274

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
