### ISSUE TITLE
[Bug]: Middlesbrough, UK unable to configure

### ISSUE THREAD

**Issue by darlowatty** [mampfes/hacs_waste_collection_schedule#2259]
### I Have A Problem With:

A specific source

### What's Your Problem

When trying to configure the integration I get the following error, once I click Submit after entering my UPRM "The source returned an invalid response: "403 Client Error: Forbidden for url: https://my.middlesbrough.gov.uk/forbidden". Please check the provided arguments and try again."

### Source (if relevant)

middlesbrough_gov_uk

### Logs

```Shell
The source returned an invalid response: "403 Client Error: Forbidden for url: https://my.middlesbrough.gov.uk/forbidden". Please check the provided arguments and try again.
```

### Relevant Configuration

```YAML
Unable to complete initial configuration.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
<https://middlesbrough.gov.uk/recycling-and-rubbish/bin-collection-dates/>:
> There's a new way to get your bin collection dates this year. You'll need to [sign in to your MyMiddlesbrough account](https://my.middlesbrough.gov.uk/login/), and your bin collection dates will be displayed on your homepage.
> 
> You'll need to type in your address the first time, but after that it'll be saved.
> 
> You'll need to [register for a MyMiddlesbrough account](https://my.middlesbrough.gov.uk/ssauth/register) if you don't have one. Once you've registered, you'll get an email with the subject 'Signup | Verification' within 10 minutes. It includes a link which you'll need to click to set up your account. Sometimes the email might go into your 'junk' or 'spam' folder, so look out for it. If you don't get a verification email, it's because you've typed your email address incorrectly, and you'll need to sign up again.

Looks like this broke the source. The image looks like they use Recollect now. Recollect is supported by the ICS source and there is documentation for [recollect](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md). Looks like the recollect form is hidden behind a login. Please report if this works, so I can add Middlesbrough to the supported services (will add a link to the README.md)
