### ISSUE TITLE
New UI configuration 

### ISSUE THREAD

**Issue by michaelthompson1991** [mampfes/hacs_waste_collection_schedule#2263]
### I Have A Problem With:

The integration in general

### What's Your Problem

Hi, I currently have this setup in yaml and it gives me a calendar with everything on. Im trying to setup in the ui since the update.

I have 2 bin collections and I’m struggling what to put on which screen. I understand it says I can leave the first page and use the default settings but it’s the last page which is confusing me. 

Im not sure whether i should leave the first page or not and Im not sure what to do with the last page. I tried just leaving the last page blank but the only thing it gave me was a sensor which said on or off.

Can you help please?

Thanks!

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
You have multiple screens

1. To select your country
2. To select the source you use
3. To fill in the parameters needed by the source
4. To select waste types you want to modify (can be left empty)
5. (only if types selected in 4) customize the selected waste types
6. To configure sensors (just click Do not create sensor if you do not want to create any sensors and leave anything else as is)

This should create a calendar entity with all your calendars and adds custom sensors (if configured in 6)

Future improvements not yet developed: We probably want to hide the quite confusing panel 6 behind a question if you want to create any sensors.

**Comment by michaelthompson1991** [comment]
Thanks I'll give that a try tomorrow and get back to you if I need further help. So to clarify, I select the country, area, add the uprn. What happens in step4 if I don't choose the waste types? So I'm assuming I can just leave everything as is and it should work like the Yaml version does? Apologies I'm struggling to understand what everything is. Thanks for the help

**Comment by 5ila5** [comment]
Yes, you can leave step 4 empty  (you can rename waste types there and do some other minor changes to specific waste events) If you leave step 4 empty you will not see step 5 you can then just select `Do not create sensor` and leave everything else untouched in step 6 if you just use the calendar and do not need any sensors for further automations like automated push messages or something like that

**Comment by michaelthompson1991** [comment]
No problem, thanks!

So I had a Quick Look before and it seemed to just name them 1 and 2 for the bins, but I’m not sure so I’ll look tomorrow.

Thanks!

**Comment by michaelthompson1991** [comment]
Got it working so you can close the issue. Although I have no idea what the extra pages and sensors do but I have it working how I had the yaml working and that seems ideal for me.

Thanks for the support 👍🏻
