### ISSUE TITLE
[Bug]: Error when configuring Circulus

### ISSUE THREAD

**Issue by philippe-tc** [mampfes/hacs_waste_collection_schedule#2265]
### I Have A Problem With:

A specific source

### What's Your Problem

When using the UI I cannot configure. I use
- Netherlands
- Circulus
- Postcode: 7231DB
- Housenumber: 23
- 
In the last step I get an error: 

The source returned an invalid response: "'BESTAFR'". Please check the provided arguments and try again.

Entering these steps manually in https://mijn.circulus.nl there is no problem. It looks like the site circulus.nl comes back with a response that this integration doesn't recognise.

![IMG_6296](https://github.com/user-attachments/assets/e7155946-86f6-4080-8247-f6eb45c06cb7)

### Logs

No relevant log information

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Seems to be a general issue with the source, not the UI configuration.

**Comment by 5ila5** [comment]
fixed in #2277

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by philippe-tc** [comment]
When I go to HACS -> Waste Collection Schedule -> 3-dot menu -> redownload -> change '2.0.0' to 'master", then the download button bottom right turns from blue to gray and 2 seconds later the version selectors says '2.0.0' again and the download button is blue again. Same after restarting HA.
So selecting and downloading this 'master' version seems impossible?

**Comment by philippe-tc** [comment]
CORRECTION
Finally I did find the new (master) version of the file circulus_nl.py, copied the contents into mine, restarted HA and now it did except the installation!
Sorry for bothering you.
