### ISSUE TITLE
[Bug]: Error when configuring KWU Entsorgung Landkreis Oder-Spree

### ISSUE THREAD

**Issue by Bill-Dung** [mampfes/hacs_waste_collection_schedule#2266]
### I Have A Problem With:

A specific source

### What's Your Problem

When using the UI I cannot configure. I use

    Germany

    KWU Entsorgung Landkreis Oder-Spree

    Spreenhagen
    Feldweg
    4

Then I get an error:
Die Quelle hat eine ungültige Antwort zurückgegeben: "cannot access local variable 'ObjektValue' where it is not associated with a value". Bitte überprüfe die Argumente und versuche es erneut.

![error](https://github.com/user-attachments/assets/ed72dd10-2cbb-46aa-8bef-9b6085b7d2cf)

I'm sure it has something to do with the name "Feldweg". There's also "Am Feldweg" here, but that doesn't work either. "Lindenring", for example, works perfectly.

Up until now I've always used the csv file downloaded from KWU, and that works without a problem.

I don't know if it's helpful, I've had the problem with the names on other websites too.

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The error message is pretty bad, but it looks like it does not find hnr 4 for this street, but only hnr 1.

I improved the error message to better communicate the actual problem in #2275, which will be part of the next release

**Comment by Bill-Dung** [comment]
Am Feldweg has only hnr 1, Feldweg has 1 to 5

**Comment by 5ila5** [comment]
I see it matched the wrong street, as it only checked if the provided street argument is part of the street text returned by the website. Fixed that in #2287
