### ISSUE TITLE
abikw.de / UI-Configuration

### ISSUE THREAD

**Issue by tonizabel** [mampfes/hacs_waste_collection_schedule#2269]
Hello,

i can't find "abikw.de" (Landkreis Anhalt-Bitterfeld) in the list of the UI Configuration.

**Comment by 5ila5** [comment]
Abfall-App.net is not a real source but just documentation on how to configure the ICS source:
the ICS source is located at country: generic -> ICS

We'll probably add these pseudo sources back in their country specific source selector in the future as multiple people had trouble finding it
