### ISSUE TITLE
[Source Request]: Michelstadt Odenwald germany

### ISSUE THREAD

**Issue by FornoffP** [mampfes/hacs_waste_collection_schedule#2272]
### Municipality / Region

64720 Michelstadt im Odenwald germany

### Collection Calendar Webpage

https://reso-gmbh.abfallkalender.services/php/Muellkalender.php?pfad=Deutsch.muellkalender&ort=Michelstadt&ot=Vielbrunn&nr=0&browser=Safari&jahr=2024 https://reso-gmbh.abfallkalender.services/php/Muellkalender.php?pfad=Deutsch.muellkalender&ort=Michelstadt&ot=Vielbrunn&nr=0&browser=Safari&jahr=2024

### Example Address

Pfarrgewann 17

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
added by #2279

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by FornoffP** [comment]
Thank you very much Am 16.07.2024 um 00:21 schrieb 5ila5 ***@***.***>:﻿
added by #2279
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
