### ISSUE TITLE
CalendarEventDevice is deprecated

### ISSUE THREAD

**Issue by mxwi** [mampfes/hacs_waste_collection_schedule#228]
Hi,

with HA 2022.05 they changed the Calendar Data Model (https://developers.home-assistant.io/blog/2022/04/18/calendar-data-model/)

Errorlog: 2022-05-05 13:41:11 WARNING (MainThread) [homeassistant.components.calendar] CalendarEventDevice is deprecated, modify WasteCollectionCalendar to extend CalendarEntityCalendar Data Model

Would be happy, if you could "fix" this issue.

greetz

**Comment by GerdRuetten** [comment]
Same problem here with 

Waste collection scheduler - Version: 1.19.1
Home Assistant Core - Version: 2022.5.0

**Comment by GerdRuetten** [comment]
it seems duplicated to #222 but a new version wasn't release .... why?

**Comment by mampfes** [comment]
Duplicate of #222. Fixed in release 1.20.0

@GerdRuetten: Because I do this all in my spare time.
