### ISSUE TITLE
[Source Request]: Simcoe, Canada (using recollect)

### ISSUE THREAD

**Issue by CanadianG00se** [mampfes/hacs_waste_collection_schedule#2282]
### Municipality / Region

Simcoe

### Collection Calendar Webpage

https://simcoe.ca/residents/organics-recycling-and-garbage/collections-schedule/

### Example Address

15 Main St, Penetanguishene

### Collection Data Format

As ICS/ICAL file, Dedicated IOS/Android APP, As PDF Download, Something different (add to additional information)

### Additional Information

Collection Data Format:
 - Email
 - Android or IOS App
 - Phone Call
 - Embed in Outlook, Google Calendar, ical
 - Print a Calendar 
 - And on webpage

For ICAL file:
- Enter address under "Please type your home address:", press search.
- "Get a reminder / alert" > "Embed in Outlook, Google Calendar, iCal", "Add to Google Calendar".
- Open following link.

**Comment by 5ila5** [comment]
Simcoe uses recollect there is documentation on how to integrate it using the ICS source [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md) I added Simcoe to the README with a link to the recollect documentation in #2288
