### ISSUE TITLE
[Source Request]: Halifax, NS, Canada

### ISSUE THREAD

**Issue by MrFutzy** [mampfes/hacs_waste_collection_schedule#2283]
### Municipality / Region

Halifax, NS, Canada

### Collection Calendar Webpage

https://www.halifax.ca/home-property/garbage-recycling-green-cart/collection-schedules-waste-app

### Example Address

18 Lynwood Drive, Halifax

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP, As PDF Download

### Additional Information

Thank you for your consideration!  I appreciate all the work you do for the community.

**Comment by 5ila5** [comment]
Halifax uses recollect there is documentation on how to integrate it using the ICS source [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md) I added Halifax to the README with a link to the recollect documentation in #2289
