### ISSUE TITLE
[Bug]: Anglesey available in UK but not in integration

### ISSUE THREAD

**Issue by deiniolj** [mampfes/hacs_waste_collection_schedule#2284]
### I Have A Problem With:

The integration in general

### What's Your Problem

From the list of available councils, Anglesey appears. But when I run the integration. Anglesey is not available in the options for UK..

### Source (if relevant)

f

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Anglesey is not a real source but just an alias for the ICS source with some additional information on how to get the right parameter for the ics source.
