### ISSUE TITLE
Germany ZHA Hildesheim Not integrated 

### ISSUE THREAD

**Issue by Serginio1001** [mampfes/hacs_waste_collection_schedule#2286]
### Municipality / Region

Germany Hildesheim 

### Additional Information

Hi, ZHA Hildesheim is indicated as integrated in the documentation. This will not be available in the integration. See pictures

![image](https://github.com/user-attachments/assets/c1e8e98e-2abc-41e0-85ba-e6a1f8d9c38c)
![image](https://github.com/user-attachments/assets/b373d172-3e68-4def-a2b9-3994f0bcc146)

**Comment by ReneNulschDE** [comment]
ZAH Hildesheim is a generic ICS source. You can find it under the country "Generic", "ICS".

**Comment by 5ila5** [comment]
These ICS sources will be located in the country specific section after the next release

**Comment by Serginio1001** [comment]
Okay, thanks. The update is really cool, thank you. Good work
