### ISSUE TITLE
[Feature]: Better matching of street names

### ISSUE THREAD

**Issue by rudibarani** [mampfes/hacs_waste_collection_schedule#2299]
### I propose a feature for:

The integration in general

### Describe your wanted feature

A handy feature could be to try "Str." instead of "Straße" when comparing street names, too. Our waste collector uses the abbreviated names in their data base and using our official street name did not lead to a match without the abbreviated version.

**Comment by 5ila5** [comment]
That's nothing that could reasonably be done for all sources, we have over 400 sources which are individual scripts trying to gather the information using web requests and implement their own logic on how to find matching parameters (that cannot easily be done at one place), deciding what to do with it and how the result needs to further processed to be passed on to other web request or find the correct dates in previous web requests. I can look into your source (if you provide it) if there is a good way to check for both, but we generally write in the documentation to check on the service provider website for exact spelling as this typically decreases complexity of scripts and checking for both may be unreasonably if the parameter is directly passed on into a web requests.

**Comment by 5ila5** [comment]
I guess (from your other issue) your source is alw_wf_de, I looked into it and made the city match case-insensitive and the street to also match case-insensitive and match `straße` for `str.` and the other way around
