### ISSUE TITLE
[Request] Support for Abfallkalender Landkreis Göttingen (Niedersachsen)

### ISSUE THREAD

**Issue by uherting** [mampfes/hacs_waste_collection_schedule#230]
Is it possible to add support for the Abfallkalender Landkreis Göttingen (Niedersachsen)?

https://www.abfallplus.de/fuer-buerger/ states "Kreis Göttingen wird unterstützt". 

I tried to find out the parameters with the help of the proxy app "postman" and the recommended Android App from https://www.abfallplus.de/, but failed so far.

**Comment by uherting** [comment]
The method of how to extract seem to be outdated or not available (the website of Landkreis Göttingen has no interface). If I get any hint how to extract the needed parameters I (software engineer and Linux user) am more than willing to work on this. So far I could not get them from the traffic generated by the Android app though.

**Comment by mampfes** [comment]
The abfall_io wizard can now be used for Göttingen (not including Osterode and Altkreis Göttingen).
