### ISSUE TITLE
[Feature]:  Add support for St. Albans 

### ISSUE THREAD

**Issue by bonstio** [mampfes/hacs_waste_collection_schedule#2311]
### I propose a feature for:

Sources

### Describe your wanted feature

Please add https://www.stalbans.gov.uk/rubbish-collections

Thanks!

**Comment by 5ila5** [comment]
added in #2314

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
