### ISSUE TITLE
[Feature]: New Source Leeds City Council, UK

### ISSUE THREAD

**Issue by jcyyu** [mampfes/hacs_waste_collection_schedule#2313]
### I propose a feature for:

Sources

### Describe your wanted feature

https://www.leeds.gov.uk/residents/bins-and-recycling/check-your-bin-day

**Comment by 5ila5** [comment]
added a source taht supports the following apps:
- Leads Bins (<https://play.google.com/store/apps/details?id=com.imactivate.bins>)
- Rotherham Bins (<https://play.google.com/store/apps/details?id=com.imactivate.rotherhambinsrelease>)
- Luton Bins (<https://play.google.com/store/apps/details?id=com.imactivate.lutonbins>)
- Fenland Bins (<https://play.google.com/store/apps/details?id=com.imactivate.fenlandbins>)

in #2315

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
