### ISSUE TITLE
[Source Request]: BLISKO

### ISSUE THREAD

**Issue by Kiniuxxx** [mampfes/hacs_waste_collection_schedule#2318]
### Municipality / Region

Poland

### Collection Calendar Webpage

https://blisko.co/

### Example Address

Ostrowiec

### Collection Data Format

Dedicated IOS/Android APP

**Comment by 5ila5** [comment]
This is now supported by the sims_pl source added in  #3340

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
