### ISSUE TITLE
[Bug]: Rhein-Sieg Kreis (RSAG) / Muellmax not working: "The source returned an invalid response."

### ISSUE THREAD

**Issue by dhoerpel** [mampfes/hacs_waste_collection_schedule#2320]
### I Have A Problem With:

The integration in general

### What's Your Problem

When trying to configure the wase collection schedule for the Rhein Sieg Kreis (RSAG) - Germany, I'm getting the following error message:
`The source returned an invalid response: “Content line could not be parsed into parts: '<!DOCTYPE html PUBLIC ‘-//W3C//DTD XHTML 1.1//EN’ ‘http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd’>': <!DOCTYPE html PUBLIC ‘-//W3C//DTD XHTML 1.1//EN’ ‘http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd’>”. Please check the arguments and try again.
`
Please see attached my configuration:

![1](https://github.com/user-attachments/assets/cdd48d80-ea91-4486-8664-3ce0b6bc88a2)
![2](https://github.com/user-attachments/assets/90b1d980-5c28-4e91-8e6e-2304ad272349)

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
The error message is not ideal but it means taht the server answered with wrong content that's probably due to wrong arguments. Did you check that you wrote the arguments exactly like https://www.rsag.de/abfallkalender/ you can select them here?

**Comment by BlackHawk1912** [comment]
Had the same problem and checked my current/old configuration. Turns out that müllmax for my location LKG) doesnt want a house number. Leaving the last field empty solved the problem for me.

**Comment by dhoerpel** [comment]
@BlackHawk1912 @5ila5 
Thank you for your prompt answers!
With the help of your answers I was able to identify that my garbage collection provider had a spelling mistake in my street name. Once I added the “wrong” street name I was able to successfully implement the integration.
