### ISSUE TITLE
[Bug]: Abfallwirtschaft Plön broken with 2.0.0

### ISSUE THREAD

**Issue by MrYukio** [mampfes/hacs_waste_collection_schedule#2330]
### I Have A Problem With:

A specific source

### What's Your Problem

The Plön waste management system no longer works correctly since the 2.0 update. I am only informed that the next collection is “unknown”. I have checked the website and apparently they have also changed the ICS calendar method.

### Source (if relevant)

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/kreis_ploen_de.md

### Logs

```Shell
no relevant logs
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Looks like they changed their iCal link URL structure. I updated the documentation on how to get the link in #2338.
So you need to get a new url with the new instructions [here](https://github.com/5ila5/hacs_waste_collection_schedule/blob/master/doc/ics/kreis_ploen_de.md) 

I doubt that has anything to do with the 2.0.0 update
