### ISSUE TITLE
[Bug]: Mein Abfallkalender: Unknown entities

### ISSUE THREAD

**Issue by moritzmaier84** [mampfes/hacs_waste_collection_schedule#2341]
### I Have A Problem With:

A specific source

### What's Your Problem

As said in the title.
Mein Abfallkalender entities are unknown since yesterday.

### Source (if relevant)

mein abfallkalender

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
HA 2024.6
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I guess you're using the ics source for mein-abfallkalender.de, did you already try to regenerate the ics url? on the website and use this new one?

**Comment by moritzmaier84** [comment]
Yes I do and yes I did but now i figured out, that it's not ".online". instead ".de".
So I got it back to work. Thx!
