### ISSUE TITLE
[Bug]: Sensors show "unknown"

### ISSUE THREAD

**Issue by RhochR** [mampfes/hacs_waste_collection_schedule#2342]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

I have recently imported an ics file from my local trash collector. The calendar all works perfectly but on the sensors all just show unknown.

![image](https://github.com/user-attachments/assets/8f96b901-4724-413b-a721-34012618419d)

`
BEGIN:VEVENT
DTSTART;VALUE=DATE:20240813
DTEND;VALUE=DATE:20240814
TRANSP:TRANSPARENT
X-MICROSOFT-CDO-BUSYSTATUS:FREE
LOCATION;LANGUAGE=de:[adress:redacted]\, [town name:redacted]
UID:[redacted]
DTSTAMP:20240727T021247Z
DESCRIPTION;LANGUAGE=de:Stellen Sie bitte die Muellsammelgefaesse am Abfuhrtag um 7.00 Uhr an der strassenseitigen Grundstuecksgrenze entlang der Fahrbahn zur Entleerung bereit.
SUMMARY;LANGUAGE=de:Bioabfallbehaelter 
PRIORITY:9
CLASS:PUBLIC
URL:www.bmv.at
STATUS:CONFIRMED
END:VEVENT
`

Does anyone have this problem or am I  just to stupid to do it?🙄

### Source (if relevant)

ics file

### Logs

```Shell
no relevant logs
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by RhochR** [comment]
The code wasnt displayd correctly:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20240813
DTEND;VALUE=DATE:20240814
TRANSP:TRANSPARENT
X-MICROSOFT-CDO-BUSYSTATUS:FREE
LOCATION;LANGUAGE=de:[redacted]\, [redacted]
UID:[redacted]
DTSTAMP:20240727T021247Z
DESCRIPTION;LANGUAGE=de:Stellen Sie bitte die Muellsammelgefaesse am Abfuhrtag um 7.00 Uhr an der strassenseitigen Grundstuecksgrenze entlang der Fahrbahn zur Entleerung bereit.
SUMMARY;LANGUAGE=de:Bioabfallbehaelter 
PRIORITY:9
CLASS:PUBLIC
URL:www.bmv.at
STATUS:CONFIRMED
END:VEVENT
```

**Comment by RhochR** [comment]
Sorry abou that.
The code wasnt displayed correctly:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20240813
DTEND;VALUE=DATE:20240814
TRANSP:TRANSPARENT
X-MICROSOFT-CDO-BUSYSTATUS:FREE
LOCATION;LANGUAGE=de:[redacted]\, [redacted]
UID:[redacted]
DTSTAMP:20240727T021247Z
DESCRIPTION;LANGUAGE=de:Stellen Sie bitte die Muellsammelgefaesse am Abfuhrtag um 7.00 Uhr an der strassenseitigen Grundstuecksgrenze entlang der Fahrbahn zur Entleerung bereit.
SUMMARY;LANGUAGE=de:Bioabfallbehaelter 
PRIORITY:9
CLASS:PUBLIC
URL:www.bmv.at
STATUS:CONFIRMED
END:VEVENT
```

**Comment by 5ila5** [comment]
If the calendar works, but the sensors show unknown, I'm pretty sure your sensors aren't configured correctly. Did you make sure that the types argument of the sensor exactly match the names of the entries in your calendar?

**Comment by RhochR** [comment]
This is the config for one of my sensors:
![image](https://github.com/user-attachments/assets/68a2c082-0fc6-45f7-a883-3ed4f1630153)
![image](https://github.com/user-attachments/assets/58706920-ba4f-43db-8f59-ca0026447eb7)
![image](https://github.com/user-attachments/assets/f88a1f6f-dd11-4738-bbbc-27ae623fb759)
I tried to set them up again using this config but the still show unknown.

**Comment by RhochR** [comment]
For some reason I tried it out with the example file and it worked perfectly. I think this is a problem with my ics file. Can anyone tell me why my file doesnt work based on the snippet or more important how i can fix it?

**Comment by RhochR** [comment]
Ok, I now I tried not specifying any type and it suddenly works. I will work on this from here. If I managed to get the other ones running I will post it here.
