### ISSUE TITLE
[Bug]: fenland district council date time error

### ISSUE THREAD

**Issue by holdmybeer1** [mampfes/hacs_waste_collection_schedule#2347]
### I Have A Problem With:

A specific source

### What's Your Problem

The source returned an invalid response: "'datetime.date' object is not subscriptable". Please check the provided arguments and try again.

Above is reported in setup using GUI (which is an excellent improvement and thanks!)

### Source (if relevant)

Fenland district council

### Logs

```Shell
The source returned an invalid response: "'datetime.date' object is not subscriptable". Please check the provided arguments and try again.
```

### Relevant Configuration

```YAML
Version 2.0.1
Home assistant 2024.7.3
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
There was a logic bug in the source that would lead to this error if there are multiple collection at the same day.

Fixed it in #2353 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
