### ISSUE TITLE
[Source Request]: Porirua City Council

### ISSUE THREAD

**Issue by adowhite** [mampfes/hacs_waste_collection_schedule#2349]
### Municipality / Region

Porirua, New Zealand

### Collection Calendar Webpage

https://poriruacity.govt.nz/services/rubbish-and-recycling/recycling-calendar/

### Example Address

6 Ration lane

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added with #2360 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
