### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by dt215git** [mampfes/hacs_waste_collection_schedule#235]
Could the repo include a requirements.txt to help in recreating a venv?
This is what I ended up with when adding/testing a new source, but there may be others needed for functionality I didn't use.
```
beautifulsoup4==4.11.1
certifi==2021.10.8
charset-normalizer==2.0.12
DateTime==4.4
httplib2==0.20.4
icalendar==4.0.9
icalevents==0.1.25
idna==3.3
pyparsing==3.0.8
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
recurring-ical-events==1.0.2b0
requests==2.27.1
six==1.16.0
soupsieve==2.3.2.post1
urllib3==1.26.9
x-wr-timezone==0.0.5
zope.interface==5.4.0
```

**Comment by mampfes** [comment]
Sorry, I'm not very familiar with venv and requirements.txt.
Adding a file shouldn't be a problem. But how do you maintain the file and all revisions?

**Comment by dt215git** [comment]
From a terminal in your project folder
`pip freeze > requirements.txt`
It'll generate the text file listing all the packages you've installed, and that file can then be used by others to setup the same packages in a new virtual environment.
`pip install -r requirements.txt`
Saves having to work out the missing packages based on error messages generated at run time.

But if you've not been using a virtual environment then the risk is it'll list every package you've installed on your system, not just those used by the project. If you install/uninstall packages, rerun the command and it'll overwrite the file with the latest list of packages.

I just tinker around with python, so am by no means an expert at the virtual environment thing, but have found them a useful thing.
