### ISSUE TITLE
[Source Request]: Stirling Council Australia

### ISSUE THREAD

**Issue by StrafeBink** [mampfes/hacs_waste_collection_schedule#2354]
### Municipality / Region

Perth, Australia

### Collection Calendar Webpage

https://www.stirling.wa.gov.au/waste-and-environment/waste-and-recycling/residential-bin-collections

### Example Address

3 Ryan Avenue, Dianella WA, Australia

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in #2378 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
