### ISSUE TITLE
[Source Request]: Swale, UK

### ISSUE THREAD

**Issue by rchiileea** [mampfes/hacs_waste_collection_schedule#2357]
### Municipality / Region

swale kent 

### Collection Calendar Webpage

https://swale.gov.uk/bins-littering-and-the-environment/bins/my-collection-day?__cf_chl_tk=GDM5HtFXoZ9zkLLH9hzJdfE655D1PGYkgJGn7XkLjiY-1722282655-0.0.1.1-4564

### Example Address

Bob amor close, faversham kent

### Collection Data Format

As html on a webpage

### Additional Information

you enter post code, select address and it gives you the info.

**Comment by 5ila5** [comment]
Added Swale source in #3064

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by rchiileea** [comment]
this is broken again

**Comment by 5ila5** [comment]
They changed the website and put it behind a Cloudflare capthaca (at least for me with a German IP) maybe @jamesonuk could have a look. But it's possible we cannot fix this, and you need to use the [static source instead](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

**Comment by jamesonuk** [comment]
they have definitely changed the website `name="2024 Bin Day Lookup Form v2"` but I didn't get any captcha thrown up.

I only added this as someone asked me to look.   I will see if I can fix it over the next few days

**Comment by rchiileea** [comment]
happy 2025 all, so would that be in the py under form data (so should i change that line from) SQ_FORM_462397_PAGE to 2024_Bin_Day_Lookup_Form_v2?

**Comment by jamesonuk** [comment]
> happy 2025 all, so would that be in the py under form data (so should i change that line from) SQ_FORM_462397_PAGE to 2024_Bin_Day_Lookup_Form_v2?

No unfortunately they have changed the whole format of the page.   I will try and have a look over the next few days

**Comment by jamesonuk** [comment]
Only had a brief amount of time to look today but if anyone does pick this up then it looks like they have added Captcha that kicks in sometimes and stops it working 😢 

However I was able to get this working the other day so I think this may just be the number of calls I made whilst testing.
Just for info, I changed first request to 
```python
        first_form_data = {
            "SQ_FORM_485465_PAGE": "1",
            "q485476:q1": self._postcode,
            "form_email_485465_submit": "Choose Your Address &#10140;",
        }
```
and second request to
```python
        second_form_data = {
            "SQ_FORM_485465_PAGE": "2",
            "q485480:q1": self._uprn,
            "form_email_462397_submit": "Get Bin Days &#10140;",
        }
```

Response is then proper HTML where the relevant bit is

```html
<div style="padding: 0 1.5em;">

    <p>Put the following bins out by 6am on Saturday, 4 January</p>
    
    <div class="SBC-bin-day-group" id="SBCFirstBins">
        <ul><li>blue bin</li><li>food waste</li></ul>
    </div>
    
    <div style="background-color: #f8f8f8; padding: 1.5em; margin: 1.5em 0;">
					<strong style="font-size:1.5em;">Did you know?</strong>
					<p style="margin: 0.5em 0 0;">You can <a href="https://swale.gov.uk/bins-littering-and-the-environment/bins/garden-waste">subscribe to our garden waste collections</a> if you need garden waste collecting regularly</p>
				</div>
    
    <div id="FutureCollections" style="display: block;">
	
				<h2>Future collections</h2>
				
				<p>Put the following bins out by 6am, starting from Friday, 10 January</p>
			
				<ul id="FirstFutureBins"><li>green bin</li><li>food waste</li></ul>
			
    </div>

</div>
```

Needs some more work when I get time but if the Captcha is going to pop up all the time then this is potentially going to stop it working at all.
