### ISSUE TITLE
[Source Request]: Indre Fosen, Norway

### ISSUE THREAD

**Issue by ramana666** [mampfes/hacs_waste_collection_schedule#2361]
### Municipality / Region

Indre Fosen, Norway

### Collection Calendar Webpage

https://fosenrenovasjon.no/tommekalender/#!/main

### Example Address

Fevågsjøen 100

### Collection Data Format

As html on a webpage, Dedicated IOS/Android APP, As PDF Download

**Comment by 5ila5** [comment]
Added in #2362 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
