### ISSUE TITLE
[Feature]: Added support for moje-odpady.pl, Poland

### ISSUE THREAD

**Issue by keysim86** [mampfes/hacs_waste_collection_schedule#2365]
### I propose a feature for:

Sources

### Describe your wanted feature

Please add support for data from the moje-odpady.pl application. The application is used in Poland.

**Comment by 5ila5** [comment]
added in #2368

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
