### ISSUE TITLE
[Bug]: Unknown error after update

### ISSUE THREAD

**Issue by ralfsteck** [mampfes/hacs_waste_collection_schedule#2376]
### I Have A Problem With:

The integration in general

### What's Your Problem

I had WCS up and running with version 1.4.9, now I updated to 2.0.1 . Now I get an "unknown error occurred when I try to start the integration, with my Landratsamt Bodenseekreis as well as with generic/ICS. I renamed the old .yaml, restarted the system, no effect.

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Is ther something in your logs (seetings->system->logs)?

**Comment by ralfsteck** [comment]
sorry, nothing to see there. It fails directly in the second step of the integration setup.

**Comment by 5ila5** [comment]
Just to clarify, you used the YAML configuration and everything works fine, and now you try to move to the GUI configuration method and when configuring the ical source you get the "Unknown error" message?

Did you provide the same arguments in the GUI as in the YAML configuration? Does the YAML configuration still work? if not what are the logs when using the YAML configuration?

**Comment by ralfsteck** [comment]
Hi,

I updated via HACS and since then, the old sensors are unknown. I thought I have to switch to GUI and tried to setup the Integration, bu that ended when I input my "Bodenseereis" with the unknown error.

So, WCS doesn't work anymore for me, neither GUI nor (old) YAML.
Viele Grüße von Unterwegs

*Von: *5ila5 ***@***.***>
*An: *mampfes/hacs_waste_collection_schedule ***@***.***>
*Kopie: *ralfsteck ***@***.***>; Author ***@***.***>
*Datum: *04.08.2024 16:58:25
*Betreff: *Re: [mampfes/hacs_waste_collection_schedule] [Bug]: Unknown error after update (Issue #2376)

**Comment by 5ila5** [comment]
Is there something in the logs If you put the configuration back in your yaml config and restart HA?

HACS sometimes destrois the install (not sure why) did you try to uninstall and reinstall WCS?

**Comment by ralfsteck** [comment]
It says: 

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:364
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 18:55:16 (9 Vorkommnisse)
Zuletzt protokolliert: 18:55:16

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 134, in async_setup_platform
    raise ValueError(
ValueError: source_index 0 out of range (0--1) please check your sensor configuration

**Comment by ralfsteck** [comment]
My YAML

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.bodenseekreis.de/umwelt-landnutzung/abfallentsorgung-privat/termine/abfuhrkalender/export/2024/friedrichshafen/friedrichshafen-b/1,4,5,9,10/ics/
      customize:
        - type: Biotonne
          alias: BioTonne
          icon: mdi:flower-outline
        - type: Gelber Sack
          alias: GelberSack
          icon: mdi:recycle
        - type: Restmüll 2-wöchentlich
          alias: Restmuell
          icon: mdi:trash-can
        - type: Papier 4-wöchentlich
          alias: PapierTonne
          icon: mdi:trash-can-outline
        - type: Gartenabfall
          alias: Gartenabfall
          icon: mdi:tree-outline

sensor:
  - platform: waste_collection_schedule
    name: AbfallRestmuell
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Restmuell

  - platform: waste_collection_schedule
    name: AbfallPapierTonne
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - PapierTonne

  - platform: waste_collection_schedule
    name: AbfallGelberSack
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - GelberSack

  - platform: waste_collection_schedule
    name: AbfallGartenabfall
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Gartenabfall

  - platform: waste_collection_schedule
    name: AbfallRestmuellnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Restmuell

  - platform: waste_collection_schedule
    name: AbfallPapierTonnenext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - PapierTonne

  - platform: waste_collection_schedule
    name: AbfallGelberSacknext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - GelberSack

  - platform: waste_collection_schedule
    name: Gartenabfallnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Gartenabfall
      
  - platform: waste_collection_schedule
    name: AbfallNaechster
    details_format: "upcoming"
    value_template: ' {{ value.daysTo }} '

**Comment by 5ila5** [comment]
Is there Something else in your logs, maybe a bit earlier? As this error message suggests it failed to set up the sensors because there are no sources, maybe you have a corrupted installation, did you try to uninstall (restart) and reinstall (restart) WCS?


Btw. (nothing to do with this error) you can replace the 2024 in your URL with `{%Y}` so it should work the following years as well (as long as they do not change something else in the url)

**Comment by ralfsteck** [comment]
Thanks,  uninstall (restart) and reinstall (restart) did the trick.
