### ISSUE TITLE
[Source Request]: Västervik Miljö & Energi (vmeab.se)

### ISSUE THREAD

**Issue by ckarrie** [mampfes/hacs_waste_collection_schedule#2377]
### Municipality / Region

Västervik, Sweden

### Collection Calendar Webpage

https://www.vmeab.se/tjanster/avfall--atervinning/min-sophamtning/

### Example Address

Gatuadress (Street): Ringsfall 1
Ort (City): Odensvi

### Collection Data Format

As html on a webpage

### Additional Information

Request:
- URL: https://www.vmeab.se/api/WasteDisposal/GetAllPickups
- Method: POST
- Form Data: 
  - `__RequestVerificationToken` : `<the Form Token, see below>`
  - `StreetAddress` : `Ringsfall 1`
  - `City` : `Odensvi`

The Token is given in a hidden input tag inside the form.

```html
<input name="__RequestVerificationToken" type="hidden" value="CfDJ8NeXHi49-VFIgpnxjD8Ox21zllN6f6V2pa5r2KkcMORmt_IuhHzmiT8nPp0vSlX0mbclc59o4E9SA2jwxpIaKii8JidpzRXkbvTmgdyJsSMKWQGTZMKvgOkqkK1TfXueYZbz-X2L-fHU-dtBe6ZBQok">
 ```

**Comment by 5ila5** [comment]
added in #2379

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by ckarrie** [comment]
Bro u are insane fast, thank you!

**Comment by danielholm** [comment]
Tack för denna!
