### ISSUE TITLE
[Source Request]: Whitehorse City Council, Vic, Aus

### ISSUE THREAD

**Issue by bilbotubbins** [mampfes/hacs_waste_collection_schedule#2381]
### Municipality / Region

Whitehorse City Council

### Collection Calendar Webpage

https://map.whitehorse.vic.gov.au/index.html?entity=lyr_waste

### Example Address

2/10 Valonia Avenue SURREY HILLS

### Collection Data Format

As html on a webpage

### Additional Information

https://map.whitehorse.vic.gov.au/weave/services/v1/index/search?start=0&limit=10&indexes=index.property&type=EXACT&crs=EPSG:3857&query=2/10%20val  appears to be used to search 

for the address and the returned URL 

https://map.whitehorse.vic.gov.au/weave/services/v1/feature/getFeaturesByIds?entityId=lyr_vicmap_property&datadefinition=dd_whm_property_address&datadefinition=dd_whm_property_wards&datadefinition=dd_whm_property_waste&ids=208440877&outCrs=EPSG:3857&returnCentroid=false

has the returned details as shown below
 "properties": {
                "dd_whm_property_waste": [
                    {
                        "_id": "208440877",
                        "collectionDay": "Wednesday",
                        "week": 1,
                        "nextRecycle": "14 Aug 2024",
                        "nextGOBS": "07 Aug 2024"

Al

**Comment by 5ila5** [comment]
added in #2382

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
