### ISSUE TITLE
[Bug]: Chilten.gov not working

### ISSUE THREAD

**Issue by guy-BW** [mampfes/hacs_waste_collection_schedule#2383]
### I Have A Problem With:

A specific source

### What's Your Problem

The chiltern.gov.uk service is no longer working. It seems the server is resolving but not answering. I wonder if the site should be changed to https://www.buckinghamshire.gov.uk.

which when I use this site, sends me over to: https://iapp.itouchvision.com/iappcollectionday/collection-day

I then need to provide postcode/address

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
We already have an Itouchvision source, but it looks like the Buckinghamshire site is not really supported as they use another API and just using the "old" one seems to not work either (which did work with Newport)

**Comment by 3dogzzz** [comment]
I have the same issue with the same source. Stopped working some time this week.

**Comment by craigsblackie** [comment]
Nothing useful, but experiencing the same here.

**Comment by wzorektom** [comment]
Chiltern.gov.uk now redirects to buckinghamshire.gov.uk.

**Comment by MarkRS-UK** [comment]
What's the next step for this?  I'm happy to help, either technically or "locally" (I'm in the Chiltern/Bucks district), if that's any use.

**Comment by craigsblackie** [comment]
I've got the following code that will decrypt and encrypt the parameters that are sent/returned by the serice:


`import sys
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
import binascii

# Encryption function
def encrypt_aes(plaintext):
    # Convert the key and IV hex strings to bytes
    key = binascii.unhexlify("F57E76482EE3DC3336495DEDEEF3962671B054FE353E815145E29C5689F72FEC")
    iv = binascii.unhexlify("2CBF4FC35C69B82362D393A4F0B9971A")

    # Convert plaintext to bytes and pad it
    data = plaintext.encode('utf-8')
    padded_data = pad(data, AES.block_size)

    # Create the AES cipher object
    cipher = AES.new(key, AES.MODE_CBC, iv)

    # Encrypt the padded data
    ciphertext = cipher.encrypt(padded_data)

    # Convert the ciphertext to hex and return it
    return binascii.hexlify(ciphertext).decode('utf-8')

# Decryption function
def decrypt_aes(ciphertext_hex):
    # Convert the key and IV hex strings to bytes
    key = binascii.unhexlify("F57E76482EE3DC3336495DEDEEF3962671B054FE353E815145E29C5689F72FEC")
    iv = binascii.unhexlify("2CBF4FC35C69B82362D393A4F0B9971A")
    ciphertext = binascii.unhexlify(ciphertext_hex)

    # Create the AES cipher object
    cipher = AES.new(key, AES.MODE_CBC, iv)

    # Decrypt the ciphertext
    decrypted_data = cipher.decrypt(ciphertext)

    # Unpad the decrypted data and convert it back to a string
    plaintext = unpad(decrypted_data, AES.block_size).decode('utf-8')

    return plaintext

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python script.py <encrypt|decrypt> <text>")
        sys.exit(1)

    action = sys.argv[1].lower()
    input_text = sys.argv[2]

    if action == "encrypt":
        encrypted_text = encrypt_aes(input_text)
        print("Encrypted data:", encrypted_text)
    elif action == "decrypt":
        decrypted_text = decrypt_aes(input_text)
        print("Decrypted data:", decrypted_text)
    else:
        print("Invalid action. Use 'encrypt' or 'decrypt'.")
`

**Comment by craigsblackie** [comment]
I have now created a pull request (sorry if this is all wrong) with the fixed source.

**Comment by 5ila5** [comment]
Thanks to the reverse engineering work of @craigsblackie this now works.

You can now use the iapp_itouchvision_com source. The chiltern_gov_uk source does work but will show a warning in your logs to move to the iapp_itouchvision_com source. GUI configuration should be moved to the iapp_itouchvision_com source automatically.

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by magicmayhem** [comment]
Doesn't work for me, I've tried to set this in the configuration.yaml

waste_collection_schedule:
  sources:
    - name: iapp_itouchvision_com
      args:
        uprn: *************

and also the GUI

![image](https://github.com/user-attachments/assets/e670dc57-d8fb-4c77-8519-f9993526e697)

**Comment by 5ila5** [comment]
Looks like you do not use the master version. This is not yet part of a release, so you need to change to the master (development) version. The iapp_itouchvision_com needs a municipality argument

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by MarkRS-UK** [comment]
That's fabulous.  Thanks for the extra info about installing it with HACS 2+.

In this case the "next collection type" seems to include type and day while "next" contains nothing.  Is that right?

**Comment by magicmayhem** [comment]
Now working!!!! That's brilliant. I didn't even know you could do that in home assistant.
