### ISSUE TITLE
[Source Request]: Falkenberg, Sweden not working

### ISSUE THREAD

**Issue by DJKatastrof** [mampfes/hacs_waste_collection_schedule#2386]
### Municipality / Region

Falkenberg, Sweden

### Collection Calendar Webpage

https://vivab.se/%C3%A5tervinning-avfall/hushallsavfall/vara-abonnemang/h%C3%A4mtning-av-hush%C3%A5llsavfall

### Example Address

Storgatan 1, Falkenberg

### Collection Data Format

Something different (add to additional information)

### Additional Information

Hi!

I noticed that VIVAB Varberg is working fine. But not any streets in Falkenberg.
Would appriciate if we can make this work :)

**Comment by 5ila5** [comment]
fixed in #2389 
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by DJKatastrof** [comment]
I just tried the master, same error im afraid.
It still says 2.0.1 in the top left even after a fully restart.
But I can wait for the next release, appriciate the help. 👍

**Comment by 5ila5** [comment]
You're right, I tested it with `Storgatan 1, FALKENBERG` which worked.
Second try of fixing this in #2391

**Comment by DJKatastrof** [comment]
Hi! 
Just tried again, neither Storgatan 1, Falkenberg or Östergränd 4, Falkenbergis working now.
Anything else you want me to try?

**Comment by 5ila5** [comment]
`Storgatan 1, FALKENBERG` and `Östergränd 4, Falkenberg` work and do return values:

 ```
 found 2 entries for Falkenberg: Storgatan 1
    2024-08-08 : Hushåll [mdi:trash-can]
    2024-08-08 : Mat [mdi:food-apple]
  found 1 entries for Falkenberg: Östergränd 4
    2024-08-14 : Hushåll [mdi:trash-can]
```

Sometimes HACS does some weird things. Recheck that you're on the latest master branch and check your logs.

**Comment by DJKatastrof** [comment]
Ah, had to remove it again and install.
After picking Östergränd 4 now, I got these empty options,
![image](https://github.com/user-attachments/assets/6de927af-34a8-424d-bd2e-b986fa8eb27d)

**Comment by DJKatastrof** [comment]
If an adress got two options, which one does it pick?

**Comment by 5ila5** [comment]
It just takes the first one, I did not know this can happen, What should be the expected behaviour?

**Comment by DJKatastrof** [comment]
In somewhere cases there are two households with different volume of waste bin and different dates. 
it’s not a speed bump but would be cool it you could pick from a menu which one is yours

**Comment by 5ila5** [comment]
I added the ability to provide the building_number as argument in #2411

**Comment by DJKatastrof** [comment]
Hi!

Working great now! 
Thank you for the fast help!! :)
