### ISSUE TITLE
[Source Request]: RD4, The Netherlands

### ISSUE THREAD

**Issue by aimbot-luc** [mampfes/hacs_waste_collection_schedule#2392]
### Municipality / Region

Heerlen, The Netherlands

### Collection Calendar Webpage

https://mijn.rd4.nl/afvalkalender

### Example Address

ZIP code: 6417 AT
Number: 32

### Collection Data Format

As html on a webpage, As PDF Download

### Additional Information

Hi, RD4 does not only waste collection in Heerlen but also: Beekdaelen, Brunssum, Eijsden-Margraten, Gulpen-Wittem, Heerlen, Kerkrade, Landgraaf, Simpelveld, Vaals and Voerendaal. You will need a ZIP code and house number to get the correct calendar. I hope the data can be extracted from the site, thanks in advance!

**Comment by 5ila5** [comment]
Added in #2393

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
