### ISSUE TITLE
[Source Request]: Charnwood Borough Council, UK

### ISSUE THREAD

**Issue by Bodfrey** [mampfes/hacs_waste_collection_schedule#2396]
### Municipality / Region

UK, Charnwood Borough Council

### Collection Calendar Webpage

https://my.charnwood.gov.uk/

### Example Address

2 Went Road, Birstall, LE4 3BG

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
added in #2402 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
