### ISSUE TITLE
[Source Request]:  Austria - Abfuhrplaene Mayer

### ISSUE THREAD

**Issue by ChiliApple** [mampfes/hacs_waste_collection_schedule#2397]
### Municipality / Region

Austria

### Collection Calendar Webpage

https://www.mayer-recycling.at/abfuhrplaene

### Example Address

https://58137901-e99c-439f-a523-d74348c63dcf.filesusr.com/ugd/5b01c5_c063e8b28f784af3b8225360a50cc00a.ics?dn=Kalender%20von%20Kammern.ics

### Collection Data Format

As ICS/ICAL file

### Additional Information

Hi, thx for your work!

best Udo

**Comment by 5ila5** [comment]
Abfuhrplaene Mayer is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2400 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/mayer_recycling_at.md)
