### ISSUE TITLE
[Bug]: list index out of range when adding a location in Switzerland

### ISSUE THREAD

**Issue by zuerom** [mampfes/hacs_waste_collection_schedule#2399]
### I Have A Problem With:

A specific source

### What's Your Problem

I'm trying to add from the list A-Region the location Speicher but i receive the following error:
Die Quelle hat eine ungültige Antwort zurückgegeben: "list index out of range". Bitte überprüfe die Argumente und versuche es erneut.
![image](https://github.com/user-attachments/assets/0271089d-91ab-4e18-ad2c-521f3581b4d2)

even when i try to use another location

regards
zuerom

### Source (if relevant)

most recent version

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Should be fixed by #2403 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
