### ISSUE TITLE
Vöhl

### ISSUE THREAD

**Issue by faye473** [mampfes/hacs_waste_collection_schedule#2401]
### Municipality / Region

Vöhl, Waldeck Frankenberg, Germany

### Collection Calendar Webpage

https://www.voehl.de/index.php/aktuelles/muellabfuhrtermine

### Example Address

Kalender für die Ortsteile Asel, Asel-Süd, Basdorf, Buchenberg, Ederbringhausen, Harbshausen, Herzhausen, Kirchlotheim, Niederorke, Oberorke, Schmittlotheim, Thalitter

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
Is there some other way to get the dates than the PDF one? I could not find one, and PDF parsing is something we currently do not do.

**Comment by faye473** [comment]
yes here https://lobbe.app/ you can get I call fornat.
Statt: Hessen
Town: Vöhl
Stress: Zur Aselbucht.

Regard.
Faye

**Comment by 5ila5** [comment]
Added in #2410

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by faye473** [comment]
Ok thanks you very much

5ila5 ***@***.***> schrieb am Fr. 9. Aug. 2024 um 13:45:
