### ISSUE TITLE
[Bug]: Whittlesea - The Integration could not be loaded.

### ISSUE THREAD

**Issue by XeKToReX** [mampfes/hacs_waste_collection_schedule#2407]
### I Have A Problem With:

A specific source

### What's Your Problem

After the API changes recently, I have moved to the master branch to reconfigure my whittlesea_vic_gov_au source.

When attempting to configure the source, I get the following error after running through the configuration, I am not making changes to the sensors etc (ie. not ticking either box)

**Success!
Created configuration for Whittlesea City Council.

The integration could not be loaded, try to restart Home Assistant.**

Opening the integration, I get the following:

**Hubs
Whittlesea City Council
No devices or entities
Not loaded**

My current version is: master 44c320d

### Source (if relevant)

whittlesea_vic_gov_au

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
- Is there something in your logs?
- Did you make sure that your address parameter exactly matches the auto complete result of https://www.whittlesea.vic.gov.au/My-Neighbourhood?
- Did you already try to uninstall and reinstall WCS?

**Comment by 5ila5** [comment]
`street_number` is not a valid parameter for this source anymore (after changes made in #2326) it looks like you set up the integration using YAML configuration and still use the old parameters `suburb`, `street_name`, `street_number` and `postcode` instead of the only valid parameter now: `street_address`.

Check your configuration.yaml and remove this entry if you use the GUI setup now

**Comment by XeKToReX** [comment]
I had a feeling it would be something stupid, I don't recall ever setting it up via YAML but there it is.

Removing existing config has fixed the issue.

Now to figure out how to get my old attributes back!
