### ISSUE TITLE
[Source Request]: For Germany 38527 Meine / Papenteich

### ISSUE THREAD

**Issue by MasterSerenus** [mampfes/hacs_waste_collection_schedule#2413]
### Municipality / Region

Meine, Germany

### Collection Calendar Webpage

https://www.abfallkalender-gifhorn.de/2024/

### Example Address

Braunschweiger Str.3, 38527 Meine, Germany

### Collection Data Format

As ICS/ICAL file

### Additional Information

My E-Mail Adress : o.gruse@t-online.de

Please notify me when you have added the location. Thank you in advance. Best regards

**Comment by 5ila5** [comment]
Added in #2419 
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by MasterSerenus** [comment]
Thank you very much for the quick implementation. It worked "grin face"
