### ISSUE TITLE
[Source Request]: antrim and newtownabbey

### ISSUE THREAD

**Issue by trackermb** [mampfes/hacs_waste_collection_schedule#2416]
### Municipality / Region

United Kingdom

### Collection Calendar Webpage

https://antrimandnewtownabbey.gov.uk/residents/bins-recycling/bins-schedule/

### Example Address

rose park 

### Collection Data Format

As html on a webpage

### Additional Information

Both Black and Brown bins are collection on same day

**Comment by 5ila5** [comment]
Added in #2421

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
