### ISSUE TITLE
[Bug]: Can't Add Integration - The source returned an invalid response

### ISSUE THREAD

**Issue by Loeffelmaster** [mampfes/hacs_waste_collection_schedule#2423]
### I Have A Problem With:

A specific source

### What's Your Problem

I want to add the integration, but I can't. When I try to add it for
Stadt Overath
Strasse: Lorkenhöhe

I get the following error:
`The source returned an invalid response: "500 Server Error: Internal Server Error for url: https://web.c-trace.de/overathabfallkalender/(S(bk2sxasn4fsmk2ghhaxjkkip))/abfallkalender/cal?Ort=&Gemeinde=&Strasse=Lorkenhoehe&Hausnr=26&Abfall=0%7C1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7C10%7C11%7C12%7C13%7C14%7C15%7C16%7C17%7C18%7C19%7C20%7C21%7C22%7C23%7C24%7C25%7C26%7C27%7C28%7C29%7C30%7C31%7C32%7C33%7C34%7C35%7C36%7C37%7C38%7C39%7C40%7C41%7C42%7C43%7C44%7C45%7C46%7C47%7C48%7C49%7C50%7C51%7C52%7C53%7C54%7C55%7C56%7C57%7C58%7C59%7C60%7C61%7C62%7C63%7C64%7C65%7C66%7C67%7C68%7C69%7C70%7C71%7C72%7C73%7C74%7C75%7C76%7C77%7C78%7C79%7C80%7C81%7C82%7C83%7C84%7C85%7C86%7C87%7C88%7C89%7C90%7C91%7C92%7C93%7C94%7C95%7C96%7C97%7C98". Please check the provided arguments and try again.`

I also tried Lorkenhöhe as Lorkenhoehe and Lorkenhohe, but the error stays the same.
When I try another street (Landwehr) it works. 
Manually entering the information to the website
https://web.c-trace.de/overathabfallkalender/(S(bk2sxasn4fsmk2ghhaxjkkip))/abfallkalender
brings up a result.

When I enter the link of the website shown in the error manually, I get a runtime error.

### Source (if relevant)

overathabfallkalender

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
Source: overathabfallkalender
Street: Lorkenhöhe
Sensor: I don't get that far.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Your error message looks like you did not set the ort value to `Overath`

**Comment by Loeffelmaster** [comment]
That worked. I haven't entered ort because it was stated as optional.
