### ISSUE TITLE
[Source Request]: Obertshausen, Germany

### ISSUE THREAD

**Issue by Larrysansan97** [mampfes/hacs_waste_collection_schedule#2427]
### Municipality / Region

Obertshausen

### Collection Calendar Webpage

https://obertshausen.mein-abfallkalender.online/ical.ics?sid=20115&cd=attachment&ft=6&fu=ical_download&fp=next_1000&wids=581,538,542,539,537,535,536,540,543,541&uid=119206&pwid=94e34ed4c9&cid=82&fn=Mein-Abfallkalender_Stadt_Obertshausen_Zukünftige_Termine.ics

### Example Address

Rathenaustraße

### Collection Data Format

As ICS/ICAL file

### Additional Information

download as ics

**Comment by 5ila5** [comment]
Obertshausen is already supported by the ICS source with documentation on how-to set it up in the [mein_abfallkalender_online ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/mein_abfallkalender_online.md) 

I just renamed the source from _de to _online in #2439
