### ISSUE TITLE
RSAG Abfallkalender

### ISSUE THREAD

**Issue by Cyrelion** [mampfes/hacs_waste_collection_schedule#244]
Would be great to get https://www.rsag.de/abfallkalender implemented too.

**Comment by FaserF** [comment]
Should be possible with Generic ICS File implementation already: 
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md

**Comment by Cyrelion** [comment]
That’s correct, but automation would be great to not forget to change the ics every year

**Comment by mampfes** [comment]
RSAG is suupported by muellmax_de
