### ISSUE TITLE
[Source Request]: Worcestershire

### ISSUE THREAD

**Issue by ItsBlacksmith** [mampfes/hacs_waste_collection_schedule#2442]
### Municipality / Region

Malvern / Worcestershire / United Kingdom

### Collection Calendar Webpage

https://swict.malvernhills.gov.uk/mhdcroundlookup/HandleSearchScreen

### Example Address

16 Bronsil Drive, WR14 1LR

### Collection Data Format

As html on a webpage, As PDF Download

### Additional Information

https://www.malvernhills.gov.uk/?option=com_fileman&view=file&routed=1&name=Annual%20Bin%20Collection%20Calendar%202023-24.pdf&folder=Documents%2FWaste%20and%20Recycling&container=fileman-files

**Comment by 5ila5** [comment]
added by #2443

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
