### ISSUE TITLE
[Source Request]: City of Orillia, Ontario, Canada

### ISSUE THREAD

**Issue by davehahn** [mampfes/hacs_waste_collection_schedule#2446]
### Municipality / Region

Orillia / Ontario / Canada

### Collection Calendar Webpage

https://orillianow.orillia.ca/dashboard

### Example Address

139 Fittons rd, West, L3V3V3

### Collection Data Format

As html on a webpage

### Additional Information

Requires an account where it stores your address

**Comment by 5ila5** [comment]
Added in #2448, You need an account [there](https://orillianow.orillia.ca/dashboard)

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by davehahn** [comment]
Man you are fast, This is amazing
