### ISSUE TITLE
[Bug]: schedular grabs calendar from next season, not the actual one

### ISSUE THREAD

**Issue by ptC7H12** [mampfes/hacs_waste_collection_schedule#2449]
### I Have A Problem With:

A specific source

### What's Your Problem

I'm using the waste_collections with the source bielefeld_de. What happend now ist, that over night the source might have changed and I'm now only getting calender items for the next season:
![image](https://github.com/user-attachments/assets/78f67d1e-538d-425d-aa06-c7cb2098d3e1)
You can see, that the remaining days changed from 9 to 52. The same happend to all other waste types.

Is it possible to choose the source? As when accessing the application via the browser to get the ical file it lets me choose to get the season 2023/2024 or 2024/2025.

### Source (if relevant)

bielefeld_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
fixed in #2458, the new implementation will try to get all available seasons

**Comment by ptC7H12** [comment]
@5ila5 thank you very much! Works like a charm!!!
