### ISSUE TITLE
Add Roslagsvatten to EDPEvent

### ISSUE THREAD

**Issue by ScanEarth** [mampfes/hacs_waste_collection_schedule#2455]
### Municipality / Region

Ekerö, Vaxholm, Österåker

### Collection Calendar Webpage

https://edpmypage.roslagsvatten.se/FutureWebOS/SimpleWastePickup

### Example Address

Andromedavägen 1, Åkersberga

### Collection Data Format

As html on a webpage, As PDF Download

### Additional Information

For Sweden:
Add Roslagsvatten to [EDPEvent - Multi Source]

Url to page: https://edpmypage.roslagsvatten.se/FutureWebOS/SimpleWastePickup

company services the areas:
Ekerö
Vaxholm
Österåker

**Comment by 5ila5** [comment]
added in #2459 
You can already use it by providing the url `https://edpmypage.roslagsvatten.se/FutureWebOS/SimpleWastePickup` and leave service_provider empty

you will be able to use the service_provider argument after the next release or now by using the master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by ScanEarth** [comment]
Yes I know, that's how I tested before making the request. ☺️
