### ISSUE TITLE
[Bug]: Shows wrong pickup dates

### ISSUE THREAD

**Issue by MRDonnii** [mampfes/hacs_waste_collection_schedule#2461]
### Municipality / Region

Denmark

### Example Address

I have a problem that my wast shows 14 days until enmty, but i get my waste collected every 7 days, when they pick up the waste my sensor resets to 14 days again

### Collection Data Format

Something different (add to additional information)

### Additional Information

i use the Home assistant intergration

**Comment by MRDonnii** [comment]
The source is renoweb, randers, hyacintvej 5

And yes it lookes like its getting the wrong info, i just set it up from the Gui.

What more can i supply u with?

**Comment by 5ila5** [comment]
The values returned by the source seem to be fine and match the PDF shown on the [website](https://randers.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx) and include waste results from just a few days from now. The website says waste is collected in a 14 day rhythm.

But there seem to be an address conflict:

The address search returns two address when just providing `hyacintvej 5`:

- Hyacintvej 5, 8930 Randers NØ (Ejd.nr. 12762, BFE.nr. 5610890)
- Hyacintvej 5, 8870 Langå (Ejd.nr. 31950, BFE.nr. 4005492)

And the address search will always pick the first one, If you need the second one you should provide address as `hyacintvej 5 Langå` (waste is collected once a week there.)

This does not explain the resetting back to 14 days, Is this behaviour reflected in your calendar tab as well? (collection shown in ~14 days and resets to another place after 7)?

**Comment by MRDonnii** [comment]
You are a god :D Thank u so much for the help!!!
