### ISSUE TITLE
[Bug]: The source returned an invalid response: "time data 'Wed 21 August 2024' does not match format '%A %d %B %Y'"

### ISSUE THREAD

**Issue by djlalpha** [mampfes/hacs_waste_collection_schedule#2473]
### I Have A Problem With:

A specific source

### What's Your Problem

Getting the following error message when trying to submit my set up.  "The source returned an invalid response: "time data 'Wed 21 August 2024' does not match format '%A %d %B %Y'". Please check the provided arguments and try again."
![Screenshot from 2024-08-16 18-53-53](https://github.com/user-attachments/assets/415cee58-a554-4def-abc2-bb3717fa1497)

### Source (if relevant)

South Kesteven

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
N/A
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
this was already fixed in #2462

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
