### ISSUE TITLE
[Source Request]: Coburg Stadt

### ISSUE THREAD

**Issue by HighStairs** [mampfes/hacs_waste_collection_schedule#2476]
### Municipality / Region

Stadt Coburg, Deutschland

### Collection Calendar Webpage

https://ceb-coburg.de/04_Stadtreinigung-Abfall/Abfallentsorgung-Recycling/Abfallbehaelter/muellabfuhrkalenderv2.php?s=Hohe+Stiege

### Example Address

Hohe Stiege 3, 96450 Coburg

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in #2482 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
