### ISSUE TITLE
[Source Request]: ASTO / Abfall- Sammel- und Transportverband Oberberg 

### ISSUE THREAD

**Issue by ppuschmann** [mampfes/hacs_waste_collection_schedule#2478]
### Municipality / Region

Oberbergischer Kreis, Germany

### Collection Calendar Webpage

https://www.asto.de/abfallkalender/2024/abfallkalender-jahresdetail

### Example Address

- An der Ziegelei, Wipperfürth
- Egener Straße, Wipperfürth

### Collection Data Format

As ICS/ICAL file, As PDF Download, Something different (add to additional information)

### Additional Information

Asto is serving only these cities in the region "Oberbergischer Kreis":
- Bergneustadt
- Gummersbach
- Marienheide
- Waldbröhl
- Wiehl
- Wipperfürth

In each city you've to look up the information for the street, of course, because collection dates vary. PDF-files and iCal-Links are generated on the webpage.

The iCal-Links are quite gibberish and I fear an API does not exist, but I'll reach out to them.

**Comment by 5ila5** [comment]
Looks like the ICal files are pretty static so I added documentation on how to use asto.de with the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) in #2483 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/asto_de.md)
