### ISSUE TITLE
[Dev] Dev testing new sources?

### ISSUE THREAD

**Issue by greghesp** [mampfes/hacs_waste_collection_schedule#248]
Is there a way we can run new source scripts without installing this into HA?

I'd like to add a few more sources, but they require BeautifulSoup scraping, so being able to code, run and use Logger would be great.

I tried running the script directly, but some of the local imports don't seem to work.

New to Python, more of a Javascript coder myself, but willing to give this a go if I can get the environment working

**Comment by mampfes** [comment]
Yes, there is :-)

https://github.com/mampfes/hacs_waste_collection_schedule#debugging
