### ISSUE TITLE
[Source Request]: La Jarrie, France

### ISSUE THREAD

**Issue by SebNania** [mampfes/hacs_waste_collection_schedule#2486]
### Municipality / Region

La Jarrie, France

### Collection Calendar Webpage

https://www.lajarrie.fr/wp-content/uploads/2024/02/A5-Calendrier-La-Jarrie_Page_1-1.png

### Example Address

1 place de la mairie,
17220 La Jarrie, France

### Collection Data Format

As html on a webpage

### Additional Information

Hi,
For La Jarrie, we have 2 waste collector type : 
Yellow (jaune) for recycling (paper, plastics) and Blue for other wastes
I've put the direct link for the image containing the calendar.
Yellow are collected every Monday at 1 PM
Blue are collected every thursday at 5 AM
Thanks in advance
Feel free to ask me if some complementary information needed
Sebastien

**Comment by 5ila5** [comment]
We cannot parse the image if there are no other way to find the collection dates, you're best of using the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

**Comment by SebNania** [comment]
Thank you for your answer, i will see that thanks a lot
