### ISSUE TITLE
[Source Request]: Switzerland, Zug, Cham

### ISSUE THREAD

**Issue by xFox13x** [mampfes/hacs_waste_collection_schedule#2494]
### Municipality / Region

Switzerland, Cham

### Collection Calendar Webpage

https://www.zeba.sammelkalender.ch/

### Example Address

Zugerstrasse 5, 6330 Cham

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added by #2500

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
