### ISSUE TITLE
Script crashes

### ISSUE THREAD

**Issue by GLehnhoff** [mampfes/hacs_waste_collection_schedule#25]
Hi all, I am pretty new to HA and so far have successfully integrated what HA found in my local network (Hue, Fritzbox, ...). I started creating my own screen and would like to have the waste calendar of MüllerMax/Hanau integrated. The python-script to create the correct files (or the source) crashes, first as of the German characters (e.g. in the name of the cities, I changed that), secondly in line 108:

glehnhoff@TUXEDO:~/Schreibtisch/glehnhoff/Dokumente/SmartHome/Home Assistant$ python muellmax_de.py
  File "muellmax_de.py", line 108
    url = f"https://www.muellmax.de/abfallkalender/{answers['service'].lower()}/res/{answers['service']}Start.php"

(a) I do not mind adding this service manually, I even downloaded an ics-file, but I don't know how.
(b) I would expect that I have to download an add-on from somewhere before I add any code to any configuration.yaml, and so on.

Honestly, I am reading documentations since days and did not get any more clever (and HA documentations are not the best for users; maybe for developers they are).

Would be great if someone is able to help.

Gerhard Lehnhoff
public@GLehnhoff.de

**Comment by mampfes** [comment]
Hi Gerhard, which python version is called if you run `python`? Please try:

`python3 muellmax_de.py` to ensure that python 3 is called.

Secondly, please post error message if the error persists.

Regards

Steffen

**Comment by GLehnhoff** [comment]
Hi Steffen,

with a different computer I get a different result. Here we are:

Python-Version: Python 3.6.9 (default, Oct  8 2020, 12:12:24), [GCC 8.4.0] on linux

glehnhoff@TUXEDO:~/Dokumente/SmartHome/Home Assistant$ python3 muellmax_de.py
Traceback (most recent call last):
  File "muellmax_de.py", line 5, in <module>
    import inquirer
ModuleNotFoundError: No module named 'inquirer'
glehnhoff@TUXEDO:~/Dokumente/SmartHome/Home Assistant$

**Comment by mampfes** [comment]
You have to install the missing Python package:
`pip3 install inquirer`
But unfortunately inquirer is not available on Windows, therefore you need a Linux box. If you don't have access to an Linux box, you can also send me your address data via PN (via Home Assistant Forum).

**Comment by GLehnhoff** [comment]
Well, 'pip3' was not installe. I googled and installed:
- sudo apt install python3-pip
- pip3 install inquirer
- python3 muellmax_de.py

Worked. Outcome:

Copy the following statements into your configuration.yaml:

# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: His
        mm_frm_str_sel: Hadrianstraße

Thanks, Steffen, so far, so good, I will try the complete process again. 

Question: your waste_collection_schedule is looking for the data online, correct? I currently have downloaded an ics-file from MüllerMax which is valid half a year only.

**Comment by mampfes** [comment]
Yes, waste_collection_schedule fetches the schedule every day from your service provider.

**Comment by mampfes** [comment]
Is it working for you now?

**Comment by GLehnhoff** [comment]
Steffen, I probably will give it a new run this week, I'll keep you informed. This issue, however, was for the crashing script. The script works. I am not sure, what the policy is, but as this problems is solved, I might close this issue.
