### ISSUE TITLE
[Bug]: City of Oklahoma City okc_gov fetch failed

### ISSUE THREAD

**Issue by joshnewman17** [mampfes/hacs_waste_collection_schedule#2503]
### I Have A Problem With:

A specific source

### What's Your Problem

Was excited to see my city is supported but unfortunately it looks like it's currently not functioning for me. Attempting initial setup and receiving the error in the attached logs.

### Source (if relevant)

okc_gov

### Logs

```Shell
fetch failed for source City of Oklahoma City: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/okc_gov.py", line 43, in fetch json_data = json.loads(r.text) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/okc_gov.py", line 45, in fetch raise Exception("Invalid response returned from data.okc.gov") from e Exception: Invalid response returned from data.okc.gov
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: okc_gov
      args:
        objectID: "1111111"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by joshnewman17** [comment]
<img width="335" alt="Screenshot 2024-08-19 at 5 19 56 PM" src="https://github.com/user-attachments/assets/73f603a8-92b8-41f5-909a-0dc792c9210d">
Update - I confirmed searching my objectID on the site is functional, but it looks like they're blocking downloading the data, so if this is how it gets captured it seems like this is likely a change on their side that broke it.

**Comment by 5ila5** [comment]
Yes this would probably be fine, But it does work again for me, and I do not get an Incapsula message anymore

**Comment by sanctas** [comment]
> Yes this would probably be fine, But it does work again for me, and I do not get an Incapsula message anymore

Mine hasn't worked for months. I just assumed it was a "me" thing and didn't troubleshoot further. I was updating my dashboard this week and saw this issue on GitHub and realized it wasn't just me. 

Anyway, I made a drop-in replacement for the URL: https://okc.schizo.dev/trash?recordID=

Just add that line into the code.

I've never made a pull request so I'm not really sure how to do it, to be honest.

**Comment by 5ila5** [comment]
Thanks for that.
The old one seems to work again, so I would keep this and replace the url if this happens again

**Comment by sanctas** [comment]
> Thanks for that.
> 
> The old one seems to work again, so I would keep this and replace the url if this happens again

Official API still doesn't work for me, FYI.

May be a regional thing or something, not sure. You could maybe add it as a fallback if the main URL fails.

**Comment by 5ila5** [comment]
You're right now I have the problem again, not sure when this triggers but

```sh
curl "https://okc.schizo.dev/trash?objectID=1935340"
# returns

{"status":"error","code":502,"message":"Application failed to respond","request_id":"W7Dgxx7_QeqtNh5Uwp2dFg_3500563535"}%
```

**Comment by sanctas** [comment]
Yeah, I slapped this code together in like 10 minutes. I need to add some error handling. I'll restart the server. 

But according to the okc_gov.py the parameter should be recordID, not objectID.

**Comment by 5ila5** [comment]
This source now uses the unofficial server by @sanctas

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by Telain** [comment]
I was unable to connect with the unofficial server. Could it be duplicated to support both? The official server always worked for me, I just have to open the data page from my PC periodically to pass the incapsula check. I set a notification when the schedule shows unavailable to keep on it.

For now, I'm rolled back to the previous version, but it'd be nice to be able to stay up to date.

**Comment by 5ila5** [comment]
I added the option to use the official server in #2754 
This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by sanctas** [comment]
I have permanently fixed the issues with the unofficial server and it should continue to work without any problems.

**Comment by Banthaf0dder** [comment]
Hello, I am currently receiving this error when trying to set this up using this unofficial source in HA.

<img width="573" height="756" alt="Image" src="https://github.com/user-attachments/assets/08e1fe68-cc93-4fa1-8f12-a121949d5ddd" />

When I go to this URL (recordID obfuscated) https://okc.schizo.dev/trash?recordID=####### I receive the following error message.

{"error":"Internal Server Error","message":"An unexpected error occurred"}

**Comment by Banthaf0dder** [comment]
> I have permanently fixed the issues with the unofficial server and it should continue to work without any problems.

Hello, I appreciate your work on this as I have struggled to get past the Incapsula filter myself. However, I am currently receiving this error when trying to set this up using this unofficial source in HA.

<img width="573" height="756" alt="Image" src="https://github.com/user-attachments/assets/08e1fe68-cc93-4fa1-8f12-a121949d5ddd" />

When I go to this URL (recordID obfuscated) https://okc.schizo.dev/trash?recordID=####### I receive the following error message.

{"error":"Internal Server Error","message":"An unexpected error occurred"}

**Comment by sanctas** [comment]
Fixed by restarting the server. Will investigate the error if it happens again. Please confirm it is working on your end. My address is working as expected now. 

#4567

**Comment by Banthaf0dder** [comment]
> Fixed by restarting the server. Will investigate the error if it happens again. Please confirm it is working on your end. My address is working as expected now.
> 
> [#4567](https://github.com/mampfes/hacs_waste_collection_schedule/issues/4567)

Working great now!
