### ISSUE TITLE
[Source Request]:  Niagara on the Lake

### ISSUE THREAD

**Issue by j2deen** [mampfes/hacs_waste_collection_schedule#2504]
### Municipality / Region

Niagara on the Lake, Ontario, Canada

### Collection Calendar Webpage

https://www.niagararegion.ca/waste/collection/schedule/default.aspx

### Example Address

665 King Street, Niagara-on-the-Lake

### Collection Data Format

As ICS/ICAL file

### Additional Information

Thank you.

**Comment by 5ila5** [comment]
They use recollect there is documentation on how to use the ICS source with recollect [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md)
If you use the GUI you need to select country custom -> ICS or USA -> recollect. You will be able to select canada -> Nigara Region in the next version as I added it to recollect in #2509
