### ISSUE TITLE
[Bug]: Filtered Sensors doesnt show value.daysTo

### ISSUE THREAD

**Issue by ckarrie** [mampfes/hacs_waste_collection_schedule#2506]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

I have some problems getting filtered sensors working (showing left days).

What I have done: I added a new sensor to existing source, set template value to `{{ value.daysTo }}` and filter to "Restmüll" (tried adding other sensors with different filters). The template value `{{ value.daysTo }}` only works for the initial added sensor (without any filter).

Screenshots:
![image](https://github.com/user-attachments/assets/4dc89a30-4846-4361-b8f1-19a84bbd48f7)

Configuration, selected a new created sensor:
![image](https://github.com/user-attachments/assets/8389f0d0-8061-4656-b463-d6439749d512)

On the sensor popup:
![image](https://github.com/user-attachments/assets/5d28290c-ef21-419d-b031-753e566e4b00)
![image](https://github.com/user-attachments/assets/257bb47b-7d00-4c72-9eb6-a9d6493e5f47)

Values:
![image](https://github.com/user-attachments/assets/90ed161e-741e-4fbe-9672-68b93eb35d85)

The initial added sensor works fine:
![image](https://github.com/user-attachments/assets/71039584-99c6-4e4b-9a6f-786577ae2329)

section from .storage/core.config_entries:
```json
{
        "created_at": "1970-01-01T00:00:00+00:00",
        "data": {
          "name": "abfallwirtschaft_germersheim_de",
          "args": {
            "city": "Winden",
            "street": ""
          }
        },
        "disabled_by": null,
        "domain": "waste_collection_schedule",
        "entry_id": "01J3CWT9ZG98B8C3BMRRX593P0",
        "minor_version": 1,
        "modified_at": "2024-08-19T19:06:02.079373+00:00",
        "options": {
          "calendar_title": "Abfallwirtschaft Germersheim",
          "separator": ", ",
          "fetch_time": "01:00",
          "random_fetch_time_offset": 60,
          "day_switch_time": "10:00",
          "sensor_select": [
            "Winden Müll Bioabfall"
          ],
          "customize": {
            "Restmüll ": {
              "show": true
            },
            "Heckenschnitt ": {
              "show": true
            },
            "Bioabfall ": {
              "show": true
            },
            "Papier ": {
              "show": true
            },
            "Gelber Sack ": {
              "show": true
            },
            "Glasbox ": {
              "show": true
            }
          },
          "sensors": [
            {
              "name": "Abfall Sensor 1",
              "details_format": "upcoming",
              "value_template": "{{ value.daysTo }}",
              "add_days_to": false
            },
            {
              "name": "Winden Müll Restmüll",
              "details_format": "upcoming",
              "value_template": "{{ value.daysTo }}",
              "types": [
                "Restmüll "
              ]
            },
            {
              "name": "Winden Müll Glasbox",
              "details_format": "upcoming",
              "value_template": "{{ value.daysTo }}",
              "types": [
                "Glasbox "
              ]
            },
            {
              "name": "Winden Müll Bioabfall",
              "details_format": "upcoming",
              "value_template": "{{ value.daysTo }}",
              "types": [
                "Bioabfall "
              ],
              "event_index": 0
            }
          ]
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "title": "Abfallwirtschaft Germersheim",
        "unique_id": "abfallwirtschaft_germersheim_de{\"city\": \"Winden\", \"street\": \"\"}",
        "version": 2
      },
```

There is a space inside the type: `"Restmüll "` and `"Bioabfall "`. This could be the problem I guess.

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
This seems to be the same as #2325

The type auto suggested these types with spaces at the end, but the internal events have the space removed.
Version 2.1.0 should have fixed this (The suggested types should no longer end with a space) or you type in the type manually and do not click the suggested value

**Comment by ckarrie** [comment]
Oh sorry, did'nt find that issue.
Your suggestion fixed my issue. I removed the suggested waste type and entered it manually.
