### ISSUE TITLE
[Source Request]: Haarbach, Germany (Bavaria)

### ISSUE THREAD

**Issue by sorted01** [mampfes/hacs_waste_collection_schedule#2507]
### Municipality / Region

Haarbach, Germany

### Collection Calendar Webpage

https://www.awg.de/abfallentsorgung/abfuhrkalender

### Example Address

Max-Wimmer-Ring 13, 94542 Haarbach

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
added by #2514 
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
