### ISSUE TITLE
[Source Request]: Stadt Winterthur

### ISSUE THREAD

**Issue by gatogatogato** [mampfes/hacs_waste_collection_schedule#2508]
### Municipality / Region

Winterthur, Switzerland

### Collection Calendar Webpage

https://stadt.winterthur.ch/themen/leben-in-winterthur/abfall

### Example Address

webcal://m.winterthur.ch/appl/ical.php?apid=4763999&calhome=1066394

### Collection Data Format

As ICS/ICAL file

### Additional Information

On the link https://stadt.winterthur.ch/themen/leben-in-winterthur/abfall you can click on the separate tours 

An separate ICS link is available for each tour and type of waste i.e. webcal://m.winterthur.ch/appl/ical.php?apid=4763999&calhome=1066394

**Comment by 5ila5** [comment]
Added in #2512

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
