### ISSUE TITLE
[Source Request]: NL-Gemeente Goes

### ISSUE THREAD

**Issue by mkampstra** [mampfes/hacs_waste_collection_schedule#2511]
### Municipality / Region

Goes

### Collection Calendar Webpage

https://afvalkalender.goes.nl/

### Example Address

Postal: 4472AS
Housenumber 2
https://afvalkalender.goes.nl/4472AS-17.html

### Collection Data Format

As ICS/ICAL file, As html on a webpage, As PDF Download

### Additional Information

https://afvalkalender.goes.nl/2024/4472AS-17.ics
https://afvalkalender.goes.nl/YYYY/4472AS-17.ics
YYYY = year/PostalCode-HouseNumber

When sneaking in code is see an example for service
it seems hvcgroep looks familiar. 

Summary:
Grijze container = mdi trash
Groene container = mdi leaf
Papierinzameling = mdi archive

**Comment by 5ila5** [comment]
Goes is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2513 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/goes_nl.md)

GUI setup: choose country Generic -> ICS. You will be able to see Goes in the Netherlands after the next WCS update.
