### ISSUE TITLE
[Source Request]: Katowice, Poland

### ISSUE THREAD

**Issue by bzyx** [mampfes/hacs_waste_collection_schedule#2524]
### Municipality / Region

Katowice, Poland

### Collection Calendar Webpage

https://www.mpgk.com.pl/dla-mieszkancow/harmonogram-wywozu-odpadow

### Example Address

Warszawska, 61

### Collection Data Format

As ICS/ICAL file

### Additional Information

The website provides a way to get individual schedule of  each address in ical format using a form to provide street name and number.

**Comment by 5ila5** [comment]
Added in #2528 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by bzyx** [comment]
Wow! Thanks a lot!💐
