### ISSUE TITLE
[Source Request]: Alzey-Worms, DE

### ISSUE THREAD

**Issue by ambiman** [mampfes/hacs_waste_collection_schedule#2527]
### Municipality / Region

Alzey-Worms, Germany

### Collection Calendar Webpage

https://www.kreis-alzey-worms.de/aktuelles/nichts-mehr-verpassen/abfalltermine/

### Example Address

Alzeyer Pforte 1, Albig

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Alzey-Worms is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2545 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/kreis_alzey_worms_de.md)

For GUI configuration, choose Country -> Generic -> ICS. You will see Alzey-Worms in the Germany selection after the next update
