### ISSUE TITLE
[Source Request]: Bassens

### ISSUE THREAD

**Issue by Huetalexis29** [mampfes/hacs_waste_collection_schedule#2531]
### Municipality / Region

Bassens

### Collection Calendar Webpage

https://www.sivom-rivedroite.fr/media/2986

### Example Address

Bassens 1 et 2

### Collection Data Format

Something different (add to additional information)

### Additional Information

Home assistant

**Comment by 5ila5** [comment]
## Questin

Does this
```
Collecte des Ordures Ménagères => Mardi, Vendredi | Matin
Collecte des déchets Recyclables=> Jeudi | Après midi
```
Mean that garbage is collected every Tuesday and Friday and recycling every Thursday?



## Note To myself on how to get the data:

Request to <https://www.google.com/maps/d/embed?mid=192kaU1tycR1QLrQuF_1hhIdtwghc1GDg&ll=44.90521499253571,-0.5239428999999873&z=13> extract Page data

**Comment by Huetalexis29** [comment]
Hi 
Yes it is.
 
Envoyé depuis l'application Mail Orange
----------------De : 5ila5 ***@***.***>Envoyé : vendredi 23 août 2024 14:21À : mampfes/hacs_waste_collection_schedule ***@***.***>Cc : Huetalexis29 ***@***.***>; Author ***@***.***>Objet : Re: [mampfes/hacs_waste_collection_schedule] [Source Request]: Bassens (Issue #2531)
Questin
Does this
Collecte des Ordures Ménagères => Mardi, Vendredi | Matin
Collecte des déchets Recyclables=> Jeudi | Après midi

Mean that garbage is collected every Tuesday and Friday and recycling every Thursday?
Note To myself on how to get the data:
Request to https://www.google.com/maps/d/embed?mid=192kaU1tycR1QLrQuF_1hhIdtwghc1GDg&ll=44.90521499253571,-0.5239428999999873&z=13 extract Page data

**Comment by 5ila5** [comment]
Added
This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot) by #2543
