### ISSUE TITLE
[Source Request]: St. John's, Newfoundland, CA

### ISSUE THREAD

**Issue by Foul-Trouble** [mampfes/hacs_waste_collection_schedule#2535]
### Municipality / Region

St. John's, Newfoundland

### Collection Calendar Webpage

https://curbitstjohns.ca/schedules/

### Example Address

12 Bayberry Pl, St. John's

### Collection Data Format

As html on a webpage, Something different (add to additional information)

### Additional Information

I'm not sure what it uses, sorry.

**Comment by ReneNulschDE** [comment]
You can use the recollect source https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md
