### ISSUE TITLE
[Source Request]: Affald Sønderborg Kommune

### ISSUE THREAD

**Issue by Alssund** [mampfes/hacs_waste_collection_schedule#2539]
### Municipality / Region

Sønderborg, Danmark

### Collection Calendar Webpage

https://sonderborg.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx

### Example Address

hundslevvej 8, 6440 Augustenborg

### Collection Data Format

As html on a webpage

### Additional Information

I dont know

**Comment by 5ila5** [comment]
This is already supported by the [Renoweb source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/renoweb_dk.md)
