### ISSUE TITLE
[Source Request]: Austria / Markt Piesting

### ISSUE THREAD

**Issue by taugen123** [mampfes/hacs_waste_collection_schedule#2540]
### Municipality / Region

Austria, Markt Piesting

### Collection Calendar Webpage

https://www.google.com/calendar/ical/7570b106hm2i4dibq23tes9p8c%40group.calendar.google.com/public/basic.ics

### Example Address

2753 Markt Piesting

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Markt Piesting is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2542 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/piesting_at.md)
