### ISSUE TITLE
[Source Request]: GPSEO (Grand Paris Seine & Oise)

### ISSUE THREAD

**Issue by Crazyscorpio88** [mampfes/hacs_waste_collection_schedule#2547]
### Municipality / Region

Yvelines North (73 Municipalities)

### Collection Calendar Webpage

https://dechets.gpseo.fr/

### Example Address

[11 Rue Jean Moulin, Mantes La Ville](https://dechets.gpseo.fr/vivre-et-habiter/gerer-mes-dechets/mes-jours-de-collecte/11-rue-jean-moulin-mantes-la-ville)

In order to get the correct written url, you should go first on : https://dechets.gpseo.fr/ 
Enter your address and you will get an URL like this : 
https://dechets.gpseo.fr/vivre-et-habiter/gerer-mes-dechets/mes-jours-de-collecte/$YOUR_VALID_ADDRESS

### Collection Data Format

As html on a webpage

### Additional Information

For each precise address it will return the specific data, no need to specify if we are : 
- Individual Clients
- Multi-family
- Companies

We can scrap data from the site result when we send a GET on the URL with the correct adress

Different Div Class for each Garbage type : 

- div  class="wrapper-block ordures-menageres"
- div  class="wrapper-block emballages"
- div  class="wrapper-block encombrants"
- div  class="wrapper-block dechets-verts"
- div  class="wrapper-block verres"

**Comment by 5ila5** [comment]
added by #2824

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
