### ISSUE TITLE
[Source Request]: Garsten, Upper Austria

### ISSUE THREAD

**Issue by neuhubereco** [mampfes/hacs_waste_collection_schedule#2548]
### Municipality / Region

Garsten, Austria

### Collection Calendar Webpage

https://www.umweltprofis.at/steyr_land/module/wann_wird_mein_abfall_abgeholt.html

### Example Address

obere hoellstraße, 4451 garsten

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
This is already supported by the [data_umweltprofis_at source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/data_umweltprofis_at.md)
