### ISSUE TITLE
Request for new provider harborough district

### ISSUE THREAD

**Issue by Bod1985** [mampfes/hacs_waste_collection_schedule#255]
Example:

https://www.fccenvironment.co.uk/harborough/

Example postcode would be LE16 9QX

There’s also PDF calendars here 

https://www.harborough.gov.uk/info/20007/environmental_services/31/bin_collection_information/2

**Comment by cpressland** [comment]
@mampfes - I think is can be closed following the changes in #262 and #523

**Comment by mampfes** [comment]
fixed in #523
