### ISSUE TITLE
[Source Request]: Siegen (NRW)

### ISSUE THREAD

**Issue by Figo81** [mampfes/hacs_waste_collection_schedule#2554]
### Municipality / Region

Siegen (NRW)

### Collection Calendar Webpage

https://www.siegen-stadt.de/abfallkalender/

### Example Address

Hauptstraße , 57074 Siegen

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Siegen is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2555 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/siegen_stadt_de.md)

For GUI configuration, choose country `Generic` -> ICS. You will see Siegen in the Germany section after the next update
