### ISSUE TITLE
[Source Request]: Waste Collection Floersheim am Main/Germany

### ISSUE THREAD

**Issue by Barbapapade** [mampfes/hacs_waste_collection_schedule#2556]
### Municipality / Region

Flörsheim am Main/Germany

### Collection Calendar Webpage

https://www.floersheim-umweltkalender.de/abfuhrtermine.html

### Example Address

Feldbergstrasse 28

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Flörsheim is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2557 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/floersheim_umweltkalender_de.md)

For GUI configuration, choose country `Generic` -> ICS. You will see Flörsheim Am Main in the Germany section after the next update
