### ISSUE TITLE
[Source Request]: Kriens Luzern Schweiz

### ISSUE THREAD

**Issue by patrikroesch** [mampfes/hacs_waste_collection_schedule#2559]
### Municipality / Region

Kriens / Luzern / Schweiz

### Collection Calendar Webpage

https://www.real-luzern.ch/abfall/sammeldienst/abfallkalender/?gemId=12&strId=

### Example Address

Zumhofweg

### Collection Data Format

As ICS/ICAL file, As PDF Download

**Comment by 5ila5** [comment]
Already supported by the [Real Luzern Source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/real_luzern_ch.md)
