### ISSUE TITLE
[Source Request]: Waterloo Region

### ISSUE THREAD

**Issue by CedarI** [mampfes/hacs_waste_collection_schedule#2563]
### Municipality / Region

Waterloo region, ON, Canada

### Collection Calendar Webpage

https://www.regionofwaterloo.ca/en/living-here/the-waste-whiz.aspx

### Example Address

608 Winterberry Ave, Waterloo, ON

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Waterloo uses Recollect, which is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md), I added Waterloo to the README.md in #2564 

You can find documentation on how to get the ICS link for the ICS source [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md)
