### ISSUE TITLE
[Source Request]: Adelaide Hills Council, Australia

### ISSUE THREAD

**Issue by Grubs** [mampfes/hacs_waste_collection_schedule#2566]
### Municipality / Region

Lobethal, Australia

### Collection Calendar Webpage

https://www.ahc.sa.gov.au/assets/downloads/services/Waste/Adelaide-Hills-Kerbside-Calendar-Updated-May-2024.pdf

### Example Address

18 Graeber Road, Lobethal SA 5241

### Collection Data Format

As PDF Download

### Additional Information

Adelaide Hills Council, South Australia

**Comment by 5ila5** [comment]
Adelaide Hills is now supported by the my_local_services_au source added in #2574 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
