### ISSUE TITLE
[Source Request]: Luxembourg - SICA

### ISSUE THREAD

**Issue by Seb3rus** [mampfes/hacs_waste_collection_schedule#2569]
### Municipality / Region

Mamer / Luxembourg

### Collection Calendar Webpage

https://sicaapp.lu/

### Example Address

rue de l'ecole 
L-8226
Mamer
Luxembourg

### Collection Data Format

As html on a webpage, Dedicated IOS/Android APP, As PDF Download

**Comment by 5ila5** [comment]
Added in #2575 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by Foxi352** [comment]
That is a duplicate. I committed Sica already in #2520.
I think that was even before the Source Request.

**Comment by 5ila5** [comment]
@Foxi352 sorry I somehow missed this

Your source seem to support some municipalities not supported by my implementation while your implementation seem to not support Habscht

How id you find the API/JSON? In the App that no longer exists (com.sica_app)? The new app ([lu.cuco.sica](https://play.google.com/store/apps/details?id=lu.cuco.sica)) uses yet another API (https://dashboard.sicaapp.lu/api/api/app/{ENDPOINT})

If this is from the old app I wonder how long the API still works.

**Comment by Foxi352** [comment]
@5ila5 I hooked an MITM proxy between my iPhone and the Internet. I used the APP i had on my iPhone for years. I only realized now, reading your comment, that there was a new APP. There was never an information or message in the old app. And it still works.

As for the municipalities, the old App got them from here: https://sicaapp.lu/wp-json/wp/v2/locations/
Hobscheid and Septfontaines merged 2018 into Habscht. And only villages from previous Septfontaines use services from SICA.
So your API's "Habscht" should be exactly the same data as the old API's "Septfontaines"

But to make a long story short: I guess if your code uses the newer API, you should remove my implementation and keep yours.

**Comment by Foxi352** [comment]
@5ila5 Was very quick:
List of municipalities with sometimes villages as children: https://dashboard.sicaapp.lu/api/api/app/community
List of pickup types: https://dashboard.sicaapp.lu/api/api/app/pickup-type
List of pickup dates: https://dashboard.sicaapp.lu/api/api/app/pickup-date

Tell me how you want to proceed. You want to modify your code and delete mine, or do you want me to modify mine ?
I am OK with both options, i'll leave it up to you.

**Comment by 5ila5** [comment]
I think deleting my source is the better approach as it is newer, and you can write migrations to automatically move people to the other one if they use the GUI configuration, which is much more likely with my newer source.

**Comment by Foxi352** [comment]
I already converted my source to the new API. Works good so far except something new i wanted to try.
Instead of having a static MUNICIPALITIES list i wanted to dynamically load it from inside `__init__` via the API.
But by using requests lib, which uses urllib under the hood, Home assistant config flow GUI errors on blocking call:
```
putrequest
urllib does blocking I/O and should be run in the executor with the standard methods above. Consider converting the integration to use aiohttp or httpx instead.
```
I wrote a custom integration myself in which i simply used `from homeassistant.helpers.aiohttp_client import async_get_clientsession` and then `session = async_get_clientsession(hass)`

Can i do something similar here ? What are my other options to have the list of towns dynamically loaded from API ? The advantage would be that the source can automatically be used if they add a village, without having to update the source.
* Move the build of the list from `__init__` to `fetch` ?
* Convert it to iohttp (would say overkill, if even possible) ?
* Other ideas ?

**Comment by 5ila5** [comment]
I think the easiest is to move this to the fetch method. 

I like something like this

```py
class Source:
  def __init__(self, a, b):
    self._a = a
    self._b = b

    self._municipalities: list[str]|None = None

  @staticmethod
  def _get_municipalities() -> list[str]:
    ...

  def fetch(self):
    if not self._municipalities:
      self._municipalities = self._get_municipalities()
    ... # Further code here or call to a get_collections function

**Comment by Foxi352** [comment]
Hmm... Correct me @5ila5  if i'm wrong, but that way you lose the advantage that config flow UI immediatly checks if the municipality is valid ? As i understood, the ini is called in config UI as soon as you hit the save / add source button ? So giving an in valid municipality would be detected and it would refuse to save / add the source ?

As your integration runs in async context anyway, did you not consider calling the sources (init and fetch) also in async context in the future ? If yes i would add sources static and wait for it :-)

**Comment by 5ila5** [comment]
The config flow does a test fetch when clicking finish to report errors or a empty result set and will not let you continue if either happens.

If you raise the newly added `waste_collection_schedule.exceptions.SourceArgumentNotFoundWithSuggestions` you will even get suggestions when modifying the argument
