### ISSUE TITLE
[Source Request]: Dover District Waste collections

### ISSUE THREAD

**Issue by bodissimus** [mampfes/hacs_waste_collection_schedule#2571]
### Municipality / Region

Dover, UK

### Collection Calendar Webpage

https://collections.dover.gov.uk/property/200002423404

### Example Address

Council Offices, Whitfield (Head Office) - [Map and directions »](https://www.google.co.uk/maps/place/Dover+District+Council/@51.1487946,1.287337,17z/data=!3m1!4b1!4m5!3m4!1s0x47debaeae943c4e5:0x47c727e4526c99c5!8m2!3d51.1487913!4d1.2895257)
White Cliffs Business Park, Dover CT16 3PJ

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
Added in #2576 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
