### ISSUE TITLE
Request for StadtService Brühl

### ISSUE THREAD

**Issue by fugazzy** [mampfes/hacs_waste_collection_schedule#258]
Hello, as I am not a developer I tried to look into the existing sources and examples but I could not find out how to implement the new source.
Please add this as a new source:
https://services.stadtservice-bruehl.de/abfallkalender/
best regards!
Fugazzy

**Comment by bbr111** [comment]
PR #491 should solve it

**Comment by mampfes** [comment]
fixed in #491
