### ISSUE TITLE
[Source Request]

### ISSUE THREAD

**Issue by flo-it** [mampfes/hacs_waste_collection_schedule#2581]
### Municipality / Region

Gmunden, Austria

### Collection Calendar Webpage

https://www.umweltprofis.at/gmunden/module/wann_wird_mein_abfall_abgeholt.html

### Example Address

Lasern, 4822 Bad Goisern am Hallstättersee

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
This is already supported by the [Umweltprofis Source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/data_umweltprofis_at.md), You need to create an XML URL here https://data.umweltprofis.at/opendata/AppointmentService/index.aspx (last Webserviceaufruf) and use this as `xmlurl` argument
