### ISSUE TITLE
[Source Request]: Tuscany Italy   Alia

### ISSUE THREAD

**Issue by Shintaro000000** [mampfes/hacs_waste_collection_schedule#2587]
### Municipality / Region

Florence/Pistoia/Prato Tuscany

### Collection Calendar Webpage

https://www.aliaserviziambientali.it/it-it/raccolta-rifiuti

### Example Address

You just need to enter the city (for example, Pistoia or Florence)

### Collection Data Format

As html on a webpage, Dedicated IOS/Android APP

### Additional Information

Good morning, on this page there is a list of Tuscan municipalities where Alia collects waste, and each one has its own calendar. In larger cities, it's divided into zones after selecting the city, but in smaller municipalities, I think it's easier to find.

For example, if you select Quarrata (the municipality where I live), it directly shows a single calendar, and by inspecting the element, it seems that the calendar is also displayed via this link:
https://differenziata.junker.app/embed/quarrata/calendario (Junker appears to be an app, but it doesn’t seem to work since it says that Quarrata is not covered). If possible, I would appreciate it if this could be integrated, as it covers a large part of Tuscany.

**Comment by 5ila5** [comment]
added in #2590

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
