### ISSUE TITLE
Kretslopp sydost

### ISSUE THREAD

**Issue by impa84** [mampfes/hacs_waste_collection_schedule#2589]
### Municipality / Region

Sävsjö Sweden

### Collection Calendar Webpage

https://kretsloppsydost.se/privat/toemningsdag/

### Example Address

Hägnevägen 1, Sävsjö

### Collection Data Format

As html on a webpage

### Additional Information

check the data collection date format

**Comment by 5ila5** [comment]
This is supported by the edpevent_se source, you can use this now by setting the `url` argument to `https://kundportal.kretsloppsydost.se/FutureWeb/SimpleWastePickup` and leaving the service_provider empty, after the next update it will be possible to use `service_provider` `kretslopp-sydost` as I added it in #2591
