### ISSUE TITLE
[Source Request]: West Vlaanderen / Belgium

### ISSUE THREAD

**Issue by MrNoisy98** [mampfes/hacs_waste_collection_schedule#2594]
### Municipality / Region

West Vlaanderen / Belgium

### Collection Calendar Webpage

https://www.mirom.be/ophaalkalender

### Example Address

Dosselstraat Westrozebeke

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
This is supported by the [recycleapp_be source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/recycleapp_be.md)
