### ISSUE TITLE
[Feature]: City of Wanneroo 

### ISSUE THREAD

**Issue by Danielson89** [mampfes/hacs_waste_collection_schedule#2602]
### I propose a feature for:

Sensors

### Describe your wanted feature

Hi,
Can I please request City Of Wanneroo to be added onto this cool addon
Example website: https://www.wanneroo.wa.gov.au/info/20008/waste_services

Example address: 23 Dundebar Road, Wanneroo WA 6065 

Thanks

**Comment by 5ila5** [comment]
Added in #2604

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by Danielson89** [comment]
> Added in #2604
> 
> This will be part of the next release or is available now as master (git) version
> 
> install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
> 
> install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

I've done this however It does not recognise my address at all.

**Comment by 5ila5** [comment]
Looks like a value I hard coded was only available a limited time and the source now fails.
I updated the source to now get this value dynamically.
This is now a pretty big source with quite a lot of potential points of failure, so I hope everything is fine now.

The source needs to make 5 web request to get the data

You probably need to rerun the update action with version `master`

**Comment by Danielson89** [comment]
Sadly it didn't.  I was really hoping it did.  It just cannot find my address.

**Comment by 5ila5** [comment]
What do you mean by  `It just cannot find my address` what's the error message? Does the example address work (`23 Bakana Loop LANDSDALE`)? 

Make sure to use an address, that is autocompleted here: https://www.wanneroo.wa.gov.au/info/20008/waste_services and is written exactly as shown in the auto complete.

**Comment by Danielson89** [comment]
![image](https://github.com/user-attachments/assets/98c7c9b0-70c2-4dbd-8395-01eb8947fc71)

**Comment by 5ila5** [comment]
This is the old error message. This should not happen after the update HACS should show a version as hash it should be a hash newer or equal cf139ba (NOTE: you cannot see from the hash alone if it is newer or not It should be a version listed newer/higher than cf139ba in the [commit overview](https://github.com/mampfes/hacs_waste_collection_schedule/commits/master/)(as shown in the image below))

![image](https://github.com/user-attachments/assets/6cdea13b-a4c7-4745-910b-e71aca93e93b)


UPDATING the master should work as installing it the first time: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

**Comment by Danielson89** [comment]
Woooooooohoooo.  Awesome,  yep that fixed it.

Thank you very much
