### ISSUE TITLE
Source Defect: Kirklees Council, UK

### ISSUE THREAD

**Issue by grimwiz** [mampfes/hacs_waste_collection_schedule#2608]
### Municipality / Region

UK, Kirklees Council

### Collection Calendar Webpage

https://www.kirklees.gov.uk/beta/your-property-bins-recycling/your-bins/calendar.aspx?UPRN=83194785

### Example Address

Lower Ozzings, 1
HD8 8NA

### Collection Data Format

As html on a webpage

### Additional Information

There are a few steps to go through to get to the right page, starting at https://www.kirklees.gov.uk/beta/your-property-bins-recycling/your-bins/default.aspx where you enter the address, then theres a page to confirm which exact house. I can understand that this is tricky. Currently when configuring the home assistant plugin I get the error: The source returned an invalid response: "'NoneType' object is not subscriptable". Please check the provided arguments and try again.

**Comment by 5ila5** [comment]
Our test cases did not need to select address step. Our test cases went from address input directly to the bin page, so the source failed with your address, as it was not designed to handle the select address step.

I fixed this in #2612, but you will need to provide a UPRN for those addresses.

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
