### ISSUE TITLE
[Source Request]: Bülach, Switzerland

### ISSUE THREAD

**Issue by luki210** [mampfes/hacs_waste_collection_schedule#2609]
### Municipality / Region

Bülach, Switzerland

### Collection Calendar Webpage

https://www.buelach.ch/themen/umwelt-energie-entsorgung/entsorgung/entsorgung-entsorgungskalender

### Collection Data Format

As ICS/ICAL file

### Additional Information

The city is split in two different collection schedules (east and west).

**Comment by 5ila5** [comment]
Bülach is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2611 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/buelach_ch.md)
