### ISSUE TITLE
[Source Request]: Central Coast council

### ISSUE THREAD

**Issue by Txelephant1** [mampfes/hacs_waste_collection_schedule#2610]
### Municipality / Region

Berkeley Vale, NSW

### Collection Calendar Webpage

https://1coast.com.au/bin-collection/bin-collection-day/

### Example Address

7 SEAWIND TCE, BERKELEY VALE. CENTRAL COAST 2261

### Collection Data Format

As ICS/ICAL file, As PDF Download

**Comment by JanekSMC** [comment]
May I also request this be added?

**Comment by Txelephant1** [comment]
> May I also request this be added?

Howdy Neighbor

**Comment by 5ila5** [comment]
Added a [1coast_com_au source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/1coast_com_au.md) in #3077

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
