### ISSUE TITLE
[Source Request]: New York City

### ISSUE THREAD

**Issue by HeroGregg** [mampfes/hacs_waste_collection_schedule#2615]
### Municipality / Region

New York City, New York, United States

### Collection Calendar Webpage

https://www.nyc.gov/assets/dsny/forms/collection-schedule

### Example Address

120-55 Queens Blvd, Kew Gardens, NY 11424
1 W 72nd St, New York, NY 10023

### Collection Data Format

As html on a webpage

### Additional Information

Additionally, information about delayed or suspended pickup is available from [this website](https://portal.311.nyc.gov/#feedsContainer).

**Comment by domdomegg** [comment]
Done in #2649
