### ISSUE TITLE
[Source Request]: Charles Sturt Council, South Australia

### ISSUE THREAD

**Issue by macmanluke** [mampfes/hacs_waste_collection_schedule#2616]
### Municipality / Region

Charles Sturt Council, South Australia

### Collection Calendar Webpage

https://www.charlessturt.sa.gov.au/__data/assets/pdf_file/0030/159186/CCSKerbsideCollectionCalendar_WEB_2425.pdf

### Example Address

Coglin Street, Brompton 5007, South Australia

### Collection Data Format

Dedicated IOS/Android APP, As PDF Download

### Additional Information

https://www.charlessturt.sa.gov.au/services/waste-and-recycling/bins
https://www.charlessturt.sa.gov.au/council/news-and-media/my-local-services-app

**Comment by 5ila5** [comment]
This is already supported by the [app_my_local_services_au source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_my_local_services_au.md), which is merged but not yet part of a release.

- added in #2574
- requested by #2566

It will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
