### ISSUE TITLE
[Bug]: Jumomind source not working - error "street not found"

### ISSUE THREAD

**Issue by borgqueenx** [mampfes/hacs_waste_collection_schedule#2620]
### I Have A Problem With:

A specific source

### What's Your Problem

Im getting the error "street not found" when i enter "hauptstraße" which translates to main street... I thought it was maybe the special character so also tried a street near our location, but that also did not work, again the same error "street not found".

I also tried to add it in configuration.yaml instead of setting it up by the integration. Without luck, unfortunately.

### Source (if relevant)

jumomind_de

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by borgqueenx** [comment]
I am not a fan of posting our full address here to investigate, but i can say its in the grafschaft region. just a few city's in there. 
service-ID "ben".

**Comment by 5ila5** [comment]
Looks like they put the sub-region or sometimes the region name behind the street for this service:

e.g. 

        "service_id": "ben",
        "city": "Neuenhaus",
        "street": "Bahnhofstraße, Osterwald",

So try using street: `hauptstraße, YOUR_SUBREGION`

This problem will be gone when #2492 is merged, the GUI will then show a list of available streets if the first attempt fails and the source supports it (#2492 also adds support for jumomind_de)

**Comment by borgqueenx** [comment]
thanks a lot for the help, this made me found a street closeby that i can use, that has the same collection region.
