### ISSUE TITLE
[Source Request]: Rapperswil Bern, Switzerland

### ISSUE THREAD

**Issue by edgegit** [mampfes/hacs_waste_collection_schedule#2621]
### Municipality / Region

Rapperswil Bern, Switzerland

### Collection Calendar Webpage

https://www.rapperswil-be.ch/de/abfallwirtschaft/abfallkalender/

### Example Address

Gemeinde Rapperswil
Hauptstrasse 29
3255 Rapperswil BE

### Collection Data Format

As ICS/ICAL file

### Additional Information

expanding the link attached to one of the calendar icons on the homepage reveals this link:

https://www.rapperswil-be.ch/de/abfallwirtschaft/abfallkalender/ical.php?i=108

but I think this is one single calendar entry

Clicking simply downloads the *.ics file and attempts to install the calendar on my machine. 

there's another calendar icon at the bottom, with a little + in the corner. This opens a calendar with all the entires. One could sort first e.g. Abfall drop-down, select "Papier und Karton" and create a ical file for all the entries. 

Update: 
I was able to manually add the ics files by saving them to the www dir. The only thing is, I needed up modify the ics files from: 

X-WR-TIMEZONE','EUROPE/BERLIN: to X-WR-TIMEZONE:EUROPE/BERLIN:

**Comment by 5ila5** [comment]
Added in #2628 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by edgegit** [comment]
Works perfectly. Thanks so much for adding this. Also for the quick turnaround!
