### ISSUE TITLE
[Source Request]: University Park, using Recollect

### ISSUE THREAD

**Issue by seeharrison** [mampfes/hacs_waste_collection_schedule#2624]
### Municipality / Region

University Park, Texas USA

### Collection Calendar Webpage

https://www.uptexas.org/271/Sanitation-Recycling

### Example Address

2825 Lovers Ln, University Park, TX 75225

### Collection Data Format

As ICS/ICAL file, As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
University Park is supported by the ICS source as they are using recollect, you can find documentation on how to set up the ICS source for [recollect here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md): I added Univerity Park to the README.md in #2629
