### ISSUE TITLE
[Source Request]: Oadby and Wigston Council

### ISSUE THREAD

**Issue by PingedPeach** [mampfes/hacs_waste_collection_schedule#2634]
### Municipality / Region

Oadby, Leicester, United Kingdom

### Collection Calendar Webpage

https://my.oadby-wigston.gov.uk/

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added by #2636, which was pretty easy, as they seem to use the same backend as Charnwood.

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by PingedPeach** [comment]
Which version is master? I’ve redownloaded 2.1.0 from hacs and it’s not showing
Regards,
Alexander Richard Hartley

On 8 Sep 2024, at 2:15 pm, 5ila5 ***@***.***> wrote:

﻿

Added by #2636<https://github.com/mampfes/hacs_waste_collection_schedule/pull/2636>, which was pretty easy, as they seem to use the same backend as Charnwood.

This will be part of the next release or is available now as master (git) version

install master/git: Developer tools -> actions -> select update: Install update -> click Coose entity and select WCS -> select version and type master in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by 5ila5** [comment]
It's not yet part of any released version if you want to install the master/development version follow the instruction above:

> install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
> 
> install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
