### ISSUE TITLE
[Source Request]: Bampton Garbage Collection

### ISSUE THREAD

**Issue by cia4satellite** [mampfes/hacs_waste_collection_schedule#2635]
### Municipality / Region

Brampton, Ontario

### Collection Calendar Webpage

https://www.peelregion.ca/waste/calendar/

### Example Address

15 Frampton Road Brampton Ontario

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Peel Region uses recollect, which is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md). There is documentation on how to use the ICS source with Recollect [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md). I added Peel Region to the Readme.md and [recollect.md](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md) in #2637
