### ISSUE TITLE
[Source Request]: Chelmsford City Council, UK

### ISSUE THREAD

**Issue by GravByte** [mampfes/hacs_waste_collection_schedule#2647]
### Municipality / Region

Chelmsford City Council

### Collection Calendar Webpage

https://www.chelmsford.gov.uk/bins-and-recycling/check-your-collection-day/

### Example Address

Duke Street
Chelmsford
Essex
CM1 1HT

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by GravByte** [comment]
Fantastic thank you

**Comment by 5ila5** [comment]
added in #2767

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
