### ISSUE TITLE
Request for ZAKB (Lindenfels)

### ISSUE THREAD

**Issue by Breakingx** [mampfes/hacs_waste_collection_schedule#265]
Could you please add support for zakb location Heppenheim, Lindenfels?
https://www.zakb.de/online-service/abfallkalender/

**Comment by moritzschieder** [comment]
I would also appreciate the support for ZAKB. They are using Abfall.IO/abfallplus.de
@mampfes: Can ZAKB be integrated via the existing support for Abfall.IO?

**Comment by mampfes** [comment]
No, ZAKB is using Abfall.io just for the smartphone apps. Therefore it is not possible (at least I don't know how) to get the magic unique number.

But ZAKB is using an Athos based version on der Homepage. There are already several sources for Athos based service providers, e.g. awn_de, bielefeld_de, bmv_at, regioentsorgung_de, rh_entsorgung_de.

Maybe one of them can be easily adapted for ZAKB.
