### ISSUE TITLE
[Source Request]: Neumarkt in der Oberpfalz

### ISSUE THREAD

**Issue by faltinho** [mampfes/hacs_waste_collection_schedule#2658]
### Municipality / Region

Neumarkt in der Oberpfalz

### Collection Calendar Webpage

https://www.abfuhrplan-landkreis-neumarkt.de/

### Example Address

Abtsdorfer Gasse, Neumarkt in der Oberpfalz

https://www.abfuhrplan-landkreis-neumarkt.de/neumarkt/abtsdorfer-gasse

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Added in #2708 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
