### ISSUE TITLE
[Source Request]: muellabfuhr-deustchland.de

### ISSUE THREAD

**Issue by onkelfu** [mampfes/hacs_waste_collection_schedule#2660]
### Municipality / Region

Sömmerda, Weimarer Land, Burgenlandkreis, Saalekreis

### Collection Calendar Webpage

https://portal.muellabfuhr-deutschland.de/

### Example Address

Fichtestraße 23, 99610 Sömmerda

### Collection Data Format

As ICS/ICAL file, As html on a webpage

**Comment by 5ila5** [comment]
Just noticed this is already supported: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/muellabfuhr_de.md

I added the individual districts to the README (and HA configuration GUI after the next update) in #2709
