### ISSUE TITLE
[Source Request]: Dundee, United Kingdom

### ISSUE THREAD

**Issue by michalceb** [mampfes/hacs_waste_collection_schedule#2663]
### Municipality / Region

Dundee City Council

### Collection Calendar Webpage

https://www.dundee-mybins.co.uk

### Example Address

23 Seaforth Crescent, Broughty Ferry, Dundee, DD5 1QD

### Collection Data Format

Dedicated IOS/Android APP, Something different (add to additional information)

### Additional Information

The only way to view the calendar graphically is using the app for iOS or Android.
However, I was able to find the URL sent by the app to get the calendar in JSON (I believe) format - 

https://www.dundee-mybins.co.uk/get_calendar.php?end_date=2021-01-01&rn=9059046613&device=undefined&postcode=DD51QD

Despite URL having more variables, it looks like only the UPRN is needed.

**Comment by 5ila5** [comment]
added in #2683 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
