### ISSUE TITLE
[Bug]: Blue Mountains, Australia. Incorrect URL

### ISSUE THREAD

**Issue by Chrus3** [mampfes/hacs_waste_collection_schedule#2666]
### I Have A Problem With:

A specific source

### What's Your Problem

The URL for Blue Mountains City Council is incorrect in impactapps_com_au.py.

The current entry is:
`    {
        "name": "Blue Mountains City Council",
        "url": "https://bmcc-waste.waste-info.com.au",
        "website": "https://www.bmcc.nsw.gov.au",
    }`

And it should be:
`    {
        "name": "Blue Mountains City Council",
        "url": "https://bmcc.waste-info.com.au",
        "website": "https://www.bmcc.nsw.gov.au",
    }`

I was able to make this source work by manually updating the URL in impactapps_com_au.py.

### Source (if relevant)

Australia - Blue Mountains City Council

### Logs

```Shell
The source returned an invalid response: "404 Client Error: Not Found for url: https://bmcc-waste.waste-info.com.au/api/v1/localities.json". Please check the provided arguments and try again.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Thanks for letting me know

Fixed this in #2675 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
