### ISSUE TITLE
[Source Request]: Bamberg (Stadt und Landkreis) ist zwar da aber es gibt nur Orte aus dem Landkreis

### ISSUE THREAD

**Issue by oli03ba** [mampfes/hacs_waste_collection_schedule#2669]
### Municipality / Region

Bamberg, Germany

### Collection Data Format

Something different (add to additional information)

### Additional Information

Servus, es ist zwar schon Bamberg (Stadt und Lankreis) vorhanden, aber Mann kann nur Orte aus dem Landkreis auswählen aber die Stadt Bamberg nicht.

**Comment by enrikre** [comment]
Please correct this source, it is only for Landkreis. City is a separate administration with other schedules. See #2836

**Comment by 5ila5** [comment]
Ich schließe das hier, ich habe LK aus der ICS Source rausgeworfen und fürs Stadtgebiet gibt es das Issue #2836
