### ISSUE TITLE
Request for waste management Stadt Bielefeld

### ISSUE THREAD

**Issue by mintert91** [mampfes/hacs_waste_collection_schedule#267]
Would be great if you could add support for Bielefeld.
https://anwendungen.bielefeld.de/WasteManagementBielefeld/WasteManagementServlet

**Comment by Todzjoe** [comment]
the downloaded ics works as a static file....download by hand twice a year

i would be great to have a fetch in a certain interval

**Comment by 5ila5** [comment]
can be cloesd allready integrated 
[bielefeld](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/bielefeld_de.md)
