### ISSUE TITLE
[Source Request]: Blaenau Gwent, United Kingdom

### ISSUE THREAD

**Issue by tjamieg** [mampfes/hacs_waste_collection_schedule#2672]
### Municipality / Region

Blaenau Gwent, United Kingdom

### Collection Calendar Webpage

https://www.blaenau-gwent.gov.uk/resident/waste-recycling/

### Example Address

NP23 6BQ

9 Saron Place, Ebbw Vale, NP23 6BQ

### Collection Data Format

As ICS/ICAL file, As html on a webpage, As PDF Download

### Additional Information

“Find Your Collection Day” link on above website takes you to the following page:
https://iportal.itouchvision.com/icollectionday/collection-day

Here, you input your post code and address. This shows your next recycling and refuse bin collection dates, in plain text.

Underneath, you can either click “Add to your calendar” to download an ICS file, or “View and download printable schedule” to view the year’s schedule in plain text.

**Comment by 5ila5** [comment]
Added in #2688 to the iapp_itouchvision_com source

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
