### ISSUE TITLE
[Source Request]: Carmarthenshire, Wales

### ISSUE THREAD

**Issue by R4nd0m70** [mampfes/hacs_waste_collection_schedule#2673]
### Municipality / Region

Carmarthenshire, Wales

### Collection Calendar Webpage

https://www.carmarthenshire.gov.wales/media/euob0yvb/week1-glass_en2024.pdf

### Example Address

SA18 1EJ, 100 Cwmamman Road

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
Added in #2680

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
