### ISSUE TITLE
[Source Request]: Spenge, Germany

### ISSUE THREAD

**Issue by BirknerAlex** [mampfes/hacs_waste_collection_schedule#2674]
### Municipality / Region

Spenge, Germany

### Collection Calendar Webpage

https://www.spenge.de/Rathaus-Politik/Allgemeines-Stadtservice/Abfall/Online-Abfall-Kalender/

### Example Address

Poststraße 13, 32139 Spenge, Deutschland

### Collection Data Format

As ICS/ICAL file

### Additional Information

On the page there is a dropdown with all the streets, some appointments (depending on the type of garbage) also differ depending on whether the house number is even or odd.

The following types would be great:

- Residual waste 14 times a day (all house numbers)
- Residual waste every 4 weeks (depending on whether the house number is even or odd)
- Bio bin (organic)
- Yellow bin (plastic, packaging)
- Blue bin (cardboard)

Open Request #2664 looks also very similar since both cities are very close by and using the same garbage collection company.

**Comment by 5ila5** [comment]
Spenge is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2681 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/spenge_de.md)

You can use it now from the gui by selection Country -> generic -> ICS. It will show up in the Germany section after the next update.
