### ISSUE TITLE
Request for new provider, West Devon UK

### ISSUE THREAD

**Issue by mothy-tim** [mampfes/hacs_waste_collection_schedule#268]
Please add the source for West Devon
https://westdevon.fccenvironment.co.uk/mycollections

Thanks,
Tim

**Comment by dt215git** [comment]
fccenvironment.co.uk is the same service provider Harborough District Council uses, but the West Devon implementation looks to be doing things a different way.  I get 403 errors and _'No direct script access allowed'_ and _'The action you have requested is not allowed'_ messages when trying to adapt the existing fccenvironment.co.uk approach.

**Comment by mothy-tim** [comment]
Ok thanks for looking, I guess I wait for a different approach?

**Comment by cpressland** [comment]
@mampfes it looks like a ton of local authorities use `fccenvironment.co.uk` in one way or another, however, the [existing module](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py) is written in a way very specific to Harborough. Changing this module might break existing users depending on how we move forward with this, I see two choices:

1) Rename `fccenvironment_co_uk` to `fccenvironment_co_uk_harborough`, create a new source called `fccenvironment_co_uk_westdevon`, symlink the renamed files. This _should_ mean existing users continue to function as is with no config changes.
2) Add multiple methods of scraping to the existing `fccenvironment_co_uk` module, this requires a config change for end users as they'll need to provide a `district` or similar config option to let the source know _what_ to scrape.

Personally, 1) feels like the correct method here. Let me know and I'll open a PR.

**Comment by dt215git** [comment]
I guess it depends on how many of the ~60 councils ultimately end up being supported - a breaking change introducing the need for a `district` argument may make sense for long-term maintenance if there's a desire to keep the number of .py and .md files to a minimum.

A number of the existing sources have multiple councils/municipalities per file, [a_region_ch](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/a_region_ch.py), so there's already a precedence for taking that approach.
Alternatively, introduce a `district`, but have the default value as "harborough". That'd also allow the current users to continue with the existing configs.

From what I could see when I originally had a quick look at West Devon, both that and Harborough just need `uprn`'s supplied, but the endpoints were different:
 - https://www.fccenvironment.co.uk/harborough/detail-address
 - https://westdevon.fccenvironment.co.uk/ajaxprocessor/getcollectiondetails

**Comment by mampfes** [comment]
I completely agree with @dt215git.

I would prefer to create one source if multiple councils share the same service. The main problem with this approach is that the user has to know the name of the service - typically they start searching with the name of their council/municipality/etc. What we did in the recent past was to add both to the documentation: 
- One markdown file which describes the source and all supported councils/...
- A link in README.md to the source markdown (with the name of the source).
- Extra links for supported councils in README.md which just link to the source markdown.
As this is an annoying activity, I dream of a script or s.th. similar which creates the documentation links automatically...

If you have any ideas please let me know - but let us discuss in a separate thread.

**Comment by cpressland** [comment]
@mothy-tim - could you give some advice here please? I've finished the scraper but the page returns the same collection multiple times:

![Screenshot 2022-12-27 at 14 07 21](https://user-images.githubusercontent.com/6557665/209678201-859d86bc-4abd-4d27-87ff-9d176e0dcaf6.png)

I'm just trying to figure out if I should treat these three "Recycling and Food Collection Service" entries as duplicates or if they're different poorly labeled services. If they are different, can you advise what each service actually is?

**Comment by mothy-tim** [comment]
Hi, @cpressland thanks for doing this :)
Yes looks like duplicates, there is one weekly Recycling and Food waste collection and the fortnightly Refuse collection! There is also a fortnightly Garden waste collection on opposing weeks to the refuse one!
Cheers,
Tim

**Comment by cpressland** [comment]
@mothy-tim fantastic, thats what I assumed and implemented. Next time @mampfes releases a new version of this it should be good to go. Feel free to contact me if you run into any bugs or raise a new issue here and I'll get it fixed pronto.

**Comment by mothy-tim** [comment]
@cpressland Ok,  that's great, thanks again for your work on this! Ok will do!
Happy New Year!
Cheers,
Tim

**Comment by mothy-tim** [comment]
Hi @cpressland it seems to have stopped working! It worked fine for a couple of months, but now I see errors in the logs:
`2023-02-27 06:23:32.195 ERROR (SyncWorker_9) [waste_collection_schedule.source_shell] fetch failed for source FCC Environment:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='westdevon.fccenvironment.co.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
entries = self._source.fetch()
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py", line 134, in fetch
return self.getcollectiondetails(
File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py", line 49, in getcollectiondetails
cookies = session.get(f"https://{domain}/")
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='westdevon.fccenvironment.co.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))`

Hoping you can help?
Cheers,
Tim

**Comment by cpressland** [comment]
@mothy-tim see new issue and PR raised above, this should fix this if it is accepted by the maintainers.

**Comment by mothy-tim** [comment]
Thanks, @cpressland for your speedy response and sorting out the issue.
