### ISSUE TITLE
Is it possible to use this for the Landkreis Vechta? 

### ISSUE THREAD

**Issue by HumongousFungus85** [mampfes/hacs_waste_collection_schedule#269]
The AWV (Abfallwirtschaft Vechta) uses Abfallplus somehow, however it uses it's own App.
I can not use the original Abfallplus app and it prompts me to use the AWV app instead if I try.
Is it still possible to use this integration with it? Since I can not get the required IDs.
[AWV Website](https://www.abfallwirtschaft-vechta.de/)

Thanks in advance

**Comment by markluebbehuesen** [comment]
Hey,

I am from Oldenburg. I have generated a ICS file and it works as expected.

Here you can create an ICS file, which you can import again.
https://www.abfallwirtschaft-vechta.de/index.php/termine/abfuhrkalender 

Mark

**Comment by HumongousFungus85** [comment]
Hi,

Yes I got it to work with the ics file as well.

However, I would prefer to set it up through the Abfallplus API, so it will constantly update itself in case there are some changes, or when the year changes.

**Comment by mampfes** [comment]
fixed by #819
