### ISSUE TITLE
[Source Request]: Waste calendar for Gladbeck, Germany

### ISSUE THREAD

**Issue by SeppLange** [mampfes/hacs_waste_collection_schedule#2694]
### Municipality / Region

Gladbeck

### Collection Calendar Webpage

https://www.zb-gladbeck.de/Abfuhrkalender-2326374551.html?SID=9c0oARFb9da5

### Example Address

Dahlmannsweg 7, 45968 Gladbeck

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP, Something different (add to additional information)

**Comment by 5ila5** [comment]
Gladbeck is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2698 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/zb_gladbeck_de.md)

GUI setup: Country: Generic -> ICS

It will show up in the Germany section after the next update.
