### ISSUE TITLE
Calendar used as a trigger for automations never fire.

### ISSUE THREAD

**Issue by envy** [mampfes/hacs_waste_collection_schedule#270]
So I created an automation that uses the generated calendar to notify me when I have to put the bins out using the new calendar triggers.

However, the automation never runs because the trigger never fires.

I debugged this a bit and found tha following issue:

HA asks the integration [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/calendar/trigger.py#L98) for all applicable events. However, the returned list is not quite correct. The timestamps are datetimes and the integration checks only the date component [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/calendar.py#L53).

In my case, my local timezone is Europe/Berlin, which is currently UTC+2. HA gives UTC timestamps to the integration, so they are shifted by two hours "into the past" (not really, but you know what I mean). This means that the date check is wrong, as it misses the events for the day.

I changed the following and it worked in my testing but maybe you have a better idea on how to fix that:

```python
    async def async_get_events(self, hass, start_datetime, end_datetime):
        """Return all events within specified time span."""
        collections = []
        for a in self._scraper.get_upcoming(include_today=True):
            event = self._convert(a)
            if event.start_datetime_local >= start_datetime and event.end_datetime_local <= end_datetime:
                collections.append(event)
        return collections

    def _convert(self, collection):
        """Convert an collection into a Home Assistant calendar event."""
        return CalendarEvent(
            summary=collection.type,
            start=collection.date,
            end=collection.date,
        )
```

Essentially, I convert to a HA calender event first and then let HA convert the start/end times of the event to local time to compare them against the given start/end times which are still in UTC. But both are now proper datetime objects with timezone information so comparing them works fine.

**Comment by mampfes** [comment]
Datetime handling is always a nightmare :-) I need some time to check this.

But upfront: You also removed the ` + timedelta(days=1)` from the end-date in `_convert`. Intentionally?

**Comment by envy** [comment]
Kinda. I removed it during testing because I thought the end being one day later might trip up HA. I did not test putting it back.

HA considers an [event an all day event](https://github.com/home-assistant/core/blob/dev/homeassistant/components/calendar/__init__.py#L99) if `start` is _not_ `datetime`, so whatever date `end` is, should not matter for this. I looked at my Thunderbird calenders and it seems all all day events always just have the same day (and time!) for start and end.

**Comment by envy** [comment]
Oh wait, I just remembered that it is intentional!

I call `_convert` once and then let HA convert it to local time so that I can then compare the start and end `datetime`s.

You could do this and then keep the one day offset:

```python
if event.start_datetime_local >= start_datetime and event.start_datetime_local <= end_datetime:
#                                                         ^ start_datetime_local instead of end_datetime_local
```

**Comment by gomble** [comment]
> So I created an automation that uses the generated calendar to notify me when I have to put the bins out using the new calendar triggers.
> 
> However, the automation never runs because the trigger never fires.
> 
> I debugged this a bit and found tha following issue:
> 
> HA asks the integration [here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/calendar/trigger.py#L98) for all applicable events. However, the returned list is not quite correct. The timestamps are datetimes and the integration checks only the date component [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/calendar.py#L53).
> 
> In my case, my local timezone is Europe/Berlin, which is currently UTC+2. HA gives UTC timestamps to the integration, so they are shifted by two hours "into the past" (not really, but you know what I mean). This means that the date check is wrong, as it misses the events for the day.
> 
> I changed the following and it worked in my testing but maybe you have a better idea on how to fix that:
> 
> ```python
>     async def async_get_events(self, hass, start_datetime, end_datetime):
>         """Return all events within specified time span."""
>         collections = []
>         for a in self._scraper.get_upcoming(include_today=True):
>             event = self._convert(a)
>             if event.start_datetime_local >= start_datetime and event.end_datetime_local <= end_datetime:
>                 collections.append(event)
>         return collections
> 
>     def _convert(self, collection):
>         """Convert an collection into a Home Assistant calendar event."""
>         return CalendarEvent(
>             summary=collection.type,
>             start=collection.date,
>             end=collection.date,
>         )
> ```
> 
> Essentially, I convert to a HA calender event first and then let HA convert the start/end times of the event to local time to compare them against the given start/end times which are still in UTC. But both are now proper datetime objects with timezone information so comparing them works fine.

Can you post your automation here ?

**Comment by envy** [comment]
Sure:

```yaml
alias: Mülltonnen rausstellen (neu)
description: ''
trigger:
  - platform: calendar
    event: start
    offset: '-06:00:00'
    entity_id: calendar.alw
condition: []
action:
  - service: notify.matrix_notify
    data:
      message: '{{trigger.calendar_event.summary}} rausstellen!'
mode: queued

```

**Comment by gomble** [comment]
> Sure:
> 
> 
> 
> ```yaml
> 
> alias: Mülltonnen rausstellen (neu)
> 
> description: ''
> 
> trigger:
> 
>   - platform: calendar
> 
>     event: start
> 
>     offset: '-06:00:00'
> 
>     entity_id: calendar.alw
> 
> condition: []
> 
> action:
> 
>   - service: notify.matrix_notify
> 
>     data:
> 
>       message: '{{trigger.calendar_event.summary}} rausstellen!'
> 
> mode: queued
> 
> 
> 
> ```

Okay i have the same automation and cant get it to work like this.
