### ISSUE TITLE
[Source Request]: Landkreis Rostock

### ISSUE THREAD

**Issue by MaxSohrt** [mampfes/hacs_waste_collection_schedule#2700]
### Municipality / Region

Rostock

### Collection Calendar Webpage

https://www.abfall-lro.de/de/abfuhrtermine/

### Example Address

Zur Mühle 5, 18184 Neu Thulendorf
![image](https://github.com/user-attachments/assets/2f83ec8f-a945-428a-8fb4-3b4827ef9060)

### Collection Data Format

As ICS/ICAL file, As PDF Download

**Comment by 5ila5** [comment]
Added in #2701 
It's basically just a pretty wrapper around the ICS source, If you want to use this immediately and do not want to install the development version you can just use the ICS source, and use the ULR shown in the Network tab of your browsers' developer console when clicking the download button as URL parameter for the ICS source (country -> generic ->ics) (you may want to replace the year with `{%Y}`)



The dedicated source will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by MrFloppy** [comment]
Thank you very much for the fast reaction and helpful description!
