### ISSUE TITLE
[Source Request]: Hampshire County Council

### ISSUE THREAD

**Issue by modem7** [mampfes/hacs_waste_collection_schedule#2702]
### Municipality / Region

United Kingdom

### Collection Calendar Webpage

https://www.winchester.gov.uk/bins

### Example Address

UPRN: 10090844130
1 Crispins Crescent
Orchard Mead 
Waterlooville
PO7 3AD

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
They only provide a PDF, which  we do not parse, and a weekday.

You can just use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

**Comment by modem7** [comment]
Ah, perfect - the static source will suit me just fine. 

Sincerely appreciated!

**Comment by modem7** [comment]
Heya, 

It seems they have changed how things are done now (seemingly for the better at least). 

e.g. ![image](https://github.com/user-attachments/assets/6774e14e-0010-46bb-a216-d4fd738f94b0)

Unsure if this can be parsed.

If not, I'll continue with the above solution. 

Thanks!

**Comment by 5ila5** [comment]
They now use itouchvision I added Winchester City Council in #2993

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
