### ISSUE TITLE
[Source Request]: AbfallNavi/RegioIT Mörfelden-Walldorf, Hessen, Germany

### ISSUE THREAD

**Issue by abaumann85** [mampfes/hacs_waste_collection_schedule#2705]
### Municipality / Region

Mörfelden-Walldorf

### Collection Calendar Webpage

https://abfallkalender.regioit.de/kalender-moerfelden-walldorf/index.jsp

### Example Address

Bamberger Str. 5, 64546 Mörfelden-Walldorf

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Mörfelden-Walldorf is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2706 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/moerfelden_walldorf_de.md)

GUI Configuration: Country: Generic -> ICS.
It will show up in the Germany section after the next update

**Comment by abaumann85** [comment]
Thank you very much, actually I did not see the ics implemantation. I configured it now with this and it is working fine but thanks for adding it officially so other users may see it directly :)
