### ISSUE TITLE
[Bug]: dorset council missing 

### ISSUE THREAD

**Issue by stav242** [mampfes/hacs_waste_collection_schedule#2719]
### I Have A Problem With:

A specific source

### What's Your Problem

Dorset council is listed on the readme, but not available on the integration.

### Logs

```Shell
No relevant loga
```

### Relevant Configuration

```YAML
Just initial setup, select UK/ Dorset council. Not listed.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
That was only added last week, it'll probably become visible on the next release.

**Comment by 5ila5** [comment]
This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA
