### ISSUE TITLE
[Source Request]: Folkestone

### ISSUE THREAD

**Issue by josh-clarke-95** [mampfes/hacs_waste_collection_schedule#2725]
### Municipality / Region

Folkestone / England 

### Collection Calendar Webpage

https://service.folkestone-hythe.gov.uk/webapp/myarea/index.php?t=area

### Example Address

Flat A1, 1 Grimston Avenue, Folkestone, Kent CT20 2QE

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in #2733

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
