### ISSUE TITLE
[Bug]: Unable to setup wyre_gov_uk

### ISSUE THREAD

**Issue by HeyworthR** [mampfes/hacs_waste_collection_schedule#2727]
### I Have A Problem With:

A specific source

### What's Your Problem

Setup for Wyre Council doesn't appear to be available in GUI but is listed as a source at https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/wyre_gov_uk.md

When I attempt to add through configuration.yaml I get the following error:

source not found: wyre_gov_uk

### Source (if relevant)

wyre_gov_uk

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:208
integration: Waste Collection Schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 14:11:52 (1 occurrences)
Last logged: 14:11:52
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: wyre_gov_uk
      args:
        uprn: "UPRN ADDRESS"
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
It was added 5 days ago and is not yet part of a release

wyre_gov_uk will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
