### ISSUE TITLE
[Bug]: Dorsten not working anymore

### ISSUE THREAD

**Issue by StefanDorschu** [mampfes/hacs_waste_collection_schedule#2729]
### I Have A Problem With:

A specific source

### What's Your Problem

Today i should have got a warning that tomorrow our garbage will be collected. But the waste calendar is empty (i dont know how long it is empty already). Trying to add the schedule does not work at all.

Clicking on "Add" when configuring through the UI does not work but also does not show any errors

### Source (if relevant)

AbfallNavi (RegioIT.de)

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I cannot really reproduce this issue:

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: dorsten
        ort: Dorsten
        strasse: Alleestraße
        hausnummer: 3
```

Seems to work as expected.

Is there something in your logs (settings -> System -> Logs _(German: Protokolle)_) ?

What do you mean when you say "Clicking on "Add" when configuring through the UI does not work but also does not show any errors"

What do you mean by clicking "Add" do you mean adding a new source with the same configuration?

**Comment by StefanDorschu** [comment]
Seems to work now. 

Maybe the issue was that my house number is 14c, and i used 14 c.

Thank you for your reply.
