### ISSUE TITLE
[Source Request]: Malta

### ISSUE THREAD

**Issue by furelid** [mampfes/hacs_waste_collection_schedule#2732]
### Municipality / Region

Malta, Gozo

### Collection Calendar Webpage

https://www.wastecollection.mt

### Example Address

24 Triq Torri Wejter, Birkirkara BKR 4732, Malta

or

4 Tas-Sellieha
Triq San Guzepp
Ix-Xewkija XWK2464
Malta

### Collection Data Format

Something different (add to additional information)

### Additional Information

Collection data is provided in image format (PNG)

The schedule data is also available in the HTML below the image of the schedule-image

## Available data sources
* [Schedule](https://www.wastecollection.mt/#schedule)
  * Day of the week
  * Expected waste- and bag type
* [Collection Times](https://www.wastecollection.mt/#collection_times)
  * Region
  * Locality
  * Time of collection
  * Contact details of locality

**Comment by dt215git** [comment]
Looks like there is a single schedule covering all regions, you could implement this using the [Static Source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

![image](https://github.com/user-attachments/assets/6a74956f-050a-4c5a-992d-9c015c3251c2)

**Comment by 5ila5** [comment]
You could generally implement this using the static source, but there are a lot of days, so I just wrote a source parsing the website for the days in #2737


This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
