### ISSUE TITLE
[Source Request]: Hungary source (Nyíregyháza city)

### ISSUE THREAD

**Issue by kocsishome** [mampfes/hacs_waste_collection_schedule#2734]
### Municipality / Region

Hungary/Nyíregyháza

### Collection Calendar Webpage

https://www.eakhulladek.hu//calendar/get.php?d=2024_2284

### Example Address

Nyíregyháza

### Collection Data Format

As ICS/ICAL file, As html on a webpage

### Additional Information

Thanks!

**Comment by 5ila5** [comment]
Is this PDF the only way you can get the collection dates? PDF parsing is something we generally do not do.
You selected that there is an ICS file and As HTML on a webpage. But I could not find either, just the PDF.

**Comment by kocsishome** [comment]
Hello my friend!

I am attaching an ics file. is that ok?

[hulladek_szallitas_2024_naptar.zip](https://github.com/user-attachments/files/17439534/hulladek_szallitas_2024_naptar.zip)

Thanks

**Comment by 5ila5** [comment]
We need a link or something. I do not want to hard-code collection dates, which would need constant updating, but a link where we can parse the collection dates

**Comment by kocsishome** [comment]
Thanks! Unfortunately, such a website is not visible, the service provider only provides the delivery days in a pdf file!

I'm sorry!

Thanks!
