### ISSUE TITLE
[Source Request]: Support for Iren --> Torino

### ISSUE THREAD

**Issue by davidepanato** [mampfes/hacs_waste_collection_schedule#2739]
### Municipality / Region

Torino, italy

### Collection Calendar Webpage

https://servizi.irenambiente.it/comune/calendario-di-raccolta-e-indicazioni-dotazioni.html?service=Calendario%20di%20raccolta%20e%20dotazioni

### Example Address

Comune: Torino
Via Piazza Corso: Corso Quintino Sella
N° civico: 133
<img width="1405" alt="Screenshot 2024-09-24 at 10 27 38 PM" src="https://github.com/user-attachments/assets/fc0c1eaa-2a68-48e0-9453-63c5f5bdeb94">

### Collection Data Format

As html on a webpage

### Additional Information

https://servizi.irenambiente.it/comune/calendario-di-raccolta-e-indicazioni-dotazioni.html.html?**istat=I001272&comune=TORINO&province=TO&haCartaServizi=true&streetCode=000000648794&street=CORSO%20QUINTINO%20SELLA&civic=133&civicAdrnr=0000144494**&service=Calendario%20di%20raccolta%20e%20dotazioni

Address is encoded in webpage address.

calendar for next week is shown on the page.

nessun conferimento = no waste for that day
orario esposizione = when you can set out your garbage bins

carta = paper
vetro e lattine = glass and cans
rifiuti organici = organic
imballaggi e plastica = plastic
Rifiuto residuo indifferenziato = all other waste

**Comment by 5ila5** [comment]
Added in #2752

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
