### ISSUE TITLE
Sensors not working in templates

### ISSUE THREAD

**Issue by medains** [mampfes/hacs_waste_collection_schedule#274]
When attempting to use the sensor in a template (mostly to use a mushroom template card in my use case, but it has the same problem in all templating) the sensor state shows as "unavailable"

To reproduce:
* Set up a collection sensor (call it 'test_collection')
* In "Developer Tools", "Templates" section, attempt to extract the value or attributes (e.g. ```{{ states('sensor.test_collection') }}``` or ```{{ state_attr('sensor.test_collection', 'daysTo') }}```   The state will render as "unavailable", and the attribute as "None".

Extra information:

If iterating the attributes in a template ( ```{%- for attr in states['sensor.test_collection'].attributes -%}{{attr}} {%- endfor %}``` - the only attributes showing are "restored", "friendly_name" and "supported_features"

I've not dug any further into the code to work out what is going on.

**Comment by dt215git** [comment]
![image](https://user-images.githubusercontent.com/86194065/177200262-922f58fd-d35e-42bc-ab30-3c70bc86708b.png)
Second card uses `{{ state_attr('sensor.bins', 'daysTo') }}`, is that what you're looking to do?

**Comment by medains** [comment]
My bad - I have some sensors that are still in the list after being renamed.
