### ISSUE TITLE
[Source Request]: Landkreis Lüneburg, Germany

### ISSUE THREAD

**Issue by MrJN15** [mampfes/hacs_waste_collection_schedule#2742]
### Municipality / Region

Lüneburg, Adendorf

### Collection Calendar Webpage

https://www.gfa-lueneburg.de/service/abfuhrkalender.html

### Example Address

Im Suren Winkel

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
added in #2753

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
