### ISSUE TITLE
[Source Request]: City of Round Rock, TX, USA

### ISSUE THREAD

**Issue by sanjairnair** [mampfes/hacs_waste_collection_schedule#2744]
### Municipality / Region

Round Rock, Texas, USA

### Collection Calendar Webpage

https://www.roundrocktexas.gov/city-departments/utilities-and-environmental-services/garbage-and-recycling/recycling/

### Example Address

Mayfield Ranch

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in  #2748

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
