### ISSUE TITLE
[Source Request]: NSW Bayside Council

### ISSUE THREAD

**Issue by staticgroup** [mampfes/hacs_waste_collection_schedule#2745]
### Municipality / Region

NSW,Australia

### Collection Calendar Webpage

https://waste.bayside.nsw.gov.au/calendar

### Example Address

5 Universal Street Eastlakes NSW 2018

### Collection Data Format

As html on a webpage

**Comment by dt215git** [comment]
Looks like the address search narrows down to a unique property id, and then start/end dates pull back the calendar. Looks achievable - I'll have a play.

**Comment by dt215git** [comment]
It looks like this is already supported via [ImpactApps](doc/source/impactapps_com_au.md), which provide the underying api.

![image](https://github.com/user-attachments/assets/38a367ef-220f-439f-babb-ae4ab56b2e48)

**Comment by dt215git** [comment]
Ah, no problem. Will get started then.

**Comment by dt215git** [comment]
Quick question...

![image](https://github.com/user-attachments/assets/18553278-f431-455c-9fed-05e2659676f4)

How important/useful is it to have the additional details about the _"special"_ events? They all seem to be community recycling drop-off events in either Bexley or Botany. Is _"special"_ qood enough, or would something like _"special: bexley"_ be more appropriate?

**Comment by 5ila5** [comment]
Added in #2771 to the impactapps_com_au source 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by dt215git** [comment]
The Clean-Up event should already be supported, an entry can be seen in the testing output shown in the original pull request referenced above.
