### ISSUE TITLE
[Source Request]: Carmarthenshire, Wales (re-add??)

### ISSUE THREAD

**Issue by R4nd0m70** [mampfes/hacs_waste_collection_schedule#2751]
### Municipality / Region

Carmarthenshire, Wales

### Collection Calendar Webpage

https://www.carmarthenshire.gov.wales/media/euob0yvb/week1-glass_en2024.pdf

### Example Address

SA18 1EJ, 100 Cwmamman Road

### Collection Data Format

As PDF Download

### Additional Information

#2673This had been previously requested, added and was working, but now appears to have been removed

**Comment by 5ila5** [comment]
It was not removed it is still there, but it is not part of a release yet. You can install the development (master) version and use it while it is not yet part of a release, or it will be part of the next release in a few weeks

install master/git/development Version: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by R4nd0m70** [comment]
Ok, apologies. I did try the master install as previously instructed but failed to find it. I will try again.

**Comment by 5ila5** [comment]
HACS now hides this option since HACS version 2.0 and you need to run this update action
