### ISSUE TITLE
[Source Request]: Caerphilly (Wales), UK

### ISSUE THREAD

**Issue by dwoosnam** [mampfes/hacs_waste_collection_schedule#2756]
### Municipality / Region

Caerphilly (Wales), UK

### Collection Calendar Webpage

https://www.caerphilly.gov.uk/services/household-waste-and-recycling/bin-collection-days

### Example Address

23 Isaf Road, NP11 6EG

### Collection Data Format

As ICS/ICAL file

### Additional Information

There are new schedules coming into place after the 28/10/2024 that provide an ICS file.
This appears to be using [Recollect / Routeware](https://uk.routeware.com/)

**Comment by 5ila5** [comment]
Recollect is supported by the ICS source I added Caerphilly to the recollect documentation (and README.md).

The old method could be very easily be added to the iweb_itouchvisoun_com source but I don't think it makes sense to add it just to remove it again next month

If you want to use it youself you can very manually patch the source file by putting

`"CAERPHILLY": "https://iweb.itouchvision.com/portal/f?p=customer:BIN_DAYS:::NO:RP:UID:7F2CBBF99C55C528752293E04531401A8C07CC2E,EN",`

into the URL dictionary in custom_components/waste_collection_schedule/waste_collection_schedule/source/iweb_itouchvision_com.py you can then use CAERPHILLY as council argument
https://github.com/mampfes/hacs_waste_collection_schedule/blob/286b9316f3d268473f5dc982b6d58f5ce8b646b8/custom_components/waste_collection_schedule/waste_collection_schedule/source/iweb_itouchvision_com.py#L72-L79
