### ISSUE TITLE
[Source Request]: Sunderland City Council

### ISSUE THREAD

**Issue by dankellys112** [mampfes/hacs_waste_collection_schedule#2762]
### Municipality / Region

Sunderland, United Kingdom 

### Collection Calendar Webpage

https://www.sunderland.gov.uk/bindays

### Example Address

191 Cleveland Road, Sunderland, SR4 7PU

### Collection Data Format

As html on a webpage
PDF

**Comment by dt215git** [comment]
Have a rough cut of this working, but need to find an address that has a garden waste subscription to confirm it also works when it comes across an address with that type of collection Don't suppose you know of one?

**Comment by dankellys112** [comment]
> Have a rough cut of this working, but need to find an address that has a garden waste subscription to confirm it also works when it comes across an address with that type of collection Don't suppose you know of one?

Sure, try 17 Sutherland Drive, Sunderland, SR4 8RJ

**Comment by 5ila5** [comment]
Added by #2818

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
