### ISSUE TITLE
[Source Request]: Support for AWG - Wuppertal Germany

### ISSUE THREAD

**Issue by OdaRobin** [mampfes/hacs_waste_collection_schedule#2774]
### Municipality / Region

Wuppertal, Germany

### Collection Calendar Webpage

https://awg-wuppertal.de/privatkunden/abfallkalender.html

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
It would generally be supported by the ICS source, but the cHASH parameter seems not to stay valid at least not for next year. So I added a dedicated source here:  #2775

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
