### ISSUE TITLE
[Bug]: Herefordshire, UK No longer working (unconverted data remains error)

### ISSUE THREAD

**Issue by LouisStephenRussell** [mampfes/hacs_waste_collection_schedule#2777]
### I Have A Problem With:

A specific source

### What's Your Problem

The integration no longer works for Herefordshire Council. The error that is returned is:

"The source returned an invalid response: "unconverted data remains: (next collection)". Please check the provided arguments and try again."

### Source (if relevant)

herefordshire_gov_uk

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
integration: Waste Collection Schedule (documentation)
First occurred: 8:26:48 AM (1 occurrences)
Last logged: 8:26:48 AM

fetch failed for source Herefordshire City Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/herefordshire_gov_uk.py", line 81, in fetch date=datetime.strptime( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/_strptime.py", line 336, in _strptime raise ValueError("unconverted data remains: %s" % ValueError: unconverted data remains: (next collection)
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
The test case doesn't return an error, and seems to match what the website shows for that address
```bash
test_sources.py -s herefordshire_gov_uk -l -i
Testing source herefordshire_gov_uk ...
  found 2 entries for houseNumber
    2024-10-09 : General rubbish [mdi:trash-can]
    2024-10-16 : Recycling [mdi:recycle]
```
![image](https://github.com/user-attachments/assets/9b7cca7f-00ba-406a-9591-3cc60408b7fc)

If you search for your address on the website is there any additional text on the lines containing  `(next collection)`? The error suggests it's failing to format a date - maybe the text is different to what it's expecting.

**Comment by dt215git** [comment]
True. You can pull down the master version:

Developer tools -> actions -> select update: Install update -> click Choose entity and select WCS -> select version and type master in the input field -> run the action -> restart HA

![image](https://github.com/user-attachments/assets/b050736d-a0d8-4f02-bb84-e5c1f20ec464)

**Comment by LouisStephenRussell** [comment]
I can confirm that this works with the code from master so will close this bug.
