### ISSUE TITLE
[Source Request]: Rochdale, UK

### ISSUE THREAD

**Issue by RulansB** [mampfes/hacs_waste_collection_schedule#2780]
### Municipality / Region

United Kingdom

### Collection Calendar Webpage

https://webforms.rochdale.gov.uk/BinCalendar

### Example Address

Postcode: OL104TJ
Address: 128 Claybank street, Heywood  

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
added in #2784 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
