### ISSUE TITLE
[Source Request]: North Lanarkshire, UK

### ISSUE THREAD

**Issue by craiglafferty** [mampfes/hacs_waste_collection_schedule#2786]
### Municipality / Region

North Lanarkshire, United Kingdom

### Collection Calendar Webpage

https://www.northlanarkshire.gov.uk/bin-collection-dates

### Example Address

34 Abbotsford Place, Greenfaulds, Cumbernauld, G67 4BJ

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by dt215git** [comment]
Looks like that may be possible with a combination of uprn and usrn. Will see what I can come up with.

**Comment by 5ila5** [comment]
added in #2788

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
