### ISSUE TITLE
[Source Request]: Slovakia - FCC

### ISSUE THREAD

**Issue by stomko11** [mampfes/hacs_waste_collection_schedule#2790]
### Municipality / Region

Bratislava Region

### Example Address

https://vylozsmeti.kabernet.sk/api/public/location?includeLocations=True

### Collection Data Format

Something different (add to additional information)

### Additional Information

This is for waste provider in Bratislava region called FCC (https://www.fcc-group.eu/slovensko/uvod)
Officially, they provide schedule via their dedicated android/ios app. I managed to sniff apk calls and I found that app calls for 3 URLs:
```
https://vylozsmeti.kabernet.sk/api/public/location?includeLocations=True
```
This URL is called and returns json formatted list of locations (cities) with `locationId`
This ID is used in the call to get json formatted waste types - `wasteId` and `frequencies` which defines in each city, how many frequencies are available (this is customer's choice):
```
https://vylozsmeti.kabernet.sk/api/public/schedule/options?locationId=XX
```
Last is URL to call for actual schedule that includes ID and year:
```
https://vylozsmeti.kabernet.sk/api/public/schedule?locationId=XX&year=2024
```
This returns schedule with `wasteID`, `date`, and whether this is `biWeekly` (if customers pays for waste to be collected every 2 weeks, then if `biWeekly` = true, this is when waste will be collected). Similarly `isMonthly` is for customers who pay for collecting waste once a month. Obviously both can be true. If both are false, then default is taken (which is usually once a week)

Examples with location ID 112:
https://vylozsmeti.kabernet.sk/api/public/schedule/options?locationId=112
https://vylozsmeti.kabernet.sk/api/public/schedule?locationId=112&year=2024

**Comment by 5ila5** [comment]
added in #2801 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by stomko11** [comment]
@5ila5 I tried to add it, it works, but there is one thing missing - frequency. So in villages where "weekly" is a schedule, it will populate events every week. But in my case, I pay for waste to be collected bi-weekly (some choose monthly, it depends on user and what is offered by company for that particular area).
Additionally, do you think it would be possible - when entering city, I had to enter name. Perhaps there could be a dropdown from grabbed list of cities/villages?

**Comment by 5ila5** [comment]
I added frequencies to the source. in #2808 

you need to rerun the service as shown above to update the master version

Having a drop-down requires me to hard-code the cities which isn't very elegant, you get a drop-down if you put in an invalid city (as an exception can provide alternatives). Adding the option for dynamic drop down in source configuration is on my radar but has a very low priority
