### ISSUE TITLE
[Source Request]: Stadt Cuxhaven

### ISSUE THREAD

**Issue by Jamon26** [mampfes/hacs_waste_collection_schedule#2793]
### Municipality / Region

Cuxhaven, Germany

### Collection Calendar Webpage

https://abfallkalender.regioit.de/kalender-cux/

### Example Address

Abendrothstraße

### Collection Data Format

As ICS/ICAL file, As PDF Download

### Additional Information

According to the URL, the calendar is hosted via regio it. The ics file has a strange format that I couldn't manage to include.

**Comment by 5ila5** [comment]
Cuxhaven is supported by the [abfallnavi_de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md). I added Cuxhaven to the documentation, and it will show up in the configuration GUI after the next WCS update. 

Use abfallnavi_de with `service: cux`
