### ISSUE TITLE
[Source Request]: ZKE Saarbrücken

### ISSUE THREAD

**Issue by YanKon** [mampfes/hacs_waste_collection_schedule#2794]
### Municipality / Region

Saarbrücken, Germany

### Collection Calendar Webpage

https://www.zke-sb.de/service/abfuhrtermine/abfuhrkalender

### Example Address

Häfnergasse 4

### Collection Data Format

As ICS/ICAL file

### Additional Information

URL is generated after you have selected which garbage is to be collected. 
Unfortunately there are duplicates in ics-file.

**Comment by 5ila5** [comment]
Diagnosis: Athos based so you can probably use something like `abfallwirtschaft_pforzheim_de` with only some minor changes

**Comment by phauch** [comment]
since we also need this integration ourselves, we have created a pull request with the corresponding implementation. see https://github.com/mampfes/hacs_waste_collection_schedule/pull/3237

**Comment by 5ila5** [comment]
added in #3237

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
