### ISSUE TITLE
[Bug]: Error during setup of component waste_collection_schedule

### ISSUE THREAD

**Issue by alessandroguerra** [mampfes/hacs_waste_collection_schedule#2797]
### I Have A Problem With:

The integration in general

### What's Your Problem

blocking error during HA startup

### Logs

```Shell
Logger: homeassistant.setup
Source: setup.py:416
First occurred: 17:31:56 (1 occurrences)
Last logged: 17:31:56

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_yaml.py", line 108, in async_setup
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_api.py", line 88, in add_source_shell
    new_shell = SourceShell.create(
                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 212, in create
    source = source_module.Source(**source_args)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'comune'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ilrifiutologo_it
      args:
        comune: Padova
        indirizzo: VIA BERNARDO TREVISAN
        civico: 8
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Oh. The documentation was wrong here the arguments names are `town`, `street`, `house_number` instead of `comune`, `indirizzo`, `civico`

BTW. You can use the GUI to configure sources now.
