### ISSUE TITLE
Limit the amount of calls per day

### ISSUE THREAD

**Issue by dawiinci** [mampfes/hacs_waste_collection_schedule#280]
I just received an error from the provider that my ip was doing too much updates. I guess I did restart the system a few times too much and it updates every time. Shouldn't this be limited to once a day?

**Comment by mampfes** [comment]
Updates will be fetched once per day and every time you restart your system. In my mind not too much requests... But not the first case where a service provider tries to torture their users (which are paying for the service).

**Comment by dawiinci** [comment]
Totally agree, I will monitor this behavior.
