### ISSUE TITLE
[Source Request]: Ittre, Belgium

### ISSUE THREAD

**Issue by lejfs-gh** [mampfes/hacs_waste_collection_schedule#2804]
### Municipality / Region

Ittre, Belgium

### Collection Calendar Webpage

https://www.ittre.be/ma-commune/services-communaux/environnement/gestion-des-dechets/collecte-des-dechets-menagers

### Example Address

Rue Catala, 1, 1460 Ittre

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in #2840

It parses the table on their website, so the source is quite fragile and might break if they change the table 


This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
