### ISSUE TITLE
[Source Request]: London Borough of Ealing 

### ISSUE THREAD

**Issue by haden111** [mampfes/hacs_waste_collection_schedule#2805]
### Municipality / Region

London Borough of Ealing

### Collection Calendar Webpage

https://www.ealing.gov.uk/site/custom_scripts/wasteCollectionWS/

### Example Address

22 Lothair Road, London, W5 4TA

### Collection Data Format

As html on a webpage

### Additional Information

Alternating Rubbish and Recycling collections each week. Food collection every week

**Comment by 5ila5** [comment]
added in #2809

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
