### ISSUE TITLE
[Source Request]: CISA - Val della torre

### ISSUE THREAD

**Issue by Dieghito72** [mampfes/hacs_waste_collection_schedule#2806]
### Municipality / Region

Val della torre (Turin), Italy

### Collection Calendar Webpage

https://junker.blob.core.windows.net/extrainfo/val_della_torre.pdf

### Example Address

Via Roma 1

### Collection Data Format

As PDF Download

### Additional Information

Calendar also available here: <https://differenziata.junkerapp.it/val-della-torre/calendario>

**Comment by 5ila5** [comment]
added a junker_app source in #2828, which supports CISA

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
