### ISSUE TITLE
[Source Request]: Landkreis Verden

### ISSUE THREAD

**Issue by dvophuysen** [mampfes/hacs_waste_collection_schedule#2807]
### Municipality / Region

Verden / Germany

### Collection Calendar Webpage

https://lkv.landkreis-verden.de/WasteManagementVerden/WasteManagementServlet

### Example Address

Thedinghauser Straße 1, 27321 Thedinghausen

### Collection Data Format

As ICS/ICAL file

### Additional Information

An individual ics file is created after entering a specific address

**Comment by 5ila5** [comment]
added in #3286

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
