### ISSUE TITLE
New source request UK, Chesterfield

### ISSUE THREAD

**Issue by nathanael-pearson** [mampfes/hacs_waste_collection_schedule#283]
Hi

Can you support the following?
https://www.chesterfield.gov.uk/bins-and-recycling/bin-collections/check-bin-collections.aspx

Kind regards

**Comment by mampfes** [comment]
Available with 1.23.0

**Comment by nathanael-pearson** [comment]
Fantastic thanks all.
Amazingly quick inclusion!
