### ISSUE TITLE
[Source Request]: Recology CleanScapes

### ISSUE THREAD

**Issue by JohnyBeGood** [mampfes/hacs_waste_collection_schedule#2833]
### Municipality / Region

Des Moines, WA

### Collection Calendar Webpage

https://www.recology.com/recology-king-county/des-moines/

### Example Address

22832 26TH AVE S

### Collection Data Format

As html on a webpage

### Additional Information

![image](https://github.com/user-attachments/assets/37c68488-79cb-42cc-ba54-ffc2bca7f908)

**Comment by 5ila5** [comment]
Recology is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md). They use recollect and there is documentation on how to use the ICS source with recollect you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md), they use a minimally different UI than the other, but it works the same.

I added Recology to the recollect documentation in #2844

**Comment by JohnyBeGood** [comment]
Thanks for the reply! I would never figure that out myself.
