### ISSUE TITLE
[Source Request]: Shire of Mundaring, Australia

### ISSUE THREAD

**Issue by declannmcc** [mampfes/hacs_waste_collection_schedule#2834]
### Municipality / Region

Shire of Mundaring, WA, Australia

### Collection Calendar Webpage

https://my.mundaring.wa.gov.au/BinLocationInfo/Details

### Example Address

1235 Katharine ST HELENA VALLEY WA 6056

### Collection Data Format

As html on a webpage

### Additional Information

HTML with just the dates is returned from the URL https://my.mundaring.wa.gov.au/BinLocationInfo/Info?parcelNumber=103239&suburb=HELENA%20VALLEY&_=1728804036071 (using the example address provided earlier)

**Comment by dt215git** [comment]
Havig had a quick play with this one, it looks like  the `parcelNumber` parameter is needed to get most of the small waste collections, but dates for  Bulk Verge Collections uses  the `suburb` parameter. Thankfully the `_` parameter doesn't seem to be required if you go direct to the endpoint, which is helpful as it appears to increment with every interaction with the site.

**Comment by 5ila5** [comment]
added in #2848 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
