### ISSUE TITLE
[Bug]: since HA 2024.10.2 fetch failed for source Berliner Stadtreinigungsbetriebe

### ISSUE THREAD

**Issue by elelch** [mampfes/hacs_waste_collection_schedule#2835]
### I Have A Problem With:

The integration in general

### What's Your Problem

since HA 2024.10.2 update fetch failed for source Berliner Stadtreinigungsbetriebe
the other source "Berlin Recycling" is ok

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 12. Oktober 2024 um 13:18:36 (3 Vorkommnisse)
Zuletzt protokolliert: 09:53:02

fetch failed for source Berliner Stadtreinigungsbetriebe: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/bsr_de.py", line 115, in fetch dates.extend(self._ics.convert(ics)) ^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 297, in parse_events raise ValueError("Content is invalid!") ValueError: Content is invalid!
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Probably this: https://www.bsr.de/abfuhrkalender-20520.php

![image](https://github.com/user-attachments/assets/c5c7c176-6d6e-4053-9cea-5f1e454195fc)

**Comment by elelch** [comment]
thanks, now it's working again
