### ISSUE TITLE
[Source Request]: Waste collection Bamberg City

### ISSUE THREAD

**Issue by enrikre** [mampfes/hacs_waste_collection_schedule#2836]
### Municipality / Region

Bamberg City

### Collection Calendar Webpage

https://www.stadt.bamberg.de/B%C3%BCrgerservice/%C3%84mter/Bamberg-Service-/Abfallwirtschaft/Abfuhrtermine/

### Example Address

There is stated that the Bamberg Landkreis Plugin already issues for the city area, but its not the case. On the Landkreis there is no data for Bamberg Stadt. I add the link for Stadt which is a separate administration. Thanks a lot!

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
Added Bamberg (city) in #2838

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by enrikre** [comment]
Works like a charme thanks a lot for fast fix!
