### ISSUE TITLE
[Bug]: Muellmax not working (stopped working

### ISSUE THREAD

**Issue by SupiTrobi** [mampfes/hacs_waste_collection_schedule#2860]
### I Have A Problem With:

The integration in general

### What's Your Problem

Not sure if this is really a bug but the Integration is not working anymore for Muellmax. 
All sensors have a unkown state.
I haven't touch this config for a long time.
I am Running HA 2024.9.3 and WCS latest version.

After a short while I treid to switch to the alternative in creating a ics manually. 
When I went to the appropiate page. I received the following message

![muell](https://github.com/user-attachments/assets/530e716d-fb90-4ea0-b7f2-ca07813f169a)

So I guess the reason why it is not working is the fact that the access is simply closed.
The next day (today) I tried it again. Still the same message. 
Is there a possibility inside the Integration to fulfill the stated requirements to enable a reliable service ?

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
This generally should not happen. The source requests once a day/or on restart (may require up to 7 Requests to go through the form) So you should only run into this if you restart your HA multiple times in a short time

**Comment by SupiTrobi** [comment]
Hmm still not working for me. I exactly did that what you say (So you should only run into this if you restart your HA multiple times in a short time). I guess I still have to wait until it is opened up again. Thx for the info.

**Comment by SupiTrobi** [comment]
It's working now so it was infact the situation that I did a little bit to much on the system with restarts ;-)
