### ISSUE TITLE
[Source Request]: Walldorf, Germany

### ISSUE THREAD

**Issue by grashopper** [mampfes/hacs_waste_collection_schedule#2862]
### Municipality / Region

Walldorf, Germany

### Collection Calendar Webpage

https://www.avr-kommunal.de/leistungen/entsorgung/abfallkalender

### Example Address

Dietrich-Bonhoeffer-Str. 11, 69190 Walldorf

### Collection Data Format

As ICS/ICAL file

### Additional Information

ICS is created an downloaded from https://api.abfall.io

Example with fake key and modus values:
https://api.abfall.io/?key=914fb9d000a9a05af4fd54&modus=d6c5855a62cf331f0f295f&waction=export_ics

The Website provides data for many other cities around Walldorf as well.

**Comment by grashopper** [comment]
Can be closed. Just figured out that the Abfall.IO API is listed as a city.

**Comment by grashopper** [comment]
Can be closed. I finally figured out that I have to select the service provider instead of my hometown.

**Comment by 5ila5** [comment]
Walldorf is supported by the [abfall_io source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md) and their app backend is supported by the [app_abfallplus_de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md)
