### ISSUE TITLE
[Bug]: Mount Barker Council Set Up Error

### ISSUE THREAD

**Issue by NoahColly** [mampfes/hacs_waste_collection_schedule#2863]
### I Have A Problem With:

A specific source, Sensor configuration

### What's Your Problem

When setting up the integration Mount Barker Council (Aus), it returns the below error:

The source returned an invalid response: "unconverted data remains: ,2025-01-02". Please check the provided arguments and try again.

Did however work with example params.
My params: -35.082943, 138.883702

### Source (if relevant)

app_my_local_services_au

### Logs

```Shell
No logs sent
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
It looks like this address retunes additional dates with only `,` separated, while for other addresses they were separated by `<SPACE>,`  

I fixed this in #2865


This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
