### ISSUE TITLE
[Source Request]: St. Kanzian, Austria

### ISSUE THREAD

**Issue by Nikey0918** [mampfes/hacs_waste_collection_schedule#2864]
### Municipality / Region

St.Kanzian, Austria

### Collection Calendar Webpage

https://kanzian.at/muellabfuhrkalender/

### Example Address

Vesielach, 9122 St. Kanzian or St.Primus, 9122 St. Kanzian

### Collection Data Format

As PDF Download

### Additional Information

sadly a very coimplicated calender, i think the important ones are "Hausmüll 2-Wöchentlich", "Altpapiersammlung" and "Leicht- und Metallverpackung" (aka "Gelber Sack").

**Comment by Nikey0918** [comment]
Maybe the Homepage of the company is better?

Page to Selection of location:
https://www.gojer.at/service/abfuhrkalender.html

Example Adress:
https://www.gojer.at/service/abfuhrkalender.html?gemeindewahl=St._Kanzian_am_Klopeiner_See&ortswahl=Vesielach&haus=Hausm%C3%BCll&plastik=Plastikflaschen&papier=Altpapier&metall=Metallverpackungen

**Comment by Nikey0918** [comment]
Hi!
Thx for the fast update, very nice!

I tried to add it as described above but i don't get my city to work :(
Others are working fine...
Tried it with Dropdown and typing manually.

![Gojer](https://github.com/user-attachments/assets/112dc6e2-5105-4ee5-b5bd-3bd9531a4ca2)

**Comment by 5ila5** [comment]
Fixed this in #2886 
you need to rerun the update action as described above
