### ISSUE TITLE
[Source Request]: Eisenkappel-Vellach: Ebriach-Trögern

### ISSUE THREAD

**Issue by Shime007** [mampfes/hacs_waste_collection_schedule#2869]
### Municipality / Region

Eisenkappel-Vellach

### Collection Calendar Webpage

https://www.bad-eisenkappel.info/gemeinde/onlineservice/abfuhrtermine.html

### Example Address

Ebriach 141, 9135 Bad Eisenkappel

### Collection Data Format

As html on a webpage

### Additional Information

On the webpage are the waste collection plans listed for different routes in the location or for the complete location.
For example, I need the route for "Ebriach, Trögern" on my adress and, if the pickup will be done on the same day in the complete location I need the Route for "Gesamtes Gemeindegebiet"

**Comment by 5ila5** [comment]
This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by Shime007** [comment]
Thank you!
I made the master/git update with the developer tools, but bad_eisenkappel is no source to choose when I install the waste collection schedule.
![image](https://github.com/user-attachments/assets/bd3a9726-9927-4950-a08e-467cb7d5bddb)

**Comment by 5ila5** [comment]
The name shown in this selection should be Eisenkappel-Vellach

**Comment by Shime007** [comment]
Sorr, ther is no Eisenkappel-Vellach.
The country I selected is Austria
![image](https://github.com/user-attachments/assets/3192b65b-c196-4ab7-a681-9f703ffdf151)

and in the source there is no Eisenkappel-Vellach
![image](https://github.com/user-attachments/assets/d9851def-b0fa-4ebf-8fa2-0ad15ef57288)
