### ISSUE TITLE
[Source Request]: Rhein-Lahn Kreis

### ISSUE THREAD

**Issue by DanielS1290** [mampfes/hacs_waste_collection_schedule#2874]
### Municipality / Region

Rhein Lahn Kreis 

### Collection Calendar Webpage

https://www.rhein-lahn-kreis-abfallwirtschaft.de/html/cs_6615.html?PHPSESSID=jkiuqc3en4cvrpdkflosh0a0c1

### Example Address

Waldstraße, 65558 Burgschwalbach 

### Collection Data Format

As ICS/ICAL file

### Additional Information

Benutze die Integration schon länger. Gute Arbeit, weiter so.
Vielen Dank

**Comment by 5ila5** [comment]
Rhein-Lahn Kreis is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2897 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/rhein_lahn_kreis_abfallwirtschaft_de.md)

## GUI configuration: 

Country: Generic -> ICS

You will find Rhein-Lahn Kreis in the Germany section of the Configuration GUI after the next update
