### ISSUE TITLE
No longer works. Log info

### ISSUE THREAD

**Issue by sblogoshs** [mampfes/hacs_waste_collection_schedule#288]
Home-Assistant OS 2022.7.2
RPi4

Problem started with 2022.7

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:124 
Integration: waste_collection_schedule (documentation) 
First occurred: 21:54:17 (1 occurrences) 
Last logged: 21:54:17

fetch failed for source Abfallkalender Würzburg: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 122, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py", line 64, in fetch self._district_id = self.map_district_id(self._district, self._street) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py", line 39, in map_district_id strdict = {option.text: option["value"] for option in strlist} File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/wuerzburg_de.py", line 39, in <dictcomp> strdict = {option.text: option["value"] for option in strlist} TypeError: string indices must be integers

**Comment by schmittey** [comment]
Hi @sblogoshs, looks like a fix is already on the way :)

https://github.com/mampfes/hacs_waste_collection_schedule/pull/285

thx @rikroe

**Comment by mampfes** [comment]
Will be available with 1.23.0
