### ISSUE TITLE
[Source Request]: [D] Schwabach

### ISSUE THREAD

**Issue by fl0rianW** [mampfes/hacs_waste_collection_schedule#2882]
### Municipality / Region

Schwabach

### Collection Calendar Webpage

https://www.abfuhrplan-schwabach.de/

### Example Address

"Bayernstraße"
"Königsplatz"
"Rennmühlweg bis 20"

### Collection Data Format

As ICS/ICAL file, As html on a webpage, As PDF Download

### Additional Information

Number is commonly not needed. 

If a Street has different schedules, it seems to be 'two different streets' e.g.
"Penzendorfer Straße, HNr. 1 - 47b, 4 - 36a"
"Penzendorfer Straße, HNr. 49 - 87, 40 - 102"
"Rennmühlweg ab 120"
"Rennmühlweg bis 20"

**Comment by 5ila5** [comment]
added in #2900

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
