### ISSUE TITLE
[Source Request]: Baden-Baden

### ISSUE THREAD

**Issue by mrst** [mampfes/hacs_waste_collection_schedule#2895]
### Municipality / Region

Baden-Baden / Germany

### Collection Calendar Webpage

https://www.baden-baden.de/buergerservice/umwelt/entsorgung/umweltkalender/

### Example Address

City part: Baden-Baden
Street: Zeppelinstraße

### Collection Data Format

As ICS/ICAL file

### Additional Information

The part of the city needs to be selected as well as the street and type of waste collection. All seem to be mapped to parameters in the URL to download the ICAL calendar:

ort=0 seems to be the main city part of Baden-Baden 
strasse=730 seems to be Zeppelinstraße 
abfallart[]=1 to 4 seem to be the different types of Trash to be collected
t=1 ?
pdf=3 ?

Example link:

https://www.baden-baden.de/buergerservice/umwelt/entsorgung/umweltkalender/?ort=0&strasse=730&abfallart[]=1&abfallart[]=2&abfallart[]=3&abfallart[]=4&t=1&pdf=3

**Comment by 5ila5** [comment]
Baden Baden is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2899 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/baden_baden_de.md)

## GUI configuration:

Country: Generic -> ICS


It will be part of the Germany selection after the next update

**Comment by mrst** [comment]
thanks a lot, works like a charm already!
