### ISSUE TITLE
Latest release is able to crash full Home Assistant

### ISSUE THREAD

**Issue by P3RF3CTION** [mampfes/hacs_waste_collection_schedule#293]
Sorry for bothering you I am still trying to ivestigate. I am running the latest release of hassio.

` 
OS Version:               Home Assistant OS 8.2
Home Assistant Core:      2022.7.3

`
After updating the plugin yesterday the HA dind't came back after a reboot. I used some backup (from 3 days ago) to get it working again.
After several attempts with problems I started updating the Plugins one by one. After the latest Update of this Plugin the HA Installation breaks (startup takes more than 1h and sometimes failed instead of 1min). After removing the Plugin from the custom_components the issue was fixed. I will try to provide logs and re do it on a second Installation, to not break my Active Setup.

**Comment by mampfes** [comment]
Sounds like #220 

Please check if you can install the required modules manually.

**Comment by CFenner** [comment]
I solved the issue by reinstalling the module. 
Would be nice if the missing requirement causing this would block the plugin startup that the user get's a useful error message.

**Comment by mampfes** [comment]
Yes, this would be nice - but has to be resolved in HACS or HomeAssistant. The plugin is not running yet, so it can't do anything.
