### ISSUE TITLE
[Source Request]: Please add Schwerin (Germany)

### ISSUE THREAD

**Issue by gnomy** [mampfes/hacs_waste_collection_schedule#2930]
### Municipality / Region

Schwerin, Germany 

### Collection Calendar Webpage

https://www.sds-schwerin.de/abfall-strassenreinigung/entsorgungskalender/

### Example Address

Kirchenweg 36, 19057 Schwerin

### Collection Data Format

As ICS/ICAL file, Dedicated IOS/Android APP, As PDF Download

**Comment by bbr111** [comment]
@gnomy 
![image](https://github.com/user-attachments/assets/f8ce7e1d-4025-455d-bfc1-321dc5d65e57)
kannst du versuchen den ICS Link einzubinden?

es könnte sein, dass das schon reicht.

Also einfach Adresse auswählen und auf ICS Export klicken, und den Link kopieren.

**Comment by 5ila5** [comment]
Schwerin is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2944 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/sds_schwerin_de.md)

GUI Configuration: Country: Generic -> ICS

Schwerin will show up in the Germany section (as link to ICS source) after the next update.
