### ISSUE TITLE
[Source Request]: Please add Calais France 

### ISSUE THREAD

**Issue by Linkra62** [mampfes/hacs_waste_collection_schedule#2933]
### Municipality / Region

Calais France 

### Collection Calendar Webpage

https://www.calais.fr/fr/Ville-de-Calais/la-mairie/infos-pratiques/collecte-des-dechets

### Example Address

16 rue Jeanne thil 62100 calais France 

### Collection Data Format

Dedicated IOS/Android APP

**Comment by vinzd** [comment]
Hey @Linkra62 , this will be addressed by https://github.com/mampfes/hacs_waste_collection_schedule/pull/3008. In the meantime you can you the `publidata` generic source with `instance_id: 679`. Let me know if you have any issue!
