### ISSUE TITLE
[Bug]: Adding source "AHE Ennepe-Ruhr-Kreis (ahe_de)" leads to error

### ISSUE THREAD

**Issue by BorgTen** [mampfes/hacs_waste_collection_schedule#2939]
### I Have A Problem With:

A specific source

### What's Your Problem

This Source cannot be added. In the configuration flow "Unknown error occured" is displayed after selecting it and pressing "Save".

### Source (if relevant)

ahe_de

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by BorgTen** [comment]
![grafik](https://github.com/user-attachments/assets/16dff445-73eb-4fe3-b60d-aa4e65bf2c34)

**Comment by ReneNulschDE** [comment]
What other custom components do you have installed? ics_calendar version 5.0.4? if yes, check [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004).

if not, please share the complete error message out of the homeassistant.log.

**Comment by BorgTen** [comment]
Yes, it was the conflict with ics_calendar 5.0.4 and its dependencies. After performing the described steps, WCS works again.
