### ISSUE TITLE
 can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by QuantumCorral** [mampfes/hacs_waste_collection_schedule#294]
I always have this error in the logs 

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:124
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 19:55:02 (1 occurrences)
Last logged: 19:55:02
fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 122, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 181, in fetch return self.fetch_url(self._url, self._params) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 209, in fetch_url return self._convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 216, in _convert dates = self._ics.convert(data) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 50, in events found_events += parse_events(content, start=start, end=end) File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 356, in parse_events for dt in rule.between(after, end, inc=True): File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 283, in between for i in gen: File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 1401, in _iter while exlist and exlist[0] < ritem: File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 1338, in __lt__ return self.dt < other.dt TypeError: can't compare offset-naive and offset-aware datetimes

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.awm-muenchen.de/entsorgen/abfuhrkalender?tx_awmabfuhrkalender_abfuhrkalender%5Bhausnummer%5D=2&tx_awmabfuhrkalender_abfuhrkalender%5Bleerungszyklus%5D%5BB%5D=1%2F2%3BG&tx_awmabfuhrkalender_abfuhrkalender%5Bleerungszyklus%5D%5BP%5D=1%2F2%3BU&tx_awmabfuhrkalender_abfuhrkalender%5Bleerungszyklus%5D%5BR%5D=001%3BG&tx_awmabfuhrkalender_abfuhrkalender%5Bsection%5D=ics&tx_awmabfuhrkalender_abfuhrkalender%5Bsinglestandplatz%5D=false&tx_awmabfuhrkalender_abfuhrkalender%5Bstandplatzwahl%5D=true&tx_awmabfuhrkalender_abfuhrkalender%5Bstellplatz%5D%5Bbio%5D=70114566&tx_awmabfuhrkalender_abfuhrkalender%5Bstellplatz%5D%5Bpapier%5D=70114566&tx_awmabfuhrkalender_abfuhrkalender%5Bstellplatz%5D%5Brestmuell%5D=70114566&tx_awmabfuhrkalender_abfuhrkalender%5Bstrasse%5D=Freimanner%20Bahnhofstr.&tx_awmabfuhrkalender_abfuhrkalender%5Byear%5D=2022"

Thank you 
Kind regards

**Comment by mampfes** [comment]
Please try to add `version: 1` to your ICS source configuration.

See also (updated docu): https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md

**Comment by mampfes** [comment]
Did this work for your?

**Comment by mampfes** [comment]
Closed because no feedback.

**Comment by ThomDietrich** [comment]
Confirmed to solve the issue. Thanks!
