### ISSUE TITLE
[Source Request]: Wallern an der Trattnach (Upper Austria)

### ISSUE THREAD

**Issue by nuki47** [mampfes/hacs_waste_collection_schedule#2941]
### Municipality / Region

Wallern an der Trattnach, Bezirk Grieskirchen, Oberösterreich

### Collection Calendar Webpage

https://data.umweltprofis.at/opendata/AppointmentService/index.aspx

### Example Address

Höhenstrasse, 4702 Wallern an der Trattnach

### Collection Data Format

As ICS/ICAL file

### Additional Information

for Home Assistant GUI

**Comment by ReneNulschDE** [comment]
This supported via the [Umweltprofis_at](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/data_umweltprofis_at.md) source already.

**Comment by nuki47** [comment]
But Umweltprofis don't work in the GUI for the Integration....I have to copy the code into the config.yaml?

**Comment by ReneNulschDE** [comment]
You have to copy the link into the xmlurl field of the gui assistant. Just tested this and it is working. Do you get an error?

**Comment by nuki47** [comment]
I get no error but also no data?

`waste_collection_schedule:
  sources:
    - name: data_umweltprofis_at
      args:
        xmlurl: https://data.umweltprofis.at/opendata/AppointmentService/AppointmentService.asmx/GetTermineForLocationSecured?Key=TEMPKeyabvvMKVCic0cMcmsTEMPKey&StreetNr=96127&HouseNr=Alle&intervall=2-wöchentlich
      `

**Comment by nuki47** [comment]
something wents wrong but I can't find which one...

a) If I use this config, I dont have any calender
<img width="614" alt="image" src="https://github.com/user-attachments/assets/f52a84e4-332a-4fc5-824e-c1a10181f350">

b) If I try to add Umweltprofis in the GUI, I became this error
<img width="251" alt="image" src="https://github.com/user-attachments/assets/81bf762f-9c39-4fbf-bb95-dddca090311b">

**Comment by nuki47** [comment]
Yes, 5.0.4 is installed
<img width="243" alt="image" src="https://github.com/user-attachments/assets/64e61729-2d59-4017-b340-6804c5adb498">

**Comment by nuki47** [comment]
If I open the [link](<img width="353" alt="image" src="https://github.com/user-attachments/assets/5edfe969-1f58-4051-bb15-fb7760c06948">) in my browser:

<img width="353" alt="image" src="https://github.com/user-attachments/assets/787c4288-44fe-421c-a30d-52a85e6e792f">

**Comment by ReneNulschDE** [comment]
> Yes, 5.0.4 is installed
> 
> <img width="243" alt="image" src="https://github.com/user-attachments/assets/64e61729-2d59-4017-b340-6804c5adb498">
> 
> 

Please follow the procedure that I shared.
