### ISSUE TITLE
[Bug]: Does not work any more

### ISSUE THREAD

**Issue by hendrik001973** [mampfes/hacs_waste_collection_schedule#2945]
### I Have A Problem With:

The integration in general

### What's Your Problem

The integration does not work anymore. After a restart of HA there is the error message "Source not found" for both services I have configured (ICS, Muellmax).

The malfunction timely falls together with the latest changes (added Schwerin)

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:221
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 19:17:33 (2 Vorkommnisse)
Zuletzt protokolliert: 19:17:33

source not found: ics
source not found: muellmax_de

----

Logger: homeassistant.components.calendar
Quelle: helpers/entity_platform.py:361
Integration: Kalender (Dokumentation, Probleme)
Erstmals aufgetreten: 19:17:33 (2 Vorkommnisse)
Zuletzt protokolliert: 19:17:33

Error while setting up waste_collection_schedule platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 165, in async_setup_entry
    entities = create_calendar_entries([shell], coordinator=coordinator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 129, in create_calendar_entries
    dedicated_calendar_types = shell.get_dedicated_calendar_types()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dedicated_calendar_types'
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
What other custom components do you have installed? ics_calendar version 5.0.4? if yes, check [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

**Comment by hendrik001973** [comment]
I had ics_calendar 5.0.3 installed. 
Now I have deleted this integration and downloaded WCS again. But it is still not working.

Other custom components integrations are:
Thermal comfort 
Deutscher Wetterdienst 
ESPSomfyRTS
MagentaTV
Best regards 
Hendrik

**Comment by hendrik001973** [comment]
Now I have un-installed I calendar 6.0.1 and icalevents and now it is working again. Thanks!

**Comment by ReneNulschDE** [comment]
Thanks for the feedback. Feel free to close the issue. I can't do it.

**Comment by hendrik001973** [comment]
Closed
