### ISSUE TITLE
[Bug]: Waste Collection Schedule suddenly stopped working

### ISSUE THREAD

**Issue by DarthSonic** [mampfes/hacs_waste_collection_schedule#2948]
### I Have A Problem With:

The integration in general

### What's Your Problem

Existing integration and configuration (by UI) does not work anymore. Entities are not available anymore, and when trying to configure again "500 Internal Server Error Server got itself in trouble" is thrown as error.

![image](https://github.com/user-attachments/assets/9fdf0fbb-a422-41d5-88a3-5697d3659f18)

![image](https://github.com/user-attachments/assets/de9a6ee4-9164-4a59-8438-92de3053560a)

### Logs

```
Logger: homeassistant.components.calendar
Quelle: helpers/entity_platform.py:361
Integration: Kalender (Dokumentation, Probleme)
Erstmals aufgetreten: 13:22:34 (1 Vorkommnisse)
Zuletzt protokolliert: 13:22:34

Error while setting up waste_collection_schedule platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 165, in async_setup_entry
    entities = create_calendar_entries([shell], coordinator=coordinator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/calendar.py", line 129, in create_calendar_entries
    dedicated_calendar_types = shell.get_dedicated_calendar_types()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dedicated_calendar_types'
```

```
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:361
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 13:22:34 (1 Vorkommnisse)
Zuletzt protokolliert: 13:22:34

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 76, in async_setup_entry
    _LOGGER.debug("Adding sensors for %s", coordinator.shell.calendar_title)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'calendar_title'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
may be the same issue as #2907

**Comment by DarthSonic** [comment]
Downgrade ICS calendar to 5.0.3 with no success.
Upgraded ICS calendar to 5.0.4 again, and upgrade Waste Collection Scheduler to 2.4.0 without success.

Do not know what else to do. Do I need to reconfigure all schedules? Was a lot of work to get them configured the way I wanted them to be.

**Comment by ReneNulschDE** [comment]
Did you really followed [this](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004) procedure? This worked in nearly all of the cases in the last few days.

**Comment by DarthSonic** [comment]
workaround fixed issue

**Comment by ReneNulschDE** [comment]
OK. feel free to close the issue.
