### ISSUE TITLE
[Bug]: Gütersloh doenst work

### ISSUE THREAD

**Issue by gaboony** [mampfes/hacs_waste_collection_schedule#2950]
### I Have A Problem With:

The integration in general

### What's Your Problem

I Can choose the Region Gütersloh in the configuration dialog, but i dont can choose the City "Werther". I cant leave the dialog, it doesnt save the config...

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
They use the abfallnavi_de source if you select Gütersloh this should autofill service to be gt2 which is only the city of Gütersloh. If you want Kreis Gürersloh you need to set service to `krwaf`.

I added Kreis Gürersloh in #2957 so you will be able to directly select Kreis Güterloh after the next update, but you can use the source as is by setting service to `krwaf`
