### ISSUE TITLE
awb_lm no longer working

### ISSUE THREAD

**Issue by CryPt00n** [mampfes/hacs_waste_collection_schedule#299]
Hello, 
there was a redesign of the website done for awb_lm, so the url has changed from "https://www.awb-lm.de/abfuhrtermine/" to "https://www.awb-lm.de/ihr-abfallkalender/". Changed it to the new values but still cant sync the plan.

Following error in logs:

`Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:124
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 06:00:41 (1 occurrences)
Last logged: 06:00:41
fetch failed for source Abfallwirtschaftsbetrieb Limburg-Weilburg: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 122, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_lm_de.py", line 50, in fetch raise Exception(f"ics url not found") Exception: ics url not found`

**Comment by dt215git** [comment]
That error message suggests they've changed how they reference the ICS file. It looks like they're now redirecting a query to api.abfall.io and getting the ICS file from there.
If that's the case, the [Abfall.IO / AbfallPlus.de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md) info might provide a work around.

**Comment by blaerf** [comment]
It works well with Abfall.IO / AbfallPlus.de

I followed the 'Hardcore' Instructions on https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md

**Comment by CryPt00n** [comment]
Works with Abfall.IO / AbfallPlus.de
