### ISSUE TITLE
[Bug]: EVA Abfallentsorgung Website doesnt exists

### ISSUE THREAD

**Issue by RALFISBORN** [mampfes/hacs_waste_collection_schedule#2998]
### I Have A Problem With:

A specific source

### What's Your Problem

Hello,

I need the EVA waste calendar and I noticed in the documentation that on the one hand the link no longer works and on the other hand that I don't know how to parameterise the URL.

I hope for a remedy :). Thank you very much

The Link to the documentation:
[doc/ics/eva_abfallentsorgung_de.md](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/eva_abfallentsorgung_de.md)

### Source (if relevant)

eva_abfallentsorgung_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I updated the documentation to reflect the new page in #3001
