### ISSUE TITLE
[Bug]: landkreis_rhoen_grabfeld not working anymore

### ISSUE THREAD

**Issue by muju91** [mampfes/hacs_waste_collection_schedule#3006]
### I Have A Problem With:

A specific source

### What's Your Problem

It seems for me that the source is not available.

it worked with this config:

waste_collection_schedule:
  sources:
    - name: landkreis_rhoen_grabfeld
      args:
        district: "Oberebersbach"

But also when i try to manage it via UI I get this message:

Die Quelle hat eine ungültige Antwort zurückgegeben: "410 Client Error: Gone for url: https://fs-api-rg.offizium.com/abfalltermine?stadt=Niederlauer&ortsteil=Oberebersbach". Bitte überprüfe die Argumente und versuche es erneut.

I tried to ping offizium.com but it is not possible to ping.

Could it be that there is a new url?

My version is 2.4.0

Thx

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Finghin** [comment]
It looks like Offizium is no longer providing an API at this address.
There seems to be a new API now at this address:
https://aht1gh-api.sqronline.de/api/modules/abfall/webshow?module_division_uuid=fde08d95-111b-11ef-bbd4-b2fd53c2005a&cityIds=26&areaIds=101
This is the API that is used by https://www.abfallinfo-rhoen-grabfeld.de/, so it should be correct.

The 'cityIds' parameter identifies the 'Kommune' and the 'areaIds' parameter the 'Ortsteil'.
The JSON response contains a list of all available IDs in the mdiv.config object.
The dates for the requested city/area are in the abfall_dates array.

If no one else picks this up until then, I will try to fix it tomorrow.

**Comment by 5ila5** [comment]
fixed by #3015 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
