### ISSUE TITLE
[Bug]: Landkreis Tübingen (awido_de) is not working anymore

### ISSUE THREAD

**Issue by karmann1991** [mampfes/hacs_waste_collection_schedule#3009]
### I Have A Problem With:

A specific source

### What's Your Problem

 Landkreis Tübingen (awido_de) is not working anymore

![grafik](https://github.com/user-attachments/assets/0af5cb44-24e3-454f-b029-c5090b46e419)

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
What other custom components do you have installed? I assume you made an update of ics_calendar to version 5.0.4? if yes, check [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

**Comment by karmann1991** [comment]
> What other custom components do you have installed? I assume you made an update of ics_calendar to version 5.0.4? if yes, check [here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/2893#issuecomment-2433200004)

Thank, it was the ics calendar. If not really use it, so I delete it and follow your instruction in terminal. Afterwards the wcs works again :)

**Comment by ReneNulschDE** [comment]
Thanks for the feedback. Feel free to close the issue.
