### ISSUE TITLE
Request for provider - Central Bedfordshire, United Kingdom

### ISSUE THREAD

**Issue by guybw** [mampfes/hacs_waste_collection_schedule#301]
Hello,
Could I please request for Central Bedfordshire, United Kingdom

https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_days#my_bin_collections
Example postcode would be :SG17 5PG
We have the following collections:
Food Waste
Garden waste
Recycling
Refuse

If I can do any testing or digging please let me know but web stuff just isn't my skill!
Also, THANK YOU!

**Comment by markhaines** [comment]
+1 for this request please!

**Comment by gingemonster** [comment]
working on this has submitted PR https://github.com/mampfes/hacs_waste_collection_schedule/pull/606

**Comment by mampfes** [comment]
@guybw Please wait until I release a new version (every 2-4 weeks). Then you can install it via HACS.
