### ISSUE TITLE
[Source Request]: Tibi Belgium, Charleroi

### ISSUE THREAD

**Issue by CCGcastiel** [mampfes/hacs_waste_collection_schedule#3018]
### Municipality / Region

Belgium Charleroi

### Collection Calendar Webpage

https://www.tibi.be/citoyens-administrations/collectes-porte-a-porte/calendrier-des-collectes.htm

### Example Address

postal code : 6044
Road : de Gohyssart 
House number: 45
Recyparc: doesn't matter

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
The Use recycleapp.be has its own source.

So Charleroi is supported by the [recycleapp_be source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/recycleapp_be.md)
