### ISSUE TITLE
[Source Request]: Add Vöcklabruck, Austria

### ISSUE THREAD

**Issue by EdeP93** [mampfes/hacs_waste_collection_schedule#3020]
### Municipality / Region

Regau, Vöcklabruck, Austria

### Collection Calendar Webpage

https://www.umweltprofis.at/voecklabruck/module/wann_wird_mein_abfall_abgeholt.html

### Example Address

Morchelweg, 4800 Regau
![image](https://github.com/user-attachments/assets/9c6bedf3-8931-424e-bdaf-6b9b6bb316ba)

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by curmet** [comment]
there is a open data portal if someone can use this:
https://data.umweltprofis.at/opendata/

**Comment by curmet** [comment]
@EdeP93 Ich habe es für meine Gemeinde geschafft. Das müsste auch in Regau gehen:
Folgende Seite aufrufen:
https://www.regau.at/BUeRGERSERVICE/Aktuelles/Abfalltermine
Dann findest du die nächsten Termine. Hier kannst du zB Restmüll anklicken und findest darunter den Link zur ICS Datei. Die Linkadresse kopieren und im Wastecollector einfügen nach dieser Anleitung:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/2.4.0/doc/source/ics.md#configuration-via-configurationyaml

Als Land "Generic" wählen! 
Und den Link zur ICS dann einfügen.

LG

**Comment by 5ila5** [comment]
This should be already supported by the [data_umweltprofis_at source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/data_umweltprofis_at.md)
