### ISSUE TITLE
[Feature]: Central Coast BINS

### ISSUE THREAD

**Issue by russell2200** [mampfes/hacs_waste_collection_schedule#3022]
### I propose a feature for:

Sources

### Describe your wanted feature

Add Central Coast council NSW bin schedules https://1coast.com.au/bin-collection/bin-collection-day/

**Comment by 5ila5** [comment]
Added a [1coast_com_au source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/1coast_com_au.md) in #3077

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
