### ISSUE TITLE
[Bug]: crawley no longer seems to work

### ISSUE THREAD

**Issue by marc115uk** [mampfes/hacs_waste_collection_schedule#3023]
### I Have A Problem With:

A specific source

### What's Your Problem

I have been using this integration for quite some time with no issues, setup via yaml. I am now getting unknown for all sensors. I have tried reconfiguring via UI I get the following error when trying to set up The source returned an invalid response: "'NoneType' object has no attribute 'find_all'". Please check the provided arguments and try again.

### Source (if relevant)

https://my.crawley.gov.uk/en/service/check_my_bin_collection

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by planetcastle** [comment]
Same issue as #2988

**Comment by alfwro13** [comment]
Same problem here

**Comment by alfwro13** [comment]
I found this UK specific integration - https://github.com/robbrad/UKBinCollectionData
That works fine.

**Comment by planetcastle** [comment]
> I found this UK specific integration - https://github.com/robbrad/UKBinCollectionData That works fine.

Crawley has been updated to the Firmstep/Granicus Platform on that service
![Screenshot 2024-11-15 at 09 12 00](https://github.com/user-attachments/assets/58bb3203-f10c-4771-bc73-f92c985b5f2c)

**Comment by 5ila5** [comment]
fixed by #3098 

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
