### ISSUE TITLE
Kumberg

### ISSUE THREAD

**Issue by GUFEL3** [mampfes/hacs_waste_collection_schedule#3025]
### Municipality / Region

Steiermark / Austria

### Collection Calendar Webpage

https://www.kumberg.gv.at/muelltermine/

### Example Address

Kumberg Lindenweg

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added
This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details> a Kumberg_gv_at source in #3025

I first thought about just adding documentation for using this with the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md), but you would need multiple ICS source for the different waste types. So I wrote a small dedicated source
