### ISSUE TITLE
[Bug]: The source returned an invalid response: "object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by cpiekacz** [mampfes/hacs_waste_collection_schedule#3028]
### I Have A Problem With:

A specific source

### What's Your Problem

When configuring the source for Poland / Warsaw, after providing address (and geolocation id) I get the following error:

The source returned an invalid response: "object of type 'NoneType' has no len()". Please check the provided arguments and try again. 

### Source (if relevant)

warszawa19115_pl

### Logs

```Shell
{
    "type": "form",
    "flow_id": "01JCKJ1NH12596AKDA56H23D0J",
    "handler": "waste_collection_schedule",
    "data_schema": [
        {
            "type": "string",
            "name": "calendar_title",
            "optional": true,
            "default": "Warsaw"
        },
        {
            "type": "string",
            "name": "street_address",
            "description": {
                "suggested_value": "MARSZAŁKOWSKA 1, 00-624 Śródmieście"
            },
            "optional": true
        },
        {
            "type": "string",
            "name": "geolocation_id",
            "description": {
                "suggested_value": "3830916"
            },
            "optional": true
        }
    ],
    "errors": {
        "base": "fetch_error"
    },
    "description_placeholders": {
        "fetch_error_message": "object of type 'NoneType' has no len()"
    },
    "last_step": null,
    "preview": null,
    "step_id": "args_warszawa19115_pl"
}
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Could you double check this again? I tried the following config:

![image](https://github.com/user-attachments/assets/cf520a76-95ab-40ed-b68e-19bc95773b13)

and it worked without errors:

![image](https://github.com/user-attachments/assets/102def99-d004-48ac-a7da-080c51a43be1)

**Comment by ReneNulschDE** [comment]
fixed in https://github.com/mampfes/hacs_waste_collection_schedule/pull/2971

This will be part of the next release or is available now as master (git) version

install master/git: Developer tools -> actions -> select update: Install update -> click Coose entity and select WCS -> select version and type master in the input field -> run the action -> restart HA

Older versions of HACS:
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by cpiekacz** [comment]
Updated from master and it works. Thanks.
