### ISSUE TITLE
[Source Request]: Gera / AWV Ostthüringen

### ISSUE THREAD

**Issue by cyn-sudo** [mampfes/hacs_waste_collection_schedule#3029]
### Municipality / Region

gera

### Example Address

Liebestraße 16

### Collection Data Format

As documented API

**Comment by 5ila5** [comment]
Added in #3101

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by TheAmazingLooser** [comment]
Correct me if I'm wrong but this PR has nothing to do with this issue. The issue remains completely untouched and should still be open.

The PR adds support for the https://www.kumberg.gv.at/kalender/ calendar and not the AWV Ostthüringen calendar.

**Comment by 5ila5** [comment]
You're right I somehow mixed this up with #3072

**Comment by 5ila5** [comment]
I don't know what I did there, but I found the original commit in my reflog. So it will be part of the next release, not the one I released yesterday. You can follow the instructions to install the master/development version above.
