### ISSUE TITLE
[Source Request]: Knowsley Council

### ISSUE THREAD

**Issue by Andyk-93** [mampfes/hacs_waste_collection_schedule#3036]
### Municipality / Region

United Kingdom

### Collection Calendar Webpage

https://knowsleytransaction.mendixcloud.com/index.html

### Example Address

L364AR
Enter house number

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
Is there any way to get the information without the need to create an account?

**Comment by Andyk-93** [comment]
Try this linkhttps://knowsleytransaction.mendixcloud.com/link/youarebeingredirected?target=bincollectioninformationThis redirects me to postcode search screenThanksAndrewSent from my iPhoneOn 29 Nov 2024, at 20:23, 5ila5 ***@***.***> wrote:﻿
Is there any way to get the information without the need to create an account?

**Comment by Andyk-93** [comment]
Hello! I hope you're doing well. I apologise for any inconvenience, but I was wondering if you might have an idea of when it would be possible for me to integrate this into my HA environment.

**Comment by 5ila5** [comment]
added in #3315

Hope it stays functional, as it's a pretty complex source. They're doing a lot of complex web requests I needed to reverse engineer.


This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
