### ISSUE TITLE
[Source Request]:  Abfallkalender Bottrop der BEST

### ISSUE THREAD

**Issue by uweoe** [mampfes/hacs_waste_collection_schedule#3037]
### Municipality / Region

Bottrop

### Collection Calendar Webpage

https://www.best-bottrop.de/abfuhrtermine-0910213539.html

### Example Address

Johannesstraße 1 46240 Bottrop

### Collection Data Format

As ICS/ICAL file, As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
BEST Bottrop is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #3112 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/best_bottrop_de.md)

GUI usage Country: Generic -> ics -> fill in URL.

It will show up as a link to the ICS source with additional documentation after the next update of WCS
