### ISSUE TITLE
[Bug]: Getting data from "Germany, Städteregion Aachen" ends with error since today

### ISSUE THREAD

**Issue by TribunMaximus** [mampfes/hacs_waste_collection_schedule#3049]
### I Have A Problem With:

The integration in general

### What's Your Problem

Getting data from "Germay, Städteregion Aachen"ends up with the following error: HTTPSConnectionPool(host='tonnen.regioentsorgung.de', port=443): Max retries exceeded with url: /WasteManagementRegioentsorgung/WasteManagementServlet?SubmitAction=wasteDisposalServices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d5b1a2360>: Failed to establish a new connection: [Errno 111] Connection refused'))".

Any idea how this can be fixed?

### Source (if relevant)

Germany - Städteregion Aachen

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
The error occurs on https://regioentsorgung.de/service/abholservice/abfallkalender too. Looks like that the server is offline. Nothing that we can solve. You could ask the provider regioentsorgung.

**Comment by 5ila5** [comment]
Is this resolved now, or do you still get this error?

**Comment by TribunMaximus** [comment]
You were right. It was only a problem from provider
