### ISSUE TITLE
[Source Request]:  Lethbridge, Canada

### ISSUE THREAD

**Issue by risozhor** [mampfes/hacs_waste_collection_schedule#3056]
### Municipality / Region

Lethbridge, Canada

### Collection Calendar Webpage

https://www.lethbridge.ca/waste-recycling/#wastewizard

### Example Address

337 Rivergrove Chase W, Lethbridge

### Collection Data Format

As html on a webpage

### Additional Information

The city also has a mobile application
https://www.lethbridge.ca/news/posts/lethbridge-loop
 an interactive map
https://lethbridgewastepv.azurewebsites.net
Maybe this API will help too https://opendata.lethbridge.ca/api/search/definition/#/

**Comment by risozhor** [comment]
I think there is a similar service in [Regina](https://github.com/mampfes/hacs_waste_collection_schedule/issues/3056).

**Comment by 5ila5** [comment]
They both use Recollect which is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added both to the dedicated Recollect documentation in #3116 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md)

GUI Usage: 
Country: USA -> Recollect -> insert ICS URL
or
Country: Generic -> ICS -> insert ICS URL


Lethbridge and Regina will show up in the Canada GUI configuration menu after the next update (they will just redirect to the Recollect source, which is basically just the ICS source)
