### ISSUE TITLE
[Source Request]: Bordeaux Metropole, France

### ISSUE THREAD

**Issue by Swiiney** [mampfes/hacs_waste_collection_schedule#3062]
### Municipality / Region

Bordeaux Metropole, France

### Collection Calendar Webpage

https://opendata.bordeaux-metropole.fr/explore/dataset/en_frcol_s/export/?disjunctive.jour_col

### Example Address

Latitude, Longitude : 44.840165649597424, -0.6395375878056988

### Collection Data Format

As documented API, Something different (add to additional information)

### Additional Information

Webservice : https://opendata.bordeaux-metropole.fr/explore/dataset/en_frcol_s/webservices/?disjunctive.jour_col
Needed to find the coordinates inside a shape.

**Comment by AthAshino** [comment]
Done, waiting for merge
