### ISSUE TITLE
[Source Request]: Südbrandenburgischer Abfallzweckverband

### ISSUE THREAD

**Issue by Sashbln** [mampfes/hacs_waste_collection_schedule#3063]
### Municipality / Region

Baruth

### Example Address

Merzdorfer str , Petkus / Baruth/Mark

### Collection Data Format

As html on a webpage

### Additional Information

![Screenshot 2024-11-19 080732](https://github.com/user-attachments/assets/2763aaa1-232c-403d-a5ba-09452288cb7c)
Leider bekomme ich die Erweiterung auch nicht mehr zum laufen. Auch manuell klappt es nicht

**Comment by ReneNulschDE** [comment]
Fixed with #3041 already. Should be part of the next version.
