### ISSUE TITLE
[Source Request]: Lama, Taranto

### ISSUE THREAD

**Issue by enygmait** [mampfes/hacs_waste_collection_schedule#3065]
### Municipality / Region

Taranto, (Lama, San Vito, Talasano) Italy

### Collection Calendar Webpage

https://araccolta.it/lama-san-vito-talsano/

### Collection Data Format

As html on a webpage, As PDF Download

**Comment by 5ila5** [comment]
added in #3284

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
