### ISSUE TITLE
[Source Request]: Germany, 27321 Thedinghausen

### ISSUE THREAD

**Issue by Groby-xyz** [mampfes/hacs_waste_collection_schedule#3067]
### Municipality / Region

Germany, 27321 Thedinghausen

### Collection Calendar Webpage

https://lkv.landkreis-verden.de/WasteManagementVerden/WasteManagementServlet

### Example Address

Thedinghausen
Hainbuchenring
1

(Hainbuchenring 1, 27321 Thedinghausen)

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
added in #3286

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
