### ISSUE TITLE
[Source Request]: Add Kristiansand, Norway

### ISSUE THREAD

**Issue by stiknu** [mampfes/hacs_waste_collection_schedule#3068]
### Municipality / Region

Kristiansand, Norway

### Collection Calendar Webpage

https://avfallsor.no/henting-av-avfall/finn-hentedag/

### Example Address

Auglandslia 1, 4620 Kristiansand 

### Collection Data Format

As PDF Download

**Comment by 5ila5** [comment]
added in #3288

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
