### ISSUE TITLE
[Bug]: Zweckverband Abfallwirtschaft Region Hannover / aha-region.de

### ISSUE THREAD

**Issue by foxmulder4223** [mampfes/hacs_waste_collection_schedule#3074]
### I Have A Problem With:

A specific source

### What's Your Problem

For some hours the source has thrown an „unknown error“. 

500 Internal Server Error Server got itself in trouble

### Source (if relevant)

Zweckverband Abfallwirtschaft Region Hannover / aha-region.de

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Could you retest this? I just executed the test-run:
```
Testing source aha_region_de ...
  found 13 entries for Neustadt a. Rbge., Am Rotdorn / Nöpke, 1 
  found 18 entries for Isernhagen, Am Lohner Hof / Isernhagen Fb, 10
  found 17 entries for Hannover, Voltastr. / Vahrenwald, 25
  found 18 entries for Hannover, Melanchthonstr., 10A
  found 15 entries for Mit Ladeort
```

In case this still fails, please share the detailed config and if works now, please close the issue...
