### ISSUE TITLE
[Bug]: sbazv_de.md not found / cant setup

### ISSUE THREAD

**Issue by Freacly** [mampfes/hacs_waste_collection_schedule#3075]
### I Have A Problem With:

A specific source, The integration in general

### What's Your Problem

Hello,

if i try to setup the integration and type in my source: Südbrandenburgischer Abfallzweckverband (sbazv_de) its shown in the menu as supported.

then it leads me to type in city, region and street.
i cant continue from this. it shows me following error:

" Die Quelle hat eine ungültige Antwort zurückgegeben: "Content line could not be parsed into parts: '<!DOCTYPE html>': <!DOCTYPE html>". Bitte überprüfe die Argumente und versuche es erneut."

when i click on the info button for this source on github:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/sbazv_de.md

it shows me 404 - page not found

Can anyone help me set it up and get it working?
Is it my own fault ?

### Source (if relevant)

sbazv_de

### Logs

```Shell
Die Quelle hat eine ungültige Antwort zurückgegeben: "Content line could not be parsed into parts: '<!DOCTYPE html>': <!DOCTYPE html>". Bitte überprüfe die Argumente und versuche es erneut
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by marci227** [comment]
With „Generic“ option and Paste the SBAZV URL, it works !

**Comment by Freacly** [comment]
> With „Generic“ option and Paste the SBAZV URL, it works !

I dont unterstand this?
Which Url i have to paste where?

**Comment by marci227** [comment]
![image](https://github.com/user-attachments/assets/652ca86a-eff4-451b-b4b6-fbe34d7533f8)

**Comment by Freacly** [comment]
> ![image](https://private-user-images.githubusercontent.com/158303172/389277431-652ca86a-eff4-451b-b4b6-fbe34d7533f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTk2NDIsIm5iZiI6MTczMjQ1OTM0MiwicGF0aCI6Ii8xNTgzMDMxNzIvMzg5Mjc3NDMxLTY1MmNhODZhLWVmZjQtNDUxYi1iNGI2LWZiZTM0ZDc1MzNmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNDQyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTkyN2Y4NjIwNWZhZDlhM2FjMWNhY2U1ZWI4NTZhMjdlODM1NDU3MTUyMmZjZjlmZmM0OWVhNzQwZmYzNmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rtr95P9SekU52_qCfvbpS8QonDI7IEjXFDPYGhxXWV4)

Thanks but i dont know how to configure it in the next step?
![Screenshot 2024-11-24 154127](https://github.com/user-attachments/assets/17ef9b32-2a10-4a36-a125-c3b182a6b7d2)

**Comment by Freacly** [comment]
isnt it possible to fix the main error?
if i try to setup normal way?!

![WasteScreenshot 2024-11-24 155033](https://github.com/user-attachments/assets/03adae1c-f678-428d-8f3f-fb5c2dcf3231)

**Comment by marci227** [comment]
Generic / Quelle .ics
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/sbazv_de.md

**Comment by 5ila5** [comment]
sbazv_de changed their API it was removed in favor of documentation and a link in the configuration menu to the ICS source in #3041

Unfortunately you cannot reuse your old source configuration but you need to move to the ICS Source. as @marci227 mentioned there is documentation here:  https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/sbazv_de.md

If you use the latest version of WCS you should be able to select `Südbrandenburgischer Abfallzweckverband` in the HA configuration GUI and there should be a description on the top. (Short: you need to get the ICAL url and use it as `url` arguemnt, You can probably leave everything else as is)
