### ISSUE TITLE
[Source Request]: Landkreis Schaumburg (aws-shg.de)

### ISSUE THREAD

**Issue by mumug1980** [mampfes/hacs_waste_collection_schedule#3082]
### Municipality / Region

Germany

### Collection Calendar Webpage

https://aws-shg.de

### Example Address

Feldstr.7
31552 Rodenberg

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
aws-shg.de is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) there is dedicated documentation on how to use it for aws-shg.de. You can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/aws_shg_de.md)
