### ISSUE TITLE
[Source Request]: Oberösterreich (Upper Austria)

### ISSUE THREAD

**Issue by Hochgue** [mampfes/hacs_waste_collection_schedule#3083]
### Municipality / Region

Alberndorf 

### Collection Calendar Webpage

www.umweltprofis.at

### Example Address

Sportplatzweg 1, A 4211 Alberndorf

### Collection Data Format

Dedicated IOS/Android APP

**Comment by 5ila5** [comment]
This is already supported by the [data_umweltprofis_at source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/data_umweltprofis_at.md)
