### ISSUE TITLE
[Source Request]: Wilnsdorf, Germany

### ISSUE THREAD

**Issue by xsibix** [mampfes/hacs_waste_collection_schedule#3094]
### Municipality / Region

Wilnsdorf

### Collection Calendar Webpage

https://www.wilnsdorf.de/Leben-Wohnen/Bauen-Wohnen-Umwelt/Abfall/Abfallkalender/index.php

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Wilnsdorf is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #3342 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/wilnsdorf_de.md)

Setup using GUI: Country: generic -> ics -> use `url`, `verify_ssl`, and `regex` like described in the link above.

After the next update you'll find wilnsdorf in the Germany section with the documentation integrated in the config_flow
