### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by wildpump** [mampfes/hacs_waste_collection_schedule#3106]
### Municipality / Region

landkreis kassel

### Collection Calendar Webpage

https://webapp.abfall-kreis-kassel.de/abfallkalender

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
This is supported by the ICS source there is even dedicated documentation for Kreis Kassel https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/abfall_kreis_kassel_de.md
