### ISSUE TITLE
Awb Esslingen Not working anymore?

### ISSUE THREAD

**Issue by Stothed775** [mampfes/hacs_waste_collection_schedule#3108]
### I Have A Problem With:

A specific source

### What's Your Problem

Hello,

Today I recognized that the source of awb Esslingen is not working anymore - is there a known issue?

### Source (if relevant)

awb_es_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Stothed775** [comment]
Here is the Error Log:


Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 28. November 2024 um 22:59:38 (2 Vorkommnisse)
Zuletzt protokolliert: 01:39:57

fetch failed for source Abfallwirtschaftsbetrieb Esslingen: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py", line 47, in fetch raise Exception("ics url not found") Exception: ics url not found

**Comment by lx05** [comment]
I also get the same error :(

**Comment by uluick** [comment]
I got the same error log:

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 07:02:58 (1 Vorkommnisse)
Zuletzt protokolliert: 07:02:58

fetch failed for source Abfallwirtschaftsbetrieb Esslingen: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py", line 47, in fetch raise Exception("ics url not found") Exception: ics url not found

**Comment by Dani0x0** [comment]
Also getting the same issue :(

**Comment by charly166** [comment]
I have the same problem. Seems there is a global error - there were so many issues reported

**Comment by uluick** [comment]
AWB Esslingen is currently switching to self-service. Maybe it could have something to do with that.

**Comment by franky1808** [comment]
Same same with staedteservice_de / city Raunheim.

**Comment by charly166** [comment]
I still see the "appointments" in the WACS created calendar, but they do not appear in the sensors anymore. That's a bit strange.

**Comment by JericoPablo** [comment]
same for me with Esslingen

**Comment by Django1982** [comment]
Also for me too.

**Comment by charly166** [comment]
I deleted all settings and set it up again ... and again ... and again. My third try was successful, now it works fine again! That's really strange 🤷‍♂️

**Comment by franky1808** [comment]
I guess it’s not setting up all and all again, mine is working suddenly as well without doing anything.

**Comment by BeSt1979** [comment]
I got the same error with AWB Esslingen

`Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 13:15:14 (1 occurrences)
Last logged: 13:15:14

fetch failed for source Abfallwirtschaftsbetrieb Esslingen: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py", line 47, in fetch raise Exception("ics url not found") Exception: ics url not found`

Is there any solution known for this?

**Comment by Videothek** [comment]
I have the same error.

I dug a little deeper and i came to the conclusion, that the error comes from this line (obviously):

```
       ics_urls = list()
        for download in downloads:
            href = download.get("href")
            if "t=ics" in href and href not in ics_urls: #The website lists the same url multiple times, we only want it once
                ics_urls.append(href)

        if not ics_urls:
            raise Exception("ics url not found")
```
As stated this is line 47 and above.

Unfortunately i am not fit with python programing.

I tried to reset the integration multiple times but it didn't help.

**Comment by Videothek** [comment]
Ok so i dug deeper again.

The AWB Site lists the following url for the download:
![grafik](https://github.com/user-attachments/assets/fbbb2806-f8fc-48ae-9271-f4bcc757724f)

The code searches for ics in the link (as far as i understand it, please correct me if i am wrong):
`if "t=ics" in href`

But there is no ics in the string, just at the end of the downloaded file, once you call the URL.

Maybe that helps.

**Comment by Django1982** [comment]
What everyone should test, is the following, which worked for me:

Go to https://www.awb-es.de/abfuhr/abfuhrtermine/abfuhrtermine-suchen.html
Search for your city and then enter your street

In my case there was written "Schulgarten Alle Hausnummern" and not only "Schulgarten"
So i filled it up with "Schulgarten Alle Hausnummern" and it worked again.

Hope this helps

**Comment by BeSt1979** [comment]
> What everyone should test, is the following, which worked for me:
> 
> Go to https://www.awb-es.de/abfuhr/abfuhrtermine/abfuhrtermine-suchen.html Search for your city and then enter your street
> 
> In my case there was written "Schulgarten Alle Hausnummern" and not only "Schulgarten" So i filled it up with "Schulgarten Alle Hausnummern" and it worked again.
> 
> Hope this helps

This worked for me as well!

**Comment by Videothek** [comment]
> What everyone should test, is the following, which worked for me:
> 
> Go to https://www.awb-es.de/abfuhr/abfuhrtermine/abfuhrtermine-suchen.html Search for your city and then enter your street
> 
> In my case there was written "Schulgarten Alle Hausnummern" and not only "Schulgarten" So i filled it up with "Schulgarten Alle Hausnummern" and it worked again.
> 
> Hope this helps

Great tip, i changed `Wiflingshauser Straße` to `Wiflingshauser Strasse Alle Hausnummern` now it is working again.
Weird that it suddenly stopped working

**Comment by VolkerMal** [comment]
hm ... same issue here.
initial value: Schwabstrasse
Now AWB ES is reporting it under: Schwabstraße Alle Hausnummern
but regardless if si choose:
Schwabstraße Alle Hausnummern
or
Schwabstrasse Alle Hausnummern

no data is retrieved ....  :-(

**Comment by VolkerMal** [comment]
Hi, 
That's what I did.
Neither "Strasse" nor "Straße" does work.
Adding "Alle Hausnummern" does not make any difference either.

**Comment by 5ila5** [comment]
It looks like they renamed a lot of streets e.g. from `Alte Dorfstraße` to `Alte Dorfstraße alle Hausnummern`

make sure your street matches exactly the one auto-complted by the website: https://www.awb-es.de/abfuhr/abfuhrtermine/__Abfuhrtermine.html

I improved error handling in #3343, so the error message reflects the actual problem
