### ISSUE TITLE
[Bug]: Yarra Ranges Council not loading schedule

### ISSUE THREAD

**Issue by dseeva** [mampfes/hacs_waste_collection_schedule#3110]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi after a recent update this integration is no longer working.
rolling back several updates did not resolve, so issue may be with HA itself.
I've tried both configuring by GUI and through yaml.
Address has been copied from council website as per git docs.

### Source (if relevant)

yarra_ranges_vic_gov_au

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 10:24:31 PM (1 occurrences)
Last logged: 10:24:31 PM

fetch failed for source Yarra Ranges Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/yarra_ranges_vic_gov_au.py", line 79, in fetch next_pickup = article.find(class_="next-service").string.strip() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'strip'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: yarra_ranges_vic_gov_au
      args:
        street_address: ########
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by abnormaliti** [comment]
I am seeing this error too with Yarra Ranges Council.

**Comment by dseeva** [comment]
Updated to latest release and re-configured and now it is working for me.
