### ISSUE TITLE
ZAW Donau-Wald Not working anymore 

### ISSUE THREAD

**Issue by sorted01** [mampfes/hacs_waste_collection_schedule#3120]
### I Have A Problem With:

A specific source

### What's Your Problem

Hey. I love using your addon. Unfortunately „ZAW Donau-Wald“ Source is not working anymore. Any hint how to fix it. Thank you :) have a nice day ✌🏻

### Source (if relevant)

ZAW Donau-Wald

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by franky1808** [comment]
Same with staedteservice_de / city raunheim

**Comment by 5ila5** [comment]
@sorted01 I cannot reproduce this issue, our test cases work fine:

```json
    "Achslach Aign 1 ": {"city": "Achslach", "street": "Aign", "hnr": "1"},
    "Böbrach Bärnerauweg 10A": {
        "city": "Böbrach",
        "street": "Bärnerauweg",
        "hnr": 10,
        "addition": "A",
    },
    "Am Bäckergütl 1, 94094 Malching": {
        "city": "Malching",
        "street": "Am Bäckergütl",
        "hnr": 1,
        "addition": "",
    },
```

Do you see something in your logs? (Settings -> system -> logs)



@franky1808 staedteservice_de works fine for me as well, please also report issues with logs. Please open a separate issue as it's probably not related to this one.

**Comment by sorted01** [comment]
I thought you already fixed it with the last update 😀 it is working fine again.
