### ISSUE TITLE
[Feature]: Landkreis Giforn -  AWIDO

### ISSUE THREAD

**Issue by BenniHeid** [mampfes/hacs_waste_collection_schedule#3123]
### I propose a feature for:

Sources

### Describe your wanted feature

Landkreis Gifhorn now has AWIDO support:
https://gifhorn.app.awido.de/home

**Comment by 5ila5** [comment]
Gifhorn is supported by the awido_de source, you can just `gifhorn` as `customer` argument.

I added it to the REAMDE in #3129, and you will be able to select it in the HA GUI config menu after the next update (not the one I released)
