### ISSUE TITLE
[Bug]: Rushcliffe not updating

### ISSUE THREAD

**Issue by SheriffOfNotts** [mampfes/hacs_waste_collection_schedule#3124]
### I Have A Problem With:

A specific source

### What's Your Problem

Stopped updating with no change to config.

### Source (if relevant)

Rushcliffe

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 28 November 2024 at 07:34:25 (7 occurrences)
Last logged: 09:09:15

fetch failed for source Rushcliffe Brough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/rushcliffe_gov_uk.py", line 105, in fetch raise Exception("Invalid response") Exception: Invalid response
```

### Relevant Configuration

```YAML
Can you let me know where to extract this info.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by Lakey91** [comment]
I'm having problems with Rushcliffe too. Haven't previously used this integration but just tried to set it up and I'm getting "invalid response" when I enter my postcode and address in the correct format.
