### ISSUE TITLE
[Source request]: Thurrock, UK

### ISSUE THREAD

**Issue by stumiles86** [mampfes/hacs_waste_collection_schedule#3128]
Would somebody please tackle adding Thurrock council collection to this integration?

Website: https://www.thurrock.gov.uk/household-bin-collection-days/normal-collections-and-public-holidays

**Comment by RedShuriken** [comment]
hi, i am also looking for this
kind regards

**Comment by 5ila5** [comment]
Added in #3346
This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by stumiles86** [comment]
Street names beginning with A do not work. The URL for street names beginning with A doesn't end with -a unlike all other letters.

I set mine to a random street name beginning with B and it gives an incorrect result (next collection in 184 days. Should be less than 7)
