### ISSUE TITLE
[Bug]: unable to add Dorset council source.

### ISSUE THREAD

**Issue by HumanSkunk** [mampfes/hacs_waste_collection_schedule#3136]
### I Have A Problem With:

A specific source

### What's Your Problem

Trying to configure the integration for Dorset council. When adding it via the integration and following the steps I get the following error:

`The source returned an invalid response: 
"'values'". Please check the provided arguments and try again.`

I have tried to add it manually which generates this error in the log:

 `fetch failed for source Dorset Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/dorset_gov_uk.py", line 41, in fetch json_data["values"][0]["dateNextVisit"], "%Y-%m-%d" ~~~~~~~~~^^^^^^^^^^ KeyError: 'values'`

I am not sure what I am doing wrong here as I followed the guide to get my UPRN. Any help would be much appreciated, I am running the latest version of the integration.

### Source (if relevant)

Dorset Council

### Logs

```Shell
fetch failed for source Dorset Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/dorset_gov_uk.py", line 41, in fetch json_data["values"][0]["dateNextVisit"], "%Y-%m-%d" ~~~~~~~~~^^^^^^^^^^ KeyError: 'values'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: dorset_gov_uk
      args:
        uprn: "1000XXXXXXXXX"
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by HumanSkunk** [comment]
As an update if I use the UPRN provided in the example config of “100040606062” it works and sensors are created, but if I use my unique one found from the website provided then it won’t accept that value. 

The number of numbers are the same, in fact the first 6 are the same. Issue is the collection days provided in the example are not the days my rubbish is collected.

**Comment by dt215git** [comment]
If you use their website, and have the developer tools window open in your browser, you should also be able to see the uprn it's using for the address you entered.

Using one of the script's test case uprn, you see a line like this:
![image](https://github.com/user-attachments/assets/bc124a66-31b0-42bc-ab5c-17a4d7d24ce8)

If it's displaying your collection schedule correctly on the website, then that may be the uprn to use.
The uprn shouldn't be any different to what  findmystreet returns, as each property is meant to have a unique number.

**Comment by HumanSkunk** [comment]
So I am being an idiot. I live in bournemouth and I have only just realised that this is using Dorset Council which is not the same as the BCP council... I have lived here long enough.

Took me a number of lookups to realise postcodes outside of Bournemouth, Poole and Christchurch work with their corresponding UPRN.

I assume BCP is just not part of this integration yet.
