### ISSUE TITLE
Multiple Dutch waste management services use the same API structure

### ISSUE THREAD

**Issue by bo0tzz** [mampfes/hacs_waste_collection_schedule#314]
The code for [hvcgroep_nl](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/hvcgroep_nl.py) should work with very few changes for multiple other Dutch waste management services, including (but not limited to) https://www.mijnblink.nl/wanneer and https://afvalkalender.cyclusnv.nl/.

Unfortunately I won't be able myself to make a code contribution for this anytime soon, but I thought I'd put the knowledge out here anyways for someone else :)

**Comment by mampfes** [comment]
Thanks for the hint. I added support for other services to hvcgroep_nl.
