### ISSUE TITLE
Austria - MuellApp.com

### ISSUE THREAD

**Issue by kathltreiber** [mampfes/hacs_waste_collection_schedule#315]
Hi! Would be nice to implement MuellApp.com too.

https://app.muellapp.com/web-reminder?channel=calendar

THX

**Comment by mampfes** [comment]
Did you try the generic [ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source for that?

As they provide a nice ICS link, it should work.
