### ISSUE TITLE
[Bug]: Republic Services won’t fetch data

### ISSUE THREAD

**Issue by mmstano** [mampfes/hacs_waste_collection_schedule#3152]
### I Have A Problem With:

A specific source

### What's Your Problem

After the last upgrade, the component seemingly worked as per usual. However, after subsequent restarts/reboots, it is unable to fetch information from the source, Republic Services. 

I did try reinstalling the latest version of this component and restarting, but to no avail.

### Source (if relevant)

Republic Services

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 10:31:53 AM (1 occurrences)
Last logged: 10:31:53 AM

fetch failed for source Republic Services: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py", line 102, in fetch if item["serviceImpacted"] is True and item["LOB"] == service: ~~~~^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by mwolter805** [comment]
Having the same issue with Republic Services

**Comment by cvkattookaran** [comment]
Same issue.

**Comment by Jinra** [comment]
Also experiencing this issue

**Comment by mmstano** [comment]
FWIW, I also tried downgrading the component, which did not fix the issue. This leads me to believe Republic changed something on their end.

**Comment by Jinra** [comment]
Created a PR for the fix [here](https://github.com/mampfes/hacs_waste_collection_schedule/pull/3173)

**Comment by mattclair** [comment]
Also having the problem. Downgrade did not solve. Glad I searched before opening an issue myself.
