### ISSUE TITLE
Request for waste managment Stadt Bayreuth and Bayreuth Landkreis

### ISSUE THREAD

**Issue by elbrodark** [mampfes/hacs_waste_collection_schedule#317]
Would be great if you could add support for 
Bayreuth Stadt: https://web.c-trace.de/bayreuthstadt-abfallkalender/
and 
Bayreuth Landkreis: https://www.landkreis-bayreuth.de/buerger-service/online-dienste-und-formulare/abfallwirtschaft/abfuhrkalender/

**Comment by pcwankenobi** [comment]
Hey, every ics file is supported!
Greetings

**Comment by elbrodark** [comment]
Yeah thanks, I thought if its implemented there is no need for updating the calender every year :)

please close if it´s to much work to do :)

**Comment by sti0** [comment]
As Bayreuth (Landkreis) uses abfall_io you can use this implementation to get the data. I added the configuration in #399 so you can use the wizard to gernerate the config.

Bayreuth Stadt seems to use a different implementation. I think its necessary to build a new source for that.

**Comment by mampfes** [comment]
Bayreuth Stadt is using [c_trace_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/c_trace_de.md). Please check if this source is working also for Bayreuth.

**Comment by mampfes** [comment]
Stadt Bayreuth is supported by c_trace_de.
Landkreis Bayreuth is supported by abfall_io.
