### ISSUE TITLE
[Bug]: Poznan source is not working

### ISSUE THREAD

**Issue by czyzniek** [mampfes/hacs_waste_collection_schedule#3183]
### I Have A Problem With:

A specific source

### What's Your Problem

Poznań changed its wast collection schedule page and it breaks current source's implementation.

### Source (if relevant)

poznan_pl

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by kayserjan** [comment]
I have been using this integration for quite some now.
Thank you for your fix! However...
For my location (Szamotulska, Poznań) the next waste collection (mixed trash) state is still _unknown_, while the next pick-up date is tomorrow Dec 24th. Can you please verify what could be the issue?

**Comment by czyzniek** [comment]
Have you `Install update` with `master` version of this hacs? Please use instructions that @5ila5 provided in comment above.

**Comment by kayserjan** [comment]
> Have you `Install update` with `master` version of this hacs? Please use instructions that @5ila5 provided in comment above.

I've removed my previous comment as the is other change I didn't notice - the _dictionary value_ for "trash sensor" changed from "Zmieszane odpady komunalne" to "Odpady zmieszane" and that was my issue. 
Sorry to bother you.

**Comment by czyzniek** [comment]
> > Have you `Install update` with `master` version of this hacs? Please use instructions that @5ila5 provided in comment above.
> 
> I've removed my previous comment as the is other change I didn't notice - the _dictionary value_ for "trash sensor" changed from "Zmieszane odpady komunalne" to "Odpady zmieszane" and that was my issue. Sorry to bother you.

Glad it is working for you 👍
