### ISSUE TITLE
Ku-Ring-Gai council - GeneralWaste not returning data?

### ISSUE THREAD

**Issue by AnthonyBe** [mampfes/hacs_waste_collection_schedule#319]
I'm using **Ku-Ring-Gai** council waste collection and am having problems with 1 of the 3 collection types.
GreenWaste and Recycling are working fine for me, but **GeneralWaste** is always giving me 'unknown' in HA.
I've only been testing this over the last 2 weeks but I've never been able to get GeneralWaste to return anything.

Could someone confirm that this is working correctly? Thanks!

**Comment by dt215git** [comment]
Seems to work okay when using the test script:
```
Testing source kuringgai_nsw_gov_au ...
  found 3 entries for randomHouse
    2022-08-10: General Waste [mdi:trash-can]
    2022-08-17: Recycling [mdi:recycle]
    2022-08-10: Green Waste [mdi:leaf]
  found 3 entries for randomAppartment
    2022-08-05: General Waste [mdi:trash-can]
    2022-08-05: Recycling [mdi:recycle]
    2022-08-05: Green Waste [mdi:leaf]
  found 3 entries for randomMultiunit
    2022-08-04: General Waste [mdi:trash-can]
    2022-08-11: Recycling [mdi:recycle]
    2022-08-04: Green Waste [mdi:leaf]
```

And if I use the example given in the docs, I get this:
![image](https://user-images.githubusercontent.com/86194065/182653033-72f11e3b-8b83-48dc-8cdd-7325eea6e8ee.png)

How have you got the sensor set up, and do you see a collection date for the General Waste when you use the website?

**Comment by AnthonyBe** [comment]
I've played around a bit more with it and managed to get it working.
It's didn't seem to like me using "Garbage" as the alias for "GeneralWaste". As soon as I changed the alias to "General Waste" (i.e. just space between the words) it all started working.

**Comment by mampfes** [comment]
If you use `types `in your sensor configuration, the value has to match the alias exactly.

**Comment by jonwaland** [comment]
@AnthonyBe  - any chance you can post your final config? Trying get this set up, and not getting any errors, but no data
