### ISSUE TITLE
[Bug]: Landkreis Schwäbisch Hall (https://www.lrasha.de/) not working anymore

### ISSUE THREAD

**Issue by Codectory** [mampfes/hacs_waste_collection_schedule#3190]
### I Have A Problem With:

A specific source

### What's Your Problem

https://www.lrasha.de/ has completely changed their calendars. You will only find an Android and iOS app on their page. I've downloaded the app, where you can import the calendars to your local iPhone calendar. Cross 7 is responsible for the calendar. Here is an example for an ics file:
https://api.cross-7.de/public/calendar/399/events/ics?CategoryIds=68352&CategoryIds=68354&CategoryIds=68353&SecondCategoryIds=68313

### Source (if relevant)

lrasha_de

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by DerDreschner** [comment]
@Codectory : Why did you closed the issue? It still doesn't work.
