### ISSUE TITLE
[Source Request]: Coventry City Council

### ISSUE THREAD

**Issue by starlightteresa** [mampfes/hacs_waste_collection_schedule#3194]
### Municipality / Region

West Midlandss

### Collection Calendar Webpage

https://www.coventry.gov.uk/bin-collection-calendar

### Example Address

linwood drive

### Collection Data Format

As ICS/ICAL file

**Comment by tajinder400** [comment]
+1 on this. Cromwell Ln is another example address.

**Comment by 5ila5** [comment]
Added in #3332

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
