### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by bkr1969** [mampfes/hacs_waste_collection_schedule#3200]
### Municipality / Region

Boise, ID USA

### Collection Calendar Webpage

https://www.hardinsanitation.com/ada/schedule/

### Example Address

9451 W. Touchstone Dr., Boise, ID 93709

### Collection Data Format

As ICS/ICAL file

**Comment by 5ila5** [comment]
Boise is supported by the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) there is dedicated documentation for recollect (the service provider they're using). Boise was added to this documentation in #3269 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md)
