### ISSUE TITLE
[Source Request]: North Norfolk District Council

### ISSUE THREAD

**Issue by Si-Hill** [mampfes/hacs_waste_collection_schedule#3231]
### Municipality / Region

Norfolk, United Kingdom

### Collection Calendar Webpage

https://www.north-norfolk.gov.uk/tasks/environmental-services/view-bin-collections-days/

### Example Address

Site uses a postcode then an address finder, my postcode is NR12 8QN so you can see an example of addresses

https://forms.north-norfolk.gov.uk/xforms/Address/Show/CollectionAddress

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
added in #3281

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
