### ISSUE TITLE
[Source Request]: Scenic Rim Council

### ISSUE THREAD

**Issue by Abardenn** [mampfes/hacs_waste_collection_schedule#3261]
### Municipality / Region

Canungra, Australia

### Collection Calendar Webpage

https://www.scenicrim.qld.gov.au/waste-resource-recovery/waste-bin-collection-lookup

### Collection Data Format

Something different (add to additional information)

### Additional Information

CSV: https://srrcwastebinserviceday.blob.core.windows.net/wastebinservicedayexport/WasteBinServiceDay_SRRCWebsiteSearch.csv

**Comment by 5ila5** [comment]
Added in #3267

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
