### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by jstephenson97** [mampfes/hacs_waste_collection_schedule#3265]
### Municipality / Region

Prince George BC

### Collection Calendar Webpage

https://www.princegeorge.ca/city-services/garbage-recycling

### Example Address

5604 Leland Road

### Collection Data Format

As html on a webpage

**Comment by dt215git** [comment]
Looks like the schedule can be processed using the [RecycleCoach](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/recyclecoach_com.md) source.
If you search for your address and then select the iCal option and hit Export you should see a url containing the info you need.
![image](https://github.com/user-attachments/assets/229747e9-033a-42b0-aee5-199da00d324c)
For the example address you gave it looks like this: _calendar.recyclecoach.com/calendar/export/523/PrinceGeorge/zone-z483-z1860.ics_

**523** is the _project_id_, **PrinceGeorge** is the _district_id_, and **zone-z483-z1860** is the _zone_id_.
