### ISSUE TITLE
[Source Request]:  CBC Central Bedfordshire Council - Dunstable

### ISSUE THREAD

**Issue by meaple** [mampfes/hacs_waste_collection_schedule#3273]
### Municipality / Region

Dunstable / Bedfordshire UK

### Collection Calendar Webpage

https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_days#my_bin_collections

### Example Address

1 Brook Close, Dunstable LU6 1HD

### Collection Data Format

As PDF Download

### Additional Information

link to actual calendar for 2025 and postcode LU6 1HD 
https://centralbedfordshirecouncil.sharepoint.com/:b:/r/sites/Communications/Website%20and%20intranet/Website%20Documents/Waste%20Communications%20%26%20Operations/2025%20Bin%20Collection%20Calendars/Calendar%201.pdf?csf=1&web=1&e=kC4xco

**Comment by dt215git** [comment]
A source for [CBC](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/centralbedfordshire_gov_uk.md) already exists, have you tried using that?

**Comment by meaple** [comment]
@dt215git appologise, I've looked for it, but haven't seen this. Thanks
