### ISSUE TITLE
[Source Request]: Royal Borough of Greenwich

### ISSUE THREAD

**Issue by timocov** [mampfes/hacs_waste_collection_schedule#3277]
### Municipality / Region

London, UK

### Example Address

1. https://www.royalgreenwich.gov.uk/info/200171/recycling_and_rubbish/100/find_your_bin_collection_day
1. https://www.royalgreenwich.gov.uk/info/200171/recycling_and_rubbish/2436/black_top_bin_collections

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added by  #3278

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
