### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by tonynieman** [mampfes/hacs_waste_collection_schedule#3289]
https://github.com/mampfes/hacs_waste_collection_schedule/blame/11e625fb521262fd80b10c29b1faac8c5f0ef5c5/doc/source/landkreis_verden_de.md#L56

Hi, 
the link does not work. The slash at the end needs to be removed. 
https://lkv.landkreis-verden.de/WasteManagementVerden/WasteManagementServlet

Rest of the integration works like a charm! Thanks

**Comment by 5ila5** [comment]
Thanks for pointing that out
