### ISSUE TITLE
[Source Request]: Richmond, BC

### ISSUE THREAD

**Issue by swonge** [mampfes/hacs_waste_collection_schedule#3297]
### Municipality / Region

Richmond, BC, Canada

### Collection Calendar Webpage

https://www.richmond.ca/services/recycling-garbage/schedule.htm

### Example Address

10531 Bassett Dr, Richmond

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Richmond, BC uses recollect, which is is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md). @dt215git added Richmond to the dedicated documentation on how to use the ICS source with recollect in #3302 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md)
