### ISSUE TITLE
[Source Request]: Joondalup city council, Western Australia

### ISSUE THREAD

**Issue by lunchplease** [mampfes/hacs_waste_collection_schedule#3298]
### Municipality / Region

Joondalup, Perth, Western Australia

### Collection Calendar Webpage

https://www.joondalup.wa.gov.au/residents/waste-and-recycling/residential-bin-collections

### Example Address

21 Ashburton Drive, Heathridge, WA 6027

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Added in #3312

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
