### ISSUE TITLE
[Source Request]: Hamilton, Ontario, Canada

### ISSUE THREAD

**Issue by jamusbojangles** [mampfes/hacs_waste_collection_schedule#3308]
### Municipality / Region

Hamilton, Ontario, Canada

### Collection Calendar Webpage

https://www.hamilton.ca/home-neighbourhood/garbage-recycling/waste-collection-schedule

### Example Address

17 Galaxy Boulevard, Flamborough

### Collection Data Format

As ICS/ICAL file

**Comment by dt215git** [comment]
That looks to be using the [recyclecoach](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/recyclecoach_com.md) service.

**Comment by 5ila5** [comment]
Hamilton is supported by the [recyclecoach_com source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/recyclecoach_com.md). To configure using the GUI you can select country USA -> Recycle Coach) 
Hamilton will show up in the Canada section (as a link to the Recycle Coach source) after the next update. (it was added in #3311)
