### ISSUE TITLE
[Source Request]: Please add Oldham, Lancashire as a source.

### ISSUE THREAD

**Issue by r4zi3lrrr** [mampfes/hacs_waste_collection_schedule#3310]
### Municipality / Region

Oldham, Lancashire

### Collection Calendar Webpage

https://portal.oldham.gov.uk/bincollectiondates/details?uprn=422000125973

### Example Address

https://portal.oldham.gov.uk/bincollectiondates/details?uprn=422000125973

### Collection Data Format

As html on a webpage

### Additional Information

https://portal.oldham.gov.uk/bincollectiondates/details?uprn=422000125973

**Comment by 5ila5** [comment]
Added in #3314

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>
