### ISSUE TITLE
Adjusted Christmas Collections - Wokingham UK

### ISSUE THREAD

**Issue by dpatterson87** [mampfes/hacs_waste_collection_schedule#3320]
### I Have A Problem With:

A specific source

### What's Your Problem

The dates returned by the integration do not include temporary adjusted dates for the Christmas holiday/New Year period.
These are provided on the source website.

example source UK - Wokingham Borough Council

A previous similar fix #1526 suggests the holiday date adjustments are expected. (Although this is  different source)

### Source (if relevant)

Wokingham_Borough_Council_UK

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
Are you wanting just the dates displayed in the top half of this image, or both the changed and  regular collection dates?

![image](https://github.com/user-attachments/assets/c22641fc-7a61-4672-9187-a35025bce1c5)

**Comment by dpatterson87** [comment]
Hi,
I’d think just the changed dates as these “override” the related regular collection dates during that period. This should then accurately show the actual collection days.

I’m not sure how the underlying calendar dataset reflects these changes.

Thanks

**Comment by 5ila5** [comment]
Fixed in #3324

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by dpatterson87** [comment]
Thanks @5ila5 @dt215git 
Just installed the master version, and while the calendar is correctly displaying the holiday dates, the default card component is not.

![IMG_1741](https://github.com/user-attachments/assets/3f66d8d3-fc35-43a9-9d94-3ac8c8f5b802)
![IMG_1742](https://github.com/user-attachments/assets/3f564d79-27ce-4d3d-86c0-7220f68307ca)
![IMG_1743](https://github.com/user-attachments/assets/499e04ff-df86-449e-ab54-17adc8614b4e)

When reverting to the current release version 2.5, the card component is correctly displayed.

![IMG_1744](https://github.com/user-attachments/assets/d8881d1e-e1e0-45b8-8d5d-21eade569e43)

**Comment by dt215git** [comment]
What entities/states are being used by the card component?
It may be the additional  _"(Christmas Schedule)"_ text is the issue.

**Comment by dpatterson87** [comment]
> What entities/states are being used by the card component? It may be the additional _"(Christmas Schedule)"_ text is the issue.


It’s a single sensor/entity with “upcoming” details format. I include all filter types (since blank doesn’t return all), and the Christmas Schedule types aren’t included.

**Comment by dt215git** [comment]
Just added a Wokingam source to my HA instance using one of the test cases from the script, and the upcoming sensor seems to work for me.

![image](https://github.com/user-attachments/assets/9f2a561c-5b09-4ce6-a926-716089e8af3c)

![image](https://github.com/user-attachments/assets/9cbd3e8b-763f-49be-8391-d7e20b92fb63)

**Comment by dpatterson87** [comment]
@dt215git adding a brand new sensor solved the issue for me - I’m new to HA so will assume it was user error somewhere.
Thank you!
