### ISSUE TITLE
[Source Request]:Please add a source for UK - Melton Mowbray

### ISSUE THREAD

**Issue by sticky1981** [mampfes/hacs_waste_collection_schedule#3325]
### Municipality / Region

Melton Mowbray, United Kingdom

### Collection Calendar Webpage

https://www.melton.gov.uk/waste-and-recycling/household-waste/bin-collection-dates/

### Example Address

LE13 0PB, [select address from list, e.g.]

Pera Business Park, 
Nottingham Road, 
Melton Mowbray, 
LE13 0PB

### Collection Data Format

As documented API

### Additional Information

Providing a postcode then select an address to receive data presented at https://my.melton.gov.uk/collections.
TYVM

**Comment by 5ila5** [comment]
added in #3339

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by sticky1981** [comment]
Thank you!
For anyone Following UPRN = Unique Property Reference Number and can be found with this tool [](https://www.findmyaddress.co.uk/search)
