### ISSUE TITLE
[Service Provider Request] RMG Rohstoff Management GmbH / Kreis Euskirchen / Abfall.io

### ISSUE THREAD

**Issue by AlexSchmitz222** [mampfes/hacs_waste_collection_schedule#340]
Recently, the Kreis Euskirchen changed it's Waste Collector from SCHOENMACKERS to RMG Rohstoffmanagement.

Since then, the MÜLLALARM App gave way for the "new" [Abfallinfoapp](https://play.google.com/store/apps/details?id=de.k4systems.abfallinfoapp) (also provided by Abfall.IO) and the "download .ics" feature has been deleted from the website of my home county, thus I can't extract the required information anymore.

Would it be possible to add RMG Rohstoff Management to WCS?

**Comment by AlexSchmitz222** [comment]
Well I managed to get it to work by intercepting network traffic between the app and the server.
@mampfes If there's anything I can share with you, just tell me :)

**Comment by mampfes** [comment]
Sure, for abfall.io we need the unique district ID:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py

**Comment by mampfes** [comment]
Just to be curios: How did you manage to intercept the app traffic?

**Comment by AlexSchmitz222** [comment]
ADB Debugging (with a rooted Testing device, altough Root Access isn't strictly necessary if you can enable ADB Debugging, IIRC) and HTTP Toolkit :)

**Comment by AlexSchmitz222** [comment]
Btw. this is the App Key of the "Abfallinfoapp" App. I'm not quite sure if it is of any use for you tho.
![Screenshot_20220827-105109.jpg](https://user-images.githubusercontent.com/28763394/187023019-d28e21e0-0270-4bdf-8391-cafff2a80b8f.jpg)

**Comment by mampfes** [comment]
I tried the key2 as district ID, but it doesn't return valid results 👎

**Comment by AlexSchmitz222** [comment]
Where did you scrape the other District IDs from? Maybe I can go back into the app and scrape one there

**Comment by AlexSchmitz222** [comment]
As it seems to me, the App(s) (I've tested "Abfallinfoapp" and compared the setup process to the MüllALARM App, mentioned in the Wizard) do not use such a District ID at all. During the setup process, it uses a completely District ID Format (see here for the MüllALARM App: 
![grafik](https://user-images.githubusercontent.com/28763394/187046213-2aa10831-00b0-4f9d-a943-cc642decd153.png)

And here from the Abfallinfoapp App:
![grafik](https://user-images.githubusercontent.com/28763394/187046246-17c05cab-3e1e-4042-9df2-24490398eaad.png)

I'll try to get a Python Script working

**Comment by AlexSchmitz222** [comment]
Maybe this is kind off personal but do you think it would ok for you to get into some kind off personal contact (Discord etc.) to share some thoughts and Ideas?

I'm kind off new to APIs (especially in Python) and how to use/reverse engineer them and stuff 😅

**Comment by mampfes** [comment]
> Where did you scrape the other District IDs from?
The IDs are extracted by intercepting the network traffic in a brower. Maybe the app(s) use a different API - then we have to write an extra "source".

**Comment by 5ila5** [comment]
I added the [app_abfallplus_de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md) with support for all apps by abfallplus including Abfallinfoapp.
It will be part of release 1.43.0 or is available now as master/git version
