### ISSUE TITLE
Not using HA supported python version

### ISSUE THREAD

**Issue by monoboy-hh** [mampfes/hacs_waste_collection_schedule#345]
HA supports the last two minor versions of Python, that is currently 3.10 and 3.9.
[calendar.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/calendar.py#L118) makes use of Python 3.10 only type hinting features for optional arguments via unions:
`def calc_unique_calendar_id(scraper: Scraper, type: str | None = None):`
The union str | None is not supported as type hint by Python 3.9, hence the waste collection schedule fails to load albeit HA runs on a supported installation.

**Comment by mampfes** [comment]
duplicate of #316
