### ISSUE TITLE
Add source for Germany - Nordwestmecklenburg --> Abfuhrtermine 2022 für den Landkreis 

### ISSUE THREAD

**Issue by SvenMartin81** [mampfes/hacs_waste_collection_schedule#349]
please, can you add this scource?

https://www.geoport-nwm.de/de/abfuhrtermine-geoportal.html

**Comment by mampfes** [comment]
Please try [ics](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source.
