### ISSUE TITLE
Waste collection for awb Karlsruhe

### ISSUE THREAD

**Issue by luebbe** [mampfes/hacs_waste_collection_schedule#37]
AWB Karlsruhe works fine with the ics integration.
URL of web site: https://www.awb-landkreis-karlsruhe.de/startseite/index.php

The URL is:
`https://www.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalte/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=<locationID>&AboID=<customerId>&Fra=RT;RC1;RC2;WT;WC;Schad;BT2;BT1;BC`

and is generated when you are logged in with your credentials.

Replace `<locationID>` and `<customerId>` with your values.

This is the "full featured" URL, which returns all different containers. The `Fra` parameter allows you to specify which containers you are interested in. As far as I could decipher it, the codes mean the following:

| code | meaning | 
| --- | --- |
| RT | Restmülltonne |
| RC1;RC2 | Restmüllcontainer 1/2 |
| WT | Wertstofftonne |
| WC | Wertstoffcontainer |
| Schad | mobile Schadstoffsammlung (*) |
| BT2;BT1| Biotonne 1/2 |
| BC | Biocontainer |

(*) a truck drives to different locations during the day to pick up harmful substances

I have no idea what the 1/2 stands for at Biotonne and Restmülltonne

Changing the `Fra` parameter didn't make a difference for me. It always returns all values.
So you can just use:
`https://www.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalte/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=<locationID>&AboID=<customerId>`
instead.

**Comment by mampfes** [comment]
Thanks for your contribution! I think there are no issues in your description, therefore I would like to close this issue. OK?

**Comment by luebbe** [comment]
Sure, go ahead. I just noticed that some angular brackets in the description were lost, Just fixed this.
