### ISSUE TITLE
Sensor with multiple sources

### ISSUE THREAD

**Issue by LennardPlay** [mampfes/hacs_waste_collection_schedule#373]
My city hired multiple contractors with multiple collection callendars. 
This integration is great to implement one of these, but in sensors under "source_index" I can only specify ONE source.
It should be possible to combine multiple sources into one sensor.

Also Thanks for taking the time to create this integration :)

**Comment by hallidaydaniel** [comment]
This applies particularly when you use static sources too - static sources only allow one waste type, so multiple are needed in many situations, leading to a multi source setup

**Comment by mampfes** [comment]
fixed with #477
