### ISSUE TITLE
Seattle Public Utilities, out of range

### ISSUE THREAD

**Issue by sebirdman** [mampfes/hacs_waste_collection_schedule#380]
Just noticed this in my logs

fetch failed for source Seattle Public Utilities: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/seattle_gov.py", line 49, in fetch prem_code = address_info["address"][0]["premCode"] IndexError: list index out of range

**Comment by sebirdman** [comment]
looks like SPU is having trouble, i can't login to my account with their portal. this may just be what it looks like when the service is down.

**Comment by mampfes** [comment]
Sorry for the delay. With my test data the source if running fine. Maybe the issue was caused by a temporary service outage on their site.

**Comment by mampfes** [comment]
unable to reproduce
