### ISSUE TITLE
Kreis Altenkkirchen (AK) hinzufügen

### ISSUE THREAD

**Issue by e-p-s** [mampfes/hacs_waste_collection_schedule#388]
Danke für dein Addon. Hier kann man die ICS für den Kreis Altenkirchen+Verbandsgemeinden herrunterladen:

https://www.awb-ak.de/de/abfuhrtermine/abfuhrkalender/

**Comment by mampfes** [comment]
Please try [AWIDO](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) source.

**Comment by bbr111** [comment]
@e-p-s

Habe mal mit diesen Daten getestet :  "altenkirchen": {"customer": "awb-ak", "city": "VG Daaden-Herdorf","street":"Mauden"}

Und bekomme Termine geliefert.

**Comment by e-p-s** [comment]
Cool danke. Fürs neue Jahr probier ich ich das direkt aus :)
