### ISSUE TITLE
Issue with AWB-LM (Abfall.io)

### ISSUE THREAD

**Issue by CryPt00n** [mampfes/hacs_waste_collection_schedule#390]
Hi,

found the integration not working with AWB-LM (Abfall.io) out of nowhere. Maybe after an update but tried to roll back to 1.24.0 which not helped me. Renewed the key and checked again all settings but it still fails with the following error:

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:143
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 02:48:17 (1 occurrences)
Last logged: 02:48:17
`fetch failed for source AbfallPlus: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.10/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <br /> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py", line 130, in fetch dates = self._ics.convert(ics_file) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 50, in events found_events += parse_events(content, start=start, end=end) File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 252, in parse_events calendar = Calendar.from_ical(content) File "/usr/local/lib/python3.10/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() File "/usr/local/lib/python3.10/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<br />': <br />`

Home Assistant: 2022.9.6
Waste Collection Schedule: 1.24.0, 1.26.0 & 1.27.0

My Config:
`sources:
    - name: abfall_io
      args:
        key: 0ff491ffdf614d6f34870659c0cXXXXX
        f_id_kommune: XXXX
        f_id_bezirk: XX
        f_id_strasse: XXXX
fetch_time: "04:00"
day_switch_time: "00:00"`

Any idea about this?

**Comment by greenishhhh** [comment]
abfall_io.py line **135**:
```python
ics_file = r.text
```
contains those errors together with the actual data
```
<br />
<b>Notice</b>:  Undefined index: id1984 in <b>/kunden/490784_78549/__global/__autoload/awk_global_termine.class.php</b> on line <b>451</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /kunden/490784_78549/__global/__autoload/awk_global_termine.class.php:451) in <b>/kunden/490784_78549/__api/widgets/publisher/canvas/scripts/export_ics.inc.php</b> on line <b>194</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /kunden/490784_78549/__global/__autoload/awk_global_termine.class.php:451) in <b>/kunden/490784_78549/__api/widgets/publisher/canvas/scripts/export_ics.inc.php</b> on line <b>203</b><br />
```

maybe someone more familiar with the API might know what those mean?

**Comment by greenishhhh** [comment]
adding this to your abfall_io .py will fix it

custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py:134
```python
ics_file = re.sub("\<br.*|\<b.*", "\\r", ics_file)
```

make sure to import re first
```python
import re
```

**Comment by CryPt00n** [comment]
> adding this to your abfall_io .py will fix it
> 
> custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py:134
> 
> ```python
> ics_file = re.sub("\<br.*|\<b.*", "\\r", ics_file)
> ```
> 
> make sure to import re first
> 
> ```python
> import re
> ```



Didn't worked for me. If i add it i get the following error:

```
Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:143
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 16:33:35 (1 occurrences)
Last logged: 16:33:35
fetch failed for source AbfallPlus: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/abfall_io.py", line 133, in fetch ics_file = re.sub("\<br.*|\<b.*", "\\r", ics_file) UnboundLocalError: local variable 'ics_file' referenced before assignment
```

**Comment by greenishhhh** [comment]
Sorry wrong line number, it should look something like this:

```python
# parse ics file
r.encoding = "utf-8"  # requests doesn't guess the encoding correctly

ics_file = r.text
ics_file = re.sub("\<br.*|\<b.*", "\\r", ics_file) #<-- Should be added here

dates = self._ics.convert(ics_file)
```

**Comment by CryPt00n** [comment]
Great, worked! Thank you!

**Comment by greenishhhh** [comment]
This is still an issue when using lm_de in abfall_io
