### ISSUE TITLE
Warning from Homeassistant: no 'version' key

### ISSUE THREAD

**Issue by hhuf** [mampfes/hacs_waste_collection_schedule#41]
After installation via HACS and restart, HA (2021.3.4) complains in the log about:

> No 'version' key in the manifest file for custom integration 'waste_collection_schedule'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'waste_collection_schedule'

Doesn't hinder the use (yet), but probably will sometime in the future.

**Comment by mampfes** [comment]
Please update your waste_collection_schedule integration. It has a version info since v1.0.0 :-)

**Comment by hhuf** [comment]
No idea why I had the old one (as I installed via HACS, not by hand), but after updating HA and the external components via HACS  I now have version 1.3.0, and HA (2021.4.1) doesn't complain anymore => closing ticket.
