### ISSUE TITLE
AVL Ludwigsburg: multiple download links for ICS

### ISSUE THREAD

**Issue by armin-gh** [mampfes/hacs_waste_collection_schedule#422]
Hi
the code for AVL Ludwigsburg assumes a field for the street in cases where a city has multiple parts with a separate calendar, however in the city where I live, the AVL web page shows 4 download links with ICS-Calendars and ( as a user on web page) you have to select the link for your part of the city.

As a workaround I modified the code to handle this

- initial loop to put all ICS-Links into a list
- second loop to look into all ICS-links and store the first link containing the "street"-parameter for ICS-Download ( if there is more than one link)
- break after the first match

instead of
```
        ics_link = ""
        for download in downloads:
            link = download.get("href")
            if ".ics" in link:
                ics_link = link

```
use
```
        ics_link = ""
        ics_num = 0
        ics_hreflinks = []
        for download in downloads:
            link = download.get("href")
            if ".ics" in link:
                ics_num +=1
                ics_hreflinks.append(link)

        for link in ics_hreflinks:
            if ics_num > 1:
                if ".ics" in link and self._street.lower() in link.lower():
                    ics_link = link
                    break
            else:
                if ".ics" in link:
                    ics_link = link
                    break

```
just in case it helps somebody else...

Armin

**Comment by mampfes** [comment]
Could you please give a hint to which city/address this special rule applies? I would like to add a test case for that.

**Comment by armin-gh** [comment]
Hi
sure, that is Ditzingen.
Currently I'm using this 
```
waste_collection_schedule:
  sources:
    - name: avl_ludwigsburg_de
      args:
        city: Ditzingen
        street: Stadt

```
But I just see that avl-ludwigsburg obviously changed their UI at https://www.avl-ludwigsburg.de/kundenportal/abfallkalender/ and now have a new UI with dropdowns for city, street and house number.

Not sure if they kept the old way to access the calendars, the URL seems to hit a 404

Armin

**Comment by armin-gh** [comment]
ah, sorry, use "Marktstraße" for testing the calendar for the main part of the city
"Weissacher Straße" in Ditzingen-Heimerdingen for example  has a different schedule for the yellow bin(LVP) and green bin(Paper)

Received the paper calendar yesterday, they really printed the exact address on the calendar and then delivered a separate sheet of paper to every address.... no wonder it's getting that expensive...

**Comment by mampfes** [comment]
Sorry, I'm a little bit lost. I tried Ditzingen with Marktstraße and Weissacher Straße. In both cases the webpage offered me just one ICS file download.

But then I saw that they also offer a "ical-Kalenderabo" which is basically a (hopefully persistant) link to an ICS file. This can be used together with the [ics](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source. Then we don't need a dedicated *AVL Ludwigsburg* source any more. Could you please try this out?

**Comment by armin-gh** [comment]
Hi 
yes, they changed the UI maybe 3 or weeks ago, prior to that I received four links as described in my initial post in early November, now you enter the full address and it generates an ICS-Link.

Wasn't aware of the ICS-Source, **works for me.**

The URL is a bit different now compared to what you have in the test case for the ICS Source
`https://kundenportal.avl-lb.de/WasteManagementLudwigsburg/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=950230001&AboID=8188&Fra=BT;RT;PT;LT;GT
`
StandortID seems to be the address
AboID is a sequence number they generate when you create the link
Fra=BT;RT;PT;LT;GT are the different types of trash bins selected when generating the link

Armin

**Comment by mampfes** [comment]
Closed, solution is to use ICS source.
