### ISSUE TITLE
Add support for Landkreis Hersfeld Rotenburg

### ISSUE THREAD

**Issue by michael2063** [mampfes/hacs_waste_collection_schedule#435]
Hi,

I want just too ask if it could be possible to add:
https://awido.cubefour.de/Customer/azv-hef-rof/mobile/#load

There are a variety of selection options for the individual communities and districts there

Here is an example for Bad Hersfeld district 4
https://awido.cubefour.de//Customer/azv-hef-rof/KalenderICS.aspx?oid=00000000-0000-0000-0000-000000000006&jahr=2023&reminder=1.19:00&fraktionen=1,2,3,5

The location seems to be coded in the "oid" and "fraktionen" are the individual pickup types

If this is possible, this would be realy great.
Thanks very much.

**Comment by mampfes** [comment]
Please try [AWIDO](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) source.

**Comment by mampfes** [comment]
Available via awido source.
