### ISSUE TITLE
Disable Calendar integration?

### ISSUE THREAD

**Issue by bbr111** [mampfes/hacs_waste_collection_schedule#44]
Is it possible to disable calendar integration?

**Comment by mampfes** [comment]
No (not yet). Just to be curious: Why do you want to disable the calender?

**Comment by bbr111** [comment]
happy easter, 

i don't use the calender yet, and want to keep HA as minimal as possible.
this adds an entry to the menu that was not there before.

**Comment by mampfes** [comment]
There is already an option to edit the sidebar items in Lovelace:
https://github.com/home-assistant/frontend/pull/6755
Does this work for you?

**Comment by bbr111** [comment]
yes
