### ISSUE TITLE
ICS: One to three types in one summary

### ISSUE THREAD

**Issue by fugazzy** [mampfes/hacs_waste_collection_schedule#451]
I have problems getting my 4 types of waste from one ics file, because of the structure of the ics:
(1 to 3 or even 4 types per row entry (sumary) )
e.g.
`BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//stadtservice-bruehl//stadtservice-bruehl.de//DE
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
SUMMARY:Biotonne (braun) - An Hornsgarten 99 (Bezirk: 8P) - Stadtservice Brühl
DTSTART;VALUE=DATE:20221130
DTEND;VALUE=DATE:20221201
UID:2022-11-30-0-@stadtservice-bruehl.de
DTSTAMP:20221129T111543
DESCRIPTION:
LOCATION:Brühl
URL;VALUE=URI:https://stadtservice-bruehl.de
BEGIN:VALARM
TRIGGER:-PT360M
ACTION:DISPLAY
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Hausmüll (grau), Gelber Sack (gelb) - An Hornsgarten 99 (Bezirk: 8P) - Stadtservice Brühl
DTSTART;VALUE=DATE:20221207
DTEND;VALUE=DATE:20221208
UID:2022-12-07-0-@stadtservice-bruehl.de
DTSTAMP:20221129T111543
DESCRIPTION:
LOCATION:Brühl
URL;VALUE=URI:https://stadtservice-bruehl.de
BEGIN:VALARM
TRIGGER:-PT360M
ACTION:DISPLAY
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Biotonne (braun) - An Hornsgarten 99 (Bezirk: 8P) - Stadtservice Brühl
DTSTART;VALUE=DATE:20221214
DTEND;VALUE=DATE:20221215
UID:2022-12-14-0-@stadtservice-bruehl.de
DTSTAMP:20221129T111543
DESCRIPTION:
LOCATION:Brühl
URL;VALUE=URI:https://stadtservice-bruehl.de
BEGIN:VALARM
TRIGGER:-PT360M
ACTION:DISPLAY
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Hausmüll (grau), Gelber Sack (gelb) - An Hornsgarten 99 (Bezirk: 8P) - Stadtservice Brühl
DTSTART;VALUE=DATE:20221221
DTEND;VALUE=DATE:20221222
UID:2022-12-21-0-@stadtservice-bruehl.de
DTSTAMP:20221129T111543
DESCRIPTION:
LOCATION:Brühl
URL;VALUE=URI:https://stadtservice-bruehl.de
BEGIN:VALARM
TRIGGER:-PT360M
ACTION:DISPLAY
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Altpapier (blau) - An Hornsgarten 99 (Bezirk: 8P) - Stadtservice Brühl
DTSTART;VALUE=DATE:20221227
DTEND;VALUE=DATE:20221228
UID:2022-12-27-0-@stadtservice-bruehl.de
DTSTAMP:20221129T111543
DESCRIPTION:
LOCATION:Brühl
URL;VALUE=URI:https://stadtservice-bruehl.de
BEGIN:VALARM
TRIGGER:-PT360M
ACTION:DISPLAY
END:VALARM
END:VEVENT
BEGIN:VEVENT
SUMMARY:Biotonne (braun) - An Hornsgarten 99 (Bezirk: 8P) - Stadtservice Brühl
DTSTART;VALUE=DATE:20221229
DTEND;VALUE=DATE:20221230
UID:2022-12-29-0-@stadtservice-bruehl.de
DTSTAMP:20221129T111543
DESCRIPTION:
LOCATION:Brühl
URL;VALUE=URI:https://stadtservice-bruehl.de
BEGIN:VALARM
TRIGGER:-PT360M
ACTION:DISPLAY
END:VALARM
END:VEVENT`

**Comment by dt215git** [comment]
A similar issue was discussed in #271, maybe that approach can be adapted to separate out the individual collections?

**Comment by mampfes** [comment]
Could you solve this issue? If yes, it would be nice if you could share your solution so that we could add it to the examples in the ICS documentation.

**Comment by dt215git** [comment]
```yaml
sources:
  - name: ics
    args:
      file: "./MyStuff/test.ics" #replace with path downloaded ics file
      regex: "(.*) - An Hornsgarten"
      split_at: ", "
      version: 2
```


![image](https://user-images.githubusercontent.com/86194065/207955355-b71b8d1c-21c6-406f-9290-f8218a559afa.png)

**Comment by fugazzy** [comment]
Sorry for the late reply, I was too busy. Now I can confirm, that this solution works nice!
It seems that some now created an even better solution for my town: PR https://github.com/mampfes/hacs_waste_collection_schedule/pull/491 should solve it
