### ISSUE TITLE
Stevenage Borough Council - Failing to get data

### ISSUE THREAD

**Issue by simonk1969** [mampfes/hacs_waste_collection_schedule#455]
Stevenage Borough Council was working great but over the last three days it seems to be failing to get the data. I've copied the error from the log below.

Thanks Simon :-)

```
This error originated from a custom integration.

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:143
Integration: waste_collection_schedule (documentation)
First occurred: 2 December 2022 at 09:51:37 (3 occurrences)
Last logged: 01:46:50

fetch failed for source Stevenage Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/stevenage_gov_uk.py", line 81, in fetch if collection[2] == "Recycling collection": IndexError: list index out of range
```

**Comment by dt215git** [comment]
That error suggests it's not finding anything in whatever response is coming back (or maybe it's not getting a response). Is your collection schedule info available on their website?

**Comment by simonk1969** [comment]
I've finally got round to looking a bit further into this and it appears there website is currently not showing the future dates directly on the webpage as it was, only the link to download PDF calendar.
I've enquired with Stevenage Borough Council why they are no longer showing this/can they fix it.
![image](https://user-images.githubusercontent.com/24876982/207969171-b0a79950-1213-4d05-a5b2-c037df390da0.png)
