### ISSUE TITLE
Enhancement Request - Hills Council NSW

### ISSUE THREAD

**Issue by scrytch** [mampfes/hacs_waste_collection_schedule#46]
Hi,

I'm wondering if it would be possible to add the Hill Council NSW to this as a data source?

They have a lookup here: https://www.thehills.nsw.gov.au/Services/For-Residents/Waste-Recycling/Check-which-bin-to-put-out but not sure how or if this could be used to get the info needed?

Thanks,
Shane.

**Comment by mampfes** [comment]
Yes, thats possible. Please see release 1.4.0.

**Comment by scrytch** [comment]
Wow! Thankyou so much.

**Comment by mampfes** [comment]
You're welcome. Please give it a star if you like it.
