### ISSUE TITLE
Request for Kreis Northeim

### ISSUE THREAD

**Issue by SvenBrauns** [mampfes/hacs_waste_collection_schedule#462]
Please add the waste collection schedule for Kreis Northeim Germany:
https://abfall.nerdbridge.de/
Provides .ics and .json Data for every city in the Kreis with multiple types of waste to sellect.

**Comment by mampfes** [comment]
Should work with [ics](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md).
