### ISSUE TITLE
if statement and value.date.strftime("%a")

### ISSUE THREAD

**Issue by pjasinsk** [mampfes/hacs_waste_collection_schedule#466]
Hi, I have a problem with the if statement. 
value_template: '{{value.date.strftime("%a")}}' works OK, but I would like to translete the English day of week shortcut into Polish. I tried this:
value_template:  >-
          {% set d = states('value.date.strftime("%a")') | string %}
          {% if d == 'Sat' %} sobota
          {% elif d == 'Sun' %} niedziela
          {% endif %}
And some more but unsuccesfully. Can you please help me solve this problem somehow?

**Comment by dt215git** [comment]
I don't think you need the single quotes in `{% set d = states('value.date.strftime("%a")') | string %}`.
Try this, but substituting the Polish days for A, B, C...

```yaml
  value_template: >
    {% set d = value.date.strftime("%a") | string %}
    {% if d == "Mon" %}
        A
    {% elif d == "Tue" %}
        B
    {% elif d == "Wed" %}
        C
    {% elif d == "Thu" %}
        D
    {% elif d == "Fri" %}
        E
    {% elif d == "Sat" %}
        F
    {% elif d == "Sun" %}
        G
    {% else %}
        Error Processing Days
    {% endif %}
```

**Comment by pjasinsk** [comment]
It is not working :(

missed comma between flow collection entries (237:22)

 234 |   - platform: waste_collection_schedule
 235 |     name: next_bulky_collection
 236 |     details_format: appointment_types
 237 |     value_template: {% set d = value.date.strftime(" ...
----------------------------^
 238 |     {% if d == "Mon" %}
 239 |         A

**Comment by pjasinsk** [comment]
I tried also with single quotation and I was able to save it but it didn't work anyway. 
I saved it like this:
value_template: '{% set d = value.date.strftime("%a") | string %}
    {% if d == "Mon" %}
        A
    {% elif d == "Tue" %}
        B
    {% elif d == "Wed" %}
        C
    {% elif d == "Thu" %}
        D
    {% elif d == "Fri" %}
        E
    {% elif d == "Sat" %}
        F
    {% elif d == "Sun" %}
        G
    {% else %}
        Error Processing Days
    {% endif %}'

**Comment by dt215git** [comment]
This is what I set up - next collection is on a Tuesday, and it's correctly converting that to a 'B'

```yaml
- platform: waste_collection_schedule
  source_index: 0
  name: BinSchedule
  details_format: appointment_types
  date_template: '{{value.date.strftime("%A %d %B %Y")}}'
  value_template: >
    {% set d = value.date.strftime("%a") | string %}
    {% if d == "Mon" %}
        A
    {% elif d == "Tue" %}
        B
    {% elif d == "Wed" %}
        C
    {% elif d == "Thu" %}
        D
    {% elif d == "Fri" %}
        E
    {% elif d == "Sat" %}
        F
    {% elif d == "Sun" %}
        G
    {% else %}
        Error Asigning Days
    {% endif %}
  add_days_to: true
```

![image](https://user-images.githubusercontent.com/86194065/207309031-8402fa16-8d60-47e0-9b7a-99667adbb6c5.png)

Is that not what you are trying to do?

**Comment by pjasinsk** [comment]
Yes, this is exactly what I wanted to achieve. Thanks a lot for your help. When I pasted yours code I understood that there was some spaces missing in beginning of mine.
