### ISSUE TITLE
ALBA Berlin / abfall.io not working properly

### ISSUE THREAD

**Issue by tinkerberlin** [mampfes/hacs_waste_collection_schedule#486]
Hi there, 

I have my "Wertstoff"-garbage provided through Alba in Berlin. Unfortunately they don't have a "native" API that data can be pulled through so it runs through abfall.io.

I have pulled the data by quering a search for my adress on Alba's website and have input that data in my confi.yaml file. Doing so initially provides the correct result. 

HOWEVER: For some reason it only pulls in the first pick-up after the date that I edit the config.yaml file on. Once that first pick-up-instance has passed, the sensor changes to unavailable and no more pick-ups are pulled. 

I've "XXX"'ed my personal info; the BSR-sensors work perfectly 100% of the time (as of right now).

> waste_collection_schedule:
> sources:
>     - name: bsr_de
>       args:
>         abf_strasse: "XXX"
>         abf_hausnr: XX
>       customize:
>         - type: "Abholung Hausmüll"
>           alias: Hausabfall
>           icon: mdi:trash-can
>         - type: "Abholung Biogut"
>           alias: Biogut
>           icon: mdi:recycle
>     - name: abfall_io
>       args:
>         key: "9583a2fa1df97ed95363382c73b41b1b"
>         f_id_kommune: 3227
>         f_id_strasse: XXX
>         f_id_bezirk: 0
>         f_id_strasse_hnr: XXX
>         f_abfallarten:
>           - 127
>       customize:
>         - type: "127"
>           alias: Wertstofftonne
>           icon: mdi:recycle-variant
>   fetch_time: "04:00"
>   day_switch_time: "08:00"
> 

Any help figuring this out would be greatly appreciated!

Thank you!

**Comment by felixfischer** [comment]
I have the same problem. The collection dates are visible in the calendar, but the custom sensor (see below) only returns "unknown".

```
- platform: waste_collection_schedule
  name: naechste_abholung_altpapier
  types:
    - Papiertonne
  add_days_to: True
  value_template: >
    {%- if value.daysTo == 0 %}heute
    {%- elif value.daysTo == 1 %}morgen
    {%- else %}in {{value.daysTo}} Tagen{% endif %}
```

Is there anything I can do to debug this?

**Comment by felixfischer** [comment]
It might have to do with the data provided by Alba. I cannot currently obtain the schedule for 2023 manually from their website, only for the current year. Maybe this is going to fix itself.

**Comment by mampfes** [comment]
> The collection dates are visible in the calendar

What do you mean with this? Do you see collection dates for the next year in the calendar? Then it would be strange if the sensor just shows unavailable/unknown. But if there no data at all (because ALBA doesn't yet provide the data for next year), it is ok that the sensors shows unavailable.

**Comment by felixfischer** [comment]
> The collection dates are visible in the calendar

@mampfes This is no longer true. I think I had something like a race condition: When I first checked this in the morning today, it showed today's collection. Now there's nothing in the calendar, since it's past `day_switch_time`.

**Comment by mampfes** [comment]
OK, then this issue is most likely caused by the missing data. Please check the webpage periodically and as soon as data is available there, the sensor should also show valid data again.

**Comment by mampfes** [comment]
Any update on this? @felixfischer @tinkerberlin

**Comment by mampfes** [comment]
Closed because no feedback.

**Comment by tinkerberlin** [comment]
Hallo @mampfes . Sorry for not getting back to you sooner!!

It seems that whatever happend fixed the problem. At least since about Christmas / new year the system worked again. 

Thanks!
