### ISSUE TITLE
Request for provider, SRV Sweden

### ISSUE THREAD

**Issue by aikkon-bacon** [mampfes/hacs_waste_collection_schedule#487]
Can we please add this to the source list?

https://www.srvatervinning.se/sophamtning/privat/hamtinformation-och-driftstorningar

Thanks

**Comment by mampfes** [comment]
They are using a JSON API, therefore implementing a source should be quite easy. Feel free to submit a PR :-)

**Comment by aikkon-bacon** [comment]
Sorry am new to this, whats a PR ?

**Comment by bbr111** [comment]
@aikkon-bacon Could you provide 2-3 example addresses?

**Comment by bbr111** [comment]
PR #518

**Comment by mampfes** [comment]
fixed in #518

**Comment by aikkon-bacon** [comment]
> @aikkon-bacon Could you provide 2-3 example addresses?

Hanvedens allé 78
146 34 Tullinge

Skogsmulles Väg 22
146 34 Tullinge
