### ISSUE TITLE
is it possible to work with * or contains() or regular expressions? 

### ISSUE THREAD

**Issue by Mart-Muc** [mampfes/hacs_waste_collection_schedule#490]
Dear all,

Um solch lange Bezeichner zu vermeiden, wie z.B.
type: 'Wertstoffsäcke in Stadt Regensburg: Luise-Giese-Straße (PLZ: 93055)'

würde ich gerne mit *, Platzhaltern, oder expressions arbeiten.

Ginge das? könnte ich ein Beispiel bekommen?

Danke, Mart
(Benutzung mit Stadtwerke München: https://www.awm-muenchen.de/entsorgen/abfuhrkalender

**Comment by mampfes** [comment]
Are you using the `ics` source? If yes, you can use a regular expression like (not tested!) like:
`regex: "(.*) in Stadt Regensburg"`
There are a lot of examples in the [ics](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#regular-expression) docu.

**Comment by Mart-Muc** [comment]
Danke, 
damit lassen sich auch die Sondertermine vom AWM München erfassen.
regex schneidet alles vor und hinter den Mülltonnenbezeichnungen ab:
        regex: "^.*(Restmülltonne|Biotonne|Papiertonne).*$"

somit bitte in die ics docu aufnehmen:

waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: Müllkalender
      args:
        url: "https://www.awm-muenchen.de/entsorgen/abfuhrkalender?tx_awmabfuhrkalender_abfuhrkalender%5Bhausnummer%5D=2&tx_awmabfuhrkalender_abfuhrkalender%5Bleerungszyklus%5D%5BB%5D=1%2F2%3BU&tx_awmabfuhrkalender_abfuhrkalender%5Bleerungszyklus%5D%5BP%5D=1%2F2%3BU&tx_awmabfuhrkalender_abfuhrkalender%5Bleerungszyklus%5D%5BR%5D=1%2F2%3BG&tx_awmabfuhrkalender_abfuhrkalender%5Bsection%5D=ics&tx_awmabfuhrkalender_abfuhrkalender%5Bsinglestandplatz%5D=false&tx_awmabfuhrkalender_abfuhrkalender%5Bstandplatzwahl%5D=true&tx_awmabfuhrkalender_abfuhrkalender%5Bstellplatz%5D%5Bbio%5D=70030981&tx_awmabfuhrkalender_abfuhrkalender%5Bstellplatz%5D%5Bpapier%5D=70030981&tx_awmabfuhrkalender_abfuhrkalender%5Bstellplatz%5D%5Brestmuell%5D=70030981&tx_awmabfuhrkalender_abfuhrkalender%5Bstrasse%5D=weg&tx_awmabfuhrkalender_abfuhrkalender%5Byear%5D={%Y}}"
        regex: "^.*(Restmülltonne|Biotonne|Papiertonne).*$"
        version: 1
      customize:
        - type: "Restmülltonne"
          alias: Restmülltonne
          icon: mdi:trash-can
        - type: "Biotonne"
          alias: Biotonne
          icon: mdi:flower-outline
        - type: "Papiertonne"
          alias: Papiertonne
          icon: mdi:trash-can-outline
  fetch_time: "04:23"
  day_switch_time: "09:30"
