### ISSUE TITLE
Recurring events in ICS from owncloud does not seem to work

### ISSUE THREAD

**Issue by ZeGuigui** [mampfes/hacs_waste_collection_schedule#5]
My waste collector does not provide ICS so I created a calendar in my owncloud instance and used the export URL in configuration.yaml. The file is parsed but recurring events does not seem to be "expanded".

[Here is my ICS file for tests](https://github.com/mampfes/hacs_waste_collection_schedule/files/4602944/owncloud.ics.zip)

Screenshot from HA : 
<img width="427" alt="Capture d’écran 2020-05-09 à 09 46 12" src="https://user-images.githubusercontent.com/13727111/81467595-fa361300-91d9-11ea-829c-4ec2839f4727.png">

If I create the event in the futur (with RRULE) it is shown in HA (as for "encombrants" in the test file)

**Comment by mampfes** [comment]
@ZeGuigui Did the fix work for you?

**Comment by ZeGuigui** [comment]
Yes it does!
Thanks a lot
