### ISSUE TITLE
Seattle provider only showing one date, two weeks from now

### ISSUE THREAD

**Issue by millercentral** [mampfes/hacs_waste_collection_schedule#50]
Hi, I'm excited to integrate this component in my HA setup and was thrilled to see a Seattle Public Utilities provider. However, I'm having some trouble getting it to work correctly.

I configured as documented with my street number, direction and street name (aka '123 E Nerd St'). When I load the component it shows as I have Garbage, Recycle and Yard Waste pickup on May 5, which is inaccurate (day is correct, but no Recycle that day), and it misses that we have pickup today (Apr 21), and next Weds (Apr 28) and the weds after May 5. When I enter my address on the Seattle website (https://myutilities.seattle.gov/eportal/#/accountlookup/calendar), everything looks correct.

It appears @sguermond submitted this data provider. Would you be able to help me debug what I'm doing wrong? Thanks so much for the efforts here!

**Comment by gabosom** [comment]
+1, @sguermond , we'll need your help :) I did the digging but I'm not proficient with python (or Home Assistant development) so I won't be of much help coding here, but I figured out the issue.

looking at the code, you're using API calls from https://www.seattle.gov/UTIL/WARP/CollectionCalendar, however they are actually not returning the right information. for example, I used the Carmona Court street address from your test case (1127 17TH AVE E) and the [WARP API](https://www.seattle.gov/UTIL/WARP/CollectionCalendar) returns different info than looking at it in the [collection calendar](https://myutilities.seattle.gov/eportal/#/solidwasteservices).

This is WARP:
![image](https://user-images.githubusercontent.com/926425/116191297-ee8c7680-a6e0-11eb-979c-85a4e4558ca3.png)

This is the collection calendar:
![image](https://user-images.githubusercontent.com/926425/116191335-f9470b80-a6e0-11eb-8cef-613367d8d095.png)

I took a look at the API calls made by the collection calendar that would yield the right result and packed the fiddler file [here](https://1drv.ms/u/s!Anr3RaOnEg1cnsQP21uiPoXAMApRqA?e=zW2t7u). Essentially what happens is:

- find account ID for a given address
- get token (uses basic auth and the customerID = guest 
-- subsequent requests include this bearer token in the headrs
- get account summary
- get calendar

I wish I could help, but I think you have everything you need here.

**Comment by gabosom** [comment]
I got the code working that pulls the right schedule - will try to clone repro and send a PR in a couple of dyas

**Comment by mampfes** [comment]
fixed in #51

**Comment by gabosom** [comment]
@millercentral  - did you update to the latest version?  it's working great for me now, curious if it is for you as well.

**Comment by millercentral** [comment]
I did and it works great, thanks so much @gabsom! So convenient having thiis as part of HA, thank you!

**Comment by sguermond** [comment]
@millercentral & @gabosom Thanks for catching that and fixing it so quickly! I found the API in another repo (https://github.com/mannkind/seattlewaste2mqtt) and did notice that it wasn't always returning correctly, but I was pretty stumped as to why.

I'll send in a request to the city to see what's up with the WARP API.
