### ISSUE TITLE
AWB Oldenburg not working anymore

### ISSUE THREAD

**Issue by philippsandhaus** [mampfes/hacs_waste_collection_schedule#539]
The old endpoint `https://services.oldenburg.de/index.php` does not work anymore. A request to the endpoint does not lead to an ICS file, but to a HTML-Error Page. A brief look into the website shows that at least here a new endpoint is used. The following snippet works for me:
``` { .python }
API_URL = "https://www.oldenburg.de/startseite/leben-umwelt/awb/abfall-a-z/abfuhrkalender.html"
HOUSE_NUMBER = "4"
args = {
            "tx_collectioncalendar_abfuhrkalender[actiom]": "exportIcs",
            "tx_collectioncalendar_abfuhrkalender[controller]": "Frontend\Export",
            "tx_collectioncalendar_abfuhrkalender[houseNumber]": str(HOUSE_NUMBER).encode("utf-8"),
            "tx_collectioncalendar_abfuhrkalender[street]": "1367",
            "tx_collectioncalendar_abfuhrkalender[wasteTypes][1]": 1,
            "tx_collectioncalendar_abfuhrkalender[wasteTypes][2]": 2,
            "tx_collectioncalendar_abfuhrkalender[wasteTypes][3]": 3,
            "tx_collectioncalendar_abfuhrkalender[wasteTypes][4]": 4,
            "tx_collectioncalendar_abfuhrkalender[wasteTypes][5]": 5,
            "tx_collectioncalendar_abfuhrkalender[year]": 2023        
}

args = urllib.parse.urlencode(args, quote_via=urllib.parse.quote)
r = requests.get(API_URL, params=args)
print(r)
``` 

However, there are now two problems:

1. The API does not expect the street in text format anymore, but as an ID now (1367 in this case). You could probably maintain a mapping for street name and id.
2. You now have to provide a parameter year. Thus, there has to be decided at which time of the year the current year or the next year should be requested. Or both?

@chbartsch As you have written the original code, what are your thoughts?

**Comment by mampfes** [comment]
@chbartsch Could you please help?

**Comment by chbartsch** [comment]
Unfortunately they changed the API. :/

> 1. The API does not expect the street in text format anymore, but as an ID now (1367 in this case). You could probably maintain a mapping for street name and id.

You are right: A lookup table for street->id would be best or maybe even the only possibility?! But how to get this table? Since I'm not a web developer: Do you have any idea on how to extract this information automatically from the oldenburg.de website? I just checked the drop-down menu for "street" in Chrome's Web-Dev-View and I can see all the entries but so far haven't found out how to extract them.

> 2. You now have to provide a parameter year. Thus, there has to be decided at which time of the year the current year or the next year should be requested. Or both?

Current year + checking if there is already data for the next year sounds good. :)

**Comment by mampfes** [comment]
There are a lot of examples which already get data from selection list. There are 2 populars way, one is to use `BeautifulSoup`, the other one is `HTMLParser`.

**Comment by chbartsch** [comment]
> There are a lot of examples which already get data from selection list. There are 2 populars way, one is to use `BeautifulSoup`, the other one is `HTMLParser`.

Thanks. I will look into it.

**Comment by dt215git** [comment]
There are probably more efficient ways of doing this, but here's a quick attempt:

```python
import requests
from bs4 import BeautifulSoup

s = requests.Session()
r = s.get("https://www.oldenburg.de/startseite/leben-umwelt/awb/abfall-a-z/abfuhrkalender.html")

soup = BeautifulSoup(r.text, "html.parser")
items = soup.find_all("option")
items = items[2:] # first two values are not street addresses so remove them

streets = []
ids = []
for item in items:
    streets.append(item.text)  # street name
    ids.append(item.attrs["value"])  # dropdown value
mapping = {k:v for (k,v) in zip(streets, ids)}
print(mapping)
```

This gives:

```bash
{'91er-Str.': '1', 'A-v-D-Hülshoff-Str': '2', 'Aalweg': '3', 'Abraham': '4', 'Achterdiek': '5', ...
'Zum Offizierskasino': '1499', 'Züricher Str.': '1500', 'Zuschlag': '1501', 'Zweigstr.': '1502', 'Zypressenweg': '1503'}
```

and for comparison from the page source:

```html
<option value="1">91er-Str.</option>
<option value="2">A-v-D-Hülshoff-Str</option>
<option value="3">Aalweg</option>
<option value="4">Abraham</option>
<option value="5">Achterdiek</option>
...
<option value="1499">Zum Offizierskasino</option>
<option value="1500">Züricher Str.</option>
<option value="1501">Zuschlag</option>
<option value="1502">Zweigstr.</option>
<option value="1503">Zypressenweg</option>
```

**Comment by chbartsch** [comment]
Thanks @dt215git! That made it easy.

I just put out a pull request. Please try it out --> https://github.com/mampfes/hacs_waste_collection_schedule/pull/568

**Comment by philippsandhaus** [comment]
Great, I can confirm it works for me!
