### ISSUE TITLE
Problem adding new source

### ISSUE THREAD

**Issue by Alfiegerner** [mampfes/hacs_waste_collection_schedule#54]
Hi,

I'm adding a new source and have it working fine provided I give it the name of an existing source.  If I give it it's own name I get an error from the scraper:

```

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:223
Integration: waste_collection_schedule
First occurred: 5:29:29 PM (1 occurrences)
Last logged: 5:29:29 PM

source not found: aucklandcouncil_govt_nz
```

Do you know if I'm missing something?  

Thanks.

**Comment by mampfes** [comment]
Sorry that I didn't respond earlier. Somehow I didn't get notification for this repo since 2 months.

The scraper name has to match a file with the ending .py in the source directory. In your example:
`hacs_waste_collection_schedule/custom_components/waste_collection_schedule/waste_collection_schedule/source/aucklandcouncil_govt_nz.py`

**Comment by Alfiegerner** [comment]
Thanks for looking at this @mampfes . I'm seeing this error after creating the appropriately named file.

Here's my config:

```
 waste_collection_schedule:
  day_switch_time: "17:00"
  sources:
#    - name: wastenet_org_nz
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12342453293
      customize:
        - type: rubbish
          alias: Rubbish
          icon: mdi:trash-can
        - type: recycle
          alias: Recycling
          icon: mdi:recycle
```

And here's a directory listing of my source directory:
```
pi@homesystems:~/hass/custom_components/waste_collection_schedule/waste_collection_schedule/source$ ls -l
-rw-r--r-- 1 homeassistant homeassistant 3378 May 24 17:25 auklandcouncil_govt_nz.py
-rw-r--r-- 1 homeassistant homeassistant 1174 May 24 16:07 awbkoeln_de.py
-rw-r--r-- 1 homeassistant homeassistant 2938 May 24 16:07 bak_wastenet_org_nz.py
-rw-r--r-- 1 homeassistant homeassistant 3735 May 24 16:07 brisbane_qld_gov_au.py
-rw-r--r-- 1 homeassistant homeassistant 3174 May 24 16:07 bsr_de.py
-rw-r--r-- 1 homeassistant homeassistant  893 May 24 16:07 example.py
-rw-r--r-- 1 homeassistant homeassistant 7132 May 24 16:07 ics.py
-rw-r--r-- 1 homeassistant homeassistant 1154 May 24 16:07 jumomind_de.py
-rw-r--r-- 1 homeassistant homeassistant 4683 May 24 16:07 muellmax_de.py
-rw-r--r-- 1 homeassistant homeassistant 1736 May 24 16:07 pgh_st.py
-rw-r--r-- 1 homeassistant homeassistant 4321 May 24 16:07 seattle_gov.py
-rw-r--r-- 1 homeassistant homeassistant  983 May 24 16:07 stadtreinigung_hamburg.py
-rw-r--r-- 1 homeassistant homeassistant 3816 May 24 16:07 stuttgart_de.py
-rw-r--r-- 1 homeassistant homeassistant 2763 May 24 16:07 thehills_nsw_gov_au.py
-rw-r--r-- 1 homeassistant homeassistant 3378 May 24 17:25 wastenet_org_nz.py
```

I get the error:

```Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:223
Integration: waste_collection_schedule
First occurred: 5:29:29 PM (1 occurrences)
Last logged: 5:29:29 PM

source not found: aucklandcouncil_govt_nz
```
[auklandcouncil_govt_nz.zip](https://github.com/mampfes/hacs_waste_collection_schedule/files/6760532/auklandcouncil_govt_nz.zip)

If I change the contents of an existing file to match my new source, and change my config to match the existing source, it works fine.

Any ideas?  I've tried clearing the __pycache__ folder but still no joy.

I have a nested folder stucture of custom_components/waste_collection_schedule/waste_collection_schedule/ and tried copying source to the higher folder too, but same result.

I've attached the file in case it helps, any thoughts appreciated.

**Comment by Alfiegerner** [comment]
Thanks @mampfes, was a silly typo all along, will make PR today.

**Comment by mampfes** [comment]
Closed because PR ongoing.
