### ISSUE TITLE
Verify configuration keeps loading

### ISSUE THREAD

**Issue by pippo93** [mampfes/hacs_waste_collection_schedule#548]
Hi, I’ve installed the last version. The configuration is made through the yaml exactly as described in the example for sttic sources. But the “verify configuration” on Home Assistant keeps loading for hours with no results…

**Comment by mampfes** [comment]
Duplicate of #220?

**Comment by pippo93** [comment]
Thx
`sudo pip install recurring_ical_events` solved the issue.
IMHO it’s better if you add this info in the main page to avoid headaches…

**Comment by mampfes** [comment]
Good idea. I added a statement to the Known Issues section.
