### ISSUE TITLE
Specify local file path information in docs

### ISSUE THREAD

**Issue by bcutter** [mampfes/hacs_waste_collection_schedule#553]
Neither
- https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/faq.md

nor
- https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#configuration-variables
- https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#local-file

specify, where the file has to be stored.

1. Is "calendar.ics" meant to be the share `/config/calendar.ics`?
2. What would the `file:` parameter need to look like when the file is e. g. located in `/config/customfolder/calendar.ics` ?

**Comment by mampfes** [comment]
The problem with local files and relative paths is, that it also depends on the Home Assistant installation type (core vs supervised vs OS vs ...). Therefore it is not easy to give a single answer. But it would be nice if you could help, e.g. by creating a PR which describes your environment and solution.

**Comment by bcutter** [comment]
Running on HA OS I'm using `file: "www/abfall/abfuhrkalender_home.ics"` now. That information basically originates from the linked YT video (you referenced).

**Comment by mampfes** [comment]
@bcutter Please check if the docu is correct for your environment.

**Comment by bcutter** [comment]
Looking good now (except one typo in "Therefore place the ics file their." ==> their --> there).

I will close it, thx for updating the docs 👍🏼
