### ISSUE TITLE
Request: Add East Herts Council Collection Service

### ISSUE THREAD

**Issue by davidmul87** [mampfes/hacs_waste_collection_schedule#554]
Hi, 

Would be hugely appreciated (and happy to sponsor) if someone could add East Herts Council to this add-in? 

https://uhte-wrp.whitespacews.com/?Track=2023/01/03/RFDIDYNQ2287Q&serviceID=A&seq=1#!

Regards,
David

**Comment by gingemonster** [comment]
now released https://github.com/mampfes/hacs_waste_collection_schedule/releases/tag/1.34.0
