### ISSUE TITLE
FR: Add support for LK Freudenstadt in the script

### ISSUE THREAD

**Issue by Vedeneb** [mampfes/hacs_waste_collection_schedule#56]
Hi,

could you possibly add the Landkreis Freudenstadt to the Wizard Script?

It works fine by adding the ICS manually, however it would make setup easier if Freudenstadt was supported by the script.

https://www.awb-fds.de/privatkunden/privatkunden-abfallkalender/

Thanks!

**Comment by mampfes** [comment]
Sorry that I didn't respond earlier. Somehow I didn't get notification for this repo since 2 months.

I will take a look at this.

**Comment by mampfes** [comment]
Fixed in 757503ed8f9f071d4d6d216f45c1596a2ca9d503
