### ISSUE TITLE
Request for Southampton, UK

### ISSUE THREAD

**Issue by andrewbpowers** [mampfes/hacs_waste_collection_schedule#570]
Link to the Bin collection calendar Southampton City Council page: 
https://www.southampton.gov.uk/bins-recycling/bins/collections/

Thank you very much in advance!

**Comment by andrewbpowers** [comment]
Link to the Bin collection calendar Southampton City Council page: [https://www.southampton.gov.uk/bins-recycling/bins/collections/](https://www.southampton.gov.uk/bins-recycling/bins/collections/)

**Comment by dt215git** [comment]
Think I've got this working - will test a few more addresses and then create the PR.

**Comment by mampfes** [comment]
fixed by #573
