### ISSUE TITLE
Request for AWS Schaumburg

### ISSUE THREAD

**Issue by marcgeurts** [mampfes/hacs_waste_collection_schedule#574]
Could someone integrate Abfallwirtschaft Schaumburg?

Link to calendar: https://aws-shg.de/WasteManagementSchaumburg.html?action=wasteDisposalServices

Thanks in advance!

**Comment by mampfes** [comment]
athos based, see awn_de, bielefeld_de, bmv_at, meinawb_de, regioentsorgung_de, rh_entsorgung_de

**Comment by mampfes** [comment]
You can also try the ICS source, because they obviously provide an persistent URL:
![image](https://user-images.githubusercontent.com/375950/210976322-f50f10fc-d86a-4f10-b7b5-63825342f0be.png)
