### ISSUE TITLE
Request for Newcastle under Lyme - United Kingdom

### ISSUE THREAD

**Issue by Malawigold** [mampfes/hacs_waste_collection_schedule#580]
Hi all, ive tried forking and creating the newcatle under lyme source, but im failing, is there anyone that could help create it?

**Comment by dt215git** [comment]
Is it the [Newcastle-under-Lyme Borough Council](https://www.newcastle-staffs.gov.uk/waste/bin-collection-day-finder) service provider you're referring to?

**Comment by Malawigold** [comment]
Hi, yes thats the one!

**Comment by dt215git** [comment]
PR #583 created.

**Comment by mampfes** [comment]
fixed by #583
