### ISSUE TITLE
fetch failed for source ICS: TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by fuuman** [mampfes/hacs_waste_collection_schedule#584]
The new ICS file for this year is not working any more. Unfortunately my city changed something because the new ICS file has a completly different structure than the 2022 file.

The logger says:
`fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 182, in fetch return self.fetch_url(self._url, self._params) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 203, in fetch_url return self._convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 214, in _convert dates = self._ics.convert(data) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 50, in events found_events += parse_events(content, start=start, end=end) File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 356, in parse_events for dt in rule.between(after, end, inc=True): File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 283, in between for i in gen: File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 1401, in _iter while exlist and exlist[0] < ritem: File "/usr/local/lib/python3.10/site-packages/dateutil/rrule.py", line 1338, in __lt__ return self.dt < other.dt TypeError: can't compare offset-naive and offset-aware datetimes`

The ICS file for 2023: https://www.bergheim.de/downloads/25594/Kalender%20von%20Abfallkalender%20Berghein%20Kenten%202023/forced

I have no clue how to debug the problem? What could I do to fix the problem?

**Comment by dt215git** [comment]
Does the fix mentioned in #575, work for you?

**Comment by fuuman** [comment]
There was a lot of configuration to change because they updated the types, but yes, in the end `version: 1` at least gave me something in HA to work with. Fixed, thanks :)
