### ISSUE TITLE
I miss one with C-Trace.de/WZV

### ISSUE THREAD

**Issue by Acey-yo** [mampfes/hacs_waste_collection_schedule#585]
Hello guys,

I just switched from ics to C-Trace.de. Since then, unfortunately, it no longer shows me all the bins. I'm missing the residual waste, everything else is displayed as usual. Can someone help me?

**Comment by mampfes** [comment]
Do you see the missing waste type in the HA calendar? If yes, it is probably an issue of your sensor configuration --> check if the values below `types`are matching exactly (they are also case sensisitive).

If not, do you see the missing waste type if you use the web browers to with your address?

**Comment by Acey-yo** [comment]
No, it cannot be seen in the calendar or can find in the sensors. I have already checked everything, but unfortunately without success.

Yes, on the WZV website, where I used to load my ics file for HA, everything is in there and it works great.
