### ISSUE TITLE
Error with Service Provider Stadtreinigung Leipzig / stadtreinigung-leipzig.de

### ISSUE THREAD

**Issue by Fereauje** [mampfes/hacs_waste_collection_schedule#589]
Hi everyone,
Since 03.01.2023 (this is where I noticed it), WCS can no longer retrieve data from Stadtwerke Leipzig.
The following error is displayed:

fetch failed for source Stadtreinigung Leipzig: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtreinigung_leipzig_de.py", line 34, in fetch raise Exception(f"street not found: {self._street}") Exception: street not found: Pflugkstraße

My configuration.yaml:
waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: Pflugkstraße
        house_number: 1
      calendar_title: Abfallkalender

I've been trying around here for a few days, but I can't find a solution to the problem. Is it possible that the API has been changed/defective?
Thanks for your help...

**Comment by mampfes** [comment]
@FoxXxHater This fix has been merged, but released yet. Are you using an official release?

**Comment by FoxXxHater** [comment]
My latest version is the 1.33.0 from the HACS Store... i mean yes it should be the official image
![image](https://user-images.githubusercontent.com/54017453/213096476-e7220c62-92ba-47c0-b8e5-110ebe99618d.png)

**Comment by mampfes** [comment]
Ok, the fix is not included in this release. Please wait for the next release - probably on the weekend.

**Comment by FoxXxHater** [comment]
i hope, thanks
