### ISSUE TITLE
Integration Grosswangen_CH

### ISSUE THREAD

**Issue by stibe881** [mampfes/hacs_waste_collection_schedule#597]
For me, these sensors are displayed as "not available". I have this in the configuration.yaml:
waste_collection_schedule:
  sources:
    - name: grosswangen_ch
      args:
        args: None

The description says the following. But this doesn't work because of the indentation of "args".
waste_collection_schedule:
  sources:
    - name: grosswangen_ch
      args:
      args: None

The following error is displayed in the sensor properties:
![Unbenannt](https://user-images.githubusercontent.com/24219649/211479057-f1e26e31-16b6-483b-ae73-c9e41eb38bfc.PNG)

**Comment by bbr111** [comment]
are there any errors in the log?
is the calendar showing the waste collection?

**Comment by stibe881** [comment]
I didn't find any error in the log.
The waste collection is not displayed in the calendar.

**Comment by bbr111** [comment]
hm, difficult to support. without any errors or logs.
please check the spaces in the yaml file.

my test is still ok.
python3 test_sources.py -s grosswangen_ch
Testing source grosswangen_ch ...
  found 58 entries for TEST

if i add the source in my HA Config the calender is displayed

**Comment by stibe881** [comment]
This i have in my configuration.yaml:
![E8C7BB71-1332-4529-A043-5CE347184C82](https://user-images.githubusercontent.com/24219649/211631420-35e5ae8e-28f5-4c5c-b726-b43b35a20fbf.jpeg)

and this my calendar:
![B798B713-D93C-4284-BCD5-BE11C656F351](https://user-images.githubusercontent.com/24219649/211631586-eaf2b20f-9580-487e-abf2-4a292198f07e.jpeg)

**Comment by bbr111** [comment]
```yaml
waste_collection_schedule:
  sources:
    - name: grosswangen_ch
      args:
        args: None
      calendar_title: grosswangen
```

This is my yaml code.

**Comment by mampfes** [comment]
#587

**Comment by mampfes** [comment]
I removed the dummy argument in #599. Please try again. Example in the docu is also up-to-date.

**Comment by mampfes** [comment]
With that I see the following data in the calendar:
![image](https://user-images.githubusercontent.com/375950/211633944-a267aa0e-ff3f-49f7-b5a5-b877f4ec34f7.png)

**Comment by bbr111** [comment]
the same in my configuration.

**Comment by stibe881** [comment]
i don‘t now where is the problem.
I have now cooy/paste the new code from the docu. 
but the calendar shows me nothing.

**Comment by dt215git** [comment]
Is the calendar pulling and displaying a cached page rather than refreshing from new?

The other thing to check is whether the calendar is enabled:
`Settings` -> `Devices & Services` -> `Entities` and search for 'calendar'. If you select the checkbox against the calendar name you should see this appear, select `Enable Selected` and then reload the calendar page

![image](https://user-images.githubusercontent.com/86194065/211641712-d0d3b7d3-a12e-4ec1-8662-4c977f7eef14.png)

**Comment by mampfes** [comment]
I don't no see a "Grosswangen" calendar in your screen shot. Did you restart Home Assistant after adding waste_collection_schedule?

**Comment by stibe881** [comment]
> 

There isn't the Calendar "Grosswangen".

**Comment by stibe881** [comment]
I had tested it with "A-region_ch". It worked with this one.

**Comment by dt215git** [comment]
This may be a silly question... can you see the `grosswangen_ch.py` file on your HA?

The latest release is 1.33.0 from 4 days ago. Grosswangen_ch was merged yesterday.

That might explain the lack of a calendar on your system if you're running 1.33.0. Test system using GitHub's latest set of files would include it and therefore generate the calendar.

**Comment by dt215git** [comment]
All the .py files for the supported sources should be in `/config/custom_components/waste_collection_schedule/waste_collection_schedule/source`

**Comment by stibe881** [comment]
OMG. I am a big idiot. That was the problem. Thanks very much @dt215git, @mampfes  and @bbr111
