### ISSUE TITLE
2 different sources in next collection

### ISSUE THREAD

**Issue by kollegahd** [mampfes/hacs_waste_collection_schedule#607]
Is it possible to include data from 2 different sources in the next collection? With several sources a source_index must be indicated yes?!

next collection displays only the data from source_index: 0

` # next collection
  - platform: waste_collection_schedule
    source_index: 0
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'`

**Comment by kollegahd** [comment]
next collection displays only the data from source_index: 0

**Comment by mampfes** [comment]
Yes it is. Unfortunately the documentation was lost during the refactoring of the docu. 

`source_index: [0, 1]`

**Comment by kollegahd** [comment]
it works. Thanks for the quick reply and the great project <3
