### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by SeriousPat** [mampfes/hacs_waste_collection_schedule#619]
Hi,
i use hassio.
installing hacs_waste_collection_schedule with hacs.
i can see my entries in the calendar, but there are no entities.
i can only find the entitie: Müllmax, calendar.mullmax, calendar.mullmax

**Comment by mampfes** [comment]
Did you define any sensors? 

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-source-sensors

**Comment by SeriousPat** [comment]
THX and sorry, it was late yesterday
