### ISSUE TITLE
Berlin Recycling

### ISSUE THREAD

**Issue by splitbrain** [mampfes/hacs_waste_collection_schedule#62]
[Berlin Recycling](berlin-recycling.de) is handling my paper waste. Unfortunately their collection dates are hidden behind a login and need to parsed from their HTML.

I found this Python implementation based on BeautifulSoup: https://github.com/belzetrigger/domoticz-BR/blob/master/brHelper.py

I'm not sure how easy it would be to integrate. I'd be happy to help with debugging and testing, but I fear my python isn't good enough to implement it myself.

**Comment by mampfes** [comment]
Hi, yes - the example should help to create a source for waste_collection_schedule. This would be the first source that requires authentication. Anyway - adding a new source may take a while.
