### ISSUE TITLE
FeatureRequest: native support of garbage collection card

### ISSUE THREAD

**Issue by sir106** [mampfes/hacs_waste_collection_schedule#624]
this very nice custom component only lacks a lovelace card like the garbage collection card. Until there is a dedicated lovelace card for this integration, the garbage collection card could be used.

Unfortunately the lovelace garbage collection card (https://github.com/amaximus/garbage-collection-card) is only supported with a workaround mentioned in the FAQ. Please provide the missing attributes needed for the lovelace garbage collection card by default.

the Garbage Collection custom component (https://github.com/bruxy70/Garbage-Collection/) provides these attributes:
days: 8
last_collection: 2022-11-03T22:31:40.416622+01:00
last_updated: 2023-01-18T00:00:02.213730+01:00
next_date: 2023-01-26T00:00:00+01:00
device_class: garbage_collection__schedule
icon: mdi:recycle
friendly_name: Altpapier

**Comment by dt215git** [comment]
From the  bruxby Garbage Collection [README](https://github.com/bruxy70/Garbage-Collection/)
![image](https://user-images.githubusercontent.com/86194065/213527801-601b03bc-ce2b-421d-a42d-aa6b8bbae9f0.png)
Not sure how much milage there'd be in doing this.

**Comment by sir106** [comment]
true; but it is for the integration component only - the lovelace garbage-collection-card has not deprecation marker.

**Comment by mampfes** [comment]
Not to be fixed. Please request garbage-collection-card to adapt to waste_collection_schedule. There is already a detail_format `generic` which provides all necessary information.
