### ISSUE TITLE
Request: Potsdam DE

### ISSUE THREAD

**Issue by MatthiasFriese** [mampfes/hacs_waste_collection_schedule#625]
Could someone integrate STEP Potsdam ?

They don't provide an ics file to download, just some selection and a pdf download. https://www.potsdam.de/abfallkalender-fuer-potsdam#Ak2023 

I also found a json file with the data for every district and street.
https://www.geben-und-nehmen-markt.de/abfallkalender/potsdam/2023/page-data/index/page-data.json

Thanks.

**Comment by thomasgregg** [comment]
Also would be interested.

**Comment by 5ila5** [comment]
I worked on this a bit a while ago. The data is a pain to parse. I'm currently looking again into this

**Comment by 5ila5** [comment]
Added by #976
The source will be part of the next release (1.40) or is available as the git/master version now.

**Comment by MatthiasFriese** [comment]
Great news, thanks

**Comment by thomasgregg** [comment]
Great. Would really like to try it. Any hint on how to configure it would be highly appreciated.

**Comment by 5ila5** [comment]
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/potsdam_de.md
