### ISSUE TITLE
Request Service Provider Glasgow City Council

### ISSUE THREAD

**Issue by SamB-GB** [mampfes/hacs_waste_collection_schedule#626]
Please could I request to add Glasgow City Council as a service provider.

Start Page:
https://www.glasgow.gov.uk/forms/refuseandrecyclingcalendar/AddressSearch.aspx

Example Postcode:
G13 1AF

URL for results:
https://www.glasgow.gov.uk/forms/refuseandrecyclingcalendar/CollectionsCalendar.aspx?UPRN=906700099060

**Comment by mampfes** [comment]
fix by #634
