### ISSUE TITLE
Error on setup - unexpected post_code

### ISSUE THREAD

**Issue by Patrick-UK** [mampfes/hacs_waste_collection_schedule#627]
I am trying to setup Central Bedfordshire and getting the below error.
I have checked everything and I am not sure if I have something wrong in my config.

waste_collection_schedule:
    sources:
    - name: centralbedfordshire_gov_uk
      args:
        post_code: "LU6XXX"
        house_name: "99 Any Street" (matches the website)

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:196
Integration: waste_collection_schedule (documentation)
First occurred: 8:10:48 AM (1 occurrences)
Last logged: 8:10:48 AM

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 200, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
TypeError: Source.__init__() got an unexpected keyword argument 'post_code'

**Comment by bbr111** [comment]
@Patrick-UK 

try postcode instead of post_code

**Comment by bbr111** [comment]
@gingemonster 
the code says: 
```python
class Source:
    def __init__(self, postcode=None, house_name=None):
        self._postcode = postcode
        self._house_name = house_name
```

and the docu this:
```yaml
waste_collection_schedule:
    sources:
    - name: centralbedfordshire_gov_uk
      args:
        post_code: POST_CODE
        house_name: HOUSE_NAME
        version: 1
```

**Comment by Patrick-UK** [comment]
thanks, now loading

> @Patrick-UK
> 
> try postcode instead of post_code

Thanks now loading.
