### ISSUE TITLE
ICS File not loaded after update to core-2021.8.6

### ISSUE THREAD

**Issue by derwolff** [mampfes/hacs_waste_collection_schedule#64]
Hi,
after update to supervisor-2021.06.8, I get this message:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:130
Integration: waste_collection_schedule (documentation)
First occurred: 11:29:13 (1 occurrences)
Last logged: 11:29:13

fetch failed for source <waste_collection_schedule.source.ics.Source object at 0x6f527490>: module 'recurring_ical_events' has no attribute 'of'

configuration.yaml:
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "/config/downloads/waste_collection/cal.ics"
  day_switch_time: "09:00"

**Comment by mampfes** [comment]
Hi, this is strange because the custom component has nothing to do with the supervisor.

Does this problem persists over a reboot of the host? If yes, please provide your ics file.

**Comment by derwolff** [comment]
Sorry, I mean the update from core-2021.8.5 to latest core-2021.8.6 from today. I manually go back to core-2021.8.5 , and the issue is solved. Direct downloading the ICS File from web with parameter "URL" in config is also not working.  Very strange.

**Comment by derwolff** [comment]
[cal.zip](https://github.com/mampfes/hacs_waste_collection_schedule/files/6973066/cal.zip)

**Comment by mampfes** [comment]
Sorry, I wasn't able to reproduce the issue. I tried a core-only system and also a hass os system. Both worked without issues with your cal.ics.

**Comment by derwolff** [comment]
Thanks for analysing. After update to core-2021.8.7 the issue is solved in my environment.
