### ISSUE TITLE
Support for awhas.de (Landkreis Haßberge)

### ISSUE THREAD

**Issue by zoesn89** [mampfes/hacs_waste_collection_schedule#645]
Hey,

it would be great, if someone could add the source awhas.de. After creating an account on https://portal.awhas.de/uebersicht.html, you'll get a ical url. I could provide a url by private message, if needed :)

Thanks in advance!
Felix

**Comment by dt215git** [comment]
If you have to register for the service before using it, then it's going to be difficult to incorporate test cases to confirm functionality in the future.

With a private url like you'd described, the [iCal/ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) option should allow you to integrate the service.
