### ISSUE TITLE
Stadtreinigung Hamburg

### ISSUE THREAD

**Issue by msiemers** [mampfes/hacs_waste_collection_schedule#648]
Moin moin, 

ich möchte diese tolle Lösung für meinen Müllkalender der Stadtreinigung Hamburg verwenden. Dafür habe ich das mitgelieferte Python Script statreinigung-hamburg.py verwendet. Leider habe ich dabei ein Problem. Und zwar soll ich bei der Einrichtung einmal ein Search String for Street eingeben. Wenn ich das mache, unsere Strasse fängt mit Sül an, erhalte ich nach EIngabe keine Liste aus der ich die richtige Strasse auswählen kann. Ich habe es auch mit Suel probiert leider ohne Erfolg. Kann mir hier eventuell jemand helfen? Mache ich etwas falsch, oder funktioniert das Script eventuell nicht richtig?

Danke ! 

Good Morning,

I would like to use this great solution for my garbage calendar for the Hamburg city cleaning department. For this I used the supplied Python script statreinigung-hamburg.py. Unfortunately I have a problem with this. I am supposed to enter a search string for street during setup. If I do that, our street starts with Sül, I don't get a list from which I can select the right street after entering it. I also tried Suel with no success. Can someone help me here? Am I doing something wrong, or is the script not working properly?

Thanks !

**Comment by mampfes** [comment]
Hi,

am Besten einfach der Anleitung folgen, dann sollte es klappen: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/stadtreinigung_hamburg.md

Also https://www.stadtreinigung.hamburg/abfuhrkalender/ öffnen und Adresse eingeben. Für "Sülfelder Weg" bekomme ich z.B. folgende URL: `https://www.stadtreinigung.hamburg/abfuhrkalender/?tx_srh_pickups%5Bstreet%5D=442&tx_srh_pickups%5Bhousenumber%5D=1761&tx_srh_pickups%5BisAllowedOwner%5D=1#c3376`.

D.h. die gesuchte `hnId` ist `1761`.

**Comment by mampfes** [comment]
Sieht gut aus. Wenn die Einrückung richtig ist (das sieht man leider nicht so wie Du es kopiert hast), solltest Du Abholtermine im HA Kalender sehen.

Jetzt fehlt noch (mindestens) ein Sensor, z.B.:

```
# Müllkalender Standtreinigung Hamburg
waste_collection_schedule:
  sources:
    - name: stadtreinigung_hamburg
      args:
        hnId: 17564

sensor:
  - platform: waste_collection_schedule
    name: abholtermine

```

**Comment by msiemers** [comment]
Ok, das habe ich gerade schon durch probieren hinbekommen. In Hamburg heißen die Mülltonnen leider ein wenig blöd. Zum Beispiel "Abfuhr schwarze Restmülltonne". Das wird, wenn ich das in einer Karte im Dashboard anzeigen lasse doof dargestellt. Kann man das noch anpassen?

**Comment by mampfes** [comment]
Ja, kann man. Stichwort alias in der Doku.

**Comment by msiemers** [comment]
Danke. Du kannst den Issue schließen.
