### ISSUE TITLE
Request: South Derbyshire District Council, United Kingdom

### ISSUE THREAD

**Issue by Novem30** [mampfes/hacs_waste_collection_schedule#650]
Great project, thank you all very much.

It would be great to add South Derbyshire District Council in the United Kingdom bin collection schedule.

Bin collection dates can be found here:
https://www.southderbyshire.gov.uk/our-services/recycling-bins-and-waste/bin-collection-dates

They also have a site here that gives bins collection dates, planning applications (that would be a cool addon, hehe), councillors, and references the UPRN of the house:
https://maps.southderbyshire.gov.uk/iShareLive.Web/atmyresponsivecouncil.aspx

Example postcode: DE65 6FT

Also, according to this website the CMS South Derbyshire are using is 'web-labs' used on other council websites so maybe it'll be useful for them too. I'm not knowledgeable enough to know though: https://www.viko.co.uk/blog/local-government-cms/

Thanks in advance!

**Comment by mampfes** [comment]
fixed by #651
