### ISSUE TITLE
Request: Amber Valley Borough Council - UK

### ISSUE THREAD

**Issue by jasontems** [mampfes/hacs_waste_collection_schedule#652]
Hi all

Just stumbled upon this plugin - cracking job!

Could I request for Amber Valley to be added?

Website: https://www.ambervalley.gov.uk/rubbish-waste-and-recycling/bin-collection-dates/

Postcode: DE56 2UH (space required)

Which references the following: https://info.ambervalley.gov.uk/WebServices/AVBCFeeds/WasteCollectionJSON.asmx/GetCollectionDetailsByUPRN?uprn=100030011598

Many thanks!

**Comment by mampfes** [comment]
fixed by #654
