### ISSUE TITLE
Request: AWB LK KA

### ISSUE THREAD

**Issue by EternalWebmedia** [mampfes/hacs_waste_collection_schedule#657]
Greetings,

It'd be great if you could add the AWB LK Karlsruhe to your list.
You can pull the events without registration from here: https://www.awb-landkreis-karlsruhe.de/start/wissen/abfuhrkalender.html

I'll try to use the ical option, but I'd like to see it working without, if it's possible.

Regards,
Felix

**Comment by mampfes** [comment]
AWB LK Karlsruhe provides a "ical-Kalenderabo", therefore the ICS source is normally sufficient and we don't have to write a dedicated source.

Please let us know if ICS works for you.
