### ISSUE TITLE
Request for Lake Macquarie Council, Australia

### ISSUE THREAD

**Issue by markszulc** [mampfes/hacs_waste_collection_schedule#658]
Could you please add support for Lake Mac council? 
Schedule look up is currently via this form;
https://www.lakemac.com.au/For-residents/Waste-and-recycling/When-are-your-bins-collected

**Comment by bbr111** [comment]
Please provide an example address

**Comment by markszulc** [comment]
Sure thing.. sorry, it autocompletes but feel free to use something like;
386 Pacific Highway, MURRAYS BEACH  NSW  2281

**Comment by dt215git** [comment]
Looks like a very similar _ocapi_ backend to [Ku-Ring-Gai](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/kuringgai_nsw_gov_au.py)

**Comment by bbr111** [comment]
ok, i wrote something new already.

**Comment by bbr111** [comment]
pr #659

**Comment by mampfes** [comment]
fixed by #659

**Comment by markszulc** [comment]
You guys are awesome. Im assuming a need to wait for the next release in order access, or does the configs pull through separately?

**Comment by bbr111** [comment]
Wait for the next Release or just Copy the new source File top your local source folder.
