### ISSUE TITLE
please add "Landkreis Fürth"

### ISSUE THREAD

**Issue by DanielR92** [mampfes/hacs_waste_collection_schedule#666]
Hello,

please add this region of Fürth.
https://www.landkreis-fuerth.de/zuhause-im-landkreis/umwelt-und-bauen/abfallwirtschaft/abfallwirtschaft-alt/abfuhrplaene-termine/abfuhrplan.html

for example: https://www.landkreis-fuerth.de/zuhause-im-landkreis/umwelt-und-bauen/abfallwirtschaft/abfallwirtschaft-alt/abfuhrplaene-termine/abfuhrplan.html?tx_athos_xml%5Bcontroller%5D=Xml&cHash=d81dfb8c0099c8fabb54e10df3c52e0e

**Comment by DanielR92** [comment]
It exist already a part of Fürth "#602". But it is in a different way...

**Comment by mampfes** [comment]
Landkreis Fuehrt provides a "ical-Kalenderabo", therefore this [ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source should work.

**Comment by DanielR92** [comment]
Yes I use already the ICS source. But my problem is, that only the "Bio" is working. The rest wont display. 
![grafik](https://user-images.githubusercontent.com/25644396/217442545-1232695b-7b6c-4820-8a91-27e18ea3e410.png)
Here you can see my problem. 

I try many things out, I have the last version updated so far. 
But it is not possoble to get the data throw.

I will send next time my changes. 
Thanks in advance. =)

**Comment by mampfes** [comment]
I tested Landkreis Fuerth with the ICS source and returns 4 different waste types:
![image](https://user-images.githubusercontent.com/375950/217451018-98e0c485-e198-46de-92e4-0d869df4451b.png)
![image](https://user-images.githubusercontent.com/375950/217451086-cd01927f-2353-46ff-840f-f8b43d4e43c5.png)
![image](https://user-images.githubusercontent.com/375950/217451147-3d88975e-a79b-456f-81a6-5bbef87c5dc7.png)

You can check if you see all waste types in the Home Assistant Calendar. If yes, it is a just a problem of your source or sensor configuration. You can use `alias` in the `customize` section of the source configuration to rename the long waste type names.

**Comment by DanielR92** [comment]
That is correct in my calendar I can see all information. 
Hmm then I need to check the sensors again...  Thank for the information. :)

**Comment by mampfes** [comment]
Waste Collection Schedule polls the ICS file every day. So, if the link stays the same (that depends on your service provider), it will work forever :-)

**Comment by DanielR92** [comment]
> Waste Collection Schedule polls the ICS file every day. So, if the link stays the same (that depends on your service provider), it will work forever :-)

Thats a idea, is it enough when I replace the static ics with the url?

And my problem are at now not solved. :(

That is my config:

`waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/WasteManagementServiceServlet.ics"
      customize:
        - type: Biotonne
          alias: BioTonne
          icon: mdi:flower-outline
        - type: AbfallGelberSack
          alias: Gelbe Tonne und -Container (1\,1cbm)
          icon: mdi:recycle
        - type: AbfallRestmuell
          alias: Restmuelltonne und -container (1\,1cbm)
          icon: mdi:trash-can
        - type: AbfallPapierTonne
          alias: Papiertonne und -container (1\,1cbm)
          icon: mdi:trash-can-outline
        - type: Restmüll 4-wöchtl.
          show: false
          
  # Müll Temrine
sensor:   
  - platform: waste_collection_schedule
    name: AbfallRestmuell
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Restmuelltonne und -container (1\,1cbm)

  - platform: waste_collection_schedule
    name: AbfallPapierTonne
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Papiertonne und -container (1\,1cbm)

  - platform: waste_collection_schedule
    name: AbfallGelberSack
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Gelbe Tonne und -Container (1\,1cbm)

  - platform: waste_collection_schedule
    name: AbfallBiotonne
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - BioTonne

  - platform: waste_collection_schedule
    name: AbfallRestmuellnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Restmuelltonne und -container (1\,1cbm)

  - platform: waste_collection_schedule
    name: AbfallPapierTonnenext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Papiertonne und -container (1\,1cbm)

  - platform: waste_collection_schedule
    name: AbfallGelberSacknext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Gelbe Tonne und -Container (1\,1cbm)

  - platform: waste_collection_schedule
    name: AbfallBiotonnenext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - BioTonne

      
  - platform: waste_collection_schedule
    name: AbfallNaechster
    details_format: "upcoming"
    value_template: ' {{ value.daysTo }} '       `

**Comment by DanielR92** [comment]
I found my problem. In the ICS it shows with "(1\,1cbm)", but later it is only need to parse it with "(1,1cbm)".
It works now, thanks!
