### ISSUE TITLE
Request: Stockton On Tees, UK

### ISSUE THREAD

**Issue by covamalia** [mampfes/hacs_waste_collection_schedule#670]
https://www.stockton.gov.uk/bin-collection-days

I have also dropped an email to their digital mailbox, [digital@stockton.gov.uk](mailto:digital@stockton.gov.uk) to see if there is anything open to the public that can be used, so will see if that gets any traction and update if I get anywhere that way.

**Comment by 5ila5** [comment]
fixed by #830
