### ISSUE TITLE
Schedules for Onkaparinga Council, South Australia

### ISSUE THREAD

**Issue by nathanhaigh** [mampfes/hacs_waste_collection_schedule#678]
I'd like a schedule for the Onkaparinga council in South Australia (https://www.onkaparingacity.com/Services/Waste-and-recycling/Bin-collections). I don't know where to start exactly, so here's some information which others might be able to use or point me in the right direction.

Looking at the various requests, getting the relevant info seems to be to do the following:

1. Search for the address entered e.g. https://www.onkaparingacity.com/api/v1/myarea/search?keywords=18+Flagstaff+Road,+FLAGSTAFF+HILL+5159
2. Extract out the first geolocationid (`d2p1:Id`) e.g. `56a3366e-9e6a-4fd2-aead-beeecdb54036`
3. Query the `geolocationid` for the waste services info e.g. https://www.onkaparingacity.com/ocapi/Public/myarea/wasteservices?ocsvclang=en-AU&geolocationid=56a3366e-9e6a-4fd2-aead-beeecdb54036

This then returns a json file with html embedded within the `responseContent` element containing the next bin collection dates and `ics`

**Comment by dt215git** [comment]
One of the links of the page showing your waste collection allows you to download an ics file with the collection schedule in it.
![image](https://user-images.githubusercontent.com/86194065/219972332-bebc35ac-8280-4baf-972b-4f96227c6734.png)
You could use that with the [iCal/ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) option.

If that doesn't work, the `ocapi` backend is also used by a number of other Australian sources, so it should be possible to adapt one of those.

**Comment by nathanhaigh** [comment]
Thanks @dt215git ... I'll take a look later this week!

**Comment by mampfes** [comment]
fixed by #700
