### ISSUE TITLE
Is anyone able to add Liverpool, UK to the providers?

### ISSUE THREAD

**Issue by jgeorge1983** [mampfes/hacs_waste_collection_schedule#681]
I would be very grateful if Liverpool could be added as a source:

https://liverpool.gov.uk/bins-and-recycling/bin-collection-dates/

**Comment by gingemonster** [comment]
Have you tried using the generic ical integration https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md as if you look at under the table of collection dates there is a "add bin collection dates to calendar" link. Right click on that and select "copy link address" and that should give you the link to use in the ical integration

**Comment by dearlove** [comment]
I've added support for Liverpool.  It should be included in the next release.

**Comment by mampfes** [comment]
fixed by #751
