### ISSUE TITLE
Request: Norway Orkland muni

### ISSUE THREAD

**Issue by radhoo2k10** [mampfes/hacs_waste_collection_schedule#682]
https://www.remidt.no/#!/main

![image](https://user-images.githubusercontent.com/78762281/219136418-5f16ef35-1369-4769-839b-ecc17ef40812.png)

**Comment by mampfes** [comment]
fixec by #683 683

**Comment by radhoo2k10** [comment]
Wow. That was fast. When will it be available in Home Assistant? Thanks!

**Comment by radhoo2k10** [comment]
It is working. Thanks for superb help.
![image](https://user-images.githubusercontent.com/78762281/219870925-0cf7092c-add9-4130-967b-581b89b0458c.png)
