### ISSUE TITLE
Request: Blackburn UK 

### ISSUE THREAD

**Issue by bexem** [mampfes/hacs_waste_collection_schedule#689]
Greetings,

It'd be great if you could add the Blackburn (UK) to the source list, accessible from anyone at this address:
https://mybins.blackburn.gov.uk

Exploring with the developer tool, I've noticed this url containing a json with the actual data:
https://mybins.blackburn.gov.uk/api/mybins/getbincollectiondays?uprn=10091617919&month=2&year=2023

Is there anyway it could be added to the component? 
I use it for a while now (manually set up the dates but holidays always screw it up) and it's amazing!

Thank you in advance in any case!

**Comment by mampfes** [comment]
fixed by #695
