### ISSUE TITLE
Request: Abfallwirtschaft Germersheim

### ISSUE THREAD

**Issue by Kurisutian** [mampfes/hacs_waste_collection_schedule#694]
After checking the ics documentation I wanted to trigger the download for an ICS file from my local waste service provider "Abfallwirtschaft Germersheim". Unfortunately it does not seem that easy as I was not able to pull any valid file from the site through the integration. 
Main Problem was that after checking all values I want to be in the ICS file I have to press a download button which I could not figure out how to automate. I followed an example in the docs (https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#abfallkalender-zollernalbkreis) but it did not work as the source code was different and I am not in too deep to make the transition.
Anyhow it should eventually be rather easy to do this for someone with more experience. 
The website of the service can be found here: https://www.abfallwirtschaft-germersheim.de/online-service/abfall-termine/abfalltermine-ics-export-bis-240-liter.html

Thanks in advance to anyone who can help providing a possible solution!

**Comment by mampfes** [comment]
fixed by #696
