### ISSUE TITLE
Multiple sources: name in calendar, not listed in sensors

### ISSUE THREAD

**Issue by boehser-enkel** [mampfes/hacs_waste_collection_schedule#70]
Hi,

i want to setup 2 sources.

'waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/gelbersack.ics"

      customize:
        - type: Gelber Sack
          alias: gelbersack
          icon: mdi:recycle

      calendar_title: Müll
    - name: ics
      args:
        url: "https://was-wolfsburg.de/subabfuhrtermine/ics_abfuhrtermine3.php"
        method: POST
        params:
          ortabf: "Zum alten Teich"
      customize:

        - type: Bioabfall
          alias: bioabfall
          icon: mdi:trash-can
        - type: Altpapier
          alias: altpapier
          icon: mdi:trash-can
        - type: Restabfall
          alias: restabfall
          icon: mdi:trash-can          
      calendar_title: Müll          
  day_switch_time: " 12:00"  '

2 problems:

1. configured sensors seem to read data only from source 1. The calendar is filled with both events but the sensor only shows events and days to "Gelber Sack"
2. 2 Calendar are created. Both named "Müll" (or "ics" if nothing is set. Is it possible to join them?

greetz

**Comment by mampfes** [comment]
1. Add the [source_index](https://github.com/mampfes/hacs_waste_collection_schedule#configuration-variables-1) attribute to your sensor configuration. 
2. No, a join is not possible right now. But you can give the 2 calendars meaningful names using the [calendar_title ](https://github.com/mampfes/hacs_waste_collection_schedule#configuration-variables) attribute in the source config.

**Comment by boehser-enkel** [comment]
1. but the sensor should refer to both sources

**Comment by mampfes** [comment]
Sorry, a join is not supported at the moment. Each source creates a calendar entry. A sensor sensor can only retrieve data from one source.
I think I understand your problem but I do not see a simple solution with the current code structure to solve this issue. I'm also thinking how to enable an UI based configuration in the future - and this request would increase the complexity of an UI based configuration dramatically.
