### ISSUE TITLE
Request for Hameln-Pyrmont Germany

### ISSUE THREAD

**Issue by CBDKaiser** [mampfes/hacs_waste_collection_schedule#704]
Hello mampfes, I would be happy if you could include our city in the system

https://kaw.hameln-pyrmont.de/Service/Abfuhrterminmodul/Abfuhrterminkalender/

Best wishes and many thanks for your great work

**Comment by mampfes** [comment]
Hameln-Pyrmont provides an _ical-Kalenderabo_. This can be used together with the ICS source. Please give it a try.
