### ISSUE TITLE
impossible to call fetch_data manual

### ISSUE THREAD

**Issue by lublak** [mampfes/hacs_waste_collection_schedule#705]
Because i try to add my own ics http url i need debug it.
Calling fetch_data doesn't work:

```
takes 0 positional arguments but 1 was given
```

just an extra question: Is it possible to use {%y} (small) to get 23 not 2023?

**Comment by thecem** [comment]
@mampfes pls open this topic since the aktion (former service) "waste_collection_schedule.fetch_data" is not available.

THX!
