### ISSUE TITLE
Request: Change Collection date to minus  1 day

### ISSUE THREAD

**Issue by Burhan1978** [mampfes/hacs_waste_collection_schedule#708]
I was able to integrate your solution and I am very thankful.
At my location for one specific waste collection service the date they provide for collecting the waste does not match the actual day they pick it up. It is always the day before. E.G. the collection day is shown as a Friday but the actual collection is always on a Thursday. Do you know how I can address this? Basically, I'd like to change the date for every collection date so that it matches the actual day in the calendar

**Comment by mampfes** [comment]
Which data provider are you using?

Some service provider allow to set an offset in the service provider home page. Did you select the right value (just in case).

If you are using the ICS source, you can also set an offset in the source configuration.

**Comment by Burhan1978** [comment]
it is abfall.io and ALBA

I just started with the home assistant and not yet fully understood it all. How can I edit the source configuration. Can you point me to it?

**Comment by Burhan1978** [comment]
well ok, now I'm getting you. No, I am not using the ICS as a source but code to import the data (see below)
I also worked through your docs and there is no hint that I can set an offset while importing. That would be handy though I want to have the correct dates in the calendar as well.

The code I am using (masked my address)

waste_collection_schedule:
sources:
- name: abfall_io
      args:
        key: 9583a2fa1df97ed95363382c73b41b1b
        f_id_kommune: 1234
        f_id_strasse: 1234
        f_id_strasse_hnr: 123456

      customize:
        alias: 'Wertstoff Tonne'
        type: 'Wertstofftonne'

**Comment by mampfes** [comment]
Sorry for the delay. Can you give us a link to a webpage and a test address so that we can try to reproduce the issue?

**Comment by mampfes** [comment]
Closed because no feedback from originator.
