### ISSUE TITLE
ics files with multiple colletion types per event

### ISSUE THREAD

**Issue by mgolisch** [mampfes/hacs_waste_collection_schedule#71]
Unfortunately ics file provided by my waste company lists multiple collection types in the same event.

Example: https://www.eaw-rheingau-taunus.de/abfallkalender/calendar.ics?streetid=1429

Is there an easy way to use it without modifing it first?

**Comment by mampfes** [comment]
Fixed in #72 

Added option `split_at` to ics source.

**Comment by mampfes** [comment]
Please let me know if the new option works for you.

**Comment by mgolisch** [comment]
Yes works.
Thanks alot.
