### ISSUE TITLE
Calendar population not correct Republic Services

### ISSUE THREAD

**Issue by ingo916** [mampfes/hacs_waste_collection_schedule#717]
Installed your integration, and it worked. However, the calendar entries do not match up with Republic Services.
I would appreciate any help you could give me in resolving this issue.

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest 

**YAML config**
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: "my address"

![image](https://user-images.githubusercontent.com/41309095/221937966-1d3645d1-a3bb-4284-a600-4f2a58f8142b.png)
Republic Services calendar
![image](https://user-images.githubusercontent.com/41309095/221938327-c1c3639d-1299-4833-ac7a-e1fc1646d0cc.png)

**Comment by ingo916** [comment]
calling the service to update generates these errors
![image](https://user-images.githubusercontent.com/41309095/221942322-b5b63d40-af52-4956-9d5d-8d74e4f954d6.png)

**Comment by mampfes** [comment]
> calling the service to update generates these errors ![image](https://user-images.githubusercontent.com/41309095/221942322-b5b63d40-af52-4956-9d5d-8d74e4f954d6.png)

This one has been already fixed by #705

**Comment by dt215git** [comment]
The Republic Services test cases appear to use `commercial` addresses with a single waste type collections. What's being returned for those seems to match what the website reports.

You may find HA  fills in the collections for the 14th once the 7th has passed.

What seems a bit odd is HA displaying 3 lots of Recycling entries, and a single entry for the other waste types. It would  be useful to have a `residential` test case to  see whether the json response is constructed differently. @ingo916 could you suggest an address from a nearby neighborhood that could be used?

![image](https://user-images.githubusercontent.com/86194065/222225480-34b3e366-effe-4e19-9965-e7de6aea8d09.png)

**Comment by ingo916** [comment]
The address I used was my residential address. 
Here is an address near my neighborhood that will be the same schedule
8957 Park Meadows Dr, Elk Grove, CA 95624

**Comment by dt215git** [comment]
I think this is working as expected.

The json response for that address shows 4 dates for Recycling collections, but just one date for both Solid Waste and Yard Waste collections. 

```bash
test_sources.py -s republicservices_com -i -l
Testing source republicservices_com ...
  found 1 entries for Scott Country Clerk
    2023-03-02: Solid Waste [mdi:trash-can]
  found 1 entries for Branch County Clerk
    2023-03-06: Solid Waste [mdi:trash-can]
  found 7 entries for Contract Collection
    2023-03-07: Recycle [mdi:recycle]
    2023-03-21: Recycle [mdi:recycle]
    2023-04-04: Recycle [mdi:recycle]
    2023-04-18: Recycle [mdi:recycle]
    2023-05-02: Recycle [mdi:recycle]
    2023-03-07: Solid Waste [mdi:trash-can]
    2023-03-07: Yard Waste [mdi:leaf]
```
It shows up as a `contract` collection rather than `residential` collection, and doesn't seem to display a calendar on their website.

It'd be worth waiting to see if the calendar updates with the missing collections once you've had the pick-up on the 7th.

**Comment by ingo916** [comment]
I will wait and report back. Thanks!

**Comment by mampfes** [comment]
fixed by #723

**Comment by seannymurrs** [comment]
I know this issue is closed, but I found it while trying to find more information on the issue I'm having. I'm having the same problem @ingo916 was having where it's showing multiple future Recycle pickup dates but only one Solid Waste pickup date. Was the conclusion that this is what should be expected?

**Comment by dt215git** [comment]
Yes, I think that behaviour is as expected. The website returns a limited number of future collections as shown in the Mar 1 post.

The website calendar may show additional waste collections, but those are presumably being generated by some website scripts that further process the returned info.
