### ISSUE TITLE
Request: Bromley Council

### ISSUE THREAD

**Issue by capandcamera** [mampfes/hacs_waste_collection_schedule#726]
Would it be possible to add support for Bromley Council, it's can be currently used via .ics, however it does not contain updates (missed collections etc)

Bromley uses WasteWorks and each property is allocated a code at the end of the url.
An example of a random address in bromley:

https://recyclingservices.bromley.gov.uk/waste/6328436 

Those with a garden waste subscription have an additional section 

```

Garden Waste

Frequency	Friday every other week
Next collection	Friday, 10th March
Last collection	Friday, 24th February, at 8:44am

Subscription	£60.00 per year (1 bin)
Renewal	16 December 2023

**Comment by mampfes** [comment]
fixed by #772
