### ISSUE TITLE
AWB Oldenburg new endpoint

### ISSUE THREAD

**Issue by askibit** [mampfes/hacs_waste_collection_schedule#731]
Hello,
AWB Oldenburg is no longer working. This new endpoint works for me : 

API_URL = "https://www.oldenburg.de/startseite/leben-umwelt/awb/awb-von-a-bis-z/abfuhrkalender.html"

Unfortunately I don't know exactly how to do the code adjustment in git. Can someone please do it?

**Comment by mampfes** [comment]
fixed by #733
