### ISSUE TITLE
customer: awb-ak - city: VG Daaden-Herdorf - Kernstadt Herdorf - Wrong values

### ISSUE THREAD

**Issue by demsarinic** [mampfes/hacs_waste_collection_schedule#737]
I am currently trying to integrate the waste calendar into Home Assistant via “Waste Collection Schedule”. I now get entries displayed, but unfortunately they are the wrong values. I find the entry on the page: 
https://awido.cubefour.de/Customer/awb-ak/v2/Calendar2.aspx

Config:
`waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: awb-ak
        city: VG Daaden-Herdorf - Kernstadt Herdorf`

![1](https://user-images.githubusercontent.com/93226293/222974726-5836727b-6ce6-4553-9606-723406e5533c.png)
![2](https://user-images.githubusercontent.com/93226293/222974731-24009729-bf6c-438e-8879-2919acac17b5.png)

**Comment by 5ila5** [comment]
There is a minor logic error in the source code using "street": "Herdorf" returns the correct data. If the fix is merged it should also be possible to not use the street argument
