### ISSUE TITLE
Help wanted: Error when running update_docu_links.py with new source

### ISSUE THREAD

**Issue by Lance0095** [mampfes/hacs_waste_collection_schedule#741]
Hi i have written a source script and a source markdown for https://www.samiljo.se/. 

The test works and outputs the relevant data (see screenshot).
![output from test_sources py](https://user-images.githubusercontent.com/127054845/223145637-485967f9-e6f1-4f87-aec7-9bc4b91a0422.png)

But when i try to update the info.md and README.md with update_docu_links.py i get an error.
![output from update_docu_links py](https://user-images.githubusercontent.com/127054845/223146784-0c71595d-fd21-4632-ab21-73ae678daf6a.png)

source script: https://github.com/Lance0095/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/samiljo_se.py
source markdown: https://github.com/Lance0095/hacs_waste_collection_schedule/blob/master/doc/source/samiljo_se.md

**Comment by dt215git** [comment]
Might be the `/` you have at the end of the URL, what happens of you change it to?
```python
URL = "https://www.samiljo.se"
```

**Comment by Lance0095** [comment]
Did a little sanity check and removed my source script and markdown. And the script still fails, so it's probably something wrong with the environment.

**Comment by dt215git** [comment]
Copying your .py and .md to my system and running update_docu_links seems to work - no errors generated and the README.md and info.md files show the change.

![image](https://user-images.githubusercontent.com/86194065/223197159-4ae86341-fa9f-4658-b307-2f6130fe0b7b.png)

![image](https://user-images.githubusercontent.com/86194065/223197313-f198e7b9-0fc6-4f94-83d1-bc63d8918447.png)

**Comment by mampfes** [comment]
If `update_docu_links.py` is not working on your machine, I would also accept a PR without the updates in the .md files. I can also do the update.

**Comment by Lance0095** [comment]
It was two things. A missing dependency and update_docu_links.py not being compatible with windows (wrong encoding for the filenames I think). Worked as expected in WSL and a VM.
