### ISSUE TITLE
Setup of waste_collection_schedule is taking over 10 seconds.

### ISSUE THREAD

**Issue by codyc1515** [mampfes/hacs_waste_collection_schedule#749]
Receiving the below message on each start. Using the `ccc` schedule.

```
Logger: homeassistant.setup
Source: runner.py:179
First occurred: 8:23:49 AM (1 occurrence)
Last logged: 8:24:23 AM

Setup of waste_collection_schedule is taking over 10 seconds.
```

**Comment by mampfes** [comment]
Do you see this issue every time? This could be caused by a delayed response of your service provider. Ideally the startup of the integration should be decoupled from the first fetch of the data and I though it is implemented like that. But maybe there is still a link.

**Comment by mampfes** [comment]
Closed because no response from originator. I also see other integrations in my production system which show the same error, even official integrations.

**Comment by codyc1515** [comment]
Sorry. I didn't see the comment. I don't think I've seen this recently, so the issue must be solved.
