### ISSUE TITLE
Request: can someone please add Felsberg

### ISSUE THREAD

**Issue by HolliDolli** [mampfes/hacs_waste_collection_schedule#763]
I did my best to understand the code, but I can't figure out to add a datasource. 
Can someone add Felsberg https://www.zva-sek.de/online-dienste/abfallkalender-2023/abfallkalender-2023.html for me?
I will take care for the upcoming years (changing existing code is much more easy :-) ), but I'm not able to transfer from another location.

Thanks.

Holger

Edit: And I forgot to mention: There is an additional problem: They added the date to the summary-text.
Testcases might be:
Felsberg/Felsberg and
Guxhagen/Guxhagen

**Comment by mampfes** [comment]
fixed by #771
