### ISSUE TITLE
Oklahoma City, Oklahoma

### ISSUE THREAD

**Issue by Telain** [mampfes/hacs_waste_collection_schedule#764]
Oklahoma City provides an API with a JSON response. RecordID is probably the most direct, but you can search by address as well.
Retrieving the proper format for either is easily done via: https://data.okc.gov/portal/page/viewer?datasetName=Address%20Trash%20Services

https://data.okc.gov/services/portal/api/data/records/Address%20Trash%20Services?recordID=######

API details: https://data.okc.gov/portal/page/api

**Comment by 5ila5** [comment]
fixed by #764
they use incapsula which can block requests, so the response sometimes raises an Exception

**Comment by sanctas** [comment]
I get blocked by Encapsula 100% of the time now. 

For the time being I have set up a private API url that bypasses encapsula using Puppeteer in Node.JS and set it up as a drop in replacement for the add-on. I assume Selenium for Python would work as well, I'm just not familiar with python. 

Would home assistant be able to use Selenium? I would guess not.

**Comment by sanctas** [comment]
Oh while I'm here, on trash days, the OKC API will drop the "upcoming trash day" item after about 10 am. Since the API only provides a single upcoming trash day in the response (as opposed to 3 upcoming for recycling day and bulky trash day) could we add a condition where if it is currently trash day according to the HA calendar, it will continue to return "0 days" until the next day passes?

**Comment by 5ila5** [comment]
> Oh while I'm here, on trash days, the OKC API will drop the "upcoming trash day" item after about 10 am. Since the API only provides a single upcoming trash day in the response (as opposed to 3 upcoming for recycling day and bulky trash day) could we add a condition where if it is currently trash day according to the HA calendar, it will continue to return "0 days" until the next day passes?

it's probably not the website but the integration `day_switch_time` defaults to 10:00 AM you can change this to 24:00 (23:59 not sure what will work)

**Comment by 5ila5** [comment]
fix #1306: I modified the requests headers to be more in line of what a browser would send and now the request work again

fix will be part of release 1.43.0 or is available now as master/git version

**Comment by sanctas** [comment]
Wow thanks so much for the quick response! I'll check the change out this evening!
