### ISSUE TITLE
Can't fiure out the sensors

### ISSUE THREAD

**Issue by jgeorge1983** [mampfes/hacs_waste_collection_schedule#765]
Am I being simple?  I have 3 bin types, I have this below as my schedule

waste_collection_schedule:
    sources:
    - name: liverpool_gov_uk
      args:
        uprn: "XXXXXXXXXXX"
but I get he below error in my log
_Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:192
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 08:42:55 (1 occurrences)
Last logged: 08:42:55

source not found: liverpool_gov_uk_

Do I need a sensor for each bin type as well?

**Comment by dt215git** [comment]
Looks like the Liverpool source was added 1 week ago, whereas the last release was 2 weeks ago.

You'll either need to wait for the next release for  your local HA instance to get the new source, or copy the [liverpool_gov_uk.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/liverpool_gov_uk.py) to your local file system.

That aside, one of the test cases in the script throws an error, but the other one works as expected.
```bash
Testing source liverpool_gov_uk ...
  52 Swallowhurst Crescent Liverpool L11 2UZ failed: 'datetime.date' object has no attribute 'date'
  found 9 entries for 1 Aston Street Liverpool L19 8LR
    2023-03-21: Refuse [mdi:trash-can]
    2023-03-28: Refuse [mdi:trash-can]
    2023-04-04: Refuse [mdi:trash-can]
    2023-03-28: Recycling [mdi:recycle]
    2023-04-11: Recycling [mdi:recycle]
    2023-04-25: Recycling [mdi:recycle]
    2023-03-28: Green [mdi:leaf]
    2023-04-11: Green [mdi:leaf]
    2023-04-25: Green [mdi:leaf]
```

**Comment by jgeorge1983** [comment]
Cool thanks! Obviously just me being inpatient

**Comment by mampfes** [comment]
Please wait for next release.
