### ISSUE TITLE
last Saturday every month 

### ISSUE THREAD

**Issue by scns** [mampfes/hacs_waste_collection_schedule#767]
Is it possible to make an static rule for every last Saturday every month?  or need i to make static dates?

**Comment by mampfes** [comment]
I think a rule for last XXX day is not possible with the current `static` source. You have to go with static dates --> still use the `static` source and add them to the `dates` section.

**Comment by scns** [comment]
Thx for your answer. i will do it that way for now!

**Comment by mampfes** [comment]
The static source has now support for weekdays.

(Please wait for the next release).
