### ISSUE TITLE
How to add calendar events from local calendar

### ISSUE THREAD

**Issue by altacoon** [mampfes/hacs_waste_collection_schedule#773]
Hi @mampfes, some sort of waste collections (in Germany called "Grünabfall") is organized by the community I am living in and not by the authority which is responsible for the waste disposal. Thus "Grünabfall"-events are not mentioned in the waste collection schedule. I have created a separate local calendar in home assistant with these events. But this leads to two separate cards in lovelace. How can I integrate local calendar events in your card instead?

**Comment by mampfes** [comment]
Hi, which card do you mean? And what do you mean with "separate local calendar"?

What you can do: You can setup multiple sources in waste_collection_schedule. A sensor can show schedules from multiple sources at once (by setting the `source_index` attribute accordingly. But it is not possible to merge multiple sources in a single calendar.

**Comment by altacoon** [comment]
![Bild der wastecollection_card](https://user-images.githubusercontent.com/99205027/226168114-32f6446a-7ae9-4049-9b1e-2f5c0d3c63e7.jpg)
This is the card I mean and local calendar is a calendar which I create within homeassistant ("local calendar" integration) and where I enter manually the dates for Grünabfuhr.
The first three entities in the card come from an internet link which I have configured in waste-collection-schedule.

**Comment by dt215git** [comment]
You could extend your current config to use a [Static](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) source for the Grünabfuhr collections. You'd have to manually add in the dates, or define the pattern if it's a regular schedule, but it's probably no more work than setting up the local calendar events.

If they provide the schedule as a calendar download, then the [iCal/ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source might also be an option.

**Comment by altacoon** [comment]
The use of "static source" works fine! Thank you very much, @dt215git  
The "source_index" must be set correctly, thanky for this hint, @mampfes
