### ISSUE TITLE
Doncaster, UK please? I have the direct URL to get it as a JSON

### ISSUE THREAD

**Issue by Nurgus** [mampfes/hacs_waste_collection_schedule#784]
Hi, could someone add Doncaster? I have a link here (UPRN randomly selected by clicking on Google Maps):
https://www.doncaster.gov.uk/Compass/PremiseDetail/GetCollectionsForCalendar?UPRN=100050695227&Start=1677456000&End=1680998400

I think the GET Start and End values need to be valid to get results.

Only the refuse, recycling and green (garden waste) are of interest.

TIA!

**Comment by mampfes** [comment]
fixed by #800
