### ISSUE TITLE
Item "slam" from Sysav breaks the component

### ISSUE THREAD

**Issue by epejans** [mampfes/hacs_waste_collection_schedule#791]
Getting waste collection schedule from Sysav where this includes "slam", breaks the component.
Sysavs API responds with a week rather than a date for this situation, i.e. "v42 Okt 2023"
Code only handles dates.

(Should be sufficient to check if date, proceed, if string don't do anything (or try to find Monday in the week...?))

**Comment by mampfes** [comment]
Could you provide a test adress which evokes the error?

**Comment by epejans** [comment]
HI,
Sure!
Ekhagsvägen 204, Svedala

Den tis 21 mars 2023 kl 20:19 skrev Steffen Zimmermann <
***@***.***>:

**Comment by epejans** [comment]
[image: image.png]

Den ons 22 mars 2023 kl 08:08 skrev Peter Jansson ***@***.***>:

**Comment by mampfes** [comment]
fixed by #793

**Comment by epejans** [comment]
Awesome, thanks!
/Peter

Den tors 23 mars 2023 20:28Steffen Zimmermann ***@***.***>
skrev:
