### ISSUE TITLE
SyntaxError while running script for AbfallnaviDe.py 

### ISSUE THREAD

**Issue by Hohenloherin** [mampfes/hacs_waste_collection_schedule#796]
While running the script for AbfallnaviDe.py I get the following syntax error:

```
xhs@xhs:/media/downloads$ python3 AbfallnaviDe.py
   File "/media/Daten/Downloads/AbfallnaviDe.py",line 73
    <title>hacs_waste_collection_schedule/AbfallnaviDe.py at master · mampfes/hacs_waste_collection_schedule<title>
                                                                    ^
SyntaxError: invalid character ' · ' (U+00B7)
```

Is it my fault and if so, what is my mistake? Please give me a hint.

**Comment by 5ila5** [comment]
looks like you downloaded the html from github containing the code instead of the actual file. you can not use cmd + s or right click save file to download a file. if you would open your file you probably would see HTML instead of python. You can open the file in github and select raw. Then you can press cmd + s to save the script.

**Comment by mampfes** [comment]
Please share your configuration.

**Comment by Hohenloherin** [comment]
I followed your hint and got the next error:

`/media/Downloads$ python3 abfallnavi_de.py
Traceback (most recent call last):
  File "/media/Downloads/abfallnavi_de.py", line 11, in <module>
    from waste_collection_schedule.service.AbfallnaviDe import SERVICE_DOMAINS, AbfallnaviDe  # type: ignore # isort:skip # noqa: E402
ModuleNotFoundError: No module named 'waste_collection_schedule'`

I have no clou what is wrong.

**Comment by Hohenloherin** [comment]
Thanks for your assistance, I got it and it works so far. I can see a calendar with all the data of the waste collection. Now I'm struggling to use the regex argument:

`args:
        service: stadt
        ort: Stadt
        strasse: strasse
        hausnummer: 115
        regex: "([A-Za-z]) 1100"`

this gives me the following error 

`Logger: homeassistant.setup
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:196
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 14:08:46 (1 occurrences)
Last logged: 14:08:46

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 202, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
TypeError: Source.__init__() got an unexpected keyword argument 'regex'`

Where is the mistake?

**Comment by 5ila5** [comment]
I'm not sure what you want to archive the regex argument is only valid for the ICS source. Take a look in the [Configuring Waste Collection Schedules documentaition](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sources) in the `args` section you only define arguments for the source you selected. If you want to display only some events or rename them you can customize them with inside the `customize:` part. (Example in provided link)

-- updated your last message to better display your current config

**Comment by Hohenloherin** [comment]
Thanks for updating my message, good to see how you did it. 
Yes, I use the regex in the arguments of the ICS source and not in the customize part of my config.yaml.  
Our service provider has different types of waste collection and there are two types looking the almost the same: "Papiertonne" and "Papiertonne 1100". I don't want information about the "Papiertonne 1100". I want to suppress this information by a regex argument. In the past this worked fine, but I forgot how I managed and also did not document it. 
After I find a solution I shall document it this time - for sure I will!

**Comment by 5ila5** [comment]
if you use The ICS you have to provide an Ical url or file the ICS. the ICS source does not have the arguments         `service`, `ort`, `strasse` or `hausnummer`. Your error messege suggest you're not using the ICS source. if you want to not display "Papiertonne 1100" you should use the customize settings.

An Example for a abfallnavi_de source not displaying events with "Papiertonne 1100":
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de #this is the name of your source
      args: #these are your arguments for the given source
        service: coe
        ort: Coesfeld
        strasse: Ahornweg
      customize:
        - type: "Papiertonne 1100" #The identity of the waste type as returned from the source
          show: False #Show (True) or hide (False) collections of this specific waste type. Default is True
```

**Comment by Hohenloherin** [comment]
Thank you very much, this does the trick for now, "Papiertonne 1100" disappeared from the calender!

file:///media/Helmut_Daten/Downloads/wastecollection_calender.png

**Comment by vardash** [comment]
My solution, if you are interested
    
  customize:
        - type: Papiertonne 1100
          alias: Papiertonne
