### ISSUE TITLE
Landkreis Miltenberg missing in wizard\abfall_io.py

### ISSUE THREAD

**Issue by halfgit** [mampfes/hacs_waste_collection_schedule#806]
On the page https://www.abfallplus.de, the district of Miltenberg is mentioned. 

On this page 

https://sperrgut.landkreis-miltenberg.de/WasteManagementMiltenberg/WasteManagementServlet

unfortunately the Hardcore Variant does not work, because the programming seems to have been done differently. In any case, I can't find the key parameter, etc.

Could you maybe have a look, thanks!

**Comment by 5ila5** [comment]
I can't find the key either but I was not involved in developing the abfall_io source. But they seem to offer `ical-Kalenderabo ` you can use the [Generic ICS / iCal File](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source

**Comment by halfgit** [comment]
Hi,
I thought by using ics, you have to change the calendar file regularly. Is this not the case?

**Comment by halfgit** [comment]
Hi,
I thought by using ics, you have to change the calendar file regularly. Is this not the case?

**Comment by 5ila5** [comment]
If you download the ics yes, but if you use the url it should work as long as the provider does not change something its called kalender abo, so the url is intended to be integrated in calender programs. So it is intended to work until you remove it (or they are making Major changes)

**Comment by halfgit** [comment]
Ok, cool thank you! I‘ll try it out.

**Comment by mampfes** [comment]
abfall_io is sometimes only used for smart phone apps, not for the service websites. We can only extract the key if it is used for websites, I don't know a way to extract the key from a smart phone app.

But ICS should work for you, als @5ila5 already mentioned.

**Comment by 5ila5** [comment]
I used the app in an emulator and analised the requests but could not find the key there either.
