### ISSUE TITLE
Request for West Oxfordshire 

### ISSUE THREAD

**Issue by ArgDave** [mampfes/hacs_waste_collection_schedule#818]
Please could you look at https://community.westoxon.gov.uk/s/waste-collection-enquiry
It seems to use an aura service that other councils use so might be a simple duplication and edit?
Thank!

**Comment by sas-mb** [comment]
Yes please 👍

**Comment by 5ila5** [comment]
Added by #2438

It was quite a hassle to integrate and unfortunately couldn't be copied and pasted from another aurora service.

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by mattsgreen** [comment]
This had been working nicely, but it seems to have broken? 

Both myself and another user using the same (West Oxfordshire) source have started seeing issues this week.  I see the below in the logs: 

`fetch failed for source West Oxfordshire District Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/westoxon_gov_uk.py", line 235, in fetch serialized_state = r.json()["actions"][0]["returnValue"]["response"][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable`

**Comment by ArgDave** [comment]
Just for the record, I am seeing the same error message in my Home Assistant logs. Thanks for anything you can do to debug this.

**Comment by 5ila5** [comment]
Please move any discussion regarding this error to #2619
