### ISSUE TITLE
Request for Landkreis Eichsfeld

### ISSUE THREAD

**Issue by askruse1** [mampfes/hacs_waste_collection_schedule#836]
Hello, could you integrate Landkreis Eichsfeld.

There are Calenders: https://www.eichsfeldwerke.de/entsorgung/entsorgungstermine/abfuhrzeiten/

Thanks

**Comment by 5ila5** [comment]
They use hausmuell.info as API. 
Can be combined with #590
I will look into it.

**Comment by 5ila5** [comment]
fixed by #851
