### ISSUE TITLE
Source request Cherwell district council

### ISSUE THREAD

**Issue by PeteB1983** [mampfes/hacs_waste_collection_schedule#848]
Could someone add Cherwell district council as a source?
https://www.cherwell.gov.uk/homepage/129/

**Comment by bbr111** [comment]
@PeteB1983 

could you please provide an example address?

**Comment by PeteB1983** [comment]
Certainly,
141 Warwick road
Ox16 2ar

**Comment by dt215git** [comment]
@PeteB1983: Would you happen to know if they include the Year in the collection date around the Dec/Jan boundary?
![image](https://user-images.githubusercontent.com/86194065/230882370-145f5571-7183-4706-8856-9dd74fb9ee81.png)

**Comment by PeteB1983** [comment]
I'm not sure...

**Comment by 5ila5** [comment]
fixed by #864
