### ISSUE TITLE
Request for muellabfuhr-deutschland.de

### ISSUE THREAD

**Issue by mampfes** [mampfes/hacs_waste_collection_schedule#849]
They provide schedules for some districts in Germany:

- [Landkreis Hildburghausen](https://portal.muellabfuhr-deutschland.de/hildburghausen)
- [Landkreis Wittenberg](https://portal.muellabfuhr-deutschland.de/wittenberg)
- [Burgenlandkreis](https://portal.muellabfuhr-deutschland.de/burgenlandkreis)
- [Dessau-Rosslau](https://portal.muellabfuhr-deutschland.de/dessau-rosslau)
- [Weimarer Land](https://portal.muellabfuhr-deutschland.de/weimarer-land)
- [Landkreis Sömmerda](https://portal.muellabfuhr-deutschland.de/soemmerda)
- [Saalekreis](https://portal.muellabfuhr-deutschland.de/saalekreis)

The API returns a JSON response.

**Comment by bbr111** [comment]
@mampfes is someone working in this? i could make it.

**Comment by mampfes** [comment]
I'm not working on it. So, yes - please do it.

@5ila5 Or are you already working on it?

**Comment by bbr111** [comment]
> I'm not working on it. So, yes - please do it.
> 
> @5ila5 Or are you already working on it?

Just want to avoid double work.

**Comment by 5ila5** [comment]
No I currently concentrate more on old issues.

**Comment by bbr111** [comment]
solved by #858
