### ISSUE TITLE
(Berliner Stadtreinigung) BSR not working

### ISSUE THREAD

**Issue by tinkerberlin** [mampfes/hacs_waste_collection_schedule#857]
Hi there, since about a day or two BSR integration isn't pulling data into HA. 
Any idea what might be wrong? Just FYI the data from abfall.io (ALBA Berlin) is working just fine. 

Sorry for not posting code / log, but I'm unsure, what I should be posting.

**Comment by chris1601** [comment]
Same Problem here. But I think it's an issue on their side.
Even when you visit the homepage directly you can't even search for streets. So maybe give them some time to fix the database.

**Comment by tinkerberlin** [comment]
Yes. I tend to agree. Just wanted to flag, in case they are changing
something on the backend that would necessitate changes here.

:-)

chris1601 ***@***.***> schrieb am So., 9. Apr. 2023, 07:39:

**Comment by tinkerberlin** [comment]
Also: Happy Easter! 🐣

Florian von Gierke ***@***.***> schrieb am So., 9. Apr. 2023,
08:10:

**Comment by PeterHoge** [comment]
BSR ist since today (?) one day earlier.

**Comment by variada** [comment]
same problem here. there's some kind of weird mismatch between the integration calendar and the BSR website going on.

![image](https://user-images.githubusercontent.com/83453466/233328959-f77feea9-5036-477d-ad96-4f2cff0ab190.png)
![image](https://user-images.githubusercontent.com/83453466/233328995-e9898ef1-b5d0-41d5-a052-d3a2cdbd00ce.png)
