### ISSUE TITLE
Error when fetching newport.gov.uk

### ISSUE THREAD

**Issue by corvus2606** [mampfes/hacs_waste_collection_schedule#866]
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 10:21:25 AM (1 occurrences)
Last logged: 10:21:25 AM

fetch failed for source Newport City Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/newport_gov_uk.py", line 38, in fetch r.raise_for_status() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.newport.gov.uk/PropertyData/bincollection/properties/100100688837/Waste%20Collection

UPRN changed to the one provided in the test case for anonymity.

**Comment by dt215git** [comment]
Putting the postcode for that urpn into the website and selecting random properties also fails to show any collection schedules. The query doesn't look to be any different to what's in the script.

![image](https://user-images.githubusercontent.com/86194065/230977374-703dedfa-f493-43e9-8d33-459c6fdbb7ab.png)

Do you see your schedule if you use the website? If not, I guess the problem is their end.

**Comment by dt215git** [comment]
I think this issue can be closed, both the script and the website are returning data again.

```bash
Testing source newport_gov_uk ...
  found 2 entries for The Coach House, Newport
    2023-04-21 : garden waste [mdi:leaf]
    2023-04-21 : kerbside recycling [mdi:recycle]
```

![image](https://user-images.githubusercontent.com/86194065/232196403-d10b190e-4af3-420b-a9c6-7cba5c6097ac.png)
