### ISSUE TITLE
Additional variable grossgeraulandkreis-abfallkalender

### ISSUE THREAD

**Issue by BastianPlatt** [mampfes/hacs_waste_collection_schedule#870]
Hi, 

first of all thanks for this integration - great idea. 
I have an issue with the data pull for "grossgeraulandkreis-abfallkalender"
The C-Trace will ask for 4 inputs (see picture) 
- Ort 
- Ortsteil
- Straße 
- Hausnummer

![grafik](https://user-images.githubusercontent.com/89517877/231119226-78a0bb7a-f7a7-4d2b-8d23-22b1213b2a69.png)

If I put these in the yaml and let it run  I get this error: 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.setup
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:196
Integration: waste_collection_schedule (documentation)
First occurred: 09:25:28 (1 occurrences)
Last logged: 09:25:28

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 202, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
TypeError: Source.__init__() got an unexpected keyword argument 'ortsteil'

The way I understand it - it is not able to work with the "Ortsteil" however this is needed to get the data loaded - any ideas how to fix this? 

Thanks a lot in advance for your help. 

Best 
Bastian

**Comment by 5ila5** [comment]
fixed by #871

**Comment by BastianPlatt** [comment]
Thanks a lot for the super fast help! Works perfectly now!
