### ISSUE TITLE
Source Request for Kiel Germany

### ISSUE THREAD

**Issue by jkasten80** [mampfes/hacs_waste_collection_schedule#872]
There are ICS files build like this https://abki.de/abki-services/abki-leerungen-ical?data=2023-streetname-housenumber-stand-12-04-2023

**Comment by 5ila5** [comment]
Do you know if the URL always contains the current date or is it only updated on some days and contains for example on a Sunday still the date of Friday?

**Comment by 5ila5** [comment]
fixed by #874

**Comment by jkasten80** [comment]
Did i do something wrong? 
![image](https://user-images.githubusercontent.com/85489899/231961694-fb6a8884-5f65-465c-be5a-21a15c15c774.png)

**Comment by jkasten80** [comment]
I got it, it didnt download the source file. I did it manual and now it works.

**Comment by 5ila5** [comment]
this source is not yet part of the current release (1.38.0) it will be part of 1.39.0 or is available with the master (bzw. git) version
