### ISSUE TITLE
Request for APM (DE - Potsdam Mittelmark)

### ISSUE THREAD

**Issue by dMopp** [mampfes/hacs_waste_collection_schedule#876]
See https://www.apm-niemegk.de/

They have an app, too, called „Müllmann“

**Comment by 5ila5** [comment]
They provide an ICS subscription link `Exportieren ICal` -> `URL in Kalender-App einbinden`
This is supported by the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) (as `url` parameter). 
I will write official documentation for this, so it will be listed as officially supported with a short description.

**Comment by dMopp** [comment]
Got it, works fine.

For everyone else:
https://www.apm-niemegk.de/kundenservice/abfuhrtermine/ --> Select the Town, select the right container types and finally click on export. Then use the url like that:

`waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: <THEURL>`

And in addition, create a sensor like in the docs:

`  - platform: waste_collection_schedule
    name: Abfuhrtermine`


Done and works like a charm  :)

**Comment by 5ila5** [comment]
You also might want to replace the year in the URL with `{%Y}` so it hopfully still works for longer than one year

official documented by #879
Documentation: [apm_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/apm_de.md)
