### ISSUE TITLE
London borough of Bexley shows doubled data

### ISSUE THREAD

**Issue by pawellygan** [mampfes/hacs_waste_collection_schedule#877]
Every Entry in the calendar is doubled - see attached

<img width="305" alt="Screenshot 2023-04-14 at 18 46 19" src="https://user-images.githubusercontent.com/45388740/232121301-053b2b6f-e610-4b99-bef1-ee7337234166.png">
<img width="358" alt="Screenshot 2023-04-14 at 18 45 16" src="https://user-images.githubusercontent.com/45388740/232121304-aa48d323-4960-4100-b029-86b6cd219461.png">
<img width="263" alt="Screenshot 2023-04-14 at 19 59 02" src="https://user-images.githubusercontent.com/45388740/232133104-9e1db245-5a39-4b49-bd63-bc782a1d69f0.png">

**Comment by dt215git** [comment]
HA is displaying the calendar entries the script creates, and the script is faithfully translating the data returned by the website.

That uprn has duplicate data:
![image](https://user-images.githubusercontent.com/86194065/232132535-8e75b03b-2605-42ec-ab05-b7023e4a978e.png)

Whereas for another house on the same street doesn't:
![image](https://user-images.githubusercontent.com/86194065/232132922-f9c7b4f2-7cef-4a53-adf1-362728ae02c7.png)

**Comment by pawellygan** [comment]
that is very interesting! thanks for this - I'll use my neighbour's UPNR ;)

**Comment by pawellygan** [comment]
I can confirm changing upnr to my neighbor's one fixed the problem. Probably my upnr is registered with council twice (previous owner?) anyways - it works now!
