### ISSUE TITLE
Request for Auckland to add in a compost tag (new collection)

### ISSUE THREAD

**Issue by hacshacdgacs** [mampfes/hacs_waste_collection_schedule#881]

**Comment by 5ila5** [comment]
Could you please be more specific:
If I understand you correctly currently only rubbish and recycling will be found and there are some addresses in Auckland, that also list compost collections? Could you provide an example address or area_number to add an test case for this?

**Comment by hacshacdgacs** [comment]
Hi yes, Soon all of Auckland will have food scraps collection with some areas already having it. ( 12341998652 is the area code for one of them). Currently Auckland just shows rubbish and recycle in the sensors

**Comment by 5ila5** [comment]
fixed by #882
