### ISSUE TITLE
[Request] Abfallkalender Leipzig

### ISSUE THREAD

**Issue by VaillantHassIo** [mampfes/hacs_waste_collection_schedule#89]
Hello,

it would be great if you could add the calendar for Leipzig Waste Management

URL: https://stadtreinigung-leipzig.de/rest/wastecalendarstreets?name=

incomplete streetname will provide all matching result incl. all registered streetnumber in JSON format

https://stadtreinigung-leipzig.de/rest/wastecalendarstreets?name=Gerichts
	
results	:
Gerichtsweg	
2	
	0	11748
3	
	0	21844
	
	
first Row is the Streetnumber, included colum contains as first Array-Element [0] the position_nos ID which is required to download the iCal calendar

https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender/ical.ics?position_nos=11748

**Comment by mampfes** [comment]
fixed by #96
