### ISSUE TITLE
Abki recycling waste wrong data

### ISSUE THREAD

**Issue by jkasten80** [mampfes/hacs_waste_collection_schedule#891]
The source is working fine, but for the recycling waste it takes the data from the test street Achterwehrer Strasse 1 A and not from my street. 

Could be also Aarhusstrasse from the source.

I tested it again, if I put my street in the source where Aarhusstrasse is, than everything is fine.

**Comment by 5ila5** [comment]
Sorry, did not see this as this only affected recycling waste 
fixed by #893

**Comment by jkasten80** [comment]
Awesome! Now everything looks fine. Thx for your fast fix!
