### ISSUE TITLE
Can't fetch the calendar for Kingston Council

### ISSUE THREAD

**Issue by ilbarone87** [mampfes/hacs_waste_collection_schedule#899]
Hello everyone,
If i try to fetch the calendar for The Royal Borough of Kingston Council i get this error:

fetch failed for source The Royal Borough of Kingston Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py", line 115, in fetch date=datetime.strptime( File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S'

https://waste-services.kingston.gov.uk/waste

Can you please help?
Thanks

**Comment by 5ila5** [comment]
fixed by #900

**Comment by ilbarone87** [comment]
@5ila5 thanks
