### ISSUE TITLE
Entity for ButtonCard

### ISSUE THREAD

**Issue by senex44** [mampfes/hacs_waste_collection_schedule#9]
I have set up the waste collection schedule and the standard lovelace card is working fine:
![grafik](https://user-images.githubusercontent.com/63457786/84597985-c64cae00-ae67-11ea-9120-12157a146c33.png)

When I try to set up this with a ButtonCard, I get the following error:
![grafik](https://user-images.githubusercontent.com/63457786/84598001-ef6d3e80-ae67-11ea-8f68-5fb4c5eb7629.png)

I can't figure out, what's the problem here. I also took a look at the code, but was not able to identify where this might come from, but I am not a programming guy. 
Maybe you have an idea?

**Comment by mampfes** [comment]
Short answer: Set sensors `value_template` as described in the button card example: `value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'`

Full description: To allow full configuration of the shown texts in the ButtonCard, the example puts all attributes (= type[s], days-to, date) in a list in the sensor value, separated by `|`. This is used by the ButtonCard and splitted again into the individual attributes. If you also want to use both, standard Lovelace card and ButtonCard at the same time, just add another sensor, one for Lovelace and one for ButtonCard and set the `value_template` accordingly.

**Comment by senex44** [comment]
Thanks for the comment, my problem was that I used an uppercase letter in the buttoncard definition - stupid mistake.
