### ISSUE TITLE
need city, street, house number support for infeo.at

### ISSUE THREAD

**Issue by PeaceTrain** [mampfes/hacs_waste_collection_schedule#902]
@dm82m 
I would really need the feature to use city, street, house number for infeo.at
customer would be IKB

**Comment by PeaceTrain** [comment]
they seem to change the IDs for at least the calendar ID and the CityID :-(
https://services.infeo.at/aloa/api/ikb/wastecalendar/export/?calendarId=<CALENDARID>&cityId=<CITYID>&streetId=<STREETID>&housenumber=<HOUSEID>&fractionIds=173&fractionIds=174&fractionIds=175&fractionIds=176&outputType=ical

**Comment by dm82m** [comment]
Will have a look next week

**Comment by dm82m** [comment]
@PeaceTrain PR is open, if you want to test it before it is released you can do so:

1) replace the file on your home assistant custom_components/waste_collection_schedule/waste_collection_schedule/source/infeo_at.py with the content of that one here: https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/c39e2a73dce01b5abd19b150709b3dd6aa64a760/custom_components/waste_collection_schedule/waste_collection_schedule/source/infeo_at.py

2) add this to your configuration.yaml
```
waste_collection_schedule:
  sources:
    - name: infeo_at
      args:
        customer: ikb
        city: your_city
        street: your_street
        housenumber: your_housenumber
```

3) restart your server and report back if you got the data

HINT: by default we are loading all available fraction data from the service. You can filter that later on in the waste collection schedule itself. see https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/faq.md and the question 'How can I hide a waste type I don't want to see?'.

and one sidenote: yes, infeo.at is frequently changing ids. that is why I added it to hacs_waste_collection_schedule. I take care of this in the code. for you as the user there is nothing to do after adding your configuration.

**Comment by PeaceTrain** [comment]
thank you very much! works like a charm
