### ISSUE TITLE
Request: Bedford Borough Council

### ISSUE THREAD

**Issue by markhaines** [mampfes/hacs_waste_collection_schedule#921]
This is a different council to the Central Bedfordshire integration already available.  
Data is here: https://www.bedford.gov.uk/bins-and-recycling

**Comment by dt215git** [comment]
Looks simple enough  - I'll try and get it done this weekend.

**Comment by markhaines** [comment]
That would be ace - thanks!

**Comment by 5ila5** [comment]
fixed by #924
