### ISSUE TITLE
Request: Add -> Abfallkalender / Main-Tauber-Kreis / Wertheim

### ISSUE THREAD

**Issue by yazend** [mampfes/hacs_waste_collection_schedule#926]
Please add the possibility of the waste calendar Main-Tauber-Kreis Wertheim, in the picture you can see that this is selected via localities,
- thanks -

german page ;-)
they provide it as .xlc .csv and .ics
https://www.main-tauber-kreis.de/abfallkalender

![Unbenannt](https://user-images.githubusercontent.com/5957256/234863053-6b22cdc6-30ba-4d5a-8f15-e4154e6b702c.PNG)

**Comment by 5ila5** [comment]
Main-Tauber-Kreis is already supported and listed on the README.md of this repository. They use c_trace which is supported: [c_trace_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/c_trace_de.md)
