### ISSUE TITLE
Request for South Tyneside Council

### ISSUE THREAD

**Issue by FuturamaPhill** [mampfes/hacs_waste_collection_schedule#929]
Hi, would it be possible to get South Tyneside Council added as a source? Their site requires me to enter postcode then pick an address from the list.

https://www.southtyneside.gov.uk/article/1023/Bin-collection-dates

**Comment by 5ila5** [comment]
fixed by #931

**Comment by FuturamaPhill** [comment]
Thank you so much for adding this! I'm not sure if I'm just being a bit dense but I can't get this working just keep getting _"This entity is no longer being provided by the waste_collection_schedule integration. If the entity is no longer in use, delete it in settings"_

`waste_collection_schedule:
  sources:
    - name: southtyneside_gov_uk
      calendar_title: Bin #feel free to edit
      args:
        postcode: "NE31 2EA"
        uprn: "100000303246"
`

`  - platform: waste_collection_schedule
    source_index: 0
    name: South Tyneside Bin Collection
    details_format: upcoming
    leadtime: 30
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
    add_days_to: false`

**Comment by FuturamaPhill** [comment]
Thank you so much for adding this! I'm not sure if I'm just being a bit dense but I can't get this working just keep getting _"This entity is no longer being provided by the waste_collection_schedule integration. If the entity is no longer in use, delete it in settings"_

> waste_collection_schedule:
>   sources:
>     - name: southtyneside_gov_uk
>       args:
>         postcode: "POSTCODE"
>         uprn: "NUMBER"


>   - platform: waste_collection_schedule
>     source_index: 0
>     name: South Tyneside Bin Collection
>     details_format: upcoming
>     leadtime: 30
>     value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
>     add_days_to: false

**Comment by 5ila5** [comment]
Which Version are you running? This Source is not yet part of Release 1.39.0 it will be part of 1.40.0 or is currently available as master (git) Version, which is a up to date copy of this Repository.
