### ISSUE TITLE
Request for North Tyneside Council

### ISSUE THREAD

**Issue by Mcgowan412** [mampfes/hacs_waste_collection_schedule#939]
Please could you look at https://my.northtyneside.gov.uk/category/81/bin-collection-dates

thanks

**Comment by dt215git** [comment]
They don't appear to return any dates
![image](https://user-images.githubusercontent.com/86194065/235723469-15132345-8a00-4ddd-b1c9-fa9946c823ac.png)

You could use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md), and the info in the pdfs they link to, to create a schedule.
