### ISSUE TITLE
Kingston Council (UK) fetch error

### ISSUE THREAD

**Issue by ilbarone87** [mampfes/hacs_waste_collection_schedule#946]
Hello seems that when trying to fetch data is giving error again:

`fetch failed for source The Royal Borough of Kingston Council: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json return complexjson.loads(self.text, **kwargs) File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode obj, end = self.raw_decode(s) File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode return self.scan_once(s, idx=_w(s, idx).end()) simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/kingston_gov_uk.py", line 48, in fetch authData = authRequest.json() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Seems something to do with auth but I might be wrong.
Can you please have a look?

**Comment by dt215git** [comment]
For me, the test cases seem to work okay:

```bash
Testing source kingston_gov_uk ...
  found 5 entries for Blagdon Road - number
    2023-05-18 : refuse bin [mdi:trash-can]
    2023-05-11 : food waste bin [mdi:trash-can]
    2023-05-18 : paper and card recycling bin [mdi:recycle]
    2023-05-11 : mixed recycling bin [mdi:recycle]
    2023-05-18 : garden waste bin [mdi:leaf]
  found 5 entries for Blagdon Road - string
    2023-05-18 : refuse bin [mdi:trash-can]
    2023-05-11 : food waste bin [mdi:trash-can]
    2023-05-18 : paper and card recycling bin [mdi:recycle]
    2023-05-11 : mixed recycling bin [mdi:recycle]
    2023-05-18 : garden waste bin [mdi:leaf]
```
And the HA calendar is populated with collections if I pick a random Kingston address:
![image](https://user-images.githubusercontent.com/86194065/236613549-24974cc7-d1a1-4c04-a856-ab006a45298e.png)

**Comment by ilbarone87** [comment]
I think now it's working again. Rebooted HA yesterday and seems have fetched correctly the collection calendar.
