### ISSUE TITLE
Request for wirral Council 

### ISSUE THREAD

**Issue by si458** [mampfes/hacs_waste_collection_schedule#949]
https://www.wirral.gov.uk/bins-and-recycling/bin-collection-dates

They do indeed return dates,

My address, 'vernon avenue, Seacombe' for my grey and green bins dates
But I have to select 'Vernon avenue, Poulton' to get my brown bin dates

**Comment by si458** [comment]
Thank you! Looking forward to the new release!

**Comment by 5ila5** [comment]
fixed by #953
