### ISSUE TITLE
Why is "add offset = 1 day for bsr.de" not in 1.39.0 ?

### ISSUE THREAD

**Issue by DenisMtfl** [mampfes/hacs_waste_collection_schedule#951]
In the commits it is, but in the zip it is not !?

**Comment by 5ila5** [comment]
Version 1.39.0 is from Apr 20, 17:19, commit ee70fe0 is from Apr 21, 7:53. So it is not part of the 1.39.0 release. If you are using HACS the master (git) Version is always up to date with this repository. If you want a zip you can download this repository as zip or wait for the next release.
