### ISSUE TITLE
Request for Aberdeenshire, UK

### ISSUE THREAD

**Issue by danq8** [mampfes/hacs_waste_collection_schedule#966]
Hi.

Would it be possible to add Aberdeenshire county in the UK as a source please?

Here's a couple of example addresses, and the URLs with UPRN:

Summerlea, Balmedie, AB23 8YE
https://online.aberdeenshire.gov.uk/Apps/Waste-Collections/Routes.aspx?uprn=000151124612

29 Ellon Resource Centre, Station Road, Ellon, AB41 9AE
https://online.aberdeenshire.gov.uk/Apps/Waste-Collections/Routes.aspx?uprn=000151650618
(No collections on the site for this one.. council owned)

Many thanks

Dan.

**Comment by 5ila5** [comment]
fixed by #967
