### ISSUE TITLE
Request for Kingston Council, Melbourne, Australia

### ISSUE THREAD

**Issue by DrewXT** [mampfes/hacs_waste_collection_schedule#971]
Hi Team,

would it be possible to add Kingston Council in Melbourne?  There's a Geo Search tool at https://www.kingston.vic.gov.au/services/rubbish-and-recycling/bins-and-collections#bin-day, but I'm in no way smart enough to know how to get python to make a call against it

**Comment by 5ila5** [comment]
Fixed by #973.
Will be available in the next release. Or in the git (master) version now
