### ISSUE TITLE
Add the Landkreis Mayen

### ISSUE THREAD

**Issue by Camouflagge** [mampfes/hacs_waste_collection_schedule#972]
Hallo mein Landkreis habe ich erfolgreich hinzugefügt.

Landkreis Mayen-Koblenz

waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: "8303df78b822c30ff2c2f98e405f86e6"
        f_id_kommune: 3295
        f_id_strasse: 270
        f_abfallarten:
          - 28
          - 17
          - 100
          - 67
      customize:
        - type: Bioabfall
          alias: BioTonne
          icon: mdi:flower-outline
        - type: Gelber Sack
          alias: GelberSack
          icon: mdi:recycle
        - type: Restabfall
          alias: Restmuell
          icon: mdi:trash-can
        - type: Papierabfall
          alias: PapierTonne
          icon: mdi:trash-can-outline
  fetch_time: "04:00"
  day_switch_time: "10:00"

**Comment by 5ila5** [comment]
added with #974 to the wizard and README
