### ISSUE TITLE
New data? Fetching data manually...

### ISSUE THREAD

**Issue by andrewbpowers** [mampfes/hacs_waste_collection_schedule#990]
Hello!

How can I check if data has been loaded? 
How can I manually trigger the loading of new calendar data?

Best regards
A!

**Comment by dt215git** [comment]
> How can I check if data has been loaded?

Search for the entity in `Developer Tools | States` and look at the attributes.

> How can I manually trigger the loading of new calendar data?

Restarting HA triggers a re-query of the source. But in routine use it happens once per day anyway, so you should have no need to do a manually update once you've got your initial config working.

**Comment by andrewbpowers** [comment]
Thank you, for your fast feedback!

I have this...

`waste_collection_schedule:
  sources:
    - name: ics
       args:
           file: "www/bincalendar/bins.ics"`

...changed to this:

`waste_collection_schedule:
  sources:
    - name: xxxxxxx_gov_uk
      args:
        uprn: "xxxxxxxxxxxxxxxxxxx"`

And it does not work anymore! 
:-(

The custimize area should actually remain the same, shouldn't it? 
Or do I no longer have to specify a separator (previously: "; ")? 

Can I see somewhere what data was loaded at all?
If this is not visible, no customisation can actually be possible if I don't know which calendars, categories and reminders are available.

**Comment by dt215git** [comment]
No need for your uprn, but it's going to be difficult to troubleshoot without knowing which council source you're using.
As for the rest of it, it depends on how similar/different the descriptions in the ics file and website responses are.

**Comment by andrewbpowers** [comment]
Thanks for the answer!

If I can't manually trigger the loading of the data and I can't see what data is being loaded, I can't make any customizations. 
I therefore find the configuration instructions simply inadequate, as it is absolutely not clear from them what data is available at all when the loading has worked. 
In the end, it means that I have to load the data manually at least once beforehand and upload it to HA and check which calendars are available, what the separator, etc. is.

I have now reactivated the old configuration. I loaded the data manually from the homepage and uploaded it to HA. Restarted HA and everything is displayed again.

**Comment by andrewbpowers** [comment]
It's getting kind of funny... :-)

I didn't make up any configuration, but here is what is stated (claimed) after all:

> **Supported Service Providers**
> Waste collection schedules in the following formats and countries are supported. Click on the section heading to view details of individual service providers.

When I then select a city, the following is displayed:

> Configuration via configuration.yaml
> waste_collection_schedule:
>     sources:
>     - name: xxxxxx_gov_uk
>       args:
>         uprn: UNIQUE_PROPERTY_REFERENCE_NUMBER

The statement is that the following cities are supported and with the insertion of the displayed code in the configuration.yaml the data will be loaded. Right!?

It is neither said what data is loaded.... e.g. which different calendars (type of waste), with reminder or not, which separator and so on.  I have written all this before. So, why is this information not given when it is said that a certain city is being supported? Yes, I still can't understand this and I find it inappropriate.

But never mind! 
I only have to load the calendar manually twice a year, and that takes no more than two minutes.
So I have already spent so much time here, that it is enough for the next ten years. ;-))


Take care and have a great day!

**Comment by mampfes** [comment]
I will close this issue because I think we don't need to support people who dont want to understand how open source software works.

> It is neither said what data is loaded.... e.g. which different calendars (type of waste), with reminder or not, which separator and so on.

This is easy to answer: We are not responsible for the content! Obvious, or? We just fetch the data - which is basically a list of waste types and dates. Ask your service provider if you need more information.

> So I have already spent so much time here, that it is enough for the next ten years. ;-))

Why do you insult the people who give you something for free? We do all this in our free time, without compensation. If everyone treated us like you, there would be no more free software.

**Comment by andrewbpowers** [comment]
> I will close this issue because I think we don't need to support people who dont want to understand how open source software works.
Yet another assertion and insinuation. 

> We are not responsible for the content! Obvious, or?
I didn't say that either.

> Why do you insult the people...
Assertion and insinuation, again. 

Well... being offended for no reason, then falsely accusing other people of something and running away is just not a good attitude. 

> We do all this in our free time, without compensation.
Nobody forced you to do it! ;-) So, what's the point?
You really have to get your thoughts straight... I only wrote that your config doesn't work and that you can't see which data is loaded into with your config at all, and that's your reaction to it. As I said before, really, really funny! :-))
Have a great day!
