### ISSUE TITLE
Request for Cambridge Massachusetts Source

### ISSUE THREAD

**Issue by bakerkj** [mampfes/hacs_waste_collection_schedule#991]
Information can be found here ([https://www.cambridgema.gov/services/curbsidecollections](https://www.cambridgema.gov/services/curbsidecollections)).

Thanks!

**Comment by dt215git** [comment]
Looks like that's using the ReCollect API, you could probably use [this](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#recollect) to implement Cambridge, MA.

**Comment by 5ila5** [comment]
added official documentation in #1018
