### ISSUE TITLE
URL changed for Aberdeenshire source

### ISSUE THREAD

**Issue by danq8** [mampfes/hacs_waste_collection_schedule#994]
Hi

It looks like Aberdeenshire council have changed their back-end system.
so the URL has changed from:
https://online.aberdeenshire.gov.uk/Apps/Waste-Collections/Routes.aspx?uprn=000151004105
To:
https://online.aberdeenshire.gov.uk/Apps/Waste-Collections/Routes/Route/000151004105

Many thanks to @dt215git for getting this working in the first place, hopefully it's a small change to update (The resulting page looks the same as it did before).

Cheers

Dan.

**Comment by danq8** [comment]
Sorry dude,
I didn't know they were just about to change their system.
If I can help in any way, just shout 👍
I know if you go to https://online.aberdeenshire.gov.uk/Apps/Waste-Collections/
And put in the post code
AB42 2FA
You can get to that uprn at 
5 Berryden Road
Peterhead
AB42 2FA

Hope that helps

Cheers

**Comment by dt215git** [comment]
Table structure and text was subtly different, hence the errors above. Now resolved.

```bash
Testing source aberdeenshire_gov_uk ...
  found 2 entries for Test_001
    2023-05-29 : Mixed recycling and food waste [mdi:recycle]
    2023-06-05 : Refuse and food waste [mdi:trash-can]
  found 2 entries for Test_002
    2023-05-30 : Mixed recycling and food waste [mdi:recycle]
    2023-06-06 : Refuse and food waste [mdi:trash-can]
  found 2 entries for Test_003
    2023-05-30 : Mixed recycling and food waste [mdi:recycle]
    2023-05-30 : Refuse and food waste [mdi:trash-can]
  found 2 entries for Test_004
    2023-06-01 : Mixed recycling and food waste [mdi:recycle]
    2023-06-08 : Refuse and food waste [mdi:trash-can]
```
If you can't wait for the next release, you can see the changes in the [PR](https://github.com/mampfes/hacs_waste_collection_schedule/pull/997/files)
